{foxy} libg2o: restrict with opengl ROS_WORKD_SKIP_GROUP
* depends on mesa
* fixes:
  ERROR: Nothing PROVIDES 'mesa' (but meta-ros2-foxy/generated-recipes/libg2o/libg2o_2020.5.29-1.bb DEPENDS on or otherwise requires it)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>