{eloquent} Fix parsing issues for rcl/rclcpp
* it still doesn't build:
  Summary: 7 tasks failed:
    /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/foonathan-memory-vendor/foonathan-memory-vendor_0.3.0-1.bb:do_configure
    virtual:native:/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rosidl/rosidl-typesupport-introspection-cpp_0.8.1-1.bb:do_configure
    /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rosidl/rosidl-typesupport-introspection-cpp_0.8.1-1.bb:do_configure
    /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rosidl/rosidl-adapter_0.8.1-1.bb:do_configure
    /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rcl/rcl-yaml-param-parser_0.8.3-1.bb:do_configure
    /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rosidl-typesupport-fastrtps/rosidl-typesupport-fastrtps-cpp_0.8.0-1.bb:do_configure
    /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rosidl-typesupport-fastrtps/rosidl-typesupport-fastrtps-c_0.8.0-1.bb:do_configure
  Summary: There were 3 WARNING messages shown.
  Summary: There were 7 ERROR messages shown, returning a non-zero exit code.

* but at least it parses now, fixing:
ERROR: Nothing PROVIDES 'tracetools' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rcl/rcl_0.8.3-1.bb DEPENDS on or otherwise requires it). Close matches:
  aoetools
  conntrack-tools
  qttools
ERROR: Nothing PROVIDES 'tracetools' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rcl/rcl_0.8.3-1.bb DEPENDS on or otherwise requires it). Close matches:
  aoetools
  conntrack-tools
  qttools
ERROR: Nothing PROVIDES 'rmw-opensplice-cpp' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rmw-implementation/rmw-implementation_0.8.2-2.bb DEPENDS on or otherwise requires it)
rmw-opensplice-cpp was skipped: Recipe is blacklisted: Not yet supporting use of OpenSplice
ERROR: Nothing PROVIDES 'rmw-connext-cpp' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rmw-implementation/rmw-implementation_0.8.2-2.bb DEPENDS on or otherwise requires it)
rmw-connext-cpp was skipped: Recipe is blacklisted: Not yet supporting use of Connext
ERROR: Nothing PROVIDES 'UNRESOLVED-spdlog' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rcl-logging/rcl-logging-spdlog_0.3.3-1.bb, /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/spdlog-vendor/spdlog-vendor_1.0.1-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'UNRESOLVED-spdlog' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/spdlog-vendor/spdlog-vendor_1.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-spdlog' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-spdlog']
ERROR: Required build target 'rcl' has no buildable providers.
Missing or unbuildable dependency chain was: ['rcl', 'rcl-logging-spdlog', 'spdlog-vendor', 'UNRESOLVED-spdlog']
ERROR: Nothing RPROVIDES 'foonathan-memory-vendor-native' (but virtual:native:/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/fastrtps/fastrtps_1.9.3-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'foonathan-memory-vendor-native' is unbuildable, removing...