{eloquent} {pendulum,gazebo,tf2,map,move-base,pcl,px4,can}-msgs: fix missing dependencies
* fixes:
  ERROR: can-msgs-2.0.0-1-r0 do_configure: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/can-msgs/2.0.0-1-r0/temp/log.do_configure.33742)
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/can-msgs/2.0.0-1-r0/temp/log.do_configure.33742
  | ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/can-msgs/2.0.0-1-r0/temp/log.do_configure.33742)
  ERROR: Task (/jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/ros-canopen/can-msgs_2.0.0-1.bb:do_configure) failed with exit code '1'
  ERROR: pcl-msgs-1.0.0-1-r0 do_configure: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/pcl-msgs/1.0.0-1-r0/temp/log.do_configure.33744)
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/pcl-msgs/1.0.0-1-r0/temp/log.do_configure.33744
  | ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/pcl-msgs/1.0.0-1-r0/temp/log.do_configure.33744)
  ERROR: Task (/jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/pcl-msgs/pcl-msgs_1.0.0-1.bb:do_configure) failed with exit code '1'
  ERROR: px4-msgs-2.0.1-1-r0 do_configure: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/px4-msgs/2.0.1-1-r0/temp/log.do_configure.33743)
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/px4-msgs/2.0.1-1-r0/temp/log.do_configure.33743
  | ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/px4-msgs/2.0.1-1-r0/temp/log.do_configure.33743)
  ERROR: move-base-msgs-2.0.2-1-r0 do_configure: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/move-base-msgs/2.0.2-1-r0/temp/log.do_configure.33745)
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/move-base-msgs/2.0.2-1-r0/temp/log.do_configure.33745
  | ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/move-base-msgs/2.0.2-1-r0/temp/log.do_configure.33745)
  ERROR: Task (/jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/px4-msgs/px4-msgs_2.0.1-1.bb:do_configure) failed with exit code '1'
  ERROR: Task (/jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/navigation-msgs/move-base-msgs_2.0.2-1.bb:do_configure) failed with exit code '1'
  ERROR: pendulum-msgs-0.8.4-1-r0 do_configure: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/pendulum-msgs/0.8.4-1-r0/temp/log.do_configure.33866)
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/pendulum-msgs/0.8.4-1-r0/temp/log.do_configure.33866
  | ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/pendulum-msgs/0.8.4-1-r0/temp/log.do_configure.33866)
  ERROR: Task (/jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/demos/pendulum-msgs_0.8.4-1.bb:do_configure) failed with exit code '1'
  ERROR: map-msgs-2.0.2-1-r0 do_configure: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/map-msgs/2.0.2-1-r0/temp/log.do_configure.33750)
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/map-msgs/2.0.2-1-r0/temp/log.do_configure.33750
  | ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/map-msgs/2.0.2-1-r0/temp/log.do_configure.33750)
  ERROR: Task (/jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/navigation-msgs/map-msgs_2.0.2-1.bb:do_configure) failed with exit code '1'
  ERROR: tf2-msgs-0.12.4-1-r0 do_configure: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/tf2-msgs/0.12.4-1-r0/temp/log.do_configure.33770)
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/tf2-msgs/0.12.4-1-r0/temp/log.do_configure.33770
  | ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/tf2-msgs/0.12.4-1-r0/temp/log.do_configure.33770)
  ERROR: Task (/jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/geometry2/tf2-msgs_0.12.4-1.bb:do_configure) failed with exit code '1'
  ERROR: gazebo-msgs-3.4.2-1-r0 do_configure: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/gazebo-msgs/3.4.2-1-r0/temp/log.do_configure.33790)
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/gazebo-msgs/3.4.2-1-r0/temp/log.do_configure.33790
  | ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/gazebo-msgs/3.4.2-1-r0/temp/log.do_configure.33790)
  ERROR: Task (/jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/gazebo-ros-pkgs/gazebo-msgs_3.4.2-1.bb:do_configure) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>