{eloquent} resolve dependency issues in new recipes
* fixes:
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2-epuck_1.0.2-1.bb, /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2-universal-robot_1.0.2-1.bb, /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/turtlebot3/turtlebot3-bringup_2.1.0-1.bb, /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2-tiago_1.0.2-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on rviz-common->qtbase; x11: depends on rviz-common->rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
NOTE: Runtime target 'webots-ros2-epuck' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-epuck', 'rviz2']
NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'webots-ros2-epuck', 'rviz2']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'webots-ros2-epuck', 'rviz2']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'webots-ros2-epuck', 'rviz2']
NOTE: Runtime target 'webots-ros2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2', 'webots-ros2-epuck', 'rviz2']
NOTE: Runtime target 'webots-ros2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-dev', 'webots-ros2-epuck', 'rviz2']
NOTE: Runtime target 'webots-ros2-universal-robot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-universal-robot', 'rviz2']
NOTE: Runtime target 'webots-ros2-demos' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-demos', 'webots-ros2-universal-robot', 'rviz2']
NOTE: Runtime target 'webots-ros2-demos-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-demos-dev', 'webots-ros2-universal-robot', 'rviz2']
NOTE: Runtime target 'turtlebot3-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-bringup', 'rviz2']
NOTE: Runtime target 'turtlebot3' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3', 'turtlebot3-bringup', 'rviz2']
NOTE: Runtime target 'turtlebot3-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-dev', 'turtlebot3-bringup', 'rviz2']
NOTE: Runtime target 'webots-ros2-tiago' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-tiago', 'rviz2']
ERROR: Nothing RPROVIDES 'webots-ros2-epuck-dev' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2-epuck_1.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros2-epuck-dev'
NOTE: Runtime target 'webots-ros2-epuck-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-epuck-dev']
ERROR: Nothing RPROVIDES 'webots-ros2-universal-robot-dev' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2-universal-robot_1.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros2-universal-robot-dev'
NOTE: Runtime target 'webots-ros2-universal-robot-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-universal-robot-dev']
ERROR: Nothing RPROVIDES 'turtlebot3-bringup-dev' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/turtlebot3/turtlebot3-bringup_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtlebot3-bringup-dev'
NOTE: Runtime target 'turtlebot3-bringup-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-bringup-dev']
ERROR: Nothing RPROVIDES 'webots-ros2-tiago-dev' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2-tiago_1.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros2-tiago-dev'
NOTE: Runtime target 'webots-ros2-tiago-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-tiago-dev']

ERROR: Nothing RPROVIDES 'webots-ros2-universal-robot' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2_1.0.2-1.bb, /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2-demos_1.0.2-1.bb RDEPENDS on or otherwise requires it)
webots-ros2-universal-robot was skipped: Recipe is blacklisted: qt5: rdepends on rviz2 which depends on rviz-common->qtbase; x11: rdepends on rviz2 which depends on rviz-common->rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'webots-ros2-universal-robot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-universal-robot']
NOTE: Runtime target 'webots-ros2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2', 'webots-ros2-universal-robot']
NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'webots-ros2', 'webots-ros2-universal-robot']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'webots-ros2', 'webots-ros2-universal-robot']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'webots-ros2', 'webots-ros2-universal-robot']
NOTE: Runtime target 'webots-ros2-demos' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-demos', 'webots-ros2-universal-robot']
ERROR: Nothing RPROVIDES 'webots-ros2-dev' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2_1.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros2-dev'
NOTE: Runtime target 'webots-ros2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-dev']
ERROR: Nothing RPROVIDES 'webots-ros2-tiago' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2_1.0.2-1.bb RDEPENDS on or otherwise requires it)
webots-ros2-tiago was skipped: Recipe is blacklisted: qt5: rdepends on rviz2 which depends on rviz-common->qtbase; x11: rdepends on rviz2 which depends on rviz-common->rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'webots-ros2-tiago' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-tiago']
ERROR: Nothing RPROVIDES 'webots-ros2-epuck' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2_1.0.2-1.bb RDEPENDS on or otherwise requires it)
webots-ros2-epuck was skipped: Recipe is blacklisted: qt5: rdepends on rviz2 which depends on rviz-common->qtbase; x11: rdepends on rviz2 which depends on rviz-common->rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'webots-ros2-epuck' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-epuck']
ERROR: Nothing RPROVIDES 'turtlebot3-bringup' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/turtlebot3/turtlebot3_2.1.0-1.bb RDEPENDS on or otherwise requires it)
turtlebot3-bringup was skipped: Recipe is blacklisted: qt5: rdepends on rviz2 which depends on rviz-common->qtbase; x11: rdepends on rviz2 which depends on rviz-common->rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'turtlebot3-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-bringup']
NOTE: Runtime target 'turtlebot3' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3', 'turtlebot3-bringup']
ERROR: Nothing RPROVIDES 'turtlebot3-dev' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/turtlebot3/turtlebot3_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtlebot3-dev'
NOTE: Runtime target 'turtlebot3-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-dev']
ERROR: Nothing RPROVIDES 'webots-ros2-demos-dev' (but /jenkins/mjansa/build/ros/ros2-eloquent-dunfell/meta-ros/meta-ros2-eloquent/generated-recipes/webots-ros2/webots-ros2-demos_1.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros2-demos-dev'
NOTE: Runtime target 'webots-ros2-demos-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-demos-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>