{rolling} resolve dependency issues in new recipes
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-sdformat' (but meta-ros/meta-ros2-rolling/generated-recipes/sdformat-urdf/sdformat-urdf_0.1.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'sdformat-urdf' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sdformat-urdf', 'ROS_UNRESOLVED_DEP-sdformat']
NOTE: Runtime target 'packagegroup-ros-world-rolling' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-rolling', 'sdformat-urdf', 'ROS_UNRESOLVED_DEP-sdformat']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'sdformat-urdf', 'ROS_UNRESOLVED_DEP-sdformat']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'sdformat-urdf', 'ROS_UNRESOLVED_DEP-sdformat']
ERROR: Nothing PROVIDES 'glfw' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb DEPENDS on or otherwise requires it)
glfw was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'mrpt2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt2', 'glfw']
ERROR: Nothing PROVIDES 'freeglut' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb DEPENDS on or otherwise requires it)
freeglut was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'libxxf86vm' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb DEPENDS on or otherwise requires it)
libxxf86vm was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'libxrandr' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb DEPENDS on or otherwise requires it)
libxrandr was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'wxwidgets' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb DEPENDS on or otherwise requires it)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-sdformat' (but meta-ros/meta-ros2-rolling/generated-recipes/sdformat-urdf/sdformat-urdf_0.1.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-sdformat' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-sdformat']
ERROR: Nothing RPROVIDES 'sdformat-urdf-dev' (but meta-ros/meta-ros2-rolling/generated-recipes/sdformat-urdf/sdformat-urdf_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'sdformat-urdf-dev'
NOTE: Runtime target 'sdformat-urdf-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sdformat-urdf-dev']
ERROR: Nothing RPROVIDES 'rqt-gui' (but meta-ros/meta-ros2-rolling/generated-recipes/rqt-bag/rqt-bag-plugins_1.0.0-1.bb, meta-ros/meta-ros2-rolling/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb, meta-ros/meta-ros2-rolling/generated-recipes/rqt-bag/rqt-bag_1.0.0-1.bb RDEPENDS on or otherwise requires it)
rqt-gui was skipped: Recipe is blacklisted: qt5: depends on qt-gui which depends on qtbase; pyqt5: depends on qt-gui which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui']
NOTE: Runtime target 'rqt-bag-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-bag-plugins', 'rqt-gui']
NOTE: Runtime target 'rqt-moveit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-moveit', 'rqt-gui']
NOTE: Runtime target 'rqt-bag' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-bag', 'rqt-gui']
ERROR: Nothing RPROVIDES 'rqt-plot' (but meta-ros/meta-ros2-rolling/generated-recipes/rqt-bag/rqt-bag-plugins_1.0.0-1.bb RDEPENDS on or otherwise requires it)
rqt-plot was skipped: Recipe is blacklisted: qt5: rdepends on rqt-gui-py which depends qt-gui which depends on qtbase; pyqt5: rdepends on python-qt-binding which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-plot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-plot']
ERROR: Nothing RPROVIDES 'rqt-bag-plugins-dev' (but meta-ros/meta-ros2-rolling/generated-recipes/rqt-bag/rqt-bag-plugins_1.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-bag-plugins-dev'
NOTE: Runtime target 'rqt-bag-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-bag-plugins-dev']
ERROR: Nothing RPROVIDES 'rqt-gui-py' (but meta-ros/meta-ros2-rolling/generated-recipes/rqt-bag/rqt-bag-plugins_1.0.0-1.bb, meta-ros/meta-ros2-rolling/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb, meta-ros/meta-ros2-rolling/generated-recipes/rqt-bag/rqt-bag_1.0.0-1.bb RDEPENDS on or otherwise requires it)
rqt-gui-py was skipped: Recipe is blacklisted: qt5: depends on qt-gui which depends on qtbase; pyqt5: depends on qt-gui which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-gui-py' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-py']
ERROR: Nothing RPROVIDES 'rqt-py-common' (but meta-ros/meta-ros2-rolling/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb RDEPENDS on or otherwise requires it)
rqt-py-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; pyqt5: rdepends on python-qt-binding which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-py-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-py-common']
ERROR: Nothing RPROVIDES 'rqt-topic' (but meta-ros/meta-ros2-rolling/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb RDEPENDS on or otherwise requires it)
rqt-topic was skipped: Recipe is blacklisted: qt5: rdepends on rqt-gui-py which depends qt-gui which depends on qtbase; pyqt5: rdepends on python-qt-binding and rqt-gui-py which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-topic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-topic']
ERROR: Nothing RPROVIDES 'python-qt-binding' (but meta-ros/meta-ros2-rolling/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb, meta-ros/meta-ros2-rolling/generated-recipes/rqt-bag/rqt-bag_1.0.0-1.bb RDEPENDS on or otherwise requires it)
python-qt-binding was skipped: Recipe is blacklisted: qt5: depends on qtbase; pyqt5: depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'python-qt-binding' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-qt-binding']
ERROR: Nothing RPROVIDES 'rqt-moveit-dev' (but meta-ros/meta-ros2-rolling/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-moveit-dev'
NOTE: Runtime target 'rqt-moveit-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-moveit-dev']
ERROR: Nothing RPROVIDES 'webots-ros2-core' (but meta-ros/meta-ros2-rolling/generated-recipes/webots-ros2/webots-ros2-tutorials_1.0.2-2.bb RDEPENDS on or otherwise requires it)
webots-ros2-core was skipped: Recipe is blacklisted: webots-python-modules: requires python-transforms3d-pip which is not available in OE yet
NOTE: Runtime target 'webots-ros2-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-core']
NOTE: Runtime target 'webots-ros2-tutorials' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-tutorials', 'webots-ros2-core']
ERROR: Nothing RPROVIDES 'webots-ros2-tutorials-dev' (but meta-ros/meta-ros2-rolling/generated-recipes/webots-ros2/webots-ros2-tutorials_1.0.2-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros2-tutorials-dev'
NOTE: Runtime target 'webots-ros2-tutorials-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-tutorials-dev']
ERROR: Nothing RPROVIDES 'rqt-bag-dev' (but meta-ros/meta-ros2-rolling/generated-recipes/rqt-bag/rqt-bag_1.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-bag-dev'
NOTE: Runtime target 'rqt-bag-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-bag-dev']
ERROR: Nothing RPROVIDES 'freeglut' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb RDEPENDS on or otherwise requires it)
freeglut was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'freeglut' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['freeglut']
ERROR: Nothing RPROVIDES 'libxrandr' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb RDEPENDS on or otherwise requires it)
libxrandr was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'libxrandr' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libxrandr']
ERROR: Nothing RPROVIDES 'mrpt2-dev' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mrpt2-dev'
NOTE: Runtime target 'mrpt2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt2-dev']
ERROR: Nothing RPROVIDES 'glfw' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb RDEPENDS on or otherwise requires it)
glfw was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'glfw' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['glfw']
ERROR: Nothing RPROVIDES 'wxwidgets' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb RDEPENDS on or otherwise requires it)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'wxwidgets' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['wxwidgets']
ERROR: Nothing RPROVIDES 'libxxf86vm' (but meta-ros/meta-ros2-rolling/generated-recipes/mrpt2/mrpt2_2.1.3-2.bb RDEPENDS on or otherwise requires it)
libxxf86vm was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'libxxf86vm' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libxxf86vm']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>