{eloquent} plansys2-domain-expert: ignore return-type errors with webOS OSE
* fixes:
/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-g++  -Dplansys2_domain_expert_EXPORTS -I/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0/git/include -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0=/usr/src/debug/plansys2-domain-expert/0.0.5-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0=/usr/src/debug/plansys2-domain-expert/0.0.5-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0/recipe-sysroot -g -fPIC   -std=gnu++17 -MD -MT CMakeFiles/plansys2_domain_expert.dir/src/plansys2_domain_expert/Types.cpp.o -MF CMakeFiles/plansys2_domain_expert.dir/src/plansys2_domain_expert/Types.cpp.o.d -o CMakeFiles/plansys2_domain_expert.dir/src/plansys2_domain_expert/Types.cpp.o -c /jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0/git/src/plansys2_domain_expert/Types.cpp
/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0/git/src/plansys2_domain_expert/Types.cpp: In function 'std::shared_ptr<plansys2::TreeNode> plansys2::get_tree_node(const string&)':
/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-domain-expert/0.0.5-1-r0/git/src/plansys2_domain_expert/Types.cpp:131:44: error: control reaches end of non-void function [-Werror=return-type]
   std::string wexpr = getReducedString(expr);
                                            ^
cc1plus: some warnings being treated as errors

Signed-off-by: Martin Jansa <martin.jansa@lge.com>