{dashing} ros-distro.inc: Set ROS_UNRESOLVED_PLATFORM_PKG_lcov to "lcov"
* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-lcov' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/navigation2/nav2-system-tests_0.2.6-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-lcov' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-lcov']
NOTE: Runtime target 'nav2-system-tests' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-system-tests', 'UNRESOLVED-lcov']
NOTE: Runtime target 'packagegroup-ros-world-dashing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-dashing', 'nav2-system-tests', 'UNRESOLVED-lcov']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'nav2-system-tests', 'UNRESOLVED-lcov']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'nav2-system-tests', 'UNRESOLVED-lcov']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>