{melodic} ros-distro-recipe-blacklist.inc: blacklist distance-map-opencv with vc4graphics-without-opengl
* fixes:
ERROR: Nothing PROVIDES 'image-geometry' (but /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/distance-map/distance-map-opencv_0.1.0-1.bb DEPENDS on or otherwise requires it)
image-geometry was skipped: Recipe is blacklisted: Depends on gstreamer1.0-plugins-base which is not available for raspberrypi MACHINEs with vc4graphics in MACHINE_FEATURES, but without opengl in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'distance-map-opencv-dev' (but /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/distance-map/distance-map-opencv_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'distance-map-opencv-dev'
NOTE: Runtime target 'distance-map-opencv-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['distance-map-opencv-dev']
ERROR: Nothing RPROVIDES 'image-geometry' (but /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/distance-map/distance-map-opencv_0.1.0-1.bb RDEPENDS on or otherwise requires it)
image-geometry was skipped: Recipe is blacklisted: Depends on gstreamer1.0-plugins-base which is not available for raspberrypi MACHINEs with vc4graphics in MACHINE_FEATURES, but without opengl in DISTRO_FEATURES
NOTE: Runtime target 'image-geometry' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-geometry']
ERROR: Nothing RPROVIDES 'distance-map-opencv' (but /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/distance-map/distance-map-opencv_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'distance-map-opencv'
NOTE: Runtime target 'distance-map-opencv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['distance-map-opencv']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>