{dashing} packagegroup-ros-world-dashing: remove lex-common
* lex-common installs only header files in PN-dev, static library in PN-staticdev
  and debug files in PN-dbg, so the PN is empty and not created, causing:

ERROR: ros-image-world-1.0-r0 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install connman packagegroup-core-boot packagegroup-ros-world run-postinsts' returned 1:
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - nothing provides lex-common needed by packagegroup-ros-world-dashing-1.0-r0.all
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

 * opkg_finalize_intercepts: Failed to open dir /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-PNrNhz/opkg-intercept-5fKzmF: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-PNrNhz/opkg-intercept-5fKzmF: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-PNrNhz: No such file or directory.

ERROR: ros-image-world-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/log.do_rootfs.48344
NOTE: recipe ros-image-world-1.0-r0: task do_rootfs: Failed
ERROR: Task (/jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros-common/recipes-core/images/ros-image-world.bb:do_rootfs) failed with exit code '1'

ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/lex-common/1.0.0-1-r0$ find packages-split/
packages-split/
packages-split/lex-common-doc
packages-split/lex-common-staticdev
packages-split/lex-common-staticdev/usr
packages-split/lex-common-staticdev/usr/lib
packages-split/lex-common-staticdev/usr/lib/liblex_common.a
packages-split/lex-common
packages-split/lex-common-dev
packages-split/lex-common-dev/usr
packages-split/lex-common-dev/usr/share
packages-split/lex-common-dev/usr/share/lex_common
packages-split/lex-common-dev/usr/share/lex_common/cmake
packages-split/lex-common-dev/usr/share/lex_common/cmake/lex_common-targets.cmake
packages-split/lex-common-dev/usr/share/lex_common/cmake/lex_commonConfigVersion.cmake
packages-split/lex-common-dev/usr/share/lex_common/cmake/lex_common-targets-noconfig.cmake
packages-split/lex-common-dev/usr/share/lex_common/cmake/lex_commonConfig.cmake
packages-split/lex-common-dev/usr/include
packages-split/lex-common-dev/usr/include/lex_common
packages-split/lex-common-dev/usr/include/lex_common/error_codes.h
packages-split/lex-common-dev/usr/include/lex_common/lex_param_helper.h
packages-split/lex-common-dev/usr/include/lex_common/lex_configuration.h
packages-split/lex-common-dev/usr/include/lex_common/lex_common.h
packages-split/lex-common-locale
packages-split/lex-common-dbg
packages-split/lex-common-dbg/usr
packages-split/lex-common-dbg/usr/src
packages-split/lex-common-dbg/usr/src/debug
packages-split/lex-common-dbg/usr/src/debug/lex-common
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include/lex_common
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include/lex_common/error_codes.h
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include/lex_common/lex_configuration.h
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include/lex_common/lex_common.h
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/src
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/src/lex_common.cpp
packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/src/lex_param_helper.cpp

Signed-off-by: Martin Jansa <martin.jansa@lge.com>