{ros2} babeltrace: Add missing native tool
The setup.py script fails to run when the Python binding is enabled.

  ImportError: cannot import name 'setup' from 'setuptools' (unknown location)

Adding python3-setuptools-native provides the missing Python module.

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>