{foxy} blacklist recipes depending on gstreamer1.0-plugins-base based on vc4graphics-without-opengl
* fixes:
ERROR: Nothing PROVIDES 'virtual/libgles2' (but /jenkins/home/workspace/jansa/ros2-foxy-warrior/ros2-foxy-warrior/openembedded-core/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.14.4.bb DEPENDS on or otherwise requires it)
vc-graphics-hardfp PROVIDES virtual/libgles2 but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
vc-graphics PROVIDES virtual/libgles2 but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics
NOTE: Runtime target 'image-pipeline' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-pipeline', 'depth-image-proc', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'image-pipeline', 'depth-image-proc', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'image-pipeline', 'depth-image-proc', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'image-pipeline', 'depth-image-proc', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-pipeline-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-pipeline-dev', 'depth-image-proc', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'depth-image-proc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['depth-image-proc', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'depth-image-proc-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['depth-image-proc-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'stereo-image-proc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['stereo-image-proc', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'stereo-image-proc-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['stereo-image-proc-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'camera-calibration' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['camera-calibration', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'camera-calibration-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['camera-calibration-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-image-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-image-util', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-image-util-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-image-util-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-publisher' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-publisher', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-publisher-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-publisher-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-proc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-proc', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-proc-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-proc-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'depthimage-to-laserscan' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['depthimage-to-laserscan', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'depthimage-to-laserscan-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['depthimage-to-laserscan-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-geometry' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'vision-opencv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['vision-opencv', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'vision-opencv-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['vision-opencv-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-geometry-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-geometry-dev', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'compressed-depth-image-transport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['compressed-depth-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-transport-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-transport-plugins', 'compressed-depth-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-transport-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-transport-plugins-dev', 'compressed-depth-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'compressed-depth-image-transport-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['compressed-depth-image-transport-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'theora-image-transport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['theora-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'theora-image-transport-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['theora-image-transport-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-opencv-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-opencv-util', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-opencv-util-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-opencv-util-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-view' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-view', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-view-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-view-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-route-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-route-util', 'swri-geometry-util', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-route-util-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-route-util-dev', 'swri-geometry-util', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-geometry-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-geometry-util', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-geometry-util-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-geometry-util-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'compressed-image-transport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['compressed-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'compressed-image-transport-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['compressed-image-transport-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-rotate' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-rotate', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-rotate-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-rotate-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-transform-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-transform-util', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'swri-transform-util-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-transform-util-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'ifm3d-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ifm3d-core', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'ifm3d-core-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ifm3d-core-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'cv-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'cv-bridge-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cv-bridge-dev', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'intra-process-demo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['intra-process-demo', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'intra-process-demo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['intra-process-demo-dev', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-tools', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'image-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-tools-dev', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'opencv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['opencv', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'opencv-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['opencv-dev', 'gstreamer1.0-plugins-base', 'virtual/libgles2']
NOTE: Runtime target 'gstreamer1.0-plugins-base-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-base-dev', 'virtual/libgles2']
NOTE: Runtime target 'gstreamer1.0-plugins-base-meta' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-base-meta', 'virtual/libgles2']
NOTE: Runtime target 'gstreamer1.0-plugins-base' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-base', 'virtual/libgles2']
ERROR: Nothing PROVIDES 'virtual/egl' (but /jenkins/home/workspace/jansa/ros2-foxy-warrior/ros2-foxy-warrior/openembedded-core/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.14.4.bb DEPENDS on or otherwise requires it)
vc-graphics-hardfp PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
vc-graphics PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics

Signed-off-by: Martin Jansa <martin.jansa@lge.com>