mcf: show layer name in sanity check failures (v7.2.2)
:Release Notes:
Without this, it's not clear which layer is failing to update and the
last lines from logger are even more confusing.

:Detailed Notes:
Without this change, the last logger message is about meta-raspberrypi
but the error is in meta-ros-webos layer which is processed after:

2020-03-25T06:20:42 INFO __main__ Updating [meta-raspberrypi]
2020-03-25T06:20:42 INFO __main__ Done updating [meta-raspberrypi]
Traceback (most recent call last):
  File "./mcf", line 928, in <module>
    update_layers(srcdir)
  File "./mcf", line 487, in update_layers
    if reposanitycheck(layer) != 0:
  File "./mcf", line 668, in reposanitycheck
    raise Exception('Could not find local and remote branch %s' % newbranch)
Exception: Could not find local and remote branch jansa/dunfell

With this change applied:

2020-03-25T06:25:07 INFO __main__ Updating [meta-raspberrypi]
2020-03-25T06:25:07 INFO __main__ Done updating [meta-raspberrypi]
2020-03-25T06:25:07 INFO __main__ Sanity checking [meta-ros-webos]
Traceback (most recent call last):
  File "./mcf", line 930, in <module>
    update_layers(srcdir)
  File "./mcf", line 487, in update_layers
    if reposanitycheck(layer) != 0:
  File "./mcf", line 670, in reposanitycheck
    raise Exception('Could not find local and remote branch "%s" for layer "%s" from "%s"' % (newbranch, layer["location"], layer["url"]))
Exception: Could not find local and remote branch "jansa/dunfell" for layer "meta-ros-webos" from "git://github.com/shr-project/meta-ros-webos.git"

:Testing Performed:

:QA Notes:
N/A

:Issues Addressed:
[PLAT-102271] Various webos.inc fixes and cleanups
[PLAT-102385] CCC: Various webos.inc fixes and cleanups

Change-Id: I4766f4cdb3d317ef2d0a13494b2371b043a866ad