{rolling}: changed meta-scipy by new meta-python-ai
As meta-ros (and kas) is now using the more maintained meta-python-ai layer.

ERROR: Nothing RPROVIDES 'pinocchio' (but ../layers/meta-ros/meta-ros2-rolling/recipes-core/packagegroups/packagegroup-ros-world-rolling.bb, ../layers/meta-ros/meta-ros2-rolling/generated-recipes/tsid/tsid_1.8.0-1.bb, layers/meta-ros/meta-ros2-rolling/generated-recipes/kinematics-interface-pinocchio/kinematics-interface-pinocchio_0.0.1-1.bb RDEPENDS on or otherwise requires it)
pinocchio was skipped: Recipe will be skipped because: pinocchio: depends on eigenpy which depends on python3-scipy which requires meta-scipy layer

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>