{common} gz-common6: add missing includes
error:
| .../meta-ros/build/tmp/work/cortexa76-oe-linux/gz-common6/6.0.1/git/testing/include/gz/common/testing/detail/AutoLogFixture.hh:79:8: error: 'replace' is not a member of 'std'
|    79 |   std::replace(this->dataPtr->logFilename.begin(),
|       |        ^~~~~~~

Patch found at https://github.com/gazebosim/gz-common/commit/be28fbd6579121cb1cfec9c39345cf6afb2be9b and is in the next release (6.0.2)

Needed the patch with ROS 2 Rolling and Yocto Styhead

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>