{noetic} azure-iot-sdk-c: package /usr/cmake in PN-dev
* it should be probably moved to /usr/share/cmake or /usr/lib/cmake
  but lets package it before finding where its users are expecting them

* fixes:
ERROR: azure-iot-sdk-c-1.7.0-4-r0 do_package: QA Issue: azure-iot-sdk-c: Files/directories were installed but not shipped in any package:
  /usr/cmake
  /usr/cmake/azure_c_shared_utilityConfigVersion.cmake
  /usr/cmake/azure_c_shared_utilityConfig.cmake
  /usr/cmake/umock_cConfig.cmake
  /usr/cmake/umock_cFunctions.cmake
  /usr/cmake/uamqpConfigVersion.cmake
  /usr/cmake/umock_cTargets.cmake
  /usr/cmake/umock_cConfigVersion.cmake
  /usr/cmake/azure_macro_utils_cTargets.cmake
  /usr/cmake/umqttConfigVersion.cmake
  /usr/cmake/umqttConfig.cmake
  /usr/cmake/umock_cTargets-noconfig.cmake
  /usr/cmake/uhttpConfigVersion.cmake
  /usr/cmake/azure_iot_build_rules.cmake
  /usr/cmake/azure_macro_utils_cConfigVersion.cmake
  /usr/cmake/azure_macro_utils_cConfig.cmake
  /usr/cmake/azure_c_shared_utilityTargets.cmake
  /usr/cmake/umqttTargets.cmake
  /usr/cmake/azure_c_shared_utilityFunctions.cmake
  /usr/cmake/umqttTargets-noconfig.cmake
  /usr/cmake/uamqpTargets-noconfig.cmake
  /usr/cmake/uamqpTargets.cmake
  /usr/cmake/uamqpConfig.cmake
  /usr/cmake/azure_c_shared_utilityTargets-noconfig.cmake
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
azure-iot-sdk-c: 24 installed and not shipped files. [installed-vs-shipped]
ERROR: azure-iot-sdk-c-1.7.0-4-r0 do_package: Fatal QA errors found, failing task.
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/azure-iot-sdk-c/1.7.0-4-r0/temp/log.do_package.8787
ERROR: Task (/jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/azure-iot-sdk-c/azure-iot-sdk-c_1.7.0-4.bb:do_package) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>