{jazzy} gz-gui8: Add patch to add missing GL define
Add patch to add missing GL_UNSIGNED_INT_8_8_8_8_REV define.

| FAILED: src/plugins/minimal_scene/CMakeFiles/MinimalScene.dir/EngineToQtInterface.cc.o
| gz-gui8/8.4.0/git/src/plugins/minimal_scene/EngineToQtInterface.cc: In member function 'GLuint gz::gui::plugins::EngineToQtInterface::TextureId(gz::rendering::v8::CameraPtr&)':
| gz-gui8/8.4.0/git/src/plugins/minimal_scene/EngineToQtInterface.cc:179:7: error: 'GL_UNSIGNED_INT_8_8_8_8_REV' was not declared in this scope; did you mean 'GL_UNSIGNED_INT_5_9_9_9_REV'?
|   179 |       GL_UNSIGNED_INT_8_8_8_8_REV, this->dataPtr->fallbackImage->Data());
|       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |       GL_UNSIGNED_INT_5_9_9_9_REV

Signed-off-by: Christian Kohn <chris.kohn@amd.com>