{melodic} xpp-vis: add missing tf, kdl_parser, robot_state_publisher to CATKIN_DEPENDS
* fixes xpp-quadrotor and xpp-hyq issue:
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: warning: libtf.so, needed by ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so, not found (try using -rpath or -rpath-link)
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: warning: librobot_state_publisher_solver.so, needed by ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so, not found (try using -rpath or -rpath-link)
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: warning: libkdl_parser.so, needed by ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so, not found (try using -rpath or -rpath-link)
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: warning: liburdf.so, needed by ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so, not found (try using -rpath or -rpath-link)
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `tf::TransformBroadcaster::TransformBroadcaster()'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `vtable for robot_state_publisher::RobotStatePublisher'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `urdf::Model::initParam(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `tf::TransformBroadcaster::sendTransform(geometry_msgs::TransformStamped_<std::allocator<void> > const&)'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `kdl_parser::treeFromUrdfModel(urdf::ModelInterface const&, KDL::Tree&)'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-quadrotor/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `robot_state_publisher::RobotStatePublisher::RobotStatePublisher(KDL::Tree const&, urdf::Model const&)'
collect2: error: ld returned 1 exit status

ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: warning: libtf.so, needed by ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so, not found (try using -rpath or -rpath-link)
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: warning: librobot_state_publisher_solver.so, needed by ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so, not found (try using -rpath or -rpath-link)
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: warning: libkdl_parser.so, needed by ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so, not found (try using -rpath or -rpath-link)
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: warning: liburdf.so, needed by ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so, not found (try using -rpath or -rpath-link)
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `tf::TransformBroadcaster::TransformBroadcaster()'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `vtable for robot_state_publisher::RobotStatePublisher'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `urdf::Model::initParam(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `tf::TransformBroadcaster::sendTransform(geometry_msgs::TransformStamped_<std::allocator<void> > const&)'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `kdl_parser::treeFromUrdfModel(urdf::ModelInterface const&, KDL::Tree&)'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/xpp-hyq/1.0.10-r0/recipe-sysroot/opt/ros/melodic/lib/libxpp_vis.so: undefined reference to `robot_state_publisher::RobotStatePublisher::RobotStatePublisher(KDL::Tree const&, urdf::Model const&)'
collect2: error: ld returned 1 exit status

Signed-off-by: Martin Jansa <martin.jansa@lge.com>