{melodic} eigenpy: fix paths pointing to eigenpy WORKDIR
* this breaks e.g. pinocchio where it fails to find numpyconfig.h, because of completely
  bogus include path pointing to native RSS in eigenpy WORKDIR:
FAILED: bindings/python/CMakeFiles/pinocchio_pywrap.dir/multibody/joint/expose-joints.cpp.o                                                                                                                                                                            webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++  -DBOOST_MPL_LIMIT_LIST_SIZE=30 -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 -DPINOCCHIO_URDFDOM_TYPEDEF_SHARED_PTR -DPINOCCHIO_URDFDOM_USE_STD_SHARED_PTR -DPINOCCHIO_WITH_URDFDOM -Dpinocchio_pywrap_EXPORTS -I. -Iinclude -Iwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/git/include -Iwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot/usr/include -Iwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot/usr/include/python2.7 -Iwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot/usr/include/eigen3 -Iwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysrootwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/eigenpy/1.6.9-1-r0/recipe-sysroot/usr/include -Iwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysrootwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/eigenpy/1.6.9-1-r0/recipe-sysroot/usr/include/python2.7 -Iwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysrootwebos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/eigenpy/1.6.9-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/numpy/core/include -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0=/usr/src/debug/pinocchio/2.3.1-1-r0 -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot= -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot -fPIC -MD -MT bindings/python/CMakeFiles/pinocchio_pywrap.dir/multibody/joint/expose-joints.cpp.o -MF bindings/python/CMakeFiles/pinocchio_pywrap.dir/multibody/joint/expose-joints.cpp.o.d -o bindings/python/CMakeFiles/pinocchio_pywrap.dir/multibody/joint/expose-joints.cpp.o -c webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/git/bindings/python/multibody/joint/expose-joints.cpp
In file included from webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot/usr/include/eigenpy/eigenpy.hpp:9,
                 from include/pinocchio/bindings/python/multibody/joint/joint-derived.hpp:9,
                 from webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/git/bindings/python/multibody/joint/expose-joints.cpp:6:
webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/pinocchio/2.3.1-1-r0/recipe-sysroot/usr/include/eigenpy/fwd.hpp:12:10: fatal error: numpy/numpyconfig.h: No such file or directory
 #include <numpy/numpyconfig.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>