{melodic} heifu-*: ignore ros_utils dependency
* the ROS_UNRESOLVED_PLATFORM_PKG_ros_utils isn't defined anywhere
  not even to UNRESOLVED-ros_utils, maybe because this is the only
  case where the dependency name contains underscore instead of dash

* fixes:
ERROR: Nothing PROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-safety_0.7.1-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-mavros_0.7.1-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-simple-waypoint_0.7.1-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-diagnostic_0.7.1-2.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'heifu-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-bringup', 'heifu-safety', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
NOTE: Runtime target 'heifu-safety' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-safety', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
NOTE: Runtime target 'heifu-mavros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-mavros', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
NOTE: Runtime target 'heifu-simple-waypoint' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-simple-waypoint', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
NOTE: Runtime target 'heifu-diagnostic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-diagnostic', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>