{melodic} resolve dependency issues in new recipes
* fixes:

ERROR: Nothing PROVIDES 'catkin-virtualenv' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover_0.21.3-1.bb DEPENDS on or otherwise requires it)
catkin-virtualenv was skipped: Recipe is blacklisted: Requires Python 3; it is not used by any other ROS 1 package.
NOTE: Runtime target 'clover' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['clover', 'catkin-virtualenv']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'clover', 'catkin-virtualenv']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'clover', 'catkin-virtualenv']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'clover', 'catkin-virtualenv']
ERROR: Nothing PROVIDES 'web-video-server' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover_0.21.3-1.bb DEPENDS on or otherwise requires it)
web-video-server was skipped: Recipe is blacklisted: ffmpeg: Depends on ffmpeg which requires commercial license; x264: Depends on ffmpeg which depends on x264 which requires commercial license
ERROR: Nothing PROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover-simulation_0.21.3-1.bb DEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'clover-simulation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['clover-simulation', 'gazebo-ros']
ERROR: Nothing PROVIDES 'gazebo-plugins' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover-simulation_0.21.3-1.bb DEPENDS on or otherwise requires it)
gazebo-plugins was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-rosdev which is not available
ERROR: Nothing PROVIDES 'moveit-ros-move-group' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/moveit/pilz-industrial-motion-planner_1.0.8-1.bb DEPENDS on or otherwise requires it)
moveit-ros-move-group was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'pilz-industrial-motion-planner' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-industrial-motion-planner', 'moveit-ros-move-group']
ERROR: Nothing PROVIDES 'moveit-ros-planning' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/moveit/pilz-industrial-motion-planner_1.0.8-1.bb DEPENDS on or otherwise requires it)
moveit-ros-planning was skipped: Recipe is blacklisted: Depends on moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
ERROR: Nothing PROVIDES 'moveit-ros-planning-interface' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/moveit/pilz-industrial-motion-planner_1.0.8-1.bb DEPENDS on or otherwise requires it)
moveit-ros-planning-interface was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
ERROR: Nothing RPROVIDES 'clover-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover_0.21.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'clover-dev'
NOTE: Runtime target 'clover-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['clover-dev']
ERROR: Nothing RPROVIDES 'web-video-server' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover_0.21.3-1.bb RDEPENDS on or otherwise requires it)
web-video-server was skipped: Recipe is blacklisted: ffmpeg: Depends on ffmpeg which requires commercial license; x264: Depends on ffmpeg which depends on x264 which requires commercial license
NOTE: Runtime target 'web-video-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['web-video-server']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover-description_0.21.3-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover-simulation_0.21.3-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
NOTE: Runtime target 'clover-description' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['clover-description', 'gazebo-ros']
ERROR: Nothing RPROVIDES 'gazebo-plugins' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover-description_0.21.3-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover-simulation_0.21.3-1.bb RDEPENDS on or otherwise requires it)
gazebo-plugins was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-rosdev which is not available
NOTE: Runtime target 'gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-plugins']
ERROR: Nothing RPROVIDES 'clover-description-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover-description_0.21.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'clover-description-dev'
NOTE: Runtime target 'clover-description-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['clover-description-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-util-linux' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/robot-upstart/robot-upstart_0.3.3-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-util-linux' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-util-linux']
NOTE: Runtime target 'robot-upstart' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-upstart', 'ROS_UNRESOLVED_DEP-util-linux']
NOTE: Runtime target 'robot-upstart-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-upstart-dev', 'ROS_UNRESOLVED_DEP-util-linux']
ERROR: Nothing RPROVIDES 'clover-simulation-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/clover/clover-simulation_0.21.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'clover-simulation-dev'
NOTE: Runtime target 'clover-simulation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['clover-simulation-dev']
ERROR: Nothing RPROVIDES 'pilz-industrial-motion-planner-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/moveit/pilz-industrial-motion-planner_1.0.8-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-industrial-motion-planner-dev'
NOTE: Runtime target 'pilz-industrial-motion-planner-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-industrial-motion-planner-dev']
ERROR: Nothing RPROVIDES 'moveit-ros-move-group' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/moveit/pilz-industrial-motion-planner_1.0.8-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-move-group was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-ros-move-group' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-move-group']
ERROR: Nothing RPROVIDES 'moveit-ros-planning-interface' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/moveit/pilz-industrial-motion-planner_1.0.8-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-planning-interface was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-ros-planning-interface' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-planning-interface']
ERROR: Nothing RPROVIDES 'moveit-ros-planning' (but /jenkins/mjansa/build/ros/ros1-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/moveit/pilz-industrial-motion-planner_1.0.8-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-planning was skipped: Recipe is blacklisted: Depends on moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-ros-planning' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-planning']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>