{foxy} moveit-core: add dependency on angles
* fixes:
FAILED: robot_model/CMakeFiles/moveit_robot_model.dir/src/planar_joint_model.cpp.o
/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DDEFAULT_RMW_IMPLEMENTATION=rmw_fastrtps_cpp -DFMT_LOCALE -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -Dmoveit_robot_model_EXPORTS -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/background_processing/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/exceptions/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/backtrace/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/collision_detection/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/collision_detection_fcl/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/constraint_samplers/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/controller_manager/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/distance_field/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/collision_distance_field/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/dynamics_solver/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/kinematics_base/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/kinematics_metrics/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/robot_model/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/transforms/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/robot_state/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/robot_trajectory/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/kinematic_constraints/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/macros/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/planning_interface/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/planning_request_adapter/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/planning_scene/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/profiler/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/sensor_manager/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/trajectory_processing/include -I/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/utils/include -Iinclude -isystem /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/recipe-sysroot/usr/include/eigen3 -isystem /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/recipe-sysroot/usr/include/bullet -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0=/usr/src/debug/moveit-core/2.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0=/usr/src/debug/moveit-core/2.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/recipe-sysroot -DNDEBUG -fPIC -Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wcast-qual -Wno-unused-parameter -Wno-unused-function -Wno-maybe-uninitialized -std=c++14 -MD -MT robot_model/CMakeFiles/moveit_robot_model.dir/src/planar_joint_model.cpp.o -MF robot_model/CMakeFiles/moveit_robot_model.dir/src/planar_joint_model.cpp.o.d -o robot_model/CMakeFiles/moveit_robot_model.dir/src/planar_joint_model.cpp.o -c /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/robot_model/src/planar_joint_model.cpp
/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/moveit-core/2.1.1-1-r0/git/robot_model/src/planar_joint_model.cpp:40:10: fatal error: angles/angles.h: No such file or directory
   40 | #include <angles/angles.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>