packagegroup-ros1-industrial-core: move to meta-ros1-melodic
* this packagegroup probably isn't used much and works only
  with melodic

* without melodic it fails with:
ERROR: Nothing RPROVIDES 'industrial-trajectory-filters' (but /OE/meta-ros/meta-ros1/recipes-core/packagegroups/packagegroup-ros1-industrial-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'industrial-trajectory-filters' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['industrial-trajectory-filters']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-ros1-industrial-core', 'industrial-trajectory-filters']

* and the next ROS 1 distro noetic doesn't have industrial-trajectory-filters
  yet, so lets move the packagegroup to be in melodic specific layer

Signed-off-by: Martin Jansa <martin.jansa@lge.com>