{melodic} packagegroup-ros-world-melodic: remove runtime dependency on empty azure-iot-sdk-c
* fixes:
ERROR: ros-image-world-1.0-r0 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install connman packagegroup-core-boot packagegroup-ros-world run-postinsts' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-ros-world-1.0-r0.qemux86_64 requires packagegroup-ros-world-melodic, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides azure-iot-sdk-c needed by packagegroup-ros-world-melodic-1.0-r0.qemux86_64
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

Signed-off-by: Martin Jansa <martin.jansa@lge.com>