{melodic} ros-distro.inc: add mapping for python-autobahn for rosbridge-server
* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-python-autobahn' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rosbridge-suite/rosbridge-server_0.11.4-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python-autobahn' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python-autobahn']
NOTE: Runtime target 'roswww' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roswww', 'rosbridge-server', 'UNRESOLVED-python-autobahn']
NOTE: Runtime target 'roswww-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roswww-dev', 'rosbridge-server', 'UNRESOLVED-python-autobahn']
NOTE: Runtime target 'rosbridge-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbridge-server', 'UNRESOLVED-python-autobahn']
NOTE: Runtime target 'swri-profiler' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-profiler', 'rosbridge-server', 'UNRESOLVED-python-autobahn']
NOTE: Runtime target 'swri-profiler-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-profiler-dev', 'rosbridge-server', 'UNRESOLVED-python-autobahn']
NOTE: Runtime target 'rosbridge-suite' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbridge-suite', 'rosbridge-server', 'UNRESOLVED-python-autobahn']
NOTE: Runtime target 'rosbridge-suite-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbridge-suite-dev', 'rosbridge-server', 'UNRESOLVED-python-autobahn']
ERROR: Nothing RPROVIDES 'rosbridge-server-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rosbridge-suite/rosbridge-server_0.11.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rosbridge-server-dev'
NOTE: Runtime target 'rosbridge-server-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbridge-server-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>