{eloquent} libg2o: don't read /proc/cpuinfo to enable sse flags
* fixes:
ERROR: libg2o-2019.11.23-4-r0 do_compile: Execution of 'webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/temp/run.do_compile.11895' failed with exit code 1:
[1/219] webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++  -DUNIX -Dstuff_EXPORTS -Iwebos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot/usr/include/eigen3 -Iwebos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/git -I. -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0=/usr/src/debug/libg2o/2019.11.23-4-r0                      -fdebug-prefix-map=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0=/usr/src/debug/libg2o/2019.11.23-4-r0                      -fdebug-prefix-map=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot=                      -fdebug-prefix-map=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot  -Wall -W -DNDEBUG -O3 -fPIC   -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -std=gnu++11 -MD -MT g2o/stuff/CMakeFiles/stuff.dir/timeutil.cpp.o -MF g2o/stuff/CMakeFiles/stuff.dir/timeutil.cpp.o.d -o g2o/stuff/CMakeFiles/stuff.dir/timeutil.cpp.o -c webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/git/g2o/stuff/timeutil.cpp
FAILED: g2o/stuff/CMakeFiles/stuff.dir/timeutil.cpp.o
webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++  -DUNIX -Dstuff_EXPORTS -Iwebos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot/usr/include/eigen3 -Iwebos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/git -I. -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0=/usr/src/debug/libg2o/2019.11.23-4-r0                      -fdebug-prefix-map=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0=/usr/src/debug/libg2o/2019.11.23-4-r0                      -fdebug-prefix-map=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot=                      -fdebug-prefix-map=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/recipe-sysroot  -Wall -W -DNDEBUG -O3 -fPIC   -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -std=gnu++11 -MD -MT g2o/stuff/CMakeFiles/stuff.dir/timeutil.cpp.o -MF g2o/stuff/CMakeFiles/stuff.dir/timeutil.cpp.o.d -o g2o/stuff/CMakeFiles/stuff.dir/timeutil.cpp.o -c webos-eloquent-zeus/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libg2o/2019.11.23-4-r0/git/g2o/stuff/timeutil.cpp
arm-webos-linux-gnueabi-g++: error: unrecognized command line option '-msse2'
arm-webos-linux-gnueabi-g++: error: unrecognized command line option '-msse3'
arm-webos-linux-gnueabi-g++: error: unrecognized command line option '-mssse3'
arm-webos-linux-gnueabi-g++: error: unrecognized command line option '-msse4.1'
arm-webos-linux-gnueabi-g++: error: unrecognized command line option '-msse4.2'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>