{rolling} pybind11-vendor: allow empty PN
* now the PN package is used only to pull python3-pybind11 into the image
* but we need PN package to be created as rosbag2-py now has runtime dependency on it
* fixes:
ERROR: Unable to install packages. Command 'TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/webos-image-ros-world/1.0-r3/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/webos-image-ros-world/1.0-r3/opkg.conf -t TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/webos-image-ros-world/1.0-r3/temp/ipktemp/ -o TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/webos-image-ros-world/1.0-r3/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends update-rc.d install bluez-firmware-rpidistro-bcm4345c0-hcd kernel-module-i2c-dev kernel-module-spi-bcm2835 kernel-module-spidev kernel-modules linux-firmware-rpidistro-bcm43455 opkg os-release ostree ostree-initramfs ostree-kernel packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-ros-world packagegroup-webos-extended run-postinsts udev-rules-rpi' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-ros-world-1.0-r0.raspberrypi4 requires packagegroup-ros-world-rolling, but none of the providers can be installed
 *   - package packagegroup-ros-world-rolling-1.0-r0.raspberrypi4 requires rosbag2-py, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides pybind11-vendor needed by rosbag2-py-0.6.0-1-r0.raspberrypi4
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

Signed-off-by: Martin Jansa <martin.jansa@lge.com>