{melodic} kinesis-manager: import fix from dashing
* fixes:
DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
-- Check for working C compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as static objects
-- Generating linux build config
-- Building project version: 1.6.53
-- Found AWS SDK for C++, Version: 1.6.53, Install Root:ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/recipe-sysroot/usr, Platform Prefix:, Platform Dependent Libraries: pthread;crypto;ssl;z;curl
-- Found CURL: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/recipe-sysroot/usr/lib/libcurl.so (found version "7.61.0")
CMake Warning at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/recipe-sysroot/usr/share/aws_common/cmake/DefineTestMacros.cmake:37 (message):
  Could not find catkin or ament!
Call Stack (most recent call first):
  CMakeLists.txt:63 (find_common_test_packages)

CMake Warning at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/recipe-sysroot/usr/share/aws_common/cmake/DefineTestMacros.cmake:56 (message):
  Not building tests as neither catkin nor ament were found.
Call Stack (most recent call first):
  CMakeLists.txt:65 (add_common_gtest)

CMake Error at CMakeLists.txt:68 (target_include_directories):
  Cannot specify include directories for target "test_kinesis_manager" which
  is not built by this project.

CMake Error at CMakeLists.txt:72 (target_link_libraries):
  Cannot specify link libraries for target "test_kinesis_manager" which is
  not built by this project.

-- Configuring incomplete, errors occurred!
See also "ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/kinesis-manager/2.0.1-1-r0/temp/log.do_configure.76349)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>