{rolling} fastrtps: backport a patch for compatibility with old toolchain on host
* building new version of rmw-fastrtps-shared-cpp-native fails on Ubuntu-18.04
  with gcc-7 with:
ERROR: rmw-fastrtps-shared-cpp-native-5.0.0-1-r0 do_compile: Execution of '/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/temp/run.do_compile.75430' failed with exit code 1:
[1/2] /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/hosttools/g++ -DFOONATHAN_MEMORY=1 -DFOONATHAN_MEMORY_VERSION_MAJOR=0 -DFOONATHAN_MEMORY_VERSION_MINOR=6 -DFOONATHAN_MEMORY_VERSION_PATCH=2 -DRMW_FASTRTPS_SHARED_CPP_BUILDING_LIBRARY -DROS_PACKAGE_NAME=\"rmw_fastrtps_shared_cpp\" -Drmw_fastrtps_shared_cpp_EXPORTS -I/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/git/include -I/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/recipe-sysroot-native/usr/include/foonathan_memory/comp -I/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/recipe-sysroot-native/usr/include/foonathan_memory -isystem/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/recipe-sysroot-native/usr/include -O2 -pipe -fPIC -Wall -Wextra -Wpedantic -std=gnu++14 -MD -MT CMakeFiles/rmw_fastrtps_shared_cpp.dir/src/utils.cpp.o -MF CMakeFiles/rmw_fastrtps_shared_cpp.dir/src/utils.cpp.o.d -o CMakeFiles/rmw_fastrtps_shared_cpp.dir/src/utils.cpp.o -c /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/git/src/utils.cpp
FAILED: CMakeFiles/rmw_fastrtps_shared_cpp.dir/src/utils.cpp.o
/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/hosttools/g++ -DFOONATHAN_MEMORY=1 -DFOONATHAN_MEMORY_VERSION_MAJOR=0 -DFOONATHAN_MEMORY_VERSION_MINOR=6 -DFOONATHAN_MEMORY_VERSION_PATCH=2 -DRMW_FASTRTPS_SHARED_CPP_BUILDING_LIBRARY -DROS_PACKAGE_NAME=\"rmw_fastrtps_shared_cpp\" -Drmw_fastrtps_shared_cpp_EXPORTS -I/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/git/include -I/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/recipe-sysroot-native/usr/include/foonathan_memory/comp -I/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/recipe-sysroot-native/usr/include/foonathan_memory -isystem/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/recipe-sysroot-native/usr/include -O2 -pipe -fPIC -Wall -Wextra -Wpedantic -std=gnu++14 -MD -MT CMakeFiles/rmw_fastrtps_shared_cpp.dir/src/utils.cpp.o -MF CMakeFiles/rmw_fastrtps_shared_cpp.dir/src/utils.cpp.o.d -o CMakeFiles/rmw_fastrtps_shared_cpp.dir/src/utils.cpp.o -c /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/git/src/utils.cpp
/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/git/src/utils.cpp: In function ?bool rmw_fastrtps_shared_cpp::find_and_check_topic_and_type(const CustomParticipantInfo*, const string&, const string&, eprosima::fastdds::dds::TopicDescription**, eprosima::fastdds::dds::TypeSupport*)?:
/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/git/src/utils.cpp:107:71: error: use of deleted function ?eprosima::fastdds::dds::TypeSupport& eprosima::fastdds::dds::TypeSupport::operator=(const eprosima::fastdds::dds::TypeSupport&)?
   *returned_type = participant_info->participant_->find_type(type_name);
                                                                       ^
In file included from /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/git/include/rmw_fastrtps_shared_cpp/utils.hpp:22:0,
                 from /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/git/src/utils.cpp:17:
/jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/x86_64-linux/rmw-fastrtps-shared-cpp-native/5.0.0-1-r0/recipe-sysroot-native/usr/include/fastdds/dds/topic/TypeSupport.hpp:50:7: note: ?eprosima::fastdds::dds::TypeSupport& eprosima::fastdds::dds::TypeSupport::operator=(const eprosima::fastdds::dds::TypeSupport&)? is implicitly declared as deleted because ?eprosima::fastdds::dds::TypeSupport? declares a move constructor or move assignment operator
 class TypeSupport : public std::shared_ptr<fastdds::dds::TopicDataType>
       ^~~~~~~~~~~

  current code requires gcc-9.1 and newer as it targets Ubuntu-20.04 (officially
  supported platform of Foxy, Rolling, Galactic). gcc-cross in OE is new enough
  (9 in dunfell, 10.2 in gatesgarth and hardknott), but in this case it was building
  native, so using host's gcc-7.

  https://github.com/ros2/rmw_fastrtps/pull/518#issuecomment-820764350
  https://github.com/eProsima/Fast-DDS/pull/1912

Signed-off-by: Martin Jansa <martin.jansa@lge.com>