{noetic} rc-genicam-driver: restrict because of rc-genicam-api
fixes:
ERROR: Nothing PROVIDES 'rc-genicam-api' (but /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rc-genicam-driver/rc-genicam-driver_0.2.0-1.bb DEPENDS on or otherwise requires it)
rc-genicam-api was skipped: incompatible with machine raspberrypi4 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'rc-genicam-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-genicam-driver', 'rc-genicam-api']
NOTE: Runtime target 'packagegroup-ros-world-noetic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-noetic', 'rc-genicam-driver', 'rc-genicam-api']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'rc-genicam-driver', 'rc-genicam-api']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'rc-genicam-driver', 'rc-genicam-api']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>