{noetic} leo-robot: add restriction with 'ffmpeg', 'x264', 'gazebo', 'python-whichcraft'
* fixes:
ERROR: Nothing RPROVIDES 'leo-bringup' (but /jenkins/home/anaconda/ros1-noetic-dunfell/meta-ros/meta-ros1-noetic/generated-recipes/leo-robot/leo-robot_1.2.1-1.bb RDEPENDS on or otherwise requires it)
leo-bringup was skipped: Recipe is blacklisted: ffmpeg: Depends on web-video-server which depends on ffmpeg which requires commercial license; x264: Depends on web-video-server which depends on ffmpeg which depends on x264 which requires commercial license
NOTE: Runtime target 'leo-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-bringup']
ERROR: Nothing RPROVIDES 'leo-robot' (but /jenkins/home/anaconda/ros1-noetic-dunfell/meta-ros/meta-ros1-noetic/generated-recipes/leo-robot/leo-robot_1.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'leo-robot'
NOTE: Runtime target 'leo-robot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-robot']
ERROR: Nothing RPROVIDES 'leo-robot-dev' (but /jenkins/home/anaconda/ros1-noetic-dunfell/meta-ros/meta-ros1-noetic/generated-recipes/leo-robot/leo-robot_1.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'leo-robot-dev'
NOTE: Runtime target 'leo-robot-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-robot-dev']
ERROR: Nothing RPROVIDES 'leo-fw' (but /jenkins/home/anaconda/ros1-noetic-dunfell/meta-ros/meta-ros1-noetic/generated-recipes/leo-robot/leo-robot_1.2.1-1.bb RDEPENDS on or otherwise requires it)
leo-fw was skipped: Recipe is blacklisted: Rdepends on python-whichcraft which is not available
NOTE: Runtime target 'leo-fw' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-fw']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>