{melodic} kobuki-ftdi: blacklist because of dependency on old libftdi
* issue reported upstream:
  https://github.com/kobuki-base/kobuki_ftdi/issues/3

* remove the dependency from kobuki-core to resolve:
  ERROR: Nothing PROVIDES 'kobuki-ftdi' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/kobuki-core/kobuki-core_0.7.8.bb DEPENDS on or otherwise requires it)
  No eligible PROVIDERs exist for 'kobuki-ftdi'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>