{melodic} {crystal} {dashing}: behaviortree-cpp-v3/behaviortree-cpp-v3: migrate .inc to .bbappend
* notice typo in directory name in
  includes-ros1/behaviotree-cpp-v3/behaviortree-cpp-v3.inc
  so it wasn't applied until now, but is needed even in dashing:
  ERROR: behaviortree-cpp-v3-3.0.9-1-r0 do_package: QA Issue: behaviortree-cpp-v3: Files/directories were installed but not shipped in any package:
    /usr/lib/BehaviorTree
    /usr/lib/BehaviorTree/cmake
    /usr/lib/BehaviorTree/cmake/BehaviorTreeConfig-noconfig.cmake
    /usr/lib/BehaviorTree/cmake/BehaviorTreeConfig.cmake
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  behaviortree-cpp-v3: 4 installed and not shipped files. [installed-vs-shipped]
  ERROR: behaviortree-cpp-v3-3.0.9-1-r0 do_package: Fatal QA errors found, failing task.
  ERROR: behaviortree-cpp-v3-3.0.9-1-r0 do_package: Function failed: do_package
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-v3/artifacts/BUILD-webos-dashing-thud.mcf/work/qemux86-webos-linux/behaviortree-cpp-v3/3.0.9-1-r0/temp/log.do_package.19278
  ERROR: Task (/jenkins/mjansa/build-ros-v3/meta-ros/meta-ros2-dashing/generated-recipes/behaviortree-cpp-v3/behaviortree-cpp-v3_3.0.9-1.bb:do_package) failed with exit code '1'

* dashing version doesn't install the tinyxml.pc file, but lets keep it simple and identical .bbappends
  $ find artifacts/BUILD-webos-dashing-thud.mcf/work/qemux86-webos-linux/behaviortree-cpp-v3/3.0.9-1-r0/packages-split/ -name \*tinyxml\*
  artifacts/BUILD-webos-dashing-thud.mcf/work/qemux86-webos-linux/behaviortree-cpp-v3/3.0.9-1-r0/packages-split/behaviortree-cpp-v3-dbg/usr/src/debug/behaviortree-cpp-v3/3.0.9-1-r0/git/src/private/tinyxml2.cpp
  artifacts/BUILD-webos-dashing-thud.mcf/work/qemux86-webos-linux/behaviortree-cpp-v3/3.0.9-1-r0/packages-split/behaviortree-cpp-v3-dbg/usr/src/debug/behaviortree-cpp-v3/3.0.9-1-r0/git/src/private/tinyxml2.h

Signed-off-by: Martin Jansa <martin.jansa@lge.com>