{rolling} builtin-interfaces: Remove depends on rosidl-default-runtime
The explicit dependency for builtin-interfaces on rosidl-default-runtime
now causes a circular dependency.

  ERROR: 1061 unbuildable tasks were found.

  These are usually caused by circular dependencies and any circular dependency
  chains found will be printed below. Increase the debug level to see a list of
  unbuildable tasks.

  Identifying dependency loops (this may take a short while)...

The dependency chain is rosidl-default-runtime, service-msgs,
builtin-interfaces, back to rosidl-default-runtime.

For more details see:
  https://index.ros.org/p/service_msgs/github-ros2-rcl_interfaces/#rolling-deps

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>