{ros1} ros_catkin.bbclass: set PYTHON_EXECUTABLE_TARGET also for native builds
* otherwise e.g. ros-environment-native and genmsg-native were failing, because
  the generated _setup_util.py from
  catkin-native/0.8.10-1-r0/recipe-sysroot-native/usr/opt/ros/noetic/share/catkin/cmake/templates/_setup_util.py.in
  had empty shebang (from empty PYTHON_EXECUTABLE_TARGET):

  diff -uNr webos-melodic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py
  --- webos-melodic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py   2021-05-21 08:29:45.000000000 -0700
  +++ webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py    2021-05-24 03:22:58.000000000 -0700
  @@ -1,4 +1,4 @@
  -#!/usr/bin/env python
  +#!
   # -*- coding: utf-8 -*-

   # Software License Agreement (BSD License)
  @@ -62,7 +62,7 @@
       'LD_LIBRARY_PATH' if not IS_DARWIN else 'DYLD_LIBRARY_PATH': ['lib', os.path.join('lib', 'x86_64-linux-gnu')],
       'PATH': PATH_TO_ADD_SUFFIX,
       'PKG_CONFIG_PATH': [os.path.join('lib', 'pkgconfig'), os.path.join('lib', 'x86_64-linux-gnu', 'pkgconfig')],
  -    'PYTHONPATH': 'lib/python2.7/site-packages',
  +    'PYTHONPATH': 'lib/python3.9/site-packages',
   }

* fixes genmsg-native:
-- BUILD_SHARED_LIBS is on
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 36: This file generates shell code for the setup.SHELL scripts to set environment variables.: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 38: from: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 40: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 41: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 42: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 43: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 44: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 45: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 47: CATKIN_MARKER_FILE: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 49: syntax error near unexpected token `('
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py: line 49: `system = platform.system()'
Traceback (most recent call last):
  File "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/build/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/env.sh')
  File "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/recipe-sysroot-native/usr/opt/ros/noetic/lib/python3.9/site-packages/catkin/environment_cache.py", line 63, in generate_environment_script
    env_after = ast.literal_eval(output.decode('utf8'))
  File "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/recipe-sysroot-native/usr/lib/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/recipe-sysroot-native/usr/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    Could not write the output of '/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/devel/_setup_util.py' to temporary file '/tmp/setup.sh.gV5m0pfOH3': may be the disk if full?
              ^
SyntaxError: invalid syntax
CMake Error at /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/recipe-sysroot-native/usr/opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
  "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/build/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/recipe-sysroot-native/usr/opt/ros/noetic/share/catkin/cmake/all.cmake:209 (safe_execute_process)
  /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/genmsg-native/0.5.16-1-r0/recipe-sysroot-native/usr/opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:3 (find_package)

* and ros-environment-native:
-- BUILD_SHARED_LIBS is on
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 36: This file generates shell code for the setup.SHELL scripts to set environment variables.: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 38: from: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 40: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 41: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 42: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 43: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 44: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 45: import: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 47: CATKIN_MARKER_FILE: command not found
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 49: syntax error near unexpected token `('
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py: line 49: `system = platform.system()'
Traceback (most recent call last):
  File "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/build/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/env.sh')
  File "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/recipe-sysroot-native/usr/opt/ros/noetic/lib/python3.9/site-packages/catkin/environment_cache.py", line 63, in generate_environment_script
    env_after = ast.literal_eval(output.decode('utf8'))
  File "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/recipe-sysroot-native/usr/lib/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/recipe-sysroot-native/usr/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    Could not write the output of '/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/devel/_setup_util.py' to temporary file '/tmp/setup.sh.i1IWD6h3kI': may be the disk if full?
              ^
SyntaxError: invalid syntax
CMake Error at /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/recipe-sysroot-native/usr/opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
  "/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/build/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/recipe-sysroot-native/usr/opt/ros/noetic/share/catkin/cmake/all.cmake:209 (safe_execute_process)
  /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/x86_64-linux/ros-environment-native/1.3.2-1-r0/recipe-sysroot-native/usr/opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:3 (find_package)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>