{noetic} resolve dependency issues in new recipes
* fixes:
NOTE: Multiple providers are available for runtime fuse-doc (fuse-doc, fuse)
Consider defining a PREFERRED_RPROVIDER entry to match fuse-doc
ERROR: Nothing PROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/fuse/fuse-viz_0.4.2-1.bb DEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'fuse-viz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse-viz', 'rviz']
NOTE: Runtime target 'packagegroup-ros-world-noetic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-noetic', 'fuse-viz', 'rviz']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'fuse-viz', 'rviz']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'fuse-viz', 'rviz']
NOTE: Runtime target 'fuse' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse', 'fuse-viz', 'rviz']
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/fuse/fuse-viz_0.4.2-1.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
ERROR: Nothing PROVIDES 'moveit-ros-planning-interface' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb DEPENDS on or otherwise requires it)
moveit-ros-planning-interface was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'webots-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros', 'moveit-ros-planning-interface']
ERROR: Nothing PROVIDES 'ros-controllers' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb DEPENDS on or otherwise requires it)
ros-controllers was skipped: Recipe is blacklisted: Requires rqt-joint-trajectory-controller->rqt-gui-py->qt-gui->qtbase which requires meta-qt5 to be included and rqt-joint-trajectory-controller->rqt-gui-py->qt-gui->python-pyqt5 which requires pyqt5
ERROR: Nothing PROVIDES 'gazebo-ros-control' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/open-manipulator-p-simulations/open-manipulator-p-gazebo_1.0.1-1.bb DEPENDS on or otherwise requires it)
gazebo-ros-control was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'open-manipulator-p-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-p-gazebo', 'gazebo-ros-control']
NOTE: Runtime target 'open-manipulator-p-simulations' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-p-simulations', 'open-manipulator-p-gazebo', 'gazebo-ros-control']
ERROR: Nothing PROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/open-manipulator-p-simulations/open-manipulator-p-gazebo_1.0.1-1.bb, /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/thunder-line-follower-pmr3100/thunder-line-follower-pmr3100_0.1.1-1.bb DEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'thunder-line-follower-pmr3100' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['thunder-line-follower-pmr3100', 'gazebo-ros']
ERROR: Nothing PROVIDES 'gazebo-plugins' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/thunder-line-follower-pmr3100/thunder-line-follower-pmr3100_0.1.1-1.bb DEPENDS on or otherwise requires it)
gazebo-plugins was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-rosdev which is not available
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-gazebo' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/thunder-line-follower-pmr3100/thunder-line-follower-pmr3100_0.1.1-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'fuse-viz-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/fuse/fuse-viz_0.4.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'fuse-viz-dev'
NOTE: Runtime target 'fuse-viz-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse-viz-dev']
ERROR: Nothing RPROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/fuse/fuse-viz_0.4.2-1.bb RDEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz']
ERROR: Nothing RPROVIDES 'fuse-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/fuse/fuse_0.4.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'fuse-dev'
NOTE: Runtime target 'fuse-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse-dev']
ERROR: Nothing RPROVIDES 'webots-ros-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros-dev'
NOTE: Runtime target 'webots-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros-dev']
ERROR: Nothing RPROVIDES 'moveit-ros-planning-interface' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-planning-interface was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-ros-planning-interface' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-planning-interface']
ERROR: Nothing RPROVIDES 'ros-controllers' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb RDEPENDS on or otherwise requires it)
ros-controllers was skipped: Recipe is blacklisted: Requires rqt-joint-trajectory-controller->rqt-gui-py->qt-gui->qtbase which requires meta-qt5 to be included and rqt-joint-trajectory-controller->rqt-gui-py->qt-gui->python-pyqt5 which requires pyqt5
NOTE: Runtime target 'ros-controllers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-controllers']
ERROR: Nothing RPROVIDES 'open-manipulator-p-gazebo-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/open-manipulator-p-simulations/open-manipulator-p-gazebo_1.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'open-manipulator-p-gazebo-dev'
NOTE: Runtime target 'open-manipulator-p-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-p-gazebo-dev']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/open-manipulator-p-simulations/open-manipulator-p-gazebo_1.0.1-1.bb, /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/thunder-line-follower-pmr3100/thunder-line-follower-pmr3100_0.1.1-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
ERROR: Nothing RPROVIDES 'gazebo-ros-control' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/open-manipulator-p-simulations/open-manipulator-p-gazebo_1.0.1-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros-control was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-control']
ERROR: Nothing RPROVIDES 'open-manipulator-p-simulations-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/open-manipulator-p-simulations/open-manipulator-p-simulations_1.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'open-manipulator-p-simulations-dev'
NOTE: Runtime target 'open-manipulator-p-simulations-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-p-simulations-dev']
ERROR: Nothing RPROVIDES 'gazebo-plugins' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/thunder-line-follower-pmr3100/thunder-line-follower-pmr3100_0.1.1-1.bb RDEPENDS on or otherwise requires it)
gazebo-plugins was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-rosdev which is not available
NOTE: Runtime target 'gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-plugins']
ERROR: Nothing RPROVIDES 'thunder-line-follower-pmr3100-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/thunder-line-follower-pmr3100/thunder-line-follower-pmr3100_0.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'thunder-line-follower-pmr3100-dev'
NOTE: Runtime target 'thunder-line-follower-pmr3100-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['thunder-line-follower-pmr3100-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-python-pygame' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/thunder-line-follower-pmr3100/thunder-line-follower-pmr3100_0.1.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-python-pygame' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-python-pygame']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-gazebo' (but /jenkins/mjansa/build/ros/ros1-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/thunder-line-follower-pmr3100/thunder-line-follower-pmr3100_0.1.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-gazebo']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>