{iron} libstatistics-collector: Add missing cstdint
The libstatistics-collector recipe fails with the following errors:

libstatistics-collector/1.5.1-2/git/include/libstatistics_collector/moving_average_statistics/types.hpp:43:3: error: 'uint64_t' does not name a type

Upstream-Status: Backport [1c340c97c731019d0c7b40f8c167b0ef666bcf75]

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>