{rolling} resolve dependency issues in new recipes
* fixes:
ERROR: Nothing PROVIDES 'gazebo-ros-pkgs' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/turtlebot3-simulations/turtlebot3-gazebo_2.2.5-1.bb DEPENDS on or otherwise requires it)
gazebo-ros-pkgs was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'turtlebot3-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-gazebo', 'gazebo-ros-pkgs']
NOTE: Runtime target 'turtlebot3-simulations' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-simulations', 'turtlebot3-gazebo', 'gazebo-ros-pkgs']
ERROR: Nothing RPROVIDES 'rmf-robot-sim-gazebo-plugins' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rmf-demos/rmf-demos-gz_1.3.0-1.bb RDEPENDS on or otherwise requires it)
rmf-robot-sim-gazebo-plugins was skipped: Recipe is blacklisted: gazebo: depends on gazebo-ros,gazebo-rosdev->gazebo which is not available; qt5: depends on qtbase
NOTE: Runtime target 'rmf-robot-sim-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-robot-sim-gazebo-plugins']
NOTE: Runtime target 'rmf-demos-gz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-demos-gz', 'rmf-robot-sim-gazebo-plugins']
NOTE: Runtime target 'rmf-demos-gz-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-demos-gz-dev', 'rmf-robot-sim-gazebo-plugins']
ERROR: Nothing RPROVIDES 'rmf-demos' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rmf-demos/rmf-demos-gz_1.3.0-1.bb, /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rmf-demos/rmf-demos-ign_1.3.0-1.bb RDEPENDS on or otherwise requires it)
rmf-demos was skipped: Recipe is blacklisted: gazebo: rdepends on rmf-robot-sim-gazebo-plugins, rmf-building-sim-gazebo-plugins which depend on gazebo-ros,gazebo-rosdev->gazebo which is not available; qt5: rdepends on rmf-robot-sim-gazebo-plugins, rmf-building-sim-gazebo-plugins which depend on qtbase
NOTE: Runtime target 'rmf-demos' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-demos']
NOTE: Runtime target 'rmf-demos-ign' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-demos-ign', 'rmf-demos']
ERROR: Nothing RPROVIDES 'rmf-building-sim-gazebo-plugins' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rmf-demos/rmf-demos-gz_1.3.0-1.bb RDEPENDS on or otherwise requires it)
rmf-building-sim-gazebo-plugins was skipped: Recipe is blacklisted: gazebo: depends on gazebo-ros,gazebo-rosdev->gazebo which is not available; qt5: depends on qtbase
NOTE: Runtime target 'rmf-building-sim-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-building-sim-gazebo-plugins']
ERROR: Nothing RPROVIDES 'rmf-demos-ign-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rmf-demos/rmf-demos-ign_1.3.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rmf-demos-ign-dev'
NOTE: Runtime target 'rmf-demos-ign-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-demos-ign-dev']
ERROR: Nothing RPROVIDES 'ros-ign-bridge' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rmf-demos/rmf-demos-ign_1.3.0-1.bb RDEPENDS on or otherwise requires it)
ros-ign-bridge was skipped: Recipe is blacklisted: ignition: depends on unavailable ROS_UNRESOLVED_DEP-ignition-msgs7, ROS_UNRESOLVED_DEP-ignition-transport10
NOTE: Runtime target 'ros-ign-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-ign-bridge']
ERROR: Nothing RPROVIDES 'rmf-building-sim-ignition-plugins' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rmf-demos/rmf-demos-ign_1.3.0-1.bb RDEPENDS on or otherwise requires it)
rmf-building-sim-ignition-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase, libqt5-qml, libqt5-quick
NOTE: Runtime target 'rmf-building-sim-ignition-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-building-sim-ignition-plugins']
ERROR: Nothing RPROVIDES 'rmf-robot-sim-ignition-plugins' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rmf-demos/rmf-demos-ign_1.3.0-1.bb RDEPENDS on or otherwise requires it)
rmf-robot-sim-ignition-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase, libqt5-qml, libqt5-quick
NOTE: Runtime target 'rmf-robot-sim-ignition-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-robot-sim-ignition-plugins']
ERROR: Nothing RPROVIDES 'webots-ros2-core' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/webots-ros2/webots-ros2-mavic_1.1.1-1.bb RDEPENDS on or otherwise requires it)
webots-ros2-core was skipped: Recipe is blacklisted: webots-python-modules: requires python-transforms3d-pip which is not available in OE yet
NOTE: Runtime target 'webots-ros2-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-core']
NOTE: Runtime target 'webots-ros2-mavic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-mavic', 'webots-ros2-core']
ERROR: Nothing RPROVIDES 'webots-ros2-mavic-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/webots-ros2/webots-ros2-mavic_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros2-mavic-dev'
NOTE: Runtime target 'webots-ros2-mavic-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-mavic-dev']
ERROR: Nothing RPROVIDES 'turtlebot3-simulations-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/turtlebot3-simulations/turtlebot3-simulations_2.2.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtlebot3-simulations-dev'
NOTE: Runtime target 'turtlebot3-simulations-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-simulations-dev']
ERROR: Nothing RPROVIDES 'gazebo-ros-pkgs' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/turtlebot3-simulations/turtlebot3-gazebo_2.2.5-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros-pkgs was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-ros-pkgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-pkgs']
ERROR: Nothing RPROVIDES 'turtlebot3-gazebo-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/turtlebot3-simulations/turtlebot3-gazebo_2.2.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtlebot3-gazebo-dev'
NOTE: Runtime target 'turtlebot3-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-gazebo-dev']