[master]{rolling}gz-utils-vendor: remove cli11 from RDEPENDS
cli11 is a header only C++ library, so the main package will be empty.[1]

ERROR: ros-image-desktop-1.0-r0 do_rootfs: Unable to install packages. Command '.../build/tmp/work/qemux86_64-oe-linux/ros-image-desktop/1.0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f .../build/tmp/work/qemux86_64-oe-linux/ros-image-desktop/1.0/opkg.conf -t .../build/tmp/work/qemux86_64-oe-linux/ros-image-desktop/1.0/temp/ipktemp/ -o .../build/tmp/work/qemux86_64-oe-linux/ros-image-desktop/1.0/rootfs  --force-postinstall --prefer-arch-to-version   install connman desktop opkg packagegroup-base-extended packagegroup-core-boot packagegroup-core-x11-base psplash run-postinsts' returned 1:
Solver encountered 1 problem(s):
Problem 1/1:
  - package rviz-default-plugins-15.1.12-1-r0.x86-64-v3 requires gz-math-vendor, but none of the providers can be installed
  - package desktop-0.13.0-1-r0.x86-64-v3 requires rviz-default-plugins, but none of the providers can be installed
  - package gz-math-vendor-0.4.2-1-r0.x86-64-v3 requires gz-utils-vendor, but none of the providers can be installed
  - conflicting requests
  - nothing provides cli11 needed by gz-utils-vendor-0.4.1-1-r0.x86-64-v3

Solution 1:
  - do not ask to install a package providing desktop

[1]: https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-support/cli11/cli11_2.6.1.bb?h=master#n15

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>