{foxy} webots-ros2-driver: fix build with python3 other than 3.8
* python3 support was added in:
  https://github.com/cyberbotics/webots_ros2/commit/b2e7635ecfddcb06ecd84e4ea1e7a0f7a0281385
  but it's not clear why only for exactly 3.8 version

* fixes:
ERROR: webots-ros2-driver-1.1.1-1-r0 do_configure: Execution of '/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/temp/run.do_configure.50710' failed with exit code 1:
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 0.9.9 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/ament_cmake/cmake)
-- Found PythonInterp: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.9.5", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
-- Found rosgraph_msgs: 1.0.0 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosgraph_msgs/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
CMake Warning at /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmake-extras.cmake:30 (find_package):
  By not providing "Findrosidl_adapter.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "rosidl_adapter", but CMake did not find one.

  Could not find a package configuration file provided by "rosidl_adapter"
  with any of the following names:

    rosidl_adapterConfig.cmake
    rosidl_adapter-config.cmake

  Add the installation prefix of "rosidl_adapter" to CMAKE_PREFIX_PATH or set
  "rosidl_adapter_DIR" to a directory containing one of the above files.  If
  "rosidl_adapter" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmakeConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/rosidl_generator_cConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_c-extras.cmake:11 (find_package)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_cConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtime-extras.cmake:12 (find_package)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtimeConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/builtin_interfacesConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosgraph_msgs/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rosgraph_msgs/cmake/rosgraph_msgsConfig.cmake:41 (include)
  CMakeLists.txt:10 (find_package)

-- Found OpenSSL: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/lib/libcrypto.so (found version "1.1.1l")
-- Found FastRTPS: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/include
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found rclcpp: 2.4.0 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rclcpp/cmake)
-- Found rmw_implementation_cmake: 1.0.3 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rmw_implementation_cmake/cmake)
-- Using RMW implementation 'rmw_fastrtps_cpp' as default
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found pluginlib: 2.5.3 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/pluginlib/cmake)
-- Found rclcpp_lifecycle: 2.4.0 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/rclcpp_lifecycle/cmake)
-- Found sensor_msgs: 2.0.4 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/sensor_msgs/cmake)
-- Found tf2_ros: 0.13.11 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/tf2_ros/cmake)
-- Found vision_msgs: 2.0.0 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/vision_msgs/cmake)
-- Found webots_ros2_msgs: 1.1.1 (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/share/webots_ros2_msgs/cmake)
-- Found TinyXML2: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/lib/libtinyxml2.so
CMake Error at /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find PythonLibs: Found unsuitable version "3.9.5", but required
  is exact version "3.8" (found
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot/usr/lib/libpython3.9.so)
Call Stack (most recent call first):
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:580 (_FPHSA_FAILURE_MESSAGE)
  /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/share/cmake-3.19/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:21 (find_package)

-- Configuring incomplete, errors occurred!
See also "/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/build/CMakeFiles/CMakeOutput.log".
See also "/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/build/CMakeFiles/CMakeError.log".
WARNING: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/temp/run.do_configure.50710:173 exit 1 from 'cmake -G 'Ninja' -DCMAKE_MAKE_PROGRAM=ninja $oecmake_sitefile /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/git -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_BINDIR:PATH=bin -DCMAKE_INSTALL_SBINDIR:PATH=sbin -DCMAKE_INSTALL_LIBEXECDIR:PATH=libexec -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc -DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=../com -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_INSTALL_INCLUDEDIR:PATH=include -DCMAKE_INSTALL_DATAROOTDIR:PATH=share -DPYTHON_EXECUTABLE:PATH=/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 -DPython_EXECUTABLE:PATH=/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 -DPython3_EXECUTABLE:PATH=/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 -DLIB_SUFFIX= -DCMAKE_INSTALL_SO_NO_EXE=0 -DCMAKE_TOOLCHAIN_FILE=/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/toolchain.cmake -DCMAKE_NO_SYSTEM_FROM_IMPORTED=1 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DBUILD_TESTING=OFF -DPYTHON_SOABI=cpython-39-x86_64-linux-gnu -Wno-dev'
WARNING: Backtrace (BB generated script):
	#1: cmake_do_configure, /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/temp/run.do_configure.50710, line 173
	#2: do_configure, /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/temp/run.do_configure.50710, line 152
	#3: main, /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/temp/run.do_configure.50710, line 208

Backtrace (metadata-relative locations):
	#1: cmake_do_configure, /jenkins/mjansa/build/ros/ros2-foxy-hardknott/openembedded-core/meta/classes/cmake.bbclass, line 171
	#2: do_configure, autogenerated, line 2
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/webots-ros2-driver/1.1.1-1-r0/temp/log.do_configure.50710
ERROR: Task (/jenkins/mjansa/build/ros/ros2-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/webots-ros2/webots-ros2-driver_1.1.1-1.bb:do_configure) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>