{noetic} catkin: Set LICENSE to BSD-3-Clause
Set LICENSE to "BSD-3-Clause" so that it gets recognized as an
SPDX identifier.

  ERROR: catkin-native-0.8.10-1-r0 do_create_spdx: Cannot find any text for license BSD

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>