{noetic} orocos-kdl: improve KDLConfig.cmake.in patch
* some recipes are depending on orocos-kdl to find Eigen3 for them
* trajectory-tracker:
FAILED: CMakeFiles/trajectory_tracker.dir/src/trajectory_tracker.cpp.o
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"trajectory_tracker\" -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/git/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/recipe-sysroot/usr/opt/ros/noetic/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/recipe-sysroot/usr/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -isystem TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/git/BEFORE -isystem TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/devel/include -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0=/usr/src/debug/trajectory-tracker/0.10.8-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0=/usr/src/debug/trajectory-tracker/0.10.8-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/recipe-sysroot -std=gnu++14 -MD -MT CMakeFiles/trajectory_tracker.dir/src/trajectory_tracker.cpp.o -MF CMakeFiles/trajectory_tracker.dir/src/trajectory_tracker.cpp.o.d -o CMakeFiles/trajectory_tracker.dir/src/trajectory_tracker.cpp.o -c TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/git/src/trajectory_tracker.cpp
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/trajectory-tracker/0.10.8-1-r0/git/src/trajectory_tracker.cpp:49:10: fatal error: Eigen/Core: No such file or directory
   49 | #include <Eigen/Core>
      |          ^~~~~~~~~~~~

* kdl-parser:
FAILED: CMakeFiles/kdl_parser.dir/src/kdl_parser.cpp.o
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DHAS_ROS -DHAS_URDF -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"kdl_parser\" -Dkdl_parser_EXPORTS -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/git/include -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0=/usr/src/debug/kdl-parser/1.14.1-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0=/usr/src/debug/kdl-parser/1.14.1-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot -fPIC -std=gnu++14 -MD -MT CMakeFiles/kdl_parser.dir/src/kdl_parser.cpp.o -MF CMakeFiles/kdl_parser.dir/src/kdl_parser.cpp.o.d -o CMakeFiles/kdl_parser.dir/src/kdl_parser.cpp.o -c TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/git/src/kdl_parser.cpp
In file included from TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot/usr/include/kdl/jntarray.hpp:26,
                 from TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot/usr/include/kdl/frames_io.hpp:81,
                 from TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/git/src/kdl_parser.cpp:45:
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/kdl-parser/1.14.1-1-r0/recipe-sysroot/usr/include/kdl/jacobian.hpp:26:10: fatal error: Eigen/Core: No such file or directory
   26 | #include <Eigen/Core>
      |          ^~~~~~~~~~~~

Signed-off-by: Martin Jansa <martin.jansa@lge.com>