{dashing} resolve dependency issues in new recipes
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-rospkg-native' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/mrt-cmake-modules/mrt-cmake-modules_1.0.8-1.bb DEPENDS on or otherwise requires it). Close matches:
  python3-rosdep-native
  python3-rospkg-native
NOTE: Runtime target 'mrt-cmake-modules' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrt-cmake-modules', 'UNRESOLVED-python3-rospkg-native']
NOTE: Runtime target 'packagegroup-ros-world-dashing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-dashing', 'mrt-cmake-modules', 'UNRESOLVED-python3-rospkg-native']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'mrt-cmake-modules', 'UNRESOLVED-python3-rospkg-native']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'mrt-cmake-modules', 'UNRESOLVED-python3-rospkg-native']
ERROR: Nothing PROVIDES 'UNRESOLVED-lcov-native' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/mrt-cmake-modules/mrt-cmake-modules_1.0.8-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'lanelet2-validation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-validation', 'mrt-cmake-modules-native']
NOTE: Runtime target 'lanelet2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2', 'lanelet2-validation', 'mrt-cmake-modules-native']
NOTE: Runtime target 'lanelet2-routing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-routing', 'mrt-cmake-modules-native']
NOTE: Runtime target 'lanelet2-examples' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-examples', 'lanelet2-routing', 'mrt-cmake-modules-native']
NOTE: Runtime target 'lanelet2-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-python', 'lanelet2-routing', 'mrt-cmake-modules-native']
NOTE: Runtime target 'lanelet2-projection' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-projection', 'lanelet2-io', 'mrt-cmake-modules-native']
NOTE: Runtime target 'lanelet2-io' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-io', 'mrt-cmake-modules-native']
NOTE: Runtime target 'lanelet2-maps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-maps', 'mrt-cmake-modules-native']
NOTE: Runtime target 'lanelet2-traffic-rules' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-traffic-rules', 'mrt-cmake-modules-native']
NOTE: Runtime target 'lanelet2-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-core', 'mrt-cmake-modules-native']
ERROR: Nothing PROVIDES 'lanelet2-core' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-validation_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-routing_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-io_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-examples_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-python_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-traffic-rules_1.1.1-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'lanelet2-core'
ERROR: Nothing PROVIDES 'lanelet2-routing' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-validation_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-examples_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-python_1.1.1-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'lanelet2-routing'
ERROR: Nothing PROVIDES 'lanelet2-projection' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-validation_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-examples_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-python_1.1.1-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'lanelet2-projection'
ERROR: Nothing PROVIDES 'lanelet2-traffic-rules' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-validation_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-routing_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-examples_1.1.1-1.bb, /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-python_1.1.1-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'lanelet2-traffic-rules'
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-serial' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/grbl-ros/grbl-ros_0.0.15-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'grbl-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['grbl-ros', 'UNRESOLVED-python3-serial']
NOTE: preferred version 3.6.1 of protobuf not available (for item protobuf)
NOTE: versions of protobuf available: 3.11.4 3.6.1+gitAUTOINC+48cb18e5c4
ERROR: Nothing PROVIDES 'UNRESOLVED-pugixml-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-io_1.1.1-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'lanelet2-python' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-examples_1.1.1-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'lanelet2-python'
ERROR: Nothing PROVIDES 'UNRESOLVED-libboost-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/image-pipeline/image-view_2.1.1-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'image-view' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-view', 'UNRESOLVED-libboost-dev']
NOTE: Runtime target 'image-pipeline' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-pipeline', 'image-view', 'UNRESOLVED-libboost-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-libboost-python-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-python_1.1.1-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'mrt-cmake-modules-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/mrt-cmake-modules/mrt-cmake-modules_1.0.8-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mrt-cmake-modules-dev'
NOTE: Runtime target 'mrt-cmake-modules-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrt-cmake-modules-dev']
ERROR: Nothing RPROVIDES 'lanelet2-validation-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-validation_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-validation-dev'
NOTE: Runtime target 'lanelet2-validation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-validation-dev']
ERROR: Nothing RPROVIDES 'grbl-ros-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/grbl-ros/grbl-ros_0.0.15-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'grbl-ros-dev'
NOTE: Runtime target 'grbl-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['grbl-ros-dev']
ERROR: Nothing RPROVIDES 'lanelet2-routing-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-routing_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-routing-dev'
NOTE: Runtime target 'lanelet2-routing-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-routing-dev']
NOTE: preferred version 3.6.1 of protobuf not available (for item protobuf)
NOTE: versions of protobuf available: 3.11.4 3.6.1+gitAUTOINC+48cb18e5c4
ERROR: Nothing RPROVIDES 'UNRESOLVED-pugixml-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-io_1.1.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-pugixml-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-pugixml-dev']
ERROR: Nothing RPROVIDES 'lanelet2-io-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-io_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-io-dev'
NOTE: Runtime target 'lanelet2-io-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-io-dev']
ERROR: Nothing RPROVIDES 'lanelet2-examples-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-examples_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-examples-dev'
NOTE: Runtime target 'lanelet2-examples-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-examples-dev']
ERROR: Nothing RPROVIDES 'image-pipeline-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/image-pipeline/image-pipeline_2.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'image-pipeline-dev'
NOTE: Runtime target 'image-pipeline-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-pipeline-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libboost-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/image-pipeline/image-view_2.1.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libboost-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libboost-dev']
ERROR: Nothing RPROVIDES 'image-view-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/image-pipeline/image-view_2.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'image-view-dev'
NOTE: Runtime target 'image-view-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-view-dev']
ERROR: Nothing RPROVIDES 'lanelet2-python-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-python_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-python-dev'
NOTE: Runtime target 'lanelet2-python-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-python-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libboost-python-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-python_1.1.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libboost-python-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libboost-python-dev']
ERROR: Nothing RPROVIDES 'lanelet2-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-dev'
NOTE: Runtime target 'lanelet2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-dev']
ERROR: Nothing RPROVIDES 'lanelet2-maps-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-maps_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-maps-dev'
NOTE: Runtime target 'lanelet2-maps-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-maps-dev']
ERROR: Nothing RPROVIDES 'lanelet2-projection-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-projection_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-projection-dev'
NOTE: Runtime target 'lanelet2-projection-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-projection-dev']
ERROR: Nothing RPROVIDES 'lanelet2-traffic-rules-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-traffic-rules_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-traffic-rules-dev'
NOTE: Runtime target 'lanelet2-traffic-rules-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-traffic-rules-dev']
ERROR: Nothing RPROVIDES 'lanelet2-core-dev' (but /jenkins/mjansa/build/ros/webos-dashing-dunfell/meta-ros/meta-ros2-dashing/generated-recipes/lanelet2/lanelet2-core_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-core-dev'
NOTE: Runtime target 'lanelet2-core-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-core-dev']