{dashing} ros-distro.inc: Set ROS_UNRESOLVED_PLATFORM_PKG_log4cplus to "log4cplus"
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-log4cplus' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/kinesis-manager/kinesis-manager_2.0.1-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'kinesis-video-streamer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['kinesis-video-streamer', 'kinesis-manager', 'UNRESOLVED-log4cplus']
NOTE: Runtime target 'kinesis-manager' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['kinesis-manager', 'UNRESOLVED-log4cplus']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>