Fixed compile error
- error log :

tmp/work/armv8a-oe4t-linux/ceres-solver/2.2.0/recipe-sysroot/usr/include/eigen3/Eigen/src/MetisSupport/MetisSupport.h:112:34: error: cannot convert 'int*' to 'idx_t*' {aka 'long int*'}

This error was from version upgrade from package version 2.1.0 to 2.2.0.

CMakeLists.txt is introduced new option,  EIGENSPARSE and it is turned on by default which also enable EIGENMETIS option to use eigen3 metis.

Signed-off-by: Mark Choi <afewgoodman.choi@gmail.com>