{rolling} resolve dependency issues in new recipes
* fixes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'ros-ign-gazebo' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb DEPENDS on or otherwise requires it)
ros-ign-gazebo was skipped: Recipe is blacklisted: ignition: depends on unavailable ROS_UNRESOLVED_DEP-ignition-gazebo5, ROS_UNRESOLVED_DEP-ignition-math6
NOTE: Runtime target 'dolly-ignition' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-ignition', 'ros-ign-gazebo']
NOTE: Runtime target 'packagegroup-ros-world-rolling' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-rolling', 'dolly-ignition', 'ros-ign-gazebo']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'dolly-ignition', 'ros-ign-gazebo']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'dolly-ignition', 'ros-ign-gazebo']
NOTE: Runtime target 'dolly' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly', 'dolly-ignition', 'ros-ign-gazebo']
ERROR: Nothing PROVIDES 'rviz-visual-tools' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit-visual-tools/moveit-visual-tools_4.0.0-1.bb DEPENDS on or otherwise requires it)
rviz-visual-tools was skipped: Recipe is blacklisted: opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'moveit-visual-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-visual-tools', 'rviz-visual-tools']
ERROR: Nothing RPROVIDES 'moveit-resources-panda-moveit-config' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit/run-move-group_2.3.0-1.bb, /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit/run-moveit-cpp_2.3.0-1.bb RDEPENDS on or otherwise requires it)
moveit-resources-panda-moveit-config was skipped: Recipe is blacklisted: qt5: rdepends on joint-state-publisher-gui which depends on python-qt-binding which depends on qtbase; pyqt5: rdepends on joint-state-publisher-gui which depends on python-qt-binding which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'moveit-resources-panda-moveit-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-resources-panda-moveit-config']
NOTE: Runtime target 'run-move-group' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['run-move-group', 'moveit-resources-panda-moveit-config']
NOTE: Runtime target 'run-move-group-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['run-move-group-dev', 'moveit-resources-panda-moveit-config']
NOTE: Runtime target 'run-moveit-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['run-moveit-cpp', 'moveit-resources-panda-moveit-config']
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit/run-move-group_2.3.0-1.bb, /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit/run-moveit-cpp_2.3.0-1.bb, /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb, /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/dolly/dolly-gazebo_0.4.0-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
NOTE: Runtime target 'dolly-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-gazebo', 'rviz2']
ERROR: Nothing RPROVIDES 'warehouse-ros-mongo' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit/run-move-group_2.3.0-1.bb, /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit/run-moveit-cpp_2.3.0-1.bb RDEPENDS on or otherwise requires it)
warehouse-ros-mongo was skipped: Recipe is blacklisted: Requires mongodb; mongodb-legacy-cxx-driver: requires unavailable mongo-cxx-driver-legacy
NOTE: Runtime target 'warehouse-ros-mongo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warehouse-ros-mongo']
ERROR: Nothing RPROVIDES 'run-moveit-cpp-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit/run-moveit-cpp_2.3.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'run-moveit-cpp-dev'
NOTE: Runtime target 'run-moveit-cpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['run-moveit-cpp-dev']
ERROR: Nothing RPROVIDES 'dolly-ignition-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dolly-ignition-dev'
NOTE: Runtime target 'dolly-ignition-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-ignition-dev']
ERROR: Nothing RPROVIDES 'ros-ign-bridge' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb RDEPENDS on or otherwise requires it)
ros-ign-bridge was skipped: Recipe is blacklisted: ignition: depends on unavailable ROS_UNRESOLVED_DEP-ignition-msgs7, ROS_UNRESOLVED_DEP-ignition-transport10
NOTE: Runtime target 'ros-ign-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-ign-bridge']
ERROR: Nothing RPROVIDES 'ros-ign-gazebo' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb RDEPENDS on or otherwise requires it)
ros-ign-gazebo was skipped: Recipe is blacklisted: ignition: depends on unavailable ROS_UNRESOLVED_DEP-ignition-gazebo5, ROS_UNRESOLVED_DEP-ignition-math6
NOTE: Runtime target 'ros-ign-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-ign-gazebo']
ERROR: Nothing RPROVIDES 'dolly-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/dolly/dolly_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dolly-dev'
NOTE: Runtime target 'dolly-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-dev']
ERROR: Nothing RPROVIDES 'dolly-gazebo-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/dolly/dolly-gazebo_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dolly-gazebo-dev'
NOTE: Runtime target 'dolly-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-gazebo-dev']
ERROR: Nothing RPROVIDES 'gazebo-ros-pkgs' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/dolly/dolly-gazebo_0.4.0-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros-pkgs was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-ros-pkgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-pkgs']
ERROR: Nothing RPROVIDES 'moveit-visual-tools-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit-visual-tools/moveit-visual-tools_4.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-visual-tools-dev'
NOTE: Runtime target 'moveit-visual-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-visual-tools-dev']
ERROR: Nothing RPROVIDES 'rviz-visual-tools' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/moveit-visual-tools/moveit-visual-tools_4.0.0-1.bb RDEPENDS on or otherwise requires it)
rviz-visual-tools was skipped: Recipe is blacklisted: opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-visual-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-tools']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-sqlite3' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/warehouse-ros-sqlite/warehouse-ros-sqlite_1.0.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-sqlite3' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-sqlite3']
NOTE: Runtime target 'warehouse-ros-sqlite' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warehouse-ros-sqlite', 'ROS_UNRESOLVED_DEP-sqlite3']
ERROR: Nothing RPROVIDES 'warehouse-ros-sqlite-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/warehouse-ros-sqlite/warehouse-ros-sqlite_1.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'warehouse-ros-sqlite-dev'
NOTE: Runtime target 'warehouse-ros-sqlite-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warehouse-ros-sqlite-dev']
ERROR: Nothing PROVIDES 'fastrtps-native' (but virtual:native:/jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rcl-interfaces/builtin-interfaces_1.1.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  attr-native
  fastcdr-native
  rmw-fastrtps-cpp-native
NOTE: Runtime target 'robot-localization' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-localization', 'builtin-interfaces-native', 'fastrtps-native']
NOTE: Runtime target 'robot-localization-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-localization-dev', 'builtin-interfaces-native', 'fastrtps-native']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>