{rolling} ros-distro.inc: Add ROS_UNRESOLVED_DEP-libyaml and -dev
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-libyaml-dev' (but meta-ros/meta-ros2-rolling/generated-recipes/libyaml-vendor/libyaml-vendor_1.6.2-1.bb DEPENDS on or otherwise requires it)

ERROR: Required build target 'ros-image-core' has no buildable providers.
Missing or unbuildable dependency chain was: ['ros-image-core', 'ros-core', 'rclcpp-lifecycle', 'rclcpp', 'rcl-yaml-param-parser', 'libyaml-vendor', 'ROS_UNRESOLVED_DEP-libyaml-dev']

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>