{dashing} ros-distro.inc: Set ROS_UNRESOLVED_PLATFORM_PKG_* for dependencies of tts
* Use gstreamer1.0-plugins-good, gstreamer1.0,
  gstreamer1.0-plugins-base, gstreamer1.0-python, and python3-boto3 as
  the values for the unresolved platform package mappings of the
  dependencies of tts.

* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-gstreamer1.0-plugins-good' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/tts/tts_2.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-gstreamer1.0-plugins-good' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-gstreamer1.0-plugins-good']
NOTE: Runtime target 'tts' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tts', 'UNRESOLVED-gstreamer1.0-plugins-good']
NOTE: Runtime target 'packagegroup-ros-world-dashing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-dashing', 'tts', 'UNRESOLVED-gstreamer1.0-plugins-good']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'tts', 'UNRESOLVED-gstreamer1.0-plugins-good']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'tts', 'UNRESOLVED-gstreamer1.0-plugins-good']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python-gst-1.0' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/tts/tts_2.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python-gst-1.0' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python-gst-1.0']
ERROR: Nothing RPROVIDES 'UNRESOLVED-gstreamer1.0' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/tts/tts_2.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-gstreamer1.0' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-gstreamer1.0']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python3-boto3' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/tts/tts_2.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python3-boto3' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python3-boto3']
ERROR: Nothing RPROVIDES 'tts-dev' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/tts/tts_2.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'tts-dev'
NOTE: Runtime target 'tts-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tts-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-gstreamer1.0-alsa' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/tts/tts_2.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-gstreamer1.0-alsa' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-gstreamer1.0-alsa']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>