{foxy} resolve dependency issues in new recipes
fixes:

ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-libomp-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/moveit/moveit-planners-ompl_2.1.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'moveit-planners-ompl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-planners-ompl', 'ROS_UNRESOLVED_DEP-libomp-dev']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'moveit-planners-ompl', 'ROS_UNRESOLVED_DEP-libomp-dev']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'moveit-planners-ompl', 'ROS_UNRESOLVED_DEP-libomp-dev']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'moveit-planners-ompl', 'ROS_UNRESOLVED_DEP-libomp-dev']
ERROR: Nothing PROVIDES 'qtsvg' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.0.0-2.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'plotjuggler-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plotjuggler-ros', 'qtsvg']
ERROR: Nothing PROVIDES 'qtwebsockets' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.0.0-2.bb DEPENDS on or otherwise requires it). Close matches:
  libwebsockets
  python3-websockets
  websocketpp
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.0.0-2.bb, /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/moveit/moveit-ros-visualization_2.1.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
NOTE: Runtime target 'moveit-ros-visualization' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-visualization', 'qtbase']
ERROR: Nothing PROVIDES 'plotjuggler' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.0.0-2.bb DEPENDS on or otherwise requires it)
plotjuggler was skipped: Recipe is blacklisted: Requires qtbase which requires meta-qt5 to be included; qt5-widgets: needs widgets enabled in qtbase PACKAGECONFIG
ERROR: Nothing PROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/moveit/moveit-ros-visualization_2.1.0-1.bb DEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'mongodb' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/warehouse-ros-mongo/warehouse-ros-mongo_2.0.0-1.bb DEPENDS on or otherwise requires it)
mongodb was skipped: Recipe is blacklisted: Depends on blacklisted python2
NOTE: Runtime target 'warehouse-ros-mongo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warehouse-ros-mongo', 'mongodb']
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-java' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ansys-vrxperience/vrxperience-bridge_1.0.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'vrxperience-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['vrxperience-bridge', 'ROS_UNRESOLVED_DEP-java']
ERROR: Nothing RPROVIDES 'moveit-planners-ompl-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/moveit/moveit-planners-ompl_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-planners-ompl-dev'
NOTE: Runtime target 'moveit-planners-ompl-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-planners-ompl-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-libomp-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/moveit/moveit-planners-ompl_2.1.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-libomp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-libomp-dev']
ERROR: Nothing RPROVIDES 'webots-ros2-core' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/webots-ros2/webots-ros2-turtlebot_1.0.3-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/webots-ros2/webots-ros2-tutorials_1.0.3-1.bb RDEPENDS on or otherwise requires it)
webots-ros2-core was skipped: Recipe is blacklisted: webots-python-modules: requires python-transforms3d-pip which is not available in OE yet
NOTE: Runtime target 'webots-ros2-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-core']
NOTE: Runtime target 'webots-ros2-turtlebot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-turtlebot', 'webots-ros2-core']
NOTE: Runtime target 'webots-ros2-tutorials' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-tutorials', 'webots-ros2-core']
ERROR: Nothing RPROVIDES 'webots-ros2-turtlebot-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/webots-ros2/webots-ros2-turtlebot_1.0.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros2-turtlebot-dev'
NOTE: Runtime target 'webots-ros2-turtlebot-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-turtlebot-dev']
ERROR: Nothing RPROVIDES 'qtsvg' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.0.0-2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtsvg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtsvg']
ERROR: Nothing RPROVIDES 'plotjuggler' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.0.0-2.bb RDEPENDS on or otherwise requires it)
plotjuggler was skipped: Recipe is blacklisted: Requires qtbase which requires meta-qt5 to be included; qt5-widgets: needs widgets enabled in qtbase PACKAGECONFIG
NOTE: Runtime target 'plotjuggler' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plotjuggler']
ERROR: Nothing RPROVIDES 'plotjuggler-ros-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.0.0-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'plotjuggler-ros-dev'
NOTE: Runtime target 'plotjuggler-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plotjuggler-ros-dev']
ERROR: Nothing RPROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.0.0-2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtbase' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtbase']
ERROR: Nothing RPROVIDES 'qtwebsockets' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.0.0-2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtwebsockets' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtwebsockets']
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/moveit/moveit-ros-visualization_2.1.0-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
ERROR: Nothing RPROVIDES 'moveit-ros-visualization-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/moveit/moveit-ros-visualization_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-ros-visualization-dev'
NOTE: Runtime target 'moveit-ros-visualization-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-visualization-dev']
ERROR: Nothing RPROVIDES 'warehouse-ros-mongo-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/warehouse-ros-mongo/warehouse-ros-mongo_2.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'warehouse-ros-mongo-dev'
NOTE: Runtime target 'warehouse-ros-mongo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warehouse-ros-mongo-dev']
ERROR: Nothing RPROVIDES 'webots-ros2-tutorials-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/webots-ros2/webots-ros2-tutorials_1.0.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros2-tutorials-dev'
NOTE: Runtime target 'webots-ros2-tutorials-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-tutorials-dev']
ERROR: Nothing RPROVIDES 'vrxperience-bridge-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ansys-vrxperience/vrxperience-bridge_1.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'vrxperience-bridge-dev'
NOTE: Runtime target 'vrxperience-bridge-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['vrxperience-bridge-dev']
ERROR: Nothing RPROVIDES 'joint-state-publisher-gui' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/moveit-resources/moveit-resources-panda-moveit-config_2.0.0-1.bb RDEPENDS on or otherwise requires it)
joint-state-publisher-gui was skipped: Recipe is blacklisted: qt5: depends on python-qt-binding which depends on qtbase; pyqt5: depends on python-qt-binding which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'joint-state-publisher-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['joint-state-publisher-gui']
NOTE: Runtime target 'moveit-resources-panda-moveit-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-resources-panda-moveit-config', 'joint-state-publisher-gui']
NOTE: Runtime target 'moveit-resources' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-resources', 'moveit-resources-panda-moveit-config', 'joint-state-publisher-gui']
NOTE: Runtime target 'moveit-resources-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-resources-dev', 'moveit-resources-panda-moveit-config', 'joint-state-publisher-gui']
ERROR: Nothing RPROVIDES 'moveit-resources-panda-moveit-config-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/moveit-resources/moveit-resources-panda-moveit-config_2.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-resources-panda-moveit-config-dev'
NOTE: Runtime target 'moveit-resources-panda-moveit-config-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-resources-panda-moveit-config-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>