{noetic} resolve dependency issues in new recipes
* fixes:
ERROR: Nothing PROVIDES 'rqt-gui-py' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/slider-publisher/slider-publisher_1.0.0-1.bb DEPENDS on or otherwise requires it)
rqt-gui-py was skipped: Recipe is blacklisted: Requires qt-gui->qtbase which requires meta-qt5 to be included and qt-gui->python-pyqt5 which requires pyqt5
NOTE: Runtime target 'slider-publisher' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slider-publisher', 'rqt-gui-py']
NOTE: Runtime target 'packagegroup-ros-world-noetic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-noetic', 'slider-publisher', 'rqt-gui-py']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'slider-publisher', 'rqt-gui-py']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'slider-publisher', 'rqt-gui-py']
ERROR: Nothing PROVIDES 'rviz' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb DEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'moveit-calibration-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-calibration-gui', 'rviz']
ERROR: Nothing PROVIDES 'rviz-visual-tools' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb DEPENDS on or otherwise requires it)
rviz-visual-tools was skipped: Recipe is blacklisted: qt5: pyqt5: Requires rviz which requires meta-qt5 to be included; ogre: depends on ogre which is not available
ERROR: Nothing PROVIDES 'moveit-visual-tools' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb DEPENDS on or otherwise requires it)
moveit-visual-tools was skipped: Recipe is blacklisted: qt5: Requires rviz-visual-tools->rviz which requires meta-qt5 to be included; ogre: depends on rviz-visual-tools->ogre which is not available
ERROR: Nothing PROVIDES 'moveit-ros-visualization' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb DEPENDS on or otherwise requires it)
moveit-ros-visualization was skipped: Recipe is blacklisted: qt5: Requires qtbase which requires meta-qt5 to be included; ogre: depends on unavailable ogre
ERROR: Nothing PROVIDES 'moveit-ros-planning-interface' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb DEPENDS on or otherwise requires it)
moveit-ros-planning-interface was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
ERROR: Nothing PROVIDES 'moveit-ros-planning' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb DEPENDS on or otherwise requires it)
moveit-ros-planning was skipped: Recipe is blacklisted: Depends on moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
ERROR: Nothing PROVIDES 'moveit-ros-perception' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb DEPENDS on or otherwise requires it)
moveit-ros-perception was skipped: Recipe is blacklisted: Depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and freeglut which requires x11
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-python3-pytest-cov' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/ros-pytest/ros-pytest_0.2.1-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'ros-pytest' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-pytest', 'ROS_UNRESOLVED_DEP-python3-pytest-cov']
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-libxt-dev' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/darknet-ros/darknet-ros_1.1.5-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'darknet-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['darknet-ros', 'ROS_UNRESOLVED_DEP-libxt-dev']
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-libx11' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/darknet-ros/darknet-ros_1.1.5-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'libxext' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/darknet-ros/darknet-ros_1.1.5-1.bb DEPENDS on or otherwise requires it)
libxext was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing RPROVIDES 'slider-publisher-dev' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/slider-publisher/slider-publisher_1.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'slider-publisher-dev'
NOTE: Runtime target 'slider-publisher-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slider-publisher-dev']
ERROR: Nothing RPROVIDES 'rqt-gui-py' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/slider-publisher/slider-publisher_1.0.0-1.bb RDEPENDS on or otherwise requires it)
rqt-gui-py was skipped: Recipe is blacklisted: Requires qt-gui->qtbase which requires meta-qt5 to be included and qt-gui->python-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-gui-py' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-py']
ERROR: Nothing RPROVIDES 'rviz-visual-tools' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb RDEPENDS on or otherwise requires it)
rviz-visual-tools was skipped: Recipe is blacklisted: qt5: pyqt5: Requires rviz which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'rviz-visual-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-tools']
ERROR: Nothing RPROVIDES 'rviz' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb RDEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz']
ERROR: Nothing RPROVIDES 'moveit-ros-planning' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-planning was skipped: Recipe is blacklisted: Depends on moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-ros-planning' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-planning']
ERROR: Nothing RPROVIDES 'moveit-visual-tools' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb RDEPENDS on or otherwise requires it)
moveit-visual-tools was skipped: Recipe is blacklisted: qt5: Requires rviz-visual-tools->rviz which requires meta-qt5 to be included; ogre: depends on rviz-visual-tools->ogre which is not available
NOTE: Runtime target 'moveit-visual-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-visual-tools']
ERROR: Nothing RPROVIDES 'moveit-ros-visualization' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-visualization was skipped: Recipe is blacklisted: qt5: Requires qtbase which requires meta-qt5 to be included; ogre: depends on unavailable ogre
NOTE: Runtime target 'moveit-ros-visualization' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-visualization']
ERROR: Nothing RPROVIDES 'moveit-calibration-gui-dev' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-calibration-gui-dev'
NOTE: Runtime target 'moveit-calibration-gui-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-calibration-gui-dev']
ERROR: Nothing RPROVIDES 'moveit-ros-perception' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-perception was skipped: Recipe is blacklisted: Depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and freeglut which requires x11
NOTE: Runtime target 'moveit-ros-perception' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-perception']
ERROR: Nothing RPROVIDES 'moveit-ros-planning-interface' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-gui_0.1.0-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-planning-interface was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-ros-planning-interface' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-planning-interface']
ERROR: Nothing RPROVIDES 'ros-pytest-dev' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/ros-pytest/ros-pytest_0.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ros-pytest-dev'
NOTE: Runtime target 'ros-pytest-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-pytest-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-python3-pytest-cov' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/ros-pytest/ros-pytest_0.2.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-python3-pytest-cov' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-python3-pytest-cov']
ERROR: Nothing RPROVIDES 'handeye' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-plugins_0.1.0-1.bb RDEPENDS on or otherwise requires it)
handeye was skipped: Recipe is blacklisted: Depends on criutils->unavailable ROS_UNRESOLVED_DEP-python-termcolor
NOTE: Runtime target 'handeye' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['handeye']
NOTE: Runtime target 'moveit-calibration-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-calibration-plugins', 'handeye']
ERROR: Nothing RPROVIDES 'criutils' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-plugins_0.1.0-1.bb RDEPENDS on or otherwise requires it)
criutils was skipped: Recipe is blacklisted: Depends on unavailable ROS_UNRESOLVED_DEP-python-termcolor
NOTE: Runtime target 'criutils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['criutils']
ERROR: Nothing RPROVIDES 'moveit-calibration-plugins-dev' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-plugins_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-calibration-plugins-dev'
NOTE: Runtime target 'moveit-calibration-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-calibration-plugins-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-libxt-dev' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/darknet-ros/darknet-ros_1.1.5-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-libxt-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-libxt-dev']
ERROR: Nothing RPROVIDES 'darknet-ros-dev' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/darknet-ros/darknet-ros_1.1.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'darknet-ros-dev'
NOTE: Runtime target 'darknet-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['darknet-ros-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-libx11' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/darknet-ros/darknet-ros_1.1.5-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-libx11' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-libx11']
ERROR: Nothing RPROVIDES 'libxext' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/darknet-ros/darknet-ros_1.1.5-1.bb RDEPENDS on or otherwise requires it)
libxext was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'libxext' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libxext']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>