{melodic} ros-distro.inc: add mapping for ca-certificates
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-ca-certificates' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/libcmt_2.1.13-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/ff_2.1.13-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/downward_2.1.13-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/slic_2.1.13-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/assimp-devel_2.1.13-1.bb DEPENDS on or otherwise requires it). Close matches:
  ca-certificates
NOTE: Runtime target 'libcmt' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libcmt', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'ff' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ff', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'downward' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['downward', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'slic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slic', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'assimp-devel' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['assimp-devel', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'euscollada' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['euscollada', 'assimp-devel', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'pr2eus' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2eus', 'euscollada', 'assimp-devel', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'jsk-pr2eus' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-pr2eus', 'pr2eus', 'euscollada', 'assimp-devel', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'pr2eus-moveit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2eus-moveit', 'pr2eus', 'euscollada', 'assimp-devel', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'jsk-model-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-model-tools', 'euscollada', 'assimp-devel', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'collada-urdf-jsk-patch' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['collada-urdf-jsk-patch', 'assimp-devel', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'eusurdf' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['eusurdf', 'collada-urdf-jsk-patch', 'assimp-devel', 'UNRESOLVED-ca-certificates']
NOTE: Runtime target 'eus-assimp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['eus-assimp', 'assimp-devel', 'UNRESOLVED-ca-certificates']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>