ros-python2-recipe-blacklist.inc: remove pcsc-lite and ccid
* it was fixed in newer meta-oe with:
  commit 4933ca545736903972cf609abc678f838b56f325
  Author: Andrey Zhizhikin <andrey.z@gmail.com>
  Date:   Mon Jan 27 17:36:06 2020 +0000

    pcsc-lite: update recipe to use python3

    Update pcsc-lite recipe to target python3 since python2 is EOL and has
    been dropped from OE-Core.

* and in gatesgarth this blacklist was causing:
ERROR: Nothing PROVIDES 'pcsc-lite' (but /jenkins/home/workspace/jansa/ros2-dashing-gatesgarth/ros2-dashing-gatesgarth/meta-openembedded/meta-oe/recipes-support/pcsc-tools/pcsc-tools_1.5.7.bb DEPENDS on or otherwise requires it)
pcsc-lite was skipped: Recipe is blacklisted: Depends on blacklisted python2
ERROR: Nothing RPROVIDES 'pcsc-tools-dev' (but /jenkins/home/workspace/jansa/ros2-dashing-gatesgarth/ros2-dashing-gatesgarth/meta-openembedded/meta-oe/recipes-support/pcsc-tools/pcsc-tools_1.5.7.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pcsc-tools-dev'
NOTE: Runtime target 'pcsc-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pcsc-tools-dev']
ERROR: Nothing RPROVIDES 'pcsc-tools' (but /jenkins/home/workspace/jansa/ros2-dashing-gatesgarth/ros2-dashing-gatesgarth/meta-openembedded/meta-oe/recipes-support/pcsc-tools/pcsc-tools_1.5.7.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pcsc-tools'
NOTE: Runtime target 'pcsc-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pcsc-tools']

* ccid was blacklisted only because of runtime dependency on pcsc-lite
  so we can unblacklist it as well to fix:
ERROR: Nothing RPROVIDES 'ccid' (but /jenkins/home/workspace/jansa/ros2-dashing-gatesgarth/ros2-dashing-gatesgarth/meta-openembedded/meta-oe/recipes-support/pcsc-lite/pcsc-lite_1.9.0.bb RDEPENDS on or otherwise requires it)
ccid was skipped: Recipe is blacklisted: Depends on blacklisted python2
NOTE: Runtime target 'ccid' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ccid']
NOTE: Runtime target 'pcsc-lite' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pcsc-lite', 'ccid']
ERROR: Nothing RPROVIDES 'pcsc-tools-dev' (but /jenkins/home/workspace/jansa/ros2-dashing-gatesgarth/ros2-dashing-gatesgarth/meta-openembedded/meta-oe/recipes-support/pcsc-tools/pcsc-tools_1.5.7.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pcsc-tools-dev'
NOTE: Runtime target 'pcsc-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pcsc-tools-dev']
ERROR: Nothing RPROVIDES 'pcsc-tools' (but /jenkins/home/workspace/jansa/ros2-dashing-gatesgarth/ros2-dashing-gatesgarth/meta-openembedded/meta-oe/recipes-support/pcsc-tools/pcsc-tools_1.5.7.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pcsc-tools'
NOTE: Runtime target 'pcsc-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pcsc-tools']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>