ros2-humble: delete duplicated tl-expected recipe
There is another recipe for 1.3.1 version in meta-ros2 which will be used
instead of the generated ones:

./meta-ros2-rolling/generated-recipes/cpp-polyfills/tl-expected_2.0.2-1.bb
./meta-ros2/recipes-devtools/tl-expected/tl-expected_1.3.1.bb
./meta-ros2-humble/generated-recipes/cpp-polyfills/tl-expected_1.3.2-1.bb
./meta-ros2-jazzy/generated-recipes/cpp-polyfills/tl-expected_1.3.1-1.bb
./meta-ros2-kilted/generated-recipes/cpp-polyfills/tl-expected_1.3.2-1.bb
./meta-spaceros-jazzy/generated-recipes-moveit2/tl-expected/tl-expected_1.3.0.bb

This one doesn't have fixed SRCREV, causing builds without network access
to fail (even when they don't depend on tl-expected at all):

Parsing recipes...WARNING: /OE/meta-ros/meta-ros2-humble/recipes-devtools/tl-expected/tl-expected_1.3.1.bb: Exception during build_dependencies for fetcher_hashes_dummyfunc
WARNING: /OE/meta-ros/meta-ros2-humble/recipes-devtools/tl-expected/tl-expected_1.3.1.bb: Error during finalise of /OE/meta-ros/meta-ros2-humble/recipes-devtools/tl-expected/tl-expected_1.3.1.bb
ERROR: ExpansionError during parsing /OE/meta-ros/meta-ros2-humble/recipes-devtools/tl-expected/tl-expected_1.3.1.bb
bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/OE/tmp/sysroots-uninative/x86_64-linux/usr/bin:/OE/oe-core/scripts:/OE/tmp/work/cortexa72-atlas-linux/tl-expected/1.3.1/recipe-sysroot-native/usr/bin/aarch64-atlas-linux:/OE/tmp/work/cortexa72-atlas-linux/tl-expected/1.3.1/recipe-sysroot/usr/bin/crossscripts:/OE/tmp/work/cortexa72-atlas-linux/tl-expected/1.3.1/recipe-sysroot-native/usr/sbin:/OE/tmp/work/cortexa72-atlas-linux/tl-expected/1.3.1/recipe-sysroot-native/usr/bin:/OE/tmp/work/cortexa72-atlas-linux/tl-expected/1.3.1/recipe-sysroot-native/sbin:/OE/tmp/work/cortexa72-atlas-linux/tl-expected/1.3.1/recipe-sysroot-native/bin:/OE/bitbake/bin:/OE/tmp/hosttools"; export HOME="/OE/"; git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all ls-remote https://github.com/TartanLlama/expected.git  failed with exit code 128, output:
fatal: unable to access 'https://github.com/TartanLlama/expected.git/': Failed to connect to github.com port 443 after 3304 ms: Could not connect to server

The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]

ERROR: Parsing halted due to errors, see error messages above

Summary: There were 2 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>