{dashing} ros-distro.inc: Set ROS_UNRESOLVED_PLATFORM_PKG_libgeos++-dev to "geos"
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libgeos++-dev' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/marti-common/swri-transform-util_3.0.3-1.bb, /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/marti-common/swri-geometry-util_3.0.3-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'swri-route-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-route-util', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'packagegroup-ros-world-dashing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-dashing', 'swri-route-util', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'swri-route-util', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'swri-route-util', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'swri-transform-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'swri-image-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-image-util', 'swri-geometry-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'swri-geometry-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-geometry-util', 'UNRESOLVED-libgeos++-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>