{foxy} mrpt2: require x11 as well
* fixes:
ERROR: Nothing PROVIDES 'libxxf86vm' (but /jenkins/mjansa/build/ros/webos-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/mrpt2/mrpt2_2.0.4-1.bb DEPENDS on or otherwise requires it)
libxxf86vm was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'freeglut' (but /jenkins/mjansa/build/ros/webos-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/mrpt2/mrpt2_2.0.4-1.bb DEPENDS on or otherwise requires it)
freeglut was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'libxrandr' (but /jenkins/mjansa/build/ros/webos-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/mrpt2/mrpt2_2.0.4-1.bb DEPENDS on or otherwise requires it)
libxrandr was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'wxwidgets' (but /jenkins/mjansa/build/ros/webos-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/mrpt2/mrpt2_2.0.4-1.bb DEPENDS on or otherwise requires it)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'glfw' (but /jenkins/mjansa/build/ros/webos-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/mrpt2/mrpt2_2.0.4-1.bb DEPENDS on or otherwise requires it)
glfw was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>