ar-track-alvar: add missing include
* fixes:
  ar-track-alvar/0.6.1-r0/ar_track_alvar-0.6.1/src/Marker.cpp: In member function 'virtual void alvar::MarkerData::VisualizeMarkerContent(IplImage*, alvar::Camera*, double*, double*) const':
  ar-track-alvar/0.6.1-r0/ar_track_alvar-0.6.1/src/Marker.cpp:123:15: error: 'CV_RGB' was not declared in this scope
  CvScalar rgb=CV_RGB(255,255,0);
               ^~~~~~

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>