{melodic} ros-distro.inc: add mapping for libusb-1.0
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libusb-1.0' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rc-genicam-api/rc-genicam-api_2.2.2-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/phidgets-drivers/phidgets-api_0.7.9-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'rc-genicam-api' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-genicam-api', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'rc-visard-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-visard-driver', 'rc-genicam-api', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'rc-visard' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-visard', 'rc-visard-driver', 'rc-genicam-api', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-api' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-api', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-high-speed-encoder' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-high-speed-encoder', 'phidgets-api', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-drivers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-drivers', 'phidgets-high-speed-encoder', 'phidgets-api', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-ik' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-ik', 'phidgets-api', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'leuze-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leuze-bringup', 'phidgets-ik', 'phidgets-api', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'leuze-ros-drivers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leuze-ros-drivers', 'leuze-bringup', 'phidgets-ik', 'phidgets-api', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-imu' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-imu', 'phidgets-api', 'UNRESOLVED-libusb-1.0']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>