{melodic} fuse-{contraints,core,graphs,loss,models,variables}: remove runtime dependency on ceres-solver
* ceres-solver PN package is empty

* fixes:
ERROR: ros-image-world-1.0-r0 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build/ros/ros1-melodic-honister/tmp-glibc/work/raspberrypi4_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros1-
melodic-honister/tmp-glibc/work/raspberrypi4_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros1-melodic-honister/tmp-glibc/work/raspberrypi4_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros1-melodic-honister/tmp-glib
c/work/raspberrypi4_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install bluez-firmware-rpidistro-bcm4345c0-hcd connman kernel-modules linux-firmware-rpidistro-bcm43455 packagegroup-core-boot packagegroup-ros-world run-postinsts
udev-rules-rpi' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-ros-world-1.0-r0.raspberrypi4_64 requires packagegroup-ros-world-melodic, but none of the providers can be installed
 *   - package packagegroup-ros-world-melodic-1.0-r0.raspberrypi4_64 requires fuse-graphs, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides ceres-solver needed by fuse-graphs-0.4.2-1-r0.cortexa72
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

Signed-off-by: Martin Jansa <martin.jansa@lge.com>