bfl: patch to obtain pkgconfig sanity
Since 3739aaf644d5a0f28e85fd07c67cecbfa5b8fb8a on openembedded-core,
the build of the bfl recipe fails with:

  ERROR: QA Issue: orocos-bfl.pc failed sanity test (tmpdir) in path /[...]/bfl/0.7.0-6-r0/sysroot-destdir//usr/lib/pkgconfig [pkgconfig]
  ERROR: QA Issue: bfl.pc failed sanity test (tmpdir) in path /[...]/bfl/0.7.0-6-r0/sysroot-destdir//usr/lib/pkgconfig [pkgconfig]
  ERROR: QA staging was broken by the package built above
  ERROR: Function failed: do_qa_staging
  ERROR: Logfile of failure stored in: /[...]/bfl/0.7.0-6-r0/temp/log.do_populate_sysroot.12063
  ERROR: Task 4361 (/[...]/meta-ros/recipes-extended/bfl/bfl_0.7.0-6.bb, do_populate_sysroot) failed with exit code '1'

The openembedded-core recipe suggests that the bfl recipe was broken
since its initial commit, but it remained unnoticed. This commit now
adds a patch to drop the unneeded and wrong paths from the pkgconfig
file.

Signed-off-by: Lukas Bulwahn <lukas.bulwahn@oss.bmw-carit.de>