velodyne-driver: address package_qa issue (resolves #442)
In builds with recent commits of openembedded-core,
`bitbake velodyne-driver` fails in do_package_qa with:
```
ERROR: velodyne-driver-1.2.0-r0 do_package_qa: QA Issue: /opt/ros/indigo/lib/velodyne_driver/vdump contained in package velodyne-driver requires /bin/bash, but no providers found in RDEPENDS_velodyne-driver? [file-rdeps]
```

In the past, the QA issue was only a warning and considered of low
priority. Now that it raises an error, it must be addressed.

Hence, this commit resolves the issue.

Signed-off-by: Lukas Bulwahn <lukas.bulwahn@gmail.com>