realsense-camera: require ros-realsense DISTRO_FEATURE, because it depends on optional meta-intel-realsense layer
* resolves following error in world builds without everybody needing
  to blacklist it manually for builds which don't include
  meta-intel-realsense layer, we could use dynamic layers for this, but
  as long as this is the only recipe depending on optional layer, we
  can just use this DISTRO_FEATURE (like thud branch of meta-ros is
  using now).

  NOTE: Resolving any missing task queue dependencies
  ERROR: Nothing PROVIDES 'librealsense' (but /OE/build/oe-core/meta-ros/recipes-extended/realsense-camera/realsense-camera_1.8.0.bb DEPENDS on or otherwise requires it)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'realsense-camera', 'librealsense']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>