{melodic} pilz-testutils: add clang-tidy to ROS_WORLD_SKIP_GROUPS
* it's not shown in ros-image-world builds, because pilz-testutils is listed only in:
  ROS_SUPERFLORE_GENERATED_RECIPES and ROS_SUPERFLORE_GENERATED_TESTS
  but the packagegroup-ros-world-*.bb builds only the recipes listed in:
  ROS_SUPERFLORE_GENERATED_WORLD_PACKAGES which doesn't include
  ROS_SUPERFLORE_GENERATED_TESTS nor ROS_SUPERFLORE_GENERATED_BUILDTOOLS
  so the error was shown only in "bitbake world" builds:

ERROR: Nothing PROVIDES 'pilz-utils' (but meta-ros/meta-ros1-melodic/generated-recipes/pilz-robots/pilz-testutils_0.5.18-1.bb DEPENDS on or otherwise requires it)
pilz-utils was skipped: Recipe is blacklisted: Depends on unavailable clang-tidy
ERROR: Nothing RPROVIDES 'pilz-testutils' (but meta-ros/meta-ros1-melodic/generated-recipes/pilz-robots/pilz-testutils_0.5.18-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-testutils'
NOTE: Runtime target 'pilz-testutils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-testutils']
ERROR: Nothing RPROVIDES 'pilz-testutils-dev' (but meta-ros/meta-ros1-melodic/generated-recipes/pilz-robots/pilz-testutils_0.5.18-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-testutils-dev'
NOTE: Runtime target 'pilz-testutils-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-testutils-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>