{noetic} pilz-industrial-motion-planner-testutils: restrict with x11 and opengl ROS_WORLD_SKIP_GROUPS
* fixes:
ERROR: Nothing PROVIDES 'moveit-commander' (but /jenkins/home/workspace/jansa/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/moveit/pilz-industrial-motion-planner-testutils_1.1.5-1.bb DEPENDS on or otherwise requires it)
moveit-commander was skipped: Recipe is blacklisted: opengl: Depends on moveit-ros-planning-interface->moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on moveit-ros-planning-interface which depends on  moveit-ros-perception->freeglut which requires x11
ERROR: Nothing RPROVIDES 'pilz-industrial-motion-planner-testutils-dev' (but /jenkins/home/workspace/jansa/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/moveit/pilz-industrial-motion-planner-testutils_1.1.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-industrial-motion-planner-testutils-dev'
NOTE: Runtime target 'pilz-industrial-motion-planner-testutils-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-industrial-motion-planner-testutils-dev']
ERROR: Nothing RPROVIDES 'moveit-commander' (but /jenkins/home/workspace/jansa/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/moveit/pilz-industrial-motion-planner-testutils_1.1.5-1.bb RDEPENDS on or otherwise requires it)
moveit-commander was skipped: Recipe is blacklisted: opengl: Depends on moveit-ros-planning-interface->moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on moveit-ros-planning-interface which depends on  moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-commander' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-commander']
ERROR: Nothing RPROVIDES 'pilz-industrial-motion-planner-testutils' (but /jenkins/home/workspace/jansa/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/moveit/pilz-industrial-motion-planner-testutils_1.1.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-industrial-motion-planner-testutils'
NOTE: Runtime target 'pilz-industrial-motion-planner-testutils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-industrial-motion-planner-testutils']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>