{dashing} ros-distro.inc: Set ROS_UNRESOLVED_PLATFORM_PKG_libgps to "gpsd"
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libgps' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/gps-umd/gpsd-client_1.0.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'gpsd-client' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gpsd-client', 'UNRESOLVED-libgps']
NOTE: Runtime target 'gps-umd' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gps-umd', 'gpsd-client', 'UNRESOLVED-libgps']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>