{melodic} ros-distro.inc: map UNRESOLVED-python-tk to python-tkinter like ROS2 does
* it cannot be used as build time dependency by exotica-python, we need to replace it
  with just PYTHON_PN
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-python-tk' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-python_5.1.3-3.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'exotica-ompl-solver' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ompl-solver_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-ompl-solver'
NOTE: Runtime target 'exotica-ompl-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ompl-solver']
ERROR: Nothing RPROVIDES 'exotica' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica'
NOTE: Runtime target 'exotica' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica']
ERROR: Nothing RPROVIDES 'exotica-python' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ilqg-solver_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ompl-solver_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ilqr-solver_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-python_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-core-task-maps_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ddp-solver_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-python'
NOTE: Runtime target 'exotica-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-python']
ERROR: Nothing RPROVIDES 'exotica-core-task-maps' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-core-task-maps_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-core-task-maps'
NOTE: Runtime target 'exotica-core-task-maps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-core-task-maps']
ERROR: Nothing RPROVIDES 'exotica-collision-scene-fcl' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb RDEPENDS on or otherwise requires it)
exotica-collision-scene-fcl was skipped: Recipe is blacklisted: Depends on exotica-core->moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and exotica-core->moveit-ros-perception->freeglut which requires x11; exotica-collision-scene-fcl: do_compile task fails: exotica-collision-scene-fcl/5.1.3-3-r0/git/include/exotica_collision_scene_fcl/collision_scene_fcl.h:36:10: fatal error: fcl/BVH/BVH_model.h: No such file or directory
NOTE: Runtime target 'exotica-collision-scene-fcl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-collision-scene-fcl']
ERROR: Nothing RPROVIDES 'exotica-dev' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-dev'
NOTE: Runtime target 'exotica-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-dev']
ERROR: Nothing RPROVIDES 'exotica-examples' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-examples'
NOTE: Runtime target 'exotica-examples' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-examples']
ERROR: Nothing RPROVIDES 'rviz' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb RDEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: Requires python-qt-binding which requires meta-qt5 to be included and ogre which is not available
NOTE: Runtime target 'rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz']
ERROR: Nothing RPROVIDES 'exotica-examples-dev' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-examples-dev'
NOTE: Runtime target 'exotica-examples-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-examples-dev']
ERROR: Nothing RPROVIDES 'exotica-ddp-solver' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ddp-solver_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-ddp-solver'
NOTE: Runtime target 'exotica-ddp-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ddp-solver']
ERROR: Nothing RPROVIDES 'exotica-ilqg-solver' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ilqg-solver_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-ilqg-solver'
NOTE: Runtime target 'exotica-ilqg-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ilqg-solver']
ERROR: Nothing RPROVIDES 'exotica-ilqr-solver' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ilqr-solver_5.1.3-3.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-ilqr-solver'
NOTE: Runtime target 'exotica-ilqr-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ilqr-solver']
ERROR: Nothing RPROVIDES 'exotica-scipy-solver' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-examples_5.1.3-3.bb RDEPENDS on or otherwise requires it)
exotica-scipy-solver was skipped: Recipe is blacklisted: Depends on exotica-core->moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and exotica-core->moveit-ros-perception->freeglut which requires x11; python-scipy: Depends on unavailable UNRESOLVED-python-scipy
NOTE: Runtime target 'exotica-scipy-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-scipy-solver']
ERROR: Nothing RPROVIDES 'exotica-ilqg-solver-dev' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ilqg-solver_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-ilqg-solver-dev'
NOTE: Runtime target 'exotica-ilqg-solver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ilqg-solver-dev']
ERROR: Nothing RPROVIDES 'exotica-ompl-solver-dev' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ompl-solver_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-ompl-solver-dev'
NOTE: Runtime target 'exotica-ompl-solver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ompl-solver-dev']
ERROR: Nothing RPROVIDES 'packagegroup-ros-world-melodic' (but ros1-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-world.bb, ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-ros-world-melodic'
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic']
ERROR: Nothing RPROVIDES 'exotica-ilqr-solver-dev' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ilqr-solver_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-ilqr-solver-dev'
NOTE: Runtime target 'exotica-ilqr-solver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ilqr-solver-dev']
ERROR: Nothing RPROVIDES 'exotica-python-dev' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-python_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-python-dev'
NOTE: Runtime target 'exotica-python-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-python-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python-tk' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-python_5.1.3-3.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python-tk' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python-tk']
ERROR: Nothing RPROVIDES 'moveit-ros-visualization' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/fetch-ros/fetch-moveit-config_0.8.2-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-visualization was skipped: Recipe is blacklisted: Requires qtbase which requires meta-qt5 to be included and ogre which is not available
NOTE: Runtime target 'moveit-ros-visualization' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-visualization']
NOTE: Runtime target 'fetch-moveit-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-moveit-config', 'moveit-ros-visualization']
NOTE: Runtime target 'fetch-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-ros-dev', 'fetch-moveit-config', 'moveit-ros-visualization']
NOTE: Runtime target 'fetch-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-ros', 'fetch-moveit-config', 'moveit-ros-visualization']
ERROR: Nothing RPROVIDES 'fetch-moveit-config-dev' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/fetch-ros/fetch-moveit-config_0.8.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'fetch-moveit-config-dev'
NOTE: Runtime target 'fetch-moveit-config-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-moveit-config-dev']
ERROR: Nothing RPROVIDES 'exotica-core-task-maps-dev' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-core-task-maps_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-core-task-maps-dev'
NOTE: Runtime target 'exotica-core-task-maps-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-core-task-maps-dev']
ERROR: Nothing RPROVIDES 'fetch-bringup' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
fetch-bringup was skipped: Recipe is blacklisted: depends on openni2-launch->openni2-camera->unavailable UNRESOLVED-libopenni2-dev
NOTE: Runtime target 'fetch-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-bringup']
ERROR: Nothing RPROVIDES 'exotica-ddp-solver-dev' (but ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ddp-solver_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-ddp-solver-dev'
NOTE: Runtime target 'exotica-ddp-solver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ddp-solver-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>