{melodic} packagegroup-ros-world-melodic: Remove RDEPENDS on packages which require opengl in DISTRO_FEATURES
* fixes:
ERROR: Nothing PROVIDES 'mesa' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/stage/stage_4.3.0.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/moveit/moveit-ros-perception_1.0.2-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/libg2o/libg2o_2018.3.25.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/uwsim-osgocean/uwsim-osgocean_1.0.4-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/uwsim-osgworks/uwsim-osgworks_3.0.3-2.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/underwater-simulation/uwsim_1.4.2-1.bb DEPENDS on or otherwise requires it)
mesa was skipped: one of '['opengl', 'vulkan']' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'stage' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['stage', 'mesa']
NOTE: Runtime target 'stage-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['stage-ros', 'stage', 'mesa']
NOTE: Runtime target 'teb-local-planner-tutorials' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['teb-local-planner-tutorials', 'stage-ros', 'stage', 'mesa']
NOTE: Runtime target 'simulators' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['simulators', 'stage-ros', 'stage', 'mesa']
NOTE: Runtime target 'desktop-full' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['desktop-full', 'simulators', 'stage-ros', 'stage', 'mesa']
NOTE: Runtime target 'roomba-stage' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roomba-stage', 'stage-ros', 'stage', 'mesa']
NOTE: Runtime target 'navigation-tutorials' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation-tutorials', 'roomba-stage', 'stage-ros', 'stage', 'mesa']
NOTE: Runtime target 'navigation-stage' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation-stage', 'stage-ros', 'stage', 'mesa']
NOTE: Runtime target 'moveit-planners-ompl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'open-manipulator-moveit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-moveit', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'fetch-moveit-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-moveit-config', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'fetch-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-bringup', 'fetch-moveit-config', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'fetch-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-ros', 'fetch-moveit-config', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'open-manipulator-with-tb3-waffle-moveit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-with-tb3-waffle-moveit', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'abb-irb6640-moveit-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['abb-irb6640-moveit-config', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'abb' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['abb', 'abb-irb6640-moveit-config', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'open-manipulator-with-tb3-waffle-pi-moveit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-with-tb3-waffle-pi-moveit', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'abb-irb2400-moveit-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['abb-irb2400-moveit-config', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'cob-moveit-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-moveit-bringup', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-planners' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-planners', 'moveit-planners-ompl', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-ros-warehouse' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-warehouse', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-ros-benchmarks' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-benchmarks', 'moveit-ros-warehouse', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-time-indexed-rrt-connect-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-time-indexed-rrt-connect-solver', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-examples' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-examples', 'exotica-time-indexed-rrt-connect-solver', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica', 'exotica-time-indexed-rrt-connect-solver', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-collision-scene-fcl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-collision-scene-fcl', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-ik-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ik-solver', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-levenberg-marquardt-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-levenberg-marquardt-solver', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-aico-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-aico-solver', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-ompl-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ompl-solver', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-python', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-core-task-maps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-core-task-maps', 'exotica-python', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-collision-scene-fcl-latest' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-collision-scene-fcl-latest', 'exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'exotica-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-core', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-fake-controller-manager' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-fake-controller-manager', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-plugins', 'moveit-fake-controller-manager', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'cob-collision-monitor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-collision-monitor', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-ros-manipulation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-manipulation', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-sim-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-sim-controller', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-ros-move-group' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-move-group', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'pr2-moveit-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2-moveit-config', 'moveit-ros-move-group', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-pr2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-pr2', 'pr2-moveit-config', 'moveit-ros-move-group', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'fsrobo-r-trajectory-filters' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fsrobo-r-trajectory-filters', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'industrial-trajectory-filters' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['industrial-trajectory-filters', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'industrial-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['industrial-core', 'industrial-trajectory-filters', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-visual-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-visual-tools', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-ros-robot-interaction' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-robot-interaction', 'moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-ros-planning' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-planning', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'robot-body-filter' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-body-filter', 'moveit-ros-perception', 'mesa']
NOTE: Runtime target 'moveit-ros-perception' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-perception', 'mesa']
NOTE: Runtime target 'teb-local-planner' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['teb-local-planner', 'libg2o', 'mesa']
NOTE: Runtime target 'seed-r7-navigation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['seed-r7-navigation', 'teb-local-planner', 'libg2o', 'mesa']
NOTE: Runtime target 'rtabmap' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rtabmap', 'libg2o', 'mesa']
NOTE: Runtime target 'rtabmap-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rtabmap-ros', 'rtabmap', 'libg2o', 'mesa']
NOTE: Runtime target 'libg2o' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libg2o', 'mesa']
NOTE: Runtime target 'uwsim-osgocean' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uwsim-osgocean', 'mesa']
NOTE: Runtime target 'uwsim-osgworks' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uwsim-osgworks', 'mesa']
NOTE: Runtime target 'uwsim-osgbullet' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uwsim-osgbullet', 'uwsim-osgworks', 'mesa']

ERROR: Nothing PROVIDES 'libglu' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros-common/recipes-extended/wxwidgets/wxwidgets_3.0.4.bb DEPENDS on or otherwise requires it)
libglu was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'rc-roi-manager-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-roi-manager-gui', 'wxwidgets', 'libglu']
NOTE: Runtime target 'rc-roi-manager-gui-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-roi-manager-gui-dev', 'wxwidgets', 'libglu']
NOTE: Runtime target 'wxwidgets' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['wxwidgets', 'libglu']
NOTE: Runtime target 'wxwidgets-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['wxwidgets-dev', 'libglu']
ERROR: Nothing PROVIDES 'gl-dependency' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-pose-view/rqt-pose-view_0.5.8.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'gl-dependency'
ERROR: Nothing PROVIDES 'UNRESOLVED-python-opengl' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-pose-view/rqt-pose-view_0.5.8.bb DEPENDS on or otherwise requires it)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>