python-rosdep: adding new dependency due to update
When compiling python-rosdep before python-nose has been built,
'bitbake python-rosdep' fails with:

| distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nose>=1.0')
| ERROR: python setup.py build_ext execution failed.
| WARNING: /[...]/build/tmp-glibc/work/i586-oe-linux/python-rosdep/0.11.0-r0/temp/run.do_compile.14813:1 exit 1 from
|   exit 1
| ERROR: Function failed: do_compile (log file is located at /[...]/build/tmp-glibc/work/i586-oe-linux/python-rosdep/0.11.0-r0/temp/log.do_compile.14813)
ERROR: Task 6 (/[...]/meta-ros/recipes-devtools/python/python-rosdep_0.11.0.bb, do_compile) failed with exit code '1'

In a recent commit in the rosdep repository [1], the dependency for
the rosdep setup on python's nose package is added. Hence, we must
also add this dependency in the rosdep recipe, which then resolves
the reported failure.

[1] https://github.com/ros-infrastructure/rosdep/commit/fc8b56be072ab672344c747de815daaacf2e9834

Signed-off-by: Lukas Bulwahn <lukas.bulwahn@oss.bmw-carit.de>