Add core-image-ros-turtlebot3-core.bb, webos-image-ros-turtlebot3-core.bb
* When not using meta-webos, need to set LICENSE variable, otherwise the error:
    Parsing recipes...    ERROR: meta-ros/meta-ros-common/recipes-core/images/webos-image-ros-turtlebot3-core.bb: This recipe does not have the LICENSE field set (webos-image-ros-turtlebot3-core)
  is shown before PNBLACKLIST is processed.

* also cannot use require instead of include, because that would cause parsing
    failure, before PNBLACKLIST skips the recipe:
    ERROR: ParseError at meta-ros-common/recipes-core/images/webos-image-ros-turtlebot3-core.bb:5:
    Could not include required file /recipes-core/images/webos-image.bb