python-rosdep: drop -rospkg runtime dependency
* this causes circular dependency when trying to build python-rospkg-native
  or python-rosdep-native:
  $ bitbake python-rospkg-native
  ...
  ERROR: Task virtual:native:meta-ros-common/recipes-infrastructure/python/python-rospkg_1.1.10.bb:do_populate_sysroot has circular dependency on virtual:native:meta-ros-common/recipes-infrastructure/python/python-rosdep_0.16.1.bb:do_populate_sysroot

* python-rospkg-native/python-rosdep-native are included in ros-image-world now
  because of strange dependencies in melodic's new version of mrt-cmake-modules,
  introduced in:
  https://github.com/KIT-MRT/mrt_cmake_modules/commit/df568cbfb04cf122aa18dfb3320ee3e6714ada13
  and this recipe is then used by various lanelet2* recipes

"mrt-cmake-modules-native.do_prepare_recipe_sysroot" -> "python-rospkg-native.do_populate_sysroot"
"mrt-cmake-modules-native.do_rm_work_all" -> "python-rosdep-native.do_rm_work"
"mrt-cmake-modules-native.do_rm_work_all" -> "python-rospkg-native.do_rm_work"
"mrt-cmake-modules.do_prepare_recipe_sysroot" -> "python-rospkg-native.do_populate_sysroot"
"mrt-cmake-modules.do_rm_work_all" -> "python-rosdep-native.do_rm_work"
"mrt-cmake-modules.do_rm_work_all" -> "python-rospkg-native.do_rm_work"

Signed-off-by: Martin Jansa <martin.jansa@lge.com>