python(3)-rospkg: upgrade to version from newer-platform-components.list
* update rospkg recipes-infrastructure recipe to version listed in:
  meta-ros1-melodic/files/melodic/generated/newer-platform-components.list
  as in:
  53f7cc72e {melodic} Sync to files/melodic/generated/cache.yaml as of 20210318174126

* add dependency on python3-distro, because now lanelet2-{core,maps} was failing with:
    -- Found PythonInterp: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/lanelet2-maps/1.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.9.2", minimum required is "3")
    -- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/lanelet2-maps/1.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
    -- Found OpenMP_C: -fopenmp (found version "4.5")
    -- Found OpenMP_CXX: -fopenmp (found version "4.5")
    -- Found OpenMP: TRUE (found version "4.5")
    CMake Error at /jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/lanelet2-maps/1.1.1-1-r0/recipe-sysroot-native/usr/share/mrt_cmake_modules/cmake/Modules/GatherDeps.cmake:24 (message):
      Gather depenencies failed: Traceback (most recent call last):

        File "/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/lanelet2-maps/1.1.1-1-r0/recipe-sysroot-native/usr/share/mrt_cmake_modules/cmake/../scripts/generate_cmake_dependency_file.py", line 21, in <module>
          from rospkg.os_detect import OsDetect
        File "/jenkins/mjansa/build/ros/ros2-foxy-hardknott/tmp-glibc/work/core2-64-oe-linux/lanelet2-maps/1.1.1-1-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/rospkg/os_detect.py", line 42, in <module>
          import distro

      ModuleNotFoundError: No module named 'distro'

    Call Stack (most recent call first):
      CMakeLists.txt:11 (include)

  and comparing os_detect.py shows python3-distro as new dependency for python > 3.8 (hardknott using 3.9.2):

    --- ./1.1.1-1-r0-new-rospkg/recipe-sysroot-native/usr/lib/python3.9/site-packages/rospkg/os_detect.py       2021-04-12 15:51:17.000000000 -0700
    +++ ./1.1.1-1-r0-old-rospkg/recipe-sysroot-native/usr/lib/python3.9/site-packages/rospkg/os_detect.py       2021-04-14 06:32:28.000000000 -0700
    @@ -32,16 +32,9 @@
     Linux distributions.
     """

    -from __future__ import absolute_import
     from __future__ import print_function

     import codecs
    -# to be removed after Ubuntu Xenial is out of support
    -import sys
    -if sys.version_info >= (3, 8):
    -    import distro
    -else:
    -    import platform as distro
     import locale
     import os
     import platform
    @@ -134,22 +127,19 @@

Signed-off-by: Martin Jansa <martin.jansa@lge.com>