{melodic} ros-distro.inc: add mapping for libtool
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libtool' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pr2-controllers/robot-mechanism-controllers_1.10.17-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/nlopt_2.1.13-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pr2-controllers/ethercat-trigger-controllers_1.10.17-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/stage/stage_4.3.0.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'pr2-calibration-controllers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2-calibration-controllers', 'pr2-mechanism-controllers', 'robot-mechanism-controllers', 'UNRESOLVED-libtool']
NOTE: Runtime target 'pr2-controllers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2-controllers', 'pr2-calibration-controllers', 'pr2-mechanism-controllers', 'robot-mechanism-controllers', 'UNRESOLVED-libtool']
NOTE: Runtime target 'pr2-gripper-action' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2-gripper-action', 'pr2-mechanism-controllers', 'robot-mechanism-controllers', 'UNRESOLVED-libtool']
NOTE: Runtime target 'pr2-mechanism-controllers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2-mechanism-controllers', 'robot-mechanism-controllers', 'UNRESOLVED-libtool']
NOTE: Runtime target 'robot-mechanism-controllers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-mechanism-controllers', 'UNRESOLVED-libtool']
NOTE: Runtime target 'nlopt' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nlopt', 'UNRESOLVED-libtool']
NOTE: Runtime target 'ethercat-trigger-controllers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ethercat-trigger-controllers', 'UNRESOLVED-libtool']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>