{melodic} ros-distro-recipe-blacklist.inc: add new openni(2) ROS_WORLD_SKIP_GROUPS and add it to fetch-bringup
* fixes:
ERROR: Nothing RPROVIDES 'fetch-bringup' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
fetch-bringup was skipped: Recipe is blacklisted: depends on openni2-launch->openni2-camera->unavailable UNRESOLVED-libopenni2-dev
NOTE: Runtime target 'fetch-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-bringup']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>