{galactic} fix dependency issues in new recipes
* fixes:
ERROR: Nothing PROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/aws-robomaker-small-warehouse-world/aws-robomaker-small-warehouse-world_1.0.4-1.bb, /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.4-1.bb DEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'aws-robomaker-small-warehouse-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['aws-robomaker-small-warehouse-world', 'gazebo-ros']
NOTE: Runtime target 'packagegroup-ros-world-galactic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-galactic', 'aws-robomaker-small-warehouse-world', 'gazebo-ros']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-galactic', 'aws-robomaker-small-warehouse-world', 'gazebo-ros']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-galactic', 'aws-robomaker-small-warehouse-world', 'gazebo-ros']
NOTE: Runtime target 'gazebo-ros2-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros2-control', 'gazebo-ros']
NOTE: Runtime target 'gazebo-ros2-control-demos' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros2-control-demos', 'gazebo-ros2-control', 'gazebo-ros']
ERROR: Nothing PROVIDES 'ros-ign-gazebo' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb DEPENDS on or otherwise requires it)
ros-ign-gazebo was skipped: Recipe is blacklisted: ignition: depends on unavailable ROS_UNRESOLVED_DEP-ignition-gazebo5, ROS_UNRESOLVED_DEP-ignition-math6
NOTE: Runtime target 'dolly-ignition' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-ignition', 'ros-ign-gazebo']
NOTE: Runtime target 'dolly' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly', 'dolly-ignition', 'ros-ign-gazebo']
ERROR: Nothing PROVIDES 'rviz-ogre-vendor' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.1-1.bb DEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'moveit-visual-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-visual-tools', 'rviz-visual-tools', 'rviz-ogre-vendor']
NOTE: Runtime target 'rviz-visual-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-tools', 'rviz-ogre-vendor']
ERROR: Nothing PROVIDES 'gazebo-rosdev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.4-1.bb DEPENDS on or otherwise requires it)
gazebo-rosdev was skipped: Recipe is blacklisted: gazebo: depends on gazebo which is not available
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/dolly/dolly-gazebo_0.4.0-1.bb, /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/moveit/run-move-group_2.3.0-1.bb, /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/moveit/run-moveit-cpp_2.3.0-1.bb, /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb, /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.1-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
NOTE: Runtime target 'dolly-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-gazebo', 'rviz2']
NOTE: Runtime target 'run-move-group' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['run-move-group', 'rviz2']
NOTE: Runtime target 'run-moveit-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['run-moveit-cpp', 'rviz2']
ERROR: Nothing RPROVIDES 'dolly-gazebo-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/dolly/dolly-gazebo_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dolly-gazebo-dev'
NOTE: Runtime target 'dolly-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-gazebo-dev']
ERROR: Nothing RPROVIDES 'gazebo-ros-pkgs' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/dolly/dolly-gazebo_0.4.0-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros-pkgs was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-ros-pkgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-pkgs']
ERROR: Nothing RPROVIDES 'moveit-visual-tools-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/moveit-visual-tools/moveit-visual-tools_4.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-visual-tools-dev'
NOTE: Runtime target 'moveit-visual-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-visual-tools-dev']
ERROR: Nothing RPROVIDES 'python3-enum34' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/navigation2/nav2-simple-commander_1.0.7-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-enum34' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-enum34']
NOTE: Runtime target 'nav2-simple-commander' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-simple-commander', 'python3-enum34']
NOTE: Runtime target 'nav2-simple-commander-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-simple-commander-dev', 'python3-enum34']
ERROR: Nothing RPROVIDES 'run-move-group-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/moveit/run-move-group_2.3.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'run-move-group-dev'
NOTE: Runtime target 'run-move-group-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['run-move-group-dev']
ERROR: Nothing RPROVIDES 'warehouse-ros-mongo' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/moveit/run-move-group_2.3.0-1.bb, /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/moveit/run-moveit-cpp_2.3.0-1.bb RDEPENDS on or otherwise requires it)
warehouse-ros-mongo was skipped: Recipe is blacklisted: Requires mongodb; mongodb-legacy-cxx-driver: requires unavailable mongo-cxx-driver-legacy
NOTE: Runtime target 'warehouse-ros-mongo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warehouse-ros-mongo']
ERROR: Nothing RPROVIDES 'moveit-resources-panda-moveit-config' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/moveit/run-move-group_2.3.0-1.bb, /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/moveit/run-moveit-cpp_2.3.0-1.bb RDEPENDS on or otherwise requires it)
moveit-resources-panda-moveit-config was skipped: Recipe is blacklisted: qt5: rdepends on joint-state-publisher-gui which depends on python-qt-binding which depends on qtbase; pyqt5: rdepends on joint-state-publisher-gui which depends on python-qt-binding which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'moveit-resources-panda-moveit-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-resources-panda-moveit-config']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/gazebo-ros2-control/gazebo-ros2-control-demos_0.0.4-1.bb, /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/aws-robomaker-small-warehouse-world/aws-robomaker-small-warehouse-world_1.0.4-1.bb, /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.4-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
ERROR: Nothing RPROVIDES 'gazebo-ros2-control-demos-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/gazebo-ros2-control/gazebo-ros2-control-demos_0.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gazebo-ros2-control-demos-dev'
NOTE: Runtime target 'gazebo-ros2-control-demos-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros2-control-demos-dev']
ERROR: Nothing RPROVIDES 'dolly-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/dolly/dolly_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dolly-dev'
NOTE: Runtime target 'dolly-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-dev']
ERROR: Nothing RPROVIDES 'aws-robomaker-small-warehouse-world-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/aws-robomaker-small-warehouse-world/aws-robomaker-small-warehouse-world_1.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'aws-robomaker-small-warehouse-world-dev'
NOTE: Runtime target 'aws-robomaker-small-warehouse-world-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['aws-robomaker-small-warehouse-world-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-gazebo' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/aws-robomaker-small-warehouse-world/aws-robomaker-small-warehouse-world_1.0.4-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-gazebo']
ERROR: Nothing RPROVIDES 'gazebo-plugins' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/aws-robomaker-small-warehouse-world/aws-robomaker-small-warehouse-world_1.0.4-1.bb RDEPENDS on or otherwise requires it)
gazebo-plugins was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-plugins']
ERROR: Nothing RPROVIDES 'run-moveit-cpp-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/moveit/run-moveit-cpp_2.3.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'run-moveit-cpp-dev'
NOTE: Runtime target 'run-moveit-cpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['run-moveit-cpp-dev']
ERROR: Nothing RPROVIDES 'ros-ign-bridge' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb RDEPENDS on or otherwise requires it)
ros-ign-bridge was skipped: Recipe is blacklisted: ignition: depends on unavailable ROS_UNRESOLVED_DEP-ignition-msgs7, ROS_UNRESOLVED_DEP-ignition-transport10
NOTE: Runtime target 'ros-ign-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-ign-bridge']
ERROR: Nothing RPROVIDES 'dolly-ignition-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dolly-ignition-dev'
NOTE: Runtime target 'dolly-ignition-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-ignition-dev']
ERROR: Nothing RPROVIDES 'ros-ign-gazebo' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/dolly/dolly-ignition_0.4.0-1.bb RDEPENDS on or otherwise requires it)
ros-ign-gazebo was skipped: Recipe is blacklisted: ignition: depends on unavailable ROS_UNRESOLVED_DEP-ignition-gazebo5, ROS_UNRESOLVED_DEP-ignition-math6
NOTE: Runtime target 'ros-ign-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-ign-gazebo']
ERROR: Nothing RPROVIDES 'rviz-ogre-vendor' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.1-1.bb RDEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-ogre-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-ogre-vendor']
ERROR: Nothing RPROVIDES 'rviz-visual-tools-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-visual-tools-dev'
NOTE: Runtime target 'rviz-visual-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-tools-dev']
ERROR: Nothing RPROVIDES 'gazebo-ros2-control-dev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gazebo-ros2-control-dev'
NOTE: Runtime target 'gazebo-ros2-control-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros2-control-dev']
ERROR: Nothing RPROVIDES 'gazebo-rosdev' (but /jenkins/mjansa/build/ros/webos-galactic-hardknott/meta-ros/meta-ros2-galactic/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.4-1.bb RDEPENDS on or otherwise requires it)
gazebo-rosdev was skipped: Recipe is blacklisted: gazebo: depends on gazebo which is not available
NOTE: Runtime target 'gazebo-rosdev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-rosdev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>