{noetic} slic: fix missing includes for OpenCV
* fixes:
| FAILED: slic-prefix/src/slic-stamp/slic-build
| cd /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/build/slic-prefix/src/slic-build && /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot-native/usr/bin/cmake --build . && /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot-native/usr/bin/cmake -E touch /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/build/slic-prefix/src/slic-stamp/slic-build
| [1/2] /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot -Dslic_EXPORTS  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0=/usr/src/debug/slic/2.1.21-2-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0=/usr/src/debug/slic/2.1.21-2-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot -fPIC -MD -MT CMakeFiles/slic.dir/slic.cpp.o -MF CMakeFiles/slic.dir/slic.cpp.o.d -o CMakeFiles/slic.dir/slic.cpp.o -c /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/git/slic-upstream/slic.cpp
| FAILED: CMakeFiles/slic.dir/slic.cpp.o
| /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot -Dslic_EXPORTS  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0=/usr/src/debug/slic/2.1.21-2-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0=/usr/src/debug/slic/2.1.21-2-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/recipe-sysroot -fPIC -MD -MT CMakeFiles/slic.dir/slic.cpp.o -MF CMakeFiles/slic.dir/slic.cpp.o.d -o CMakeFiles/slic.dir/slic.cpp.o -c /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/git/slic-upstream/slic.cpp
| In file included from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/git/slic-upstream/slic.cpp:1:
| /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/slic/2.1.21-2-r0/git/slic-upstream/slic.h:22:10: fatal error: opencv2/opencv.hpp: No such file or directory
|    22 | #include <opencv2/opencv.hpp>
|       |          ^~~~~~~~~~~~~~~~~~~~
| compilation terminated.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>