{noetic} resolve dependency issues in new recipes
* fixes:

ERROR: Nothing PROVIDES 'phidgets-api' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/phidgets-drivers/phidgets-analog-outputs_1.0.3-1.bb DEPENDS on or otherwise requires it)
phidgets-api was skipped: Recipe is blacklisted: libphidget21: depends on libphidget21 which fails to compile
NOTE: Runtime target 'phidgets-analog-outputs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-analog-outputs', 'phidgets-api']
ERROR: Nothing PROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/jderobot-drones/drone-assets_1.4.2-1.bb DEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'drone-assets' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['drone-assets', 'gazebo-ros']
ERROR: Nothing PROVIDES 'opw-kinematics' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/moveit-opw-kinematics-plugin/moveit-opw-kinematics-plugin_0.3.1-2.bb DEPENDS on or otherwise requires it)
opw-kinematics was skipped: Recipe is blacklisted: Depends on unavailable ROS_UNRESOLVED_DEP-cmake-common-scripts
NOTE: Runtime target 'moveit-opw-kinematics-plugin' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-opw-kinematics-plugin', 'opw-kinematics']
ERROR: Nothing RPROVIDES 'phidgets-analog-outputs-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/phidgets-drivers/phidgets-analog-outputs_1.0.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'phidgets-analog-outputs-dev'
NOTE: Runtime target 'phidgets-analog-outputs-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-analog-outputs-dev']
ERROR: Nothing RPROVIDES 'phidgets-api' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/phidgets-drivers/phidgets-analog-outputs_1.0.3-1.bb RDEPENDS on or otherwise requires it)
phidgets-api was skipped: Recipe is blacklisted: libphidget21: depends on libphidget21 which fails to compile
NOTE: Runtime target 'phidgets-api' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-api']
ERROR: Nothing RPROVIDES 'rm-gazebo' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-control_0.1.7-3.bb RDEPENDS on or otherwise requires it)
rm-gazebo was skipped: Recipe is blacklisted: gazebo: Depends on gazebo-ros which is not available
NOTE: Runtime target 'rm-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rm-gazebo']
NOTE: Runtime target 'rm-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rm-control', 'rm-gazebo']
ERROR: Nothing RPROVIDES 'rm-control-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-control_0.1.7-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rm-control-dev'
NOTE: Runtime target 'rm-control-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rm-control-dev']
ERROR: Nothing RPROVIDES 'web-video-server' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/leo-robot/leo-bringup_1.2.1-1.bb RDEPENDS on or otherwise requires it)
web-video-server was skipped: Recipe is blacklisted: ffmpeg: Depends on ffmpeg which requires commercial license; x264: Depends on ffmpeg which depends on x264 which requires commercial license
NOTE: Runtime target 'web-video-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['web-video-server']
NOTE: Runtime target 'leo-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-bringup', 'web-video-server']
NOTE: Runtime target 'leo-robot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-robot', 'leo-bringup', 'web-video-server']
NOTE: Runtime target 'leo-robot-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-robot-dev', 'leo-bringup', 'web-video-server']
NOTE: Runtime target 'leo-bringup-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-bringup-dev', 'web-video-server']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/jderobot-drones/drone-assets_1.4.2-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
ERROR: Nothing RPROVIDES 'drone-assets-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/jderobot-drones/drone-assets_1.4.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'drone-assets-dev'
NOTE: Runtime target 'drone-assets-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['drone-assets-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-python3-whichcraft' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/leo-robot/leo-fw_1.2.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-python3-whichcraft' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-python3-whichcraft']
NOTE: Runtime target 'leo-fw' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-fw', 'ROS_UNRESOLVED_DEP-python3-whichcraft']
ERROR: Nothing RPROVIDES 'leo-fw-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/leo-robot/leo-fw_1.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'leo-fw-dev'
NOTE: Runtime target 'leo-fw-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['leo-fw-dev']
ERROR: Nothing RPROVIDES 'moveit-opw-kinematics-plugin-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/moveit-opw-kinematics-plugin/moveit-opw-kinematics-plugin_0.3.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-opw-kinematics-plugin-dev'
NOTE: Runtime target 'moveit-opw-kinematics-plugin-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-opw-kinematics-plugin-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>