{dashing} graphicsmagick: force building shared instead of static libs
* with static libs nav2-map-server fails to link with:
| libmap_server_core.so: error: undefined reference to 'ProfileImage'
| libmap_server_core.so: error: undefined reference to 'GetExceptionInfo'
...

Signed-off-by: Martin Jansa <martin.jansa@lge.com>