fcl: upgrade to 0.6.1
* LICENSE was included in 0.4.0:
  https://github.com/flexible-collision-library/fcl/commit/6d9cace950e218c025fd8ba748ca0a8556419103
* 0001-Add-configure-option-NO_DEFAULT_RPATH.patch was included in 0.6.0:
  https://github.com/flexible-collision-library/fcl/commit/2e3d262195fbfd5369e5aa00fb6c6c7c0ae855de
* add dependency on libeigen
  it's mandatory now and configure fails without it:
  | CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  | Please set them or make sure they are set and tested correctly in the CMake files:
  | /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl/0.6.1-r0/git/src/EIGEN3_INCLUDE_DIR
  |    used as include directory in directory /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl/0.6.1-r0/git/src
* 0.3.2 version is too old e.g. for moveit-core, main issue is use
  of boost::shared_ptr in old fcl while newer fcl 0.5 already uses
  std::shared_ptr and moveit-core expects that as discussed here:
  https://github.com/ros-planning/moveit_core/issues/319

* fixes:
moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_robot_fcl.cpp:68:103: error: no matching function for call to 'fcl::CollisionObject::CollisionObject(const std::shared_ptr<fcl::CollisionGeometry>&)'
moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_robot_fcl.cpp:124:97: error: no matching function for call to 'fcl::CollisionObject::CollisionObject(const std::shared_ptr<fcl::CollisionGeometry>&, fcl::Transform3d&)'
moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_robot_fcl.cpp:272:105: error: no matching function for call to 'fcl::CollisionObject::CollisionObject(const std::shared_ptr<fcl::CollisionGeometry>&)'
moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_world_fcl.cpp:194:102: error: no matching function for call to 'fcl::CollisionObject::CollisionObject(const std::shared_ptr<fcl::CollisionGeometry>&, fcl::Transform3d)'
moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp:822:40: error: no matching function for call to 'fcl::OcTree::OcTree(const std::shared_ptr<const octomap::OcTree>&)'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>