{foxy} *-msgs: use ament_cmake instead of ros_catkin for new *-msgs recipes
* fixes:
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/kartech-linear-actuator-msgs_3.1.0-1.bb:64: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/automotive-autonomy-msgs/automotive-autonomy-msgs_3.0.3-1.bb:54: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/automotive-autonomy-msgs/automotive-platform-msgs_3.0.3-1.bb:64: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/ibeo-msgs_3.1.0-1.bb:64: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/mobileye-560-660-msgs_3.1.0-1.bb:64: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/automotive-autonomy-msgs/automotive-navigation-msgs_3.0.3-1.bb:67: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/delphi-srr-msgs_3.1.0-1.bb:64: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/delphi-esr-msgs_3.1.0-1.bb:64: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/derived-object-msgs_3.1.0-1.bb:70: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/astuff-sensor-msgs_3.1.0-1.bb:60: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/pacmod-msgs_3.1.0-1.bb:64: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/delphi-mrr-msgs_3.1.0-1.bb:64: Could not inherit file classes/ros_catkin.bbclass
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/astuff-sensor-msgs/neobotix-usboard-msgs_3.1.0-1.bb:64: Could not inherit file classes/ros_catkin.bbclass

Signed-off-by: Martin Jansa <martin.jansa@lge.com>