graphviz: remove recipe
* it was imported from meta-oe long time ago, but now the version in meta-oe is actually
  newer and better
* from dunfell it's missing:
  https://git.openembedded.org/meta-openembedded/commit/?id=2cb6ed738ebfe27336be64e09214e4bf34c3a39a
  https://git.openembedded.org/meta-openembedded/commit/?id=e839371c3554e7d7c7311e352fefbdb23957d80c
  https://git.openembedded.org/meta-openembedded/commit/?id=b934d3bf846ee544d8786d1b851a5baf82fff70b
  and the fix for gitlab archives is on it's way to dunfell:
  https://lists.openembedded.org/g/openembedded-devel/message/89395
* from gatesgarth:
  https://git.openembedded.org/meta-openembedded/commit/?id=a661a41606d0f0b4bac1665c29ba7d5c7e6ef486
  https://git.openembedded.org/meta-openembedded/commit/?id=985be3901e79c9e45cd5d23774e3cfdaab476b44
* from hardknott:
  https://git.openembedded.org/meta-openembedded/commit/?id=c660604bc4c9a3a618a462b0888f86b71aaf4e7d
  and more importantly 2.40.1 version is now failing in hardknott with:

  | ../../lib/gvpr/.libs/libgvpr.so: error: undefined reference to 'qldexp'
  | ../../lib/gvpr/.libs/libgvpr.so: error: undefined reference to 'qfrexp'
  | collect2: error: ld returned 1 exit status
  | Makefile:734: recipe for target 'gvpr' failed

Signed-off-by: Martin Jansa <martin.jansa@lge.com>