festival: fix host-user-contamination issues
* fixes:
ERROR: festival-2.4-r0 do_package_qa: QA Issue: festival: /festival/usr/share/festival/dicts/wsj.wp39.poslexR is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/wsj.wp39.tri.ngrambin is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/COPYING.poslex is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict-0.4.diff is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmu_lts_rules.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict_extensions.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmulex.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict-0.4.out is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/Makefile is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict_compile.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/allowables.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict-0.4.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmu2ft is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/COPYING is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/oald/cuvoald710-0.2.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/oald/oald-0.4.out is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/oald/oald2ft.tar.gz is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/oald/Makefile is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/oald/oald_extensions.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/oald/oald_lts_rules.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/oald/oaldlex.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/oald/README.oald is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/oald/COPYING is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/rab_diphone/COPYING is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/rab_diphone/festvox/rab_diphone.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/rab_diphone/group/rablpc16k.group is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/kal_diphone/COPYING is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/kal_diphone/festvox/kal_diphone.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/kal_diphone/festvox/kaldurtreeZ.scm is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/kal_diphone/group/kallpc16k.group is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>