{eloquent} packagegroup-ros-world-eloquent: drop dependency on octovis
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libqt4-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/octomap/octovis_1.9.2-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'octovis' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['octovis', 'UNRESOLVED-libqt4-dev']
NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'octovis', 'UNRESOLVED-libqt4-dev']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'octovis', 'UNRESOLVED-libqt4-dev']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'octovis', 'UNRESOLVED-libqt4-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-libqt4-opengl-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/octomap/octovis_1.9.2-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-libqglviewer-qt4-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/octomap/octovis_1.9.2-1.bb DEPENDS on or otherwise requires it)

ERROR: Nothing RPROVIDES 'UNRESOLVED-libqglviewer-qt4' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/octomap/octovis_1.9.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libqglviewer-qt4' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libqglviewer-qt4']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libqtgui4' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/octomap/octovis_1.9.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libqtgui4' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libqtgui4']
ERROR: Nothing RPROVIDES 'octovis-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/octomap/octovis_1.9.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'octovis-dev'
NOTE: Runtime target 'octovis-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['octovis-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libqt4-opengl' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/octomap/octovis_1.9.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libqt4-opengl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libqt4-opengl']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>