libflann: updating to 1.9.1 to compile with gcc6
Compiling libflann 1.8.4 with gcc6 fails with:

```
| /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/libflann/1.8.4-r0/flann-1.8.4-src/src/cpp/flann/algorithms/kdtree_index.h:666:39: error: call of overloaded 'abs(flann::KDTreeIndex<flann::KL_Divergence<double> >::ElementType)' is ambiguous
|                  ElementType span = abs(point[i]-leaf_point[i]);
|                                     ~~~^~~~~~~~~~~~~~~~~~~~~~~~
```

This issue has been already addressed in the latest version 1.9.1,
hence the commit simply updates the recipe to the version 1.9.1,
which is available on github.

Signed-off-by: Lukas Bulwahn <lukas.bulwahn@oss.bmw-carit.de>