{melodic} packagegroup-ros-world-melodic: remove recipes depending on license restricted ffmpeg
* fixes:
ERROR: Nothing PROVIDES 'ffmpeg' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/usb-cam/usb-cam_0.3.6.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rospilot/rospilot_1.5.6.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/h264-encoder-core/h264-encoder-core_2.0.3-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/codec-image-transport/codec-image-transport_0.0.4.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/web-video-server/web-video-server_0.2.1-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/parrot-arsdk/parrot-arsdk_3.14.1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mrpt1/mrpt1_1.5.9-1.bb DEPENDS on or otherwise requires it)
ffmpeg was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'rospilot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rospilot', 'ffmpeg']
NOTE: Runtime target 'h264-encoder-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['h264-encoder-core', 'ffmpeg']
NOTE: Runtime target 'h264-video-encoder' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['h264-video-encoder', 'h264-encoder-core', 'ffmpeg']
NOTE: Runtime target 'codec-image-transport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['codec-image-transport', 'ffmpeg']
NOTE: Runtime target 'parrot-arsdk' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['parrot-arsdk', 'ffmpeg']
NOTE: Runtime target 'mrpt1' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-graphslam-2d' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-graphslam-2d', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-slam' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-slam', 'mrpt-graphslam-2d', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-icp-slam-2d' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-icp-slam-2d', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-reactivenav2d' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-reactivenav2d', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-navigation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-navigation', 'mrpt-reactivenav2d', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-localization' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-localization', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mvsim' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mvsim', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-rbpf-slam' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-rbpf-slam', 'mvsim', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-rawlog' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-rawlog', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-ekf-slam-2d' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-ekf-slam-2d', 'mrpt-rawlog', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-ekf-slam-3d' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-ekf-slam-3d', 'mrpt-rawlog', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-local-obstacles' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-local-obstacles', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'pose-cov-ops' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pose-cov-ops', 'mrpt-bridge', 'mrpt1', 'ffmpeg']
NOTE: Runtime target 'mrpt-map' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrpt-map', 'mrpt-bridge', 'mrpt1', 'ffmpeg']

ERROR: Nothing RPROVIDES 'ffmpeg' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/usb-cam/usb-cam_0.3.6.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/h264-encoder-core/h264-encoder-core_2.0.3-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/codec-image-transport/codec-image-transport_0.0.4.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/web-video-server/web-video-server_0.2.1-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/movie-publisher/movie-publisher_1.3.0-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mrpt1/mrpt1_1.5.9-1.bb RDEPENDS on or otherwise requires it)
ffmpeg was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'ffmpeg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ffmpeg']
NOTE: Runtime target 'movie-publisher' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['movie-publisher', 'ffmpeg']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>

ffmpeg

Signed-off-by: Martin Jansa <martin.jansa@lge.com>