{galactic} mavros: switch CXX standard from 20 back to 14
* it was introduced in:
  https://github.com/mavlink/mavros/commit/cf15f80f9ee6d1b5ab0ffd665207bc1947e4ed41

* otherwise rclcpp include fails to build with gcc-11 (in honister and kirkstone), builds ok with gcc-10 and older):

FAILED: CMakeFiles/mavros.dir/src/lib/enum_to_string.cpp.o
/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++ -DDEFAULT_RMW_IMPLEMENTATION=rmw_cyclonedds_cpp -DTINYXML2_IMPORT -Dmavros_EXPORTS -I/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/git/include -I/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/eigen3 -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0=/usr/src/debug/mavros/2.0.4-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0=/usr/src/debug/mavros/2.0.4-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot -std=c++2a -Wall -Wextra -Wpedantic -Wcomment -fPIC -std=gnu++20 -MD -MT CMakeFiles/mavros.dir/src/lib/enum_to_string.cpp.o -MF CMakeFiles/mavros.dir/src/lib/enum_to_string.cpp.o.d -o CMakeFiles/mavros.dir/src/lib/enum_to_string.cpp.o -c /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/git/src/lib/enum_to_string.cpp
In file included from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/subscription.hpp:45,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/any_executable.hpp:25,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/memory_strategy.hpp:25,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/memory_strategies.hpp:18,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/executor_options.hpp:20,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/executor.hpp:37,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/executors.hpp:21,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/rclcpp.hpp:155,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/git/src/lib/enum_to_string.cpp:22:
/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/subscription_options.hpp:97:47: error: expected unqualified-id before ')' token
   97 |   SubscriptionOptionsWithAllocator<Allocator>() {}
      |                                               ^
In file included from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/publisher.hpp:40,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/topic_statistics/subscription_topic_statistics.hpp:31,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/subscription.hpp:50,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/any_executable.hpp:25,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/memory_strategy.hpp:25,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/memory_strategies.hpp:18,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/executor_options.hpp:20,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/executor.hpp:37,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/executors.hpp:21,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/rclcpp.hpp:155,
                 from /jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/git/src/lib/enum_to_string.cpp:22:
/jenkins/mjansa/build/ros/webos-galactic-kirkstone/tmp-glibc/work/qemux86-webos-linux/mavros/2.0.4-1-r0/recipe-sysroot/usr/include/rclcpp/publisher_options.hpp:75:44: error: expected unqualified-id before ')' token
   75 |   PublisherOptionsWithAllocator<Allocator>() {}
      |                                            ^

Signed-off-by: Martin Jansa <martin.jansa@lge.com>