gscam, pocketsphinx, ros-pocketsphinx, wxwidgets, wxpython, joint-state-publisher, sound-play: blacklist because of gstreamer 0.10 dependency
* if you still need these and use older OpenEmbedded which still provides
  gstreamer 0.10 recipes, you can unblacklist these by setting it to empty
  value, e.g.
  PNBLACKLIST[gscam] = ""
  in your local.conf or distro config.

* gstreamer 0.10 recipes were removed with:
  commit 010c2f388095c1615b99d9f38a26bbd0c9e77b39
  Author: Khem Raj <raj.khem@gmail.com>
  Date:   Fri Mar 15 18:36:40 2019 -0700

    gstreamer-0.10: Remove recipes

    It has been over 5+ years for migration to gstreamer 1.x

    Signed-off-by: Khem Raj <raj.khem@gmail.com>

* webkit-gtk was removed from oe-core even earlier in 2.0 Jethro:
  commit 68a1e346751c4d644a14035b0d7acf01d212f38c
  Author: Alexander Kanavin <alexander.kanavin@linux.intel.com>
  Date:   Mon Jun 15 17:15:39 2015 +0300

    webkit-gtk: remove the recipe for the obsolete version 1.8.3

    webkitgtk 2.8.3 is provided instead and midori browser is replaced by epiphany in
    separate commits.

    (From OE-Core rev: 1a72dc9c44c7806c869c3b3afcd5d31bcf2da979)

* fixes packagegroup-ros-world errors:
  ERROR: Nothing PROVIDES 'gst-plugins-good' (but /OE/build/oe-core/meta-ros/recipes-ros/gscam/gscam_0.2.0.bb DEPENDS on or otherwise requires it). Close matches:
    gstreamer1.0-plugins-good
  NOTE: Runtime target 'gscam' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['gscam', 'gst-plugins-good']
  NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'gscam', 'gst-plugins-good']
  NOTE: Runtime target 'core-image-ros-world' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['core-image-ros-world', 'packagegroup-ros-world', 'gscam', 'gst-plugins-good']
  ERROR: Nothing PROVIDES 'gst-plugins-base' (but /OE/build/oe-core/meta-ros/recipes-ros/gscam/gscam_0.2.0.bb DEPENDS on or otherwise requires it). Close matches:
    gstreamer1.0-plugins-base
    gstreamer1.0-plugins-bad
  ERROR: Nothing PROVIDES 'gstreamer' (but /OE/build/oe-core/meta-ros/recipes-ros/gscam/gscam_0.2.0.bb DEPENDS on or otherwise requires it). Close matches:
    gstreamer1.0
    gstreamer1.0-omx
  ERROR: Nothing RPROVIDES 'gst-plugins-good-gconfelements' (but /OE/build/oe-core/meta-ros/recipes-ros/ros-pocketsphinx/ros-pocketsphinx_0.3.0.bb RDEPENDS on or otherwise requires it)
  NOTE: Runtime target 'gst-plugins-good-gconfelements' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['gst-plugins-good-gconfelements']
  NOTE: Runtime target 'ros-pocketsphinx' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['ros-pocketsphinx', 'gst-plugins-good-gconfelements']
  ERROR: Nothing RPROVIDES 'ros-pocketsphinx-dev' (but /OE/build/oe-core/meta-ros/recipes-ros/ros-pocketsphinx/ros-pocketsphinx_0.3.0.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'ros-pocketsphinx-dev'
  NOTE: Runtime target 'ros-pocketsphinx-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['ros-pocketsphinx-dev']
  NOTE: Runtime target 'gstreamer0.10-pocketsphinx' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['gstreamer0.10-pocketsphinx']
  ERROR: Nothing RPROVIDES 'gscam-dev' (but /OE/build/oe-core/meta-ros/recipes-ros/gscam/gscam_0.2.0.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'gscam-dev'
  NOTE: Runtime target 'gscam-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['gscam-dev']

  ERROR: Nothing PROVIDES 'gst-plugins-good' (but /OE/build/oe-core/meta-ros/recipes-extended/cmusphinx/pocketsphinx_0.8.bb DEPENDS on or otherwise requires it). Close matches:
    gstreamer1.0-plugins-good
  ERROR: Required build target 'pocketsphinx' has no buildable providers.
  Missing or unbuildable dependency chain was: ['pocketsphinx', 'gst-plugins-good']

  Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
  NOTE: Started PRServer with DBfile: /OE/build/oe-core/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 45411, PID: 32361
  Parsing recipes...done.
  Parsing of 2732 .bb files complete (0 cached, 2732 parsed). 3866 targets, 65 skipped, 0 masked, 0 errors.
  NOTE: Resolving any missing task queue dependencies
  ERROR: Nothing PROVIDES 'webkit-gtk' (but /OE/build/oe-core/meta-ros/recipes-extended/wxwidgets/wxwidgets_2.9.5.bb DEPENDS on or otherwise requires it). Close matches:
    webkitgtk
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'wxpython', 'wxwidgets', 'webkit-gtk']

  Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
  NOTE: Started PRServer with DBfile: /OE/build/oe-core/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 36105, PID: 32425
  Parsing recipes...done.
  Parsing of 2732 .bb files complete (0 cached, 2732 parsed). 3866 targets, 104 skipped, 0 masked, 0 errors.
  NOTE: Resolving any missing task queue dependencies
  ERROR: Nothing PROVIDES 'gstreamer' (but /OE/build/oe-core/meta-ros/recipes-extended/wxwidgets/wxwidgets_2.9.5.bb DEPENDS on or otherwise requires it). Close matches:
    gstreamer1.0
    gstreamer1.0-omx
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'joint-state-publisher', 'wxpython', 'wxwidgets', 'gstreamer']

  ERROR: Nothing RPROVIDES 'gst-plugins-ugly' (but /OE/build/oe-core/meta-ros/recipes-ros/audio-common/sound-play_0.2.13.bb RDEPENDS on or otherwise requires it)
  NOTE: Runtime target 'gst-plugins-ugly' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['gst-plugins-ugly']
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'sound-play', 'gst-plugins-ugly']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>