{melodic} libdlib: fetch dlib with bitbake fetcher and fix build issues
* fixes externally built dlib from trying to link with native
  libsqlite3.so and libnsl.so

DEBUG: Executing shell function do_compile
NOTE: VERBOSE=1 cmake --build ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build --target all -- -j 80
[1/3] cd ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake --build . --config Release -- -Wno-deprecated-declarations -Wno-terminate -Wno-pragmas -Wno-shift-negative-value && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E copy_directory ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-src/dlib ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/devel/include/libdlib && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E copy_if_different ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build/libdlib.a ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/devel/lib && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/EP_libdlib-prefix/src/EP_libdlib-stamp/EP_libdlib-build
FAILED: EP_libdlib-prefix/src/EP_libdlib-stamp/EP_libdlib-build
cd ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake --build . --config Release -- -Wno-deprecated-declarations -Wno-terminate -Wno-pragmas -Wno-shift-negative-value && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E copy_directory ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-src/dlib ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/devel/include/libdlib && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E copy_if_different ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build/libdlib.a ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/devel/lib && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/EP_libdlib-prefix/src/EP_libdlib-stamp/EP_libdlib-build
ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -Hros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-src/dlib -Bros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build --check-build-system CMakeFiles/Makefile.cmake 0
ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E cmake_progress_start ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build/CMakeFiles ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
make -f CMakeFiles/dlib.dir/build.make CMakeFiles/dlib.dir/depend
make[2]: Entering directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
cd ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E cmake_depends "Unix Makefiles" ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-src/dlib ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-src/dlib ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build/CMakeFiles/dlib.dir/DependInfo.cmake --color=
make[2]: Leaving directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
make -f CMakeFiles/dlib.dir/build.make CMakeFiles/dlib.dir/build
make[2]: Entering directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
make[2]: Nothing to be done for 'CMakeFiles/dlib.dir/build'.
make[2]: Leaving directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
[ 50%] Built target dlib
make -f CMakeFiles/dlib_shared.dir/build.make CMakeFiles/dlib_shared.dir/depend
make[2]: Entering directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
cd ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build && ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E cmake_depends "Unix Makefiles" ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-src/dlib ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-src/dlib ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build/CMakeFiles/dlib_shared.dir/DependInfo.cmake --color=
make[2]: Leaving directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
make -f CMakeFiles/dlib_shared.dir/build.make CMakeFiles/dlib_shared.dir/build
make[2]: Entering directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
[ 51%] Linking CXX shared library libdlib.so
ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/cmake -E cmake_link_script CMakeFiles/dlib_shared.dir/link.txt --verbose=1
ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/aarch64-oe-linux/aarch64-oe-linux-g++   --sysroot=ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot -fPIC -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0=/usr/src/debug/libdlib/0.6.15-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   --sysroot=ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot -O3 -DNDEBUG -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -shared -Wl,-soname,libdlib.so.19.9.0 -o libdlib.so.19.9.0 CMakeFiles/dlib_shared.dir/base64/base64_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/bigint/bigint_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/bigint/bigint_kernel_2.cpp.o CMakeFiles/dlib_shared.dir/bit_stream/bit_stream_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o CMakeFiles/dlib_shared.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o CMakeFiles/dlib_shared.dir/md5/md5_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/tokenizer/tokenizer_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/unicode/unicode.cpp.o CMakeFiles/dlib_shared.dir/data_io/image_dataset_metadata.cpp.o CMakeFiles/dlib_shared.dir/data_io/mnist.cpp.o CMakeFiles/dlib_shared.dir/global_optimization/global_function_search.cpp.o CMakeFiles/dlib_shared.dir/sockets/sockets_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/bsp/bsp.cpp.o CMakeFiles/dlib_shared.dir/dir_nav/dir_nav_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/dir_nav/dir_nav_kernel_2.cpp.o CMakeFiles/dlib_shared.dir/dir_nav/dir_nav_extensions.cpp.o CMakeFiles/dlib_shared.dir/linker/linker_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/logger/extra_logger_headers.cpp.o CMakeFiles/dlib_shared.dir/logger/logger_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/logger/logger_config_file.cpp.o CMakeFiles/dlib_shared.dir/misc_api/misc_api_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/misc_api/misc_api_kernel_2.cpp.o CMakeFiles/dlib_shared.dir/sockets/sockets_extensions.cpp.o CMakeFiles/dlib_shared.dir/sockets/sockets_kernel_2.cpp.o CMakeFiles/dlib_shared.dir/sockstreambuf/sockstreambuf.cpp.o CMakeFiles/dlib_shared.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o CMakeFiles/dlib_shared.dir/server/server_kernel.cpp.o CMakeFiles/dlib_shared.dir/server/server_iostream.cpp.o CMakeFiles/dlib_shared.dir/server/server_http.cpp.o CMakeFiles/dlib_shared.dir/threads/multithreaded_object_extension.cpp.o CMakeFiles/dlib_shared.dir/threads/threaded_object_extension.cpp.o CMakeFiles/dlib_shared.dir/threads/threads_kernel_1.cpp.o CMakeFiles/dlib_shared.dir/threads/threads_kernel_2.cpp.o CMakeFiles/dlib_shared.dir/threads/threads_kernel_shared.cpp.o CMakeFiles/dlib_shared.dir/threads/thread_pool_extension.cpp.o CMakeFiles/dlib_shared.dir/threads/async.cpp.o CMakeFiles/dlib_shared.dir/timer/timer.cpp.o CMakeFiles/dlib_shared.dir/stack_trace.cpp.o CMakeFiles/dlib_shared.dir/dnn/cpu_dlib.cpp.o CMakeFiles/dlib_shared.dir/dnn/tensor_tools.cpp.o CMakeFiles/dlib_shared.dir/external/libpng/png.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngerror.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngget.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngmem.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngpread.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngread.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngrio.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngrtran.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngrutil.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngset.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngtrans.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngwio.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngwrite.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngwtran.c.o CMakeFiles/dlib_shared.dir/external/libpng/pngwutil.c.o CMakeFiles/dlib_shared.dir/external/zlib/adler32.c.o CMakeFiles/dlib_shared.dir/external/zlib/compress.c.o CMakeFiles/dlib_shared.dir/external/zlib/crc32.c.o CMakeFiles/dlib_shared.dir/external/zlib/deflate.c.o CMakeFiles/dlib_shared.dir/external/zlib/gzclose.c.o CMakeFiles/dlib_shared.dir/external/zlib/gzlib.c.o CMakeFiles/dlib_shared.dir/external/zlib/gzread.c.o CMakeFiles/dlib_shared.dir/external/zlib/gzwrite.c.o CMakeFiles/dlib_shared.dir/external/zlib/infback.c.o CMakeFiles/dlib_shared.dir/external/zlib/inffast.c.o CMakeFiles/dlib_shared.dir/external/zlib/inflate.c.o CMakeFiles/dlib_shared.dir/external/zlib/inftrees.c.o CMakeFiles/dlib_shared.dir/external/zlib/trees.c.o CMakeFiles/dlib_shared.dir/external/zlib/uncompr.c.o CMakeFiles/dlib_shared.dir/external/zlib/zutil.c.o CMakeFiles/dlib_shared.dir/image_loader/png_loader.cpp.o CMakeFiles/dlib_shared.dir/image_saver/save_png.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcomapi.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdapimin.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdapistd.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdatasrc.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdcoefct.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdcolor.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jddctmgr.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdhuff.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdinput.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdmainct.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdmarker.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdmaster.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdmerge.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdphuff.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdpostct.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdsample.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jerror.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jidctflt.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jidctfst.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jidctint.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jidctred.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jmemmgr.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jmemnobs.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jquant1.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jquant2.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jutils.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcapimin.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jdatadst.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcparam.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcapistd.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcmarker.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcinit.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcmaster.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcdctmgr.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jccoefct.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jccolor.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jchuff.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcmainct.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcphuff.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcprepct.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jcsample.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jfdctint.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jfdctflt.cpp.o CMakeFiles/dlib_shared.dir/external/libjpeg/jfdctfst.cpp.o CMakeFiles/dlib_shared.dir/image_loader/jpeg_loader.cpp.o CMakeFiles/dlib_shared.dir/image_saver/save_jpeg.cpp.o -Wl,-rpath,ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/lib: -lpthread ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/lib/libsqlite3.so
ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/bin/aarch64-oe-linux/../../libexec/aarch64-oe-linux/gcc/aarch64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/recipe-sysroot-native/usr/lib/libsqlite3.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/dlib_shared.dir/build.make:1884: recipe for target 'libdlib.so.19.9.0' failed
make[2]: *** [libdlib.so.19.9.0] Error 1
make[2]: Leaving directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/dlib_shared.dir/all' failed
make[1]: *** [CMakeFiles/dlib_shared.dir/all] Error 2
make[1]: Leaving directory 'ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/build/libdlib-build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
ninja: build stopped: subcommand failed.
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at ros1-melodic-thud/tmp-glibc/work/aarch64-oe-linux/libdlib/0.6.15-1-r0/temp/log.do_compile.9888)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>