{dashing} packagegroup-ros-world-dashing: Remove various packages unless LICENSE_FLAGS_WHITELIST contains "commercial"
* Remove web-video-server, h264-video-encoder, and h264-encoder-core
  unless LICENSE_FLAGS_WHITELIST contains "commercial".

* fixes:
ERROR: Nothing PROVIDES 'ffmpeg' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/web-video-server/web-video-server_1.0.0-1.bb, /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/h264-encoder-core/h264-encoder-core_2.0.3-1.bb DEPENDS on or otherwise requires it)
ffmpeg was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'web-video-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['web-video-server', 'ffmpeg']
NOTE: Runtime target 'h264-encoder-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['h264-encoder-core', 'ffmpeg']
ERROR: Nothing PROVIDES 'h264-encoder-core' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/h264-video-encoder/h264-video-encoder_2.0.0-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'h264-encoder-core'
NOTE: Runtime target 'h264-video-encoder' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['h264-video-encoder', 'h264-encoder-core']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>