{melodic} asmach-tutorials: add dependency on smach-msgs
* fixes:
DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
-- Check for working C compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/devel
-- Using CMAKE_PREFIX_PATH: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot/opt/ros/melodic;ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot/usr
-- This workspace overlays: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot/opt/ros/melodic
-- Found PythonInterp: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot-native/usr/bin/python-native/python2 (found suitable version "2.7.16", minimum required is "2")
-- Using PYTHON_EXECUTABLE: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot-native/usr/bin/python-native/python2
-- Using default Python package layout
-- Found PY_em: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using empy: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using CATKIN_ENABLE_TESTING: 0
-- catkin 0.7.23
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;gennodejs;genpy
CMake Error at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot/opt/ros/melodic/share/smach_ros/cmake/smach_rosConfig.cmake:231 (find_package):
  Could not find a package configuration file provided by "smach_msgs" with
  any of the following names:

    smach_msgsConfig.cmake
    smach_msgs-config.cmake

  Add the installation prefix of "smach_msgs" to CMAKE_PREFIX_PATH or set
  "smach_msgs_DIR" to a directory containing one of the above files.  If
  "smach_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/recipe-sysroot/opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/asmach-tutorials/1.0.16-1-r0/temp/log.do_configure.34388)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>