{foxy} fcl: add dependency on octomap needed by moveit-core
* otherwise moveit-core fails to build with:
FAILED: collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/src/collision_common.cpp.o
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++ -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DDEFAULT_RMW_IMPLEMENTATION=rmw_fastrtps_cpp -DFMT_LOCALE -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -Dmoveit_collision_detection_fcl_EXPORTS -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/background_processing/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/exceptions/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/backtrace/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/constraint_samplers/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/controller_manager/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/distance_field/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_distance_field/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/dynamics_solver/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/kinematics_base/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/kinematics_metrics/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/robot_model/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/transforms/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/robot_state/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/robot_trajectory/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/kinematic_constraints/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/macros/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/planning_interface/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/planning_request_adapter/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/planning_scene/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/profiler/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/sensor_manager/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/trajectory_processing/include -ITOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/utils/include -Iinclude -isystem TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot/usr/include/eigen3 -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0=/usr/src/debug/moveit-core/2.1.0-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0=/usr/src/debug/moveit-core/2.1.0-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot -DNDEBUG -fPIC -Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wcast-qual -Wno-unused-parameter -Wno-unused-function -Wno-maybe-uninitialized -std=c++14 -MD -MT collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/src/collision_common.cpp.o -MF collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/src/collision_common.cpp.o.d -o collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/src/collision_common.cpp.o -c TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp: In function 'bool collision_detection::distanceCallback(fcl::CollisionObjectd*, fcl::CollisionObjectd*, void*, double&)':
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp:523:40: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
  523 |        !std::static_pointer_cast<const fcl::OcTreed>(o1->collisionGeometry())->getRoot()) ||
      |                                        ^~~
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp:523:14: error: parse error in template argument list
  523 |        !std::static_pointer_cast<const fcl::OcTreed>(o1->collisionGeometry())->getRoot()) ||
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp:523:77: error: no matching function for call to 'static_pointer_cast<<expression error> >(const std::shared_ptr<const fcl::CollisionGeometry<double> >&)'
  523 |        !std::static_pointer_cast<const fcl::OcTreed>(o1->collisionGeometry())->getRoot()) ||
      |                                                                             ^
In file included from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot/usr/include/c++/10.2.0/bits/shared_ptr.h:52,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot/usr/include/c++/10.2.0/memory:84,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/macros/include/moveit/macros/declare_ptr.h:37,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/macros/include/moveit/macros/class_forward.h:39,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection/include/moveit/collision_detection/world.h:39,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h:39,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp:37:
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot/usr/include/c++/10.2.0/bits/shared_ptr_base.h:1575:5: note: candidate: 'template<class _Tp, class _Tp1, __gnu_cxx::_Lock_policy _Lp> std::__shared_ptr<_Tp1, _Lp> std::static_pointer_cast(const std::__shared_ptr<_Tp2, _Lp>&)'
 1575 |     static_pointer_cast(const __shared_ptr<_Tp1, _Lp>& __r) noexcept
      |     ^~~~~~~~~~~~~~~~~~~
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot/usr/include/c++/10.2.0/bits/shared_ptr_base.h:1575:5: note:   template argument deduction/substitution failed:
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp:523:77: error: template argument 1 is invalid
  523 |        !std::static_pointer_cast<const fcl::OcTreed>(o1->collisionGeometry())->getRoot()) ||
      |                                                                             ^
In file included from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot/usr/include/c++/10.2.0/memory:84,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/macros/include/moveit/macros/declare_ptr.h:37,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/macros/include/moveit/macros/class_forward.h:39,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection/include/moveit/collision_detection/world.h:39,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h:39,
                 from TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp:37:
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/recipe-sysroot/usr/include/c++/10.2.0/bits/shared_ptr.h:581:5: note: candidate: 'template<class _Tp, class _Up> std::shared_ptr<_Tp> std::static_pointer_cast(const std::shared_ptr<_Tp>&)'
  581 |     static_pointer_cast(const shared_ptr<_Up>& __r) noexcept
      |     ^~~~~~~~~~~~~~~~~~~
...
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp: In function 'collision_detection::FCLGeometryConstPtr collision_detection::createCollisionGeometry(const ShapeConstPtr&, const T*, int)':
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp:842:18: error: expected type-specifier
  842 |       cg_g = new fcl::OcTreed(g->octree);
      |                  ^~~
TOPDIR/tmp-glibc/work/qemux86-webos-linux/moveit-core/2.1.0-1-r0/git/collision_detection_fcl/src/collision_common.cpp:842:17: error: expected ';'
  842 |       cg_g = new fcl::OcTreed(g->octree);
      |                 ^~~~
      |                 ;

Signed-off-by: Martin Jansa <martin.jansa@lge.com>