packagegroup-ros-turtlebot3-*: remove packages depending on opengl in DISTRO_FEATURES
* fixes:
ERROR: Nothing RPROVIDES 'compressed-image-transport' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
compressed-image-transport was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'compressed-image-transport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['compressed-image-transport']
NOTE: Runtime target 'packagegroup-ros-turtlebot3-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-turtlebot3-core', 'compressed-image-transport']
NOTE: Runtime target 'ros-image-turtlebot3-all' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-turtlebot3-all', 'packagegroup-ros-turtlebot3-core', 'compressed-image-transport']
NOTE: Runtime target 'packagegroup-ros-turtlebot3-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-turtlebot3-extended', 'compressed-image-transport']
ERROR: Nothing RPROVIDES 'rgbd-launch' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
rgbd-launch was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'rgbd-launch' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rgbd-launch']
ERROR: Nothing RPROVIDES 'depthimage-to-laserscan' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
depthimage-to-laserscan was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'depthimage-to-laserscan' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['depthimage-to-laserscan']
ERROR: Nothing RPROVIDES 'turtlebot3-autorace' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
turtlebot3-autorace was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'turtlebot3-autorace' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-autorace']
ERROR: Nothing RPROVIDES 'turtlebot3-applications' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
turtlebot3-applications was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'turtlebot3-applications' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-applications']
ERROR: Nothing PROVIDES 'compressed-image-transport' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1/recipes-extended/raspicam-node/raspicam-node_git.bb DEPENDS on or otherwise requires it)
compressed-image-transport was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'raspicam-node' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['raspicam-node', 'compressed-image-transport']
ERROR: Nothing RPROVIDES 'raspicam-node-dev' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1/recipes-extended/raspicam-node/raspicam-node_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'raspicam-node-dev'
NOTE: Runtime target 'raspicam-node-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['raspicam-node-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>