{eloquent} costmap-converter, slide-show: blacklist with vc4graphics-without-opengl skip group
* fixes:
ERROR: Nothing PROVIDES 'cv-bridge' (but ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/costmap-converter/costmap-converter_0.1.1-1.bb DEPENDS on or otherwise requires it)
cv-bridge was skipped: Recipe is blacklisted: vc4graphics-without-opengl: depends on opencv->gstreamer1.0-plugins-base which is not available for raspberrypi MACHINEs with vc4graphics in MACHINE_FEATURES, but without opengl in DISTRO_FEATURES
NOTE: Runtime target 'costmap-converter' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['costmap-converter', 'cv-bridge']
NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'costmap-converter', 'cv-bridge']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'costmap-converter', 'cv-bridge']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'costmap-converter', 'cv-bridge']
ERROR: Nothing RPROVIDES 'cv-bridge' (but ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/slide-show/slide-show_0.1.0-1.bb, ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/costmap-converter/costmap-converter_0.1.1-1.bb RDEPENDS on or otherwise requires it)
cv-bridge was skipped: Recipe is blacklisted: vc4graphics-without-opengl: depends on opencv->gstreamer1.0-plugins-base which is not available for raspberrypi MACHINEs with vc4graphics in MACHINE_FEATURES, but without opengl in DISTRO_FEATURES
NOTE: Runtime target 'cv-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cv-bridge']
NOTE: Runtime target 'slide-show' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slide-show', 'cv-bridge']
NOTE: Runtime target 'slide-show-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slide-show-dev', 'cv-bridge']
ERROR: Nothing RPROVIDES 'opencv' (but ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/slide-show/slide-show_0.1.0-1.bb RDEPENDS on or otherwise requires it)
opencv was skipped: Recipe is blacklisted: depends on gstreamer1.0-plugins-base which depends on virtual/libgles2, virtual/egl which is not available for raspberrypi MACHINEs with vc4graphics in MACHINE_FEATURES, but without opengl in DISTRO_FEATURES
NOTE: Runtime target 'opencv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['opencv']
ERROR: Nothing RPROVIDES 'costmap-converter-dev' (but ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/costmap-converter/costmap-converter_0.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'costmap-converter-dev'
NOTE: Runtime target 'costmap-converter-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['costmap-converter-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>