{common}{jazzy} *ogre*: Update mesa to virtual/mesa
Update build and export dependencies for various ogre recipes from
mesa to virtual/mesa to avoid build failures with mesa-gl as mesa
provider.

ERROR: Nothing PROVIDES 'mesa' (but meta-ros/meta-ros2-jazzy/generated-recipes/rviz/rviz-ogre-vendor_14.1.19-1.bb,
       meta-ros/meta-ros2-jazzy/generated-recipes/gz-ogre-next-vendor/gz-ogre-next-vendor_0.0.5-1.bb
       DEPENDS on or otherwise requires it)
mesa was skipped: PREFERRED_PROVIDER_virtual/libgl set to mesa-gl, not mesa

Signed-off-by: Christian Kohn <chris.kohn@amd.com>