ogre: enable GL plugin only with opengl in DISTRO_FEATURES
* fixes:
ERROR: Nothing PROVIDES 'virtual/libgl' (but ros2-foxy-dunfell/meta-ros/meta-ros-common/recipes-devtools/ogre/ogre_1.12.8.bb DEPENDS on or otherwise requires it)
mesa-gl PROVIDES virtual/libgl but was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'libglu' (but ros2-foxy-dunfell/meta-ros/meta-ros-common/recipes-devtools/ogre/ogre_1.12.8.bb DEPENDS on or otherwise requires it)
libglu was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
ERROR: Nothing RPROVIDES 'ogre-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros-common/recipes-devtools/ogre/ogre_1.12.8.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ogre-dev'
NOTE: Runtime target 'ogre-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ogre-dev']
ERROR: Nothing RPROVIDES 'ogre' (but ros2-foxy-dunfell/meta-ros/meta-ros-common/recipes-devtools/ogre/ogre_1.12.8.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ogre'
NOTE: Runtime target 'ogre' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ogre']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>