{noetic} audio-to-spectrogram: restrict on x11 as well
* fixes world builds with webOS:
ERROR: Nothing RPROVIDES 'image-view' (but /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/jsk-recognition/audio-to-spectrogram_1.2.15-1.bb RDEPENDS on or otherwise requires it)
image-view was skipped: Recipe is blacklisted: Depends on gtk+->x11
NOTE: Runtime target 'image-view' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-view']
NOTE: Runtime target 'audio-to-spectrogram' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-to-spectrogram', 'image-view']
NOTE: Runtime target 'audio-to-spectrogram-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-to-spectrogram-dev', 'image-view']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>