console-bridge: upgrade to 1.0.1
* console-bridge-vendor-1.2.2-1-r0 now in foxy checks for 1.0.1 version now
  and when it builds it with ExternalProject_Add it fails with:

  ERROR: console-bridge-vendor-1.2.2-1-r0 do_populate_sysroot: QA Issue: console_bridge.pc failed sanity test (tmpdir) in path /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/console-bridge-vendor/1.2.2-1-r0/sysroot-destdir/usr/lib/pkgconfig [pkgconfig]
  ERROR: console-bridge-vendor-1.2.2-1-r0 do_populate_sysroot: QA staging was broken by the package built above
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/console-bridge-vendor/1.2.2-1-r0/temp/log.do_populate_sysroot.49454
  ERROR: Task (/jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/console-bridge-vendor/console-bridge-vendor_1.2.2-1.bb:do_populate_sysroot) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>