python-nose-yanc: fix LIC_FILES_CHKSUM
* use file inside the source repo, COMMON_LICENSE_DIR shouldn't be used
  in LIC_FILES_CHKSUM except few exceptions where it makes sense (like
  pure meta-data without any SRC_URI e.g. image, packagegroup recipes).
  Using COMMON_LICENSE_DIR completely defeats whole purpose of checking
  LIC_FILES_CHKSUM during the build.

* the license file was renamed in:
  https://git.openembedded.org/openembedded-core/commit/?id=5ecf139a31fa7bd813855f1235ea9f434fbcb2e0

* fixes:
  WARNING: python3-nose-yanc-0.3.3-r0 do_populate_lic: Could not copy license file openembedded-core/meta/files/common-licenses/GPL-3.0 to tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/python3-nose-yanc/0.3.3-r0/license-destdir/python3-nose-yanc/GPL-3.0: [Errno 2] No such file or directory: 'openembedded-core/meta/files/common-licenses/GPL-3.0'
  ERROR: python3-nose-yanc-0.3.3-r0 do_populate_lic: QA Issue: python3-nose-yanc: LIC_FILES_CHKSUM points to an invalid file: openembedded-core/meta/files/common-licenses/GPL-3.0 [license-checksum]
  ERROR: python3-nose-yanc-0.3.3-r0 do_populate_lic: Fatal QA errors found, failing task.
  ERROR: Logfile of failure stored in: tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/python3-nose-yanc/0.3.3-r0/temp/log.do_populate_lic.16902
  ERROR: Task (meta-ros/meta-ros-common/recipes-devtools/python/python3-nose-yanc_0.3.3.bb:do_populate_lic) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>