{common} openexr: Remove unnecessary clang-native dependency
meta-clang is not a required layer and clang-native is not needed
to build this recipe. Remove unnecessary dependency.

ERROR: Nothing PROVIDES 'clang-native' (but meta-ros/meta-ros-common/recipes-graphics/openexr/openexr_3.2.1.bb
       DEPENDS on or otherwise requires it). Close matches:

Signed-off-by: Christian Kohn <chris.kohn@amd.com>