{humble} generate-parameter-library-example, generate-parameter-module-example: delete bbappends
The recipes were deleted in:
https://github.com/ros/meta-ros/pull/1637
but bbappends weren't, causing parsing failure:
  ERROR: No recipes in default available for:
    meta-ros/meta-ros2-humble/recipes-bbappends/generate-parameter-library/generate-parameter-library-example_0.5.0-1.bbappend
    meta-ros/meta-ros2-humble/recipes-bbappends/generate-parameter-library/generate-parameter-module-example_0.5.0-1.bbappend

Signed-off-by: Martin Jansa <martin2.jansa@lgepartner.com>