{noetic} rcdiscover: move package.xml so it's packaged in PN
* fixes:
  ERROR: rcdiscover-1.1.2-1-r0 do_package: QA Issue: rcdiscover: Files/directories were installed but not shipped in any package:
    /usr/share/package.xml
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  rcdiscover: 1 installed and not shipped files. [installed-vs-shipped]
  ERROR: rcdiscover-1.1.2-1-r0 do_package: Fatal QA errors found, failing task.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>