meta-ros-common: Move python3-nose from meta-ros2
The noetic builds now require python3-nose for catkin.

    ERROR: Nothing PROVIDES 'python3-nose-native' (but virtual:native:/meta-ros/meta-ros1-noetic/generated-recipes/catkin/catkin_0.8.10-1.bb DEPENDS on or otherwise requires it). Close matches:
      python3-nose-yanc-native
      python3-rosdep-native
      python3-twine-native
    NOTE: Runtime target 'ros-core' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['ros-core', 'catkin-native', 'python3-nose-native']
    ERROR: Required build target 'ros-image-core' has no buildable providers.
    Missing or unbuildable dependency chain was: ['ros-image-core', 'ros-core', 'catkin-native', 'python3-nose-native']

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>