{noetic} pr2-app-manager: add runtime dependency on bash
* fixes:
  ERROR: pr2-app-manager-0.6.1-r0 do_package_qa: QA Issue:
  /opt/ros/noetic/lib/pr2_app_manager/install_applications.sh contained
  in package pr2-app-manager requires /bin/bash, but no providers found in
  RDEPENDS_pr2-app-manager? [file-rdeps]

Signed-off-by: Martin Jansa <martin.jansa@lge.com>