{noetic} rm-chassis-controllers: add missing dependency on nav-msgs
* fixes:

FAILED: CMakeFiles/rm_chassis_controllers.dir/src/chassis_base.cpp.o
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"rm_chassis_controllers\" -Drm_chassis_controllers_EXPORTS -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/include/eigen3 -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot -fPIC   -Wall -Werror -Wno-enum-compare -std=gnu++14 -MD -MT CMakeFiles/rm_chassis_controllers.dir/src/chassis_base.cpp.o -MF CMakeFiles/rm_chassis_controllers.dir/src/chassis_base.cpp.o.d -o CMakeFiles/rm_chassis_controllers.dir/src/chassis_base.cpp.o -c /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/chassis_base.cpp
In file included from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/chassis_base.cpp:37:
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include/rm_chassis_controllers/chassis_base.h:50:10: fatal error: nav_msgs/Odometry.h: No such file or directory
   50 | #include <nav_msgs/Odometry.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

FAILED: CMakeFiles/rm_chassis_controllers.dir/src/swerve.cpp.o
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"rm_chassis_controllers\" -Drm_chassis_controllers_EXPORTS -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/include/eigen3 -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot -fPIC   -Wall -Werror -Wno-enum-compare -std=gnu++14 -MD -MT CMakeFiles/rm_chassis_controllers.dir/src/swerve.cpp.o -MF CMakeFiles/rm_chassis_controllers.dir/src/swerve.cpp.o.d -o CMakeFiles/rm_chassis_controllers.dir/src/swerve.cpp.o -c /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/swerve.cpp
In file included from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include/rm_chassis_controllers/swerve.h:41,
                 from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/swerve.cpp:38:
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include/rm_chassis_controllers/chassis_base.h:50:10: fatal error: nav_msgs/Odometry.h: No such file or directory
   50 | #include <nav_msgs/Odometry.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

FAILED: CMakeFiles/rm_chassis_controllers.dir/src/balance.cpp.o
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"rm_chassis_controllers\" -Drm_chassis_controllers_EXPORTS -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/include/eigen3 -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot -fPIC   -Wall -Werror -Wno-enum-compare -std=gnu++14 -MD -MT CMakeFiles/rm_chassis_controllers.dir/src/balance.cpp.o -MF CMakeFiles/rm_chassis_controllers.dir/src/balance.cpp.o.d -o CMakeFiles/rm_chassis_controllers.dir/src/balance.cpp.o -c /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/balance.cpp
In file included from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include/rm_chassis_controllers/balance.h:41,
                 from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/balance.cpp:37:
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include/rm_chassis_controllers/chassis_base.h:50:10: fatal error: nav_msgs/Odometry.h: No such file or directory
   50 | #include <nav_msgs/Odometry.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
FAILED: CMakeFiles/rm_chassis_controllers.dir/src/sentry.cpp.o
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"rm_chassis_controllers\" -Drm_chassis_controllers_EXPORTS -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/include/eigen3 -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot -fPIC   -Wall -Werror -Wno-enum-compare -std=gnu++14 -MD -MT CMakeFiles/rm_chassis_controllers.dir/src/sentry.cpp.o -MF CMakeFiles/rm_chassis_controllers.dir/src/sentry.cpp.o.d -o CMakeFiles/rm_chassis_controllers.dir/src/sentry.cpp.o -c /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/sentry.cpp
In file included from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include/rm_chassis_controllers/sentry.h:41,
                 from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/sentry.cpp:37:
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include/rm_chassis_controllers/chassis_base.h:50:10: fatal error: nav_msgs/Odometry.h: No such file or directory
   50 | #include <nav_msgs/Odometry.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

FAILED: CMakeFiles/rm_chassis_controllers.dir/src/mecanum.cpp.o
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"rm_chassis_controllers\" -Drm_chassis_controllers_EXPORTS -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/include -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot/usr/include/eigen3 -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0=/usr/src/debug/rm-chassis-controllers/0.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/recipe-sysroot -fPIC   -Wall -Werror -Wno-enum-compare -std=gnu++14 -MD -MT CMakeFiles/rm_chassis_controllers.dir/src/mecanum.cpp.o -MF CMakeFiles/rm_chassis_controllers.dir/src/mecanum.cpp.o.d -o CMakeFiles/rm_chassis_controllers.dir/src/mecanum.cpp.o -c /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/mecanum.cpp
In file included from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include/rm_chassis_controllers/mecanum.h:41,
                 from /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/src/mecanum.cpp:37:
/jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/qemux86-webos-linux/rm-chassis-controllers/0.1.1-1-r0/git/include/rm_chassis_controllers/chassis_base.h:50:10: fatal error: nav_msgs/Odometry.h: No such file or directory
   50 | #include <nav_msgs/Odometry.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>