{melodic} fix dependency issues from new recipes
* remove pyudev mapping upstreamed to rosdistro in:
  commit b7b563a2445031375e5fed8eb2fd5b6c8961d9f7
  Author: Martin 'JaMa' Jansa <martin.jansa@lge.com>
  Date:   Wed Jan 13 06:13:00 2021 -0800

    rosdep: update OpenEmbedded mapping for python*-websocket and add python-pyudev (#27826)

* add new mapping for curlpp-dev and net-tools,
  will be upstreamed through:
  https://github.com/ros/rosdistro/pull/28952

* fixes:
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-curlpp-dev' (but webos-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/pf-lidar-ros-driver/pf-driver_1.1.1-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'pf-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pf-driver', 'ROS_UNRESOLVED_DEP-curlpp-dev']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'pf-driver', 'ROS_UNRESOLVED_DEP-curlpp-dev']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'pf-driver', 'ROS_UNRESOLVED_DEP-curlpp-dev']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'pf-driver', 'ROS_UNRESOLVED_DEP-curlpp-dev']
ERROR: Nothing PROVIDES 'rviz' (but webos-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/heron-desktop/heron-viz_0.0.3-2.bb DEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'heron-desktop' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heron-desktop', 'heron-viz', 'rviz']
NOTE: Runtime target 'heron-viz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heron-viz', 'rviz']
ERROR: Nothing RPROVIDES 'pf-driver-dev' (but webos-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/pf-lidar-ros-driver/pf-driver_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pf-driver-dev'
NOTE: Runtime target 'pf-driver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pf-driver-dev']
ERROR: Nothing RPROVIDES 'rviz' (but webos-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/pf-lidar-ros-driver/pf-driver_1.1.1-1.bb, webos-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/heron-desktop/heron-viz_0.0.3-2.bb RDEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-curlpp-dev' (but webos-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/pf-lidar-ros-driver/pf-driver_1.1.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-curlpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-curlpp-dev']
ERROR: Nothing RPROVIDES 'heron-desktop-dev' (but webos-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/heron-desktop/heron-desktop_0.0.3-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'heron-desktop-dev'
NOTE: Runtime target 'heron-desktop-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heron-desktop-dev']
ERROR: Nothing RPROVIDES 'heron-viz-dev' (but webos-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/heron-desktop/heron-viz_0.0.3-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'heron-viz-dev'
NOTE: Runtime target 'heron-viz-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heron-viz-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-net-tools' (but webos-melodic-hardknott/meta-ros/meta-ros1-melodic/generated-recipes/robot-upstart/robot-upstart_0.3.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-net-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-net-tools']
NOTE: Runtime target 'robot-upstart' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-upstart', 'ROS_UNRESOLVED_DEP-net-tools']
NOTE: Runtime target 'robot-upstart-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-upstart-dev', 'ROS_UNRESOLVED_DEP-net-tools']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>