{eloquent} libphidget22: use Unix Makefiles instead of ninja
* fixes:
ERROR: libphidget22-2.0.1-1-r0 do_compile: Function failed: do_compile (log file is located at /jenkins/mjansa/build-ros/ros2-eloquent-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/libphidget22/2.0.1-1-r0/temp/log.do_compile.21609)
ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros/ros2-eloquent-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/libphidget22/2.0.1-1-r0/temp/log.do_compile.21609
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: VERBOSE=1 cmake --build /jenkins/mjansa/build-ros/ros2-eloquent-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/libphidget22/2.0.1-1-r0/build --target all -- -j 20
| ninja: error: build.ninja:135: bad $-escape (literal $ must be written as $$)
|
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /jenkins/mjansa/build-ros/ros2-eloquent-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/libphidget22/2.0.1-1-r0/temp/log.do_compile.21609)
NOTE: recipe libphidget22-2.0.1-1-r0: task do_compile: Failed
ERROR: Task (/jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/phidgets-drivers/libphidget22_2.0.1-1.bb:do_compile) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>