{eloquent} ros-distro.inc: use libusb1 instead of unresolved libusb-1.0
* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-libusb-1.0' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/phidgets-drivers/libphidget22_2.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libusb-1.0' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-digital-outputs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-digital-outputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-ik' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-ik', 'phidgets-digital-outputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-drivers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-drivers', 'phidgets-ik', 'phidgets-digital-outputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-digital-outputs-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-digital-outputs-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-temperature' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-temperature', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-temperature-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-temperature-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-gyroscope' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-gyroscope', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-gyroscope-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-gyroscope-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-motors' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-motors', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-magnetometer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-magnetometer', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-digital-inputs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-digital-inputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-analog-inputs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-analog-inputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-accelerometer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-accelerometer', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-high-speed-encoder' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-high-speed-encoder', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-spatial' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-spatial', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-api' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'libphidget22' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'libphidget22-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libphidget22-dev', 'UNRESOLVED-libusb-1.0']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>