packagegroup-ros-world*: make it MACHINE_ARCH also for dashing and eloquent
* fixes signature issue detected with sstate-diff-machines.sh:
   === Comparing signatures for task do_package_write_ipk.sigdata between qemux86 and qemuarm ===
  ERROR: packagegroup-ros-world-eloquent different signature for task do_package_write_ipk.sigdata between qemux86 and qemuarm
  NOTE: Starting bitbake server...
  Hash for dependent task packagegroups/packagegroup-ros-world-eloquent.bb:do_package changed from 482d299df29a0d715dff1c82d1085e5bcd633f785f094bf0c9584ef2bf3445a5 to 22ef77a40327fdeb0e0e043a99d7294ab6ea1f63245165a02c021000590ae134
  Unable to find matching sigdata for /jenkins/home/anaconda/build-webos-ose-ros-dunfell/build/meta-ros/meta-ros2-eloquent/recipes-core/packagegroups/packagegroup-ros-world-eloquent.bb:do_package with hashes 482d299df29a0d715dff1c82d1085e5bcd633f785f094bf0c9584ef2bf3445a5 or 22ef77a40327fdeb0e0e043a99d7294ab6ea1f63245165a02c021000590ae134

  ERROR: 1 errors found in /jenkins/home/anaconda/build-webos-ose-ros-dunfell/build/BUILD/sstate-diff/1602805039/signatures.qemuarm.do_package_write_ipk.sigdata.log
  ERROR: 1 issues were found in these recipes: packagegroup-ros-world-eloquent

Signed-off-by: Martin Jansa <martin.jansa@lge.com>