{eloquent} ros-distro.inc: add mapping for python3-future
* fixes:
  ERROR: Nothing PROVIDES 'UNRESOLVED-python3-future' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/mavlink/mavlink_2019.12.30-1.bb DEPENDS on or otherwise requires it). Close matches:
  python3-future
  NOTE: Runtime target 'mavlink' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['mavlink', 'UNRESOLVED-python3-future']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>