{foxy} resolve dependency issues in new recipes
* fixes:

ERROR: Nothing PROVIDES 'librealsense2' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/realsense-hardware-interface/realsense-hardware-interface_0.0.1-1.bb DEPENDS on or otherwise requires it)
librealsense2 was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; glfw: depends on librealsense2 which depends on glfw which is available only in dunfell and requires x11 in DISTRO_FEATURES
NOTE: Runtime target 'realsense-hardware-interface' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['realsense-hardware-interface', 'librealsense2']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'realsense-hardware-interface', 'librealsense2']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'realsense-hardware-interface', 'librealsense2']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'realsense-hardware-interface', 'librealsense2']
ERROR: Nothing PROVIDES 'ffmpeg' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/usb-cam/usb-cam_0.4.0-1.bb DEPENDS on or otherwise requires it)
ffmpeg was skipped: because it has a restricted license 'commercial'. Which is not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'usb-cam' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['usb-cam', 'ffmpeg']
ERROR: Nothing PROVIDES 'qt-gui-cpp' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb DEPENDS on or otherwise requires it)
qt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qtbase which requires meta-qt5 to be included; pyqt5: depends on python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: do_compile task fails: requires pyqt5-native for sip
NOTE: Runtime target 'rtabmap' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rtabmap', 'qt-gui-cpp']
ERROR: Nothing PROVIDES 'libfreenect' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb DEPENDS on or otherwise requires it)
libfreenect was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-libopenni-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'libg2o' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb DEPENDS on or otherwise requires it)
libg2o was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libglu which requires x11 in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'pal-gazebo-worlds' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/pmb2-simulation/pmb2-gazebo_3.0.0-1.bb RDEPENDS on or otherwise requires it)
pal-gazebo-worlds was skipped: Recipe is blacklisted: gazebo: rdepends on gazebo-ros which depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'pal-gazebo-worlds' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pal-gazebo-worlds']
NOTE: Runtime target 'pmb2-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-gazebo', 'pal-gazebo-worlds']
NOTE: Runtime target 'pmb2-2dnav-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-2dnav-gazebo', 'pmb2-gazebo', 'pal-gazebo-worlds']
NOTE: Runtime target 'pmb2-simulation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-simulation', 'pmb2-2dnav-gazebo', 'pmb2-gazebo', 'pal-gazebo-worlds']
NOTE: Runtime target 'pmb2-2dnav-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-2dnav-gazebo-dev', 'pmb2-gazebo', 'pal-gazebo-worlds']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/pmb2-simulation/pmb2-gazebo_3.0.0-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
ERROR: Nothing RPROVIDES 'gazebo-plugins' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/pmb2-simulation/pmb2-gazebo_3.0.0-1.bb RDEPENDS on or otherwise requires it)
gazebo-plugins was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-plugins']
ERROR: Nothing RPROVIDES 'pmb2-gazebo-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/pmb2-simulation/pmb2-gazebo_3.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pmb2-gazebo-dev'
NOTE: Runtime target 'pmb2-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-gazebo-dev']
ERROR: Nothing RPROVIDES 'pmb2-simulation-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/pmb2-simulation/pmb2-simulation_3.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pmb2-simulation-dev'
NOTE: Runtime target 'pmb2-simulation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-simulation-dev']
ERROR: Nothing RPROVIDES 'realsense-hardware-interface-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/realsense-hardware-interface/realsense-hardware-interface_0.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'realsense-hardware-interface-dev'
NOTE: Runtime target 'realsense-hardware-interface-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['realsense-hardware-interface-dev']
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/realsense-hardware-interface/realsense-hardware-interface_0.0.1-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
ERROR: Nothing RPROVIDES 'librealsense2' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/realsense-hardware-interface/realsense-hardware-interface_0.0.1-1.bb RDEPENDS on or otherwise requires it)
librealsense2 was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; glfw: depends on librealsense2 which depends on glfw which is available only in dunfell and requires x11 in DISTRO_FEATURES
NOTE: Runtime target 'librealsense2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['librealsense2']
ERROR: Nothing RPROVIDES 'usb-cam-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/usb-cam/usb-cam_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'usb-cam-dev'
NOTE: Runtime target 'usb-cam-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['usb-cam-dev']
ERROR: Nothing RPROVIDES 'ffmpeg' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/usb-cam/usb-cam_0.4.0-1.bb RDEPENDS on or otherwise requires it)
ffmpeg was skipped: because it has a restricted license 'commercial'. Which is not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'ffmpeg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ffmpeg']
ERROR: Nothing RPROVIDES 'qt-gui-cpp' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
qt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qtbase which requires meta-qt5 to be included; pyqt5: depends on python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: do_compile task fails: requires pyqt5-native for sip
NOTE: Runtime target 'qt-gui-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-cpp']
ERROR: Nothing RPROVIDES 'libfreenect' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
libfreenect was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'libfreenect' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libfreenect']
ERROR: Nothing RPROVIDES 'rtabmap-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rtabmap-dev'
NOTE: Runtime target 'rtabmap-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rtabmap-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-libopenni-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-libopenni-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-libopenni-dev']
ERROR: Nothing RPROVIDES 'libg2o' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
libg2o was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libglu which requires x11 in DISTRO_FEATURES
NOTE: Runtime target 'libg2o' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libg2o']
ERROR: Nothing RPROVIDES 'webots-ros2-core' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/webots-ros2/webots-ros2-mavic_1.1.0-1.bb RDEPENDS on or otherwise requires it)
webots-ros2-core was skipped: Recipe is blacklisted: webots-python-modules: requires python-transforms3d-pip which is not available in OE yet
NOTE: Runtime target 'webots-ros2-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-core']
NOTE: Runtime target 'webots-ros2-mavic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-mavic', 'webots-ros2-core']
NOTE: Runtime target 'webots-ros2-mavic-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros2-mavic-dev', 'webots-ros2-core']
ERROR: Nothing RPROVIDES 'joint-state-publisher-gui' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/pmb2-robot/pmb2-description_4.0.2-1.bb RDEPENDS on or otherwise requires it)
joint-state-publisher-gui was skipped: Recipe is blacklisted: qt5: depends on python-qt-binding which depends on qtbase; pyqt5: depends on python-qt-binding which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'joint-state-publisher-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['joint-state-publisher-gui']
NOTE: Runtime target 'pmb2-description' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-description', 'joint-state-publisher-gui']
NOTE: Runtime target 'pmb2-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-bringup', 'pmb2-description', 'joint-state-publisher-gui']
NOTE: Runtime target 'pmb2-robot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-robot', 'pmb2-bringup', 'pmb2-description', 'joint-state-publisher-gui']
NOTE: Runtime target 'pmb2-robot-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-robot-dev', 'pmb2-bringup', 'pmb2-description', 'joint-state-publisher-gui']
NOTE: Runtime target 'pmb2-bringup-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-bringup-dev', 'pmb2-description', 'joint-state-publisher-gui']
ERROR: Nothing RPROVIDES 'pmb2-description-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/pmb2-robot/pmb2-description_4.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pmb2-description-dev'
NOTE: Runtime target 'pmb2-description-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pmb2-description-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>