{melodic} rc-roi-manager-gui: export WX_CONFIG to fix FindwxWidgets.cmake use
* fixes:
DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
-- Check for working C compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- PACKAGE_XML_VERSION: 2.7.0
-- RC_PROJECT_VERSION: 2.7.0
-- PACKAGE_VERSION: 2.7.0
-- Using CATKIN_DEVEL_PREFIX: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/devel
-- Using CMAKE_PREFIX_PATH: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot/opt/ros/melodic;ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot/usr
-- This workspace overlays: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot/opt/ros/melodic
-- Found PythonInterp: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/bin/python-native/python2 (found suitable version "2.7.16", minimum required is "2")
-- Using PYTHON_EXECUTABLE: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/bin/python-native/python2
-- Using default Python package layout
-- Found PY_em: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using empy: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using CATKIN_ENABLE_TESTING: 0
-- catkin 0.7.23
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;gennodejs;genpy
CMake Error at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FindwxWidgets.cmake:963 (find_package_handle_standard_args)
  CMakeLists.txt:31 (find_package)

-- Configuring incomplete, errors occurred!
See also "ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/rc-roi-manager-gui/2.7.0-1-r0/temp/log.do_configure.25420)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>