{foxy} resolve dependency issues in new recipes
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libjsoncpp-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/tile-map_2.1.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'tile-map' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tile-map', 'UNRESOLVED-libjsoncpp-dev']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'tile-map', 'UNRESOLVED-libjsoncpp-dev']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'tile-map', 'UNRESOLVED-libjsoncpp-dev']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'tile-map', 'UNRESOLVED-libjsoncpp-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-libglew-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/tile-map_2.1.0-1.bb, /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'multires-image' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multires-image', 'mapviz', 'UNRESOLVED-libglew-dev']
NOTE: Runtime target 'mapviz-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-plugins', 'mapviz', 'UNRESOLVED-libglew-dev']
NOTE: Runtime target 'mapviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz', 'UNRESOLVED-libglew-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-rviz' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/common2_0.1.1-4.bb, /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-launcher2_0.1.1-4.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'common2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['common2', 'UNRESOLVED-rviz']
NOTE: Runtime target 'dsr-launcher2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dsr-launcher2', 'UNRESOLVED-rviz']
ERROR: Nothing PROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/common2_0.1.1-4.bb, /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-launcher2_0.1.1-4.bb DEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
ERROR: Nothing PROVIDES 'rqt-gui' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb DEPENDS on or otherwise requires it)
rqt-gui was skipped: Recipe is blacklisted: qt5: depends on qt-gui which depends on qtbase; pyqt5: depends on qt-gui which depends on python3-pyqt5 which requires pyqt5
ERROR: Nothing PROVIDES 'rqt-gui-cpp' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb DEPENDS on or otherwise requires it)
rqt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qt-gui-cpp and qtbase itself which requires meta-qt5 to be included; pyqt5: depends on qt-gui-cpp which depends python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: depends on qt-gui-cpp which fails to compile
ERROR: Nothing PROVIDES 'UNRESOLVED-libxi-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-libxmu-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'freeglut' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb DEPENDS on or otherwise requires it)
freeglut was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_ament_python-native}' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-example2-py_0.1.1-4.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'dsr-example2-py' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dsr-example2-py', '${ROS_UNRESOLVED_PLATFORM_PKG_ament_python-native}']
ERROR: Nothing PROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_hardware_interface}' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-control2_0.1.1-4.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'dsr-control2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dsr-control2', '${ROS_UNRESOLVED_PLATFORM_PKG_hardware_interface}']
ERROR: Nothing PROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_controller_manager}' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-control2_0.1.1-4.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'UNRESOLVED-libjsoncpp' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/tile-map_2.1.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libjsoncpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libjsoncpp']
ERROR: Nothing RPROVIDES 'tile-map-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/tile-map_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'tile-map-dev'
NOTE: Runtime target 'tile-map-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tile-map-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libglew-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/tile-map_2.1.0-1.bb, /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libglew-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libglew-dev']
ERROR: Nothing RPROVIDES 'common2-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/common2_0.1.1-4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'common2-dev'
NOTE: Runtime target 'common2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['common2-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python3-tk' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/teleop-tools/mouse-teleop_1.2.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python3-tk' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python3-tk']
NOTE: Runtime target 'mouse-teleop' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mouse-teleop', 'UNRESOLVED-python3-tk']
ERROR: Nothing RPROVIDES 'mouse-teleop-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/teleop-tools/mouse-teleop_1.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mouse-teleop-dev'
NOTE: Runtime target 'mouse-teleop-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mouse-teleop-dev']
ERROR: Nothing RPROVIDES 'rqt-gui' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
rqt-gui was skipped: Recipe is blacklisted: qt5: depends on qt-gui which depends on qtbase; pyqt5: depends on qt-gui which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui']
ERROR: Nothing RPROVIDES 'rqt-gui-cpp' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
rqt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qt-gui-cpp and qtbase itself which requires meta-qt5 to be included; pyqt5: depends on qt-gui-cpp which depends python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: depends on qt-gui-cpp which fails to compile
NOTE: Runtime target 'rqt-gui-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-cpp']
ERROR: Nothing RPROVIDES 'mapviz-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mapviz-dev'
NOTE: Runtime target 'mapviz-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libxi-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libxi-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libxi-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libxmu-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libxmu-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libxmu-dev']
ERROR: Nothing RPROVIDES 'freeglut' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
freeglut was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'freeglut' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['freeglut']
ERROR: Nothing RPROVIDES 'dsr-example2-py-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-example2-py_0.1.1-4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dsr-example2-py-dev'
NOTE: Runtime target 'dsr-example2-py-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dsr-example2-py-dev']
ERROR: Nothing RPROVIDES 'dsr-launcher2-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-launcher2_0.1.1-4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dsr-launcher2-dev'
NOTE: Runtime target 'dsr-launcher2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dsr-launcher2-dev']
ERROR: Nothing RPROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_hardware_interface}' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-control2_0.1.1-4.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${ROS_UNRESOLVED_PLATFORM_PKG_hardware_interface}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${ROS_UNRESOLVED_PLATFORM_PKG_hardware_interface}']
ERROR: Nothing RPROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_controller_manager}' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-control2_0.1.1-4.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${ROS_UNRESOLVED_PLATFORM_PKG_controller_manager}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${ROS_UNRESOLVED_PLATFORM_PKG_controller_manager}']
ERROR: Nothing RPROVIDES 'dsr-control2-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-control2_0.1.1-4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dsr-control2-dev'
NOTE: Runtime target 'dsr-control2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dsr-control2-dev']
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3/turtlebot3-bringup_2.1.0-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
NOTE: Runtime target 'turtlebot3-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-bringup', 'rviz2']
NOTE: Runtime target 'turtlebot3' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3', 'turtlebot3-bringup', 'rviz2']
ERROR: Nothing RPROVIDES 'turtlebot3-bringup-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3/turtlebot3-bringup_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtlebot3-bringup-dev'
NOTE: Runtime target 'turtlebot3-bringup-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-bringup-dev']
ERROR: Nothing RPROVIDES 'multires-image-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/multires-image_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'multires-image-dev'
NOTE: Runtime target 'multires-image-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multires-image-dev']
ERROR: Nothing RPROVIDES 'joint-state-publisher-gui' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-description2_0.1.1-4.bb RDEPENDS on or otherwise requires it)
joint-state-publisher-gui was skipped: Recipe is blacklisted: qt5: depends on python-qt-binding which depends on qtbase; pyqt5: depends on python-qt-binding which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'joint-state-publisher-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['joint-state-publisher-gui']
NOTE: Runtime target 'dsr-description2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dsr-description2', 'joint-state-publisher-gui']
ERROR: Nothing RPROVIDES 'dsr-description2-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/doosan-robot2/dsr-description2_0.1.1-4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dsr-description2-dev'
NOTE: Runtime target 'dsr-description2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dsr-description2-dev']
ERROR: Nothing RPROVIDES 'nav2-bringup' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3/turtlebot3-navigation2_2.1.0-1.bb RDEPENDS on or otherwise requires it)
nav2-bringup was skipped: Recipe is blacklisted: qt5: depends on slam-toolbox which depends on qtbase; x11: depends on slam-toolbox which depends on rviz-common->rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'nav2-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup']
NOTE: Runtime target 'turtlebot3-navigation2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-navigation2', 'nav2-bringup']
NOTE: Runtime target 'turtlebot3-navigation2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-navigation2-dev', 'nav2-bringup']
ERROR: Nothing RPROVIDES 'mapviz-plugins-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz-plugins_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mapviz-plugins-dev'
NOTE: Runtime target 'mapviz-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-plugins-dev']
ERROR: Nothing RPROVIDES 'turtlebot3-dev' (but /jenkins/mjansa/build/ros/webos-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3/turtlebot3_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtlebot3-dev'
NOTE: Runtime target 'turtlebot3-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>