{melodic} packagegroup-ros-world-melodic: Remove RDEPENDS on packages depending on libqt4-dev
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libqt4-dev' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/hector-slam/hector-geotiff_0.4.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'hector-geotiff' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['hector-geotiff', 'UNRESOLVED-libqt4-dev']
NOTE: Runtime target 'hector-slam' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['hector-slam', 'hector-geotiff', 'UNRESOLVED-libqt4-dev']
NOTE: Runtime target 'hector-geotiff-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['hector-geotiff-plugins', 'hector-geotiff', 'UNRESOLVED-libqt4-dev']
NOTE: Runtime target 'hector-slam-launch' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['hector-slam-launch', 'hector-geotiff-plugins', 'hector-geotiff', 'UNRESOLVED-libqt4-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libqt4-dev' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/hector-slam/hector-geotiff_0.4.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libqt4-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libqt4-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>