{eloquent} packagegroup-ros-world-eloquent: drop dependency on rqt-common-plugins
* Drop dependency on rqt-common-plugins when ros-rqt or ros-qt5 isn't in
  DISTRO_FEATURES.

* fixes:
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-image-view/rqt-image-view_1.0.3-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-py-common_1.0.5-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/qt-gui-core/qt-gui-cpp_1.0.7-1.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
NOTE: Runtime target 'rqt-image-view' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-image-view', 'qtbase']
NOTE: Runtime target 'rqt-common-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-common-plugins', 'rqt-image-view', 'qtbase']
NOTE: Runtime target 'rqt-common-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-common-plugins-dev', 'rqt-image-view', 'qtbase']
NOTE: Runtime target 'rqt-py-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-py-common', 'qtbase']
NOTE: Runtime target 'rqt-msg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-msg', 'rqt-py-common', 'qtbase']
NOTE: Runtime target 'rqt-srv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-srv', 'rqt-msg', 'rqt-py-common', 'qtbase']
NOTE: Runtime target 'rqt-action' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-action', 'rqt-msg', 'rqt-py-common', 'qtbase']
NOTE: Runtime target 'rqt-topic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-topic', 'rqt-py-common', 'qtbase']
NOTE: Runtime target 'rqt-reconfigure' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-reconfigure', 'rqt-py-common', 'qtbase']
NOTE: Runtime target 'rqt-console' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-console', 'rqt-py-common', 'qtbase']
NOTE: Runtime target 'rqt-service-caller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-service-caller', 'rqt-py-common', 'qtbase']
NOTE: Runtime target 'rqt-publisher' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-publisher', 'rqt-py-common', 'qtbase']
NOTE: Runtime target 'rqt-plot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-plot', 'rqt-py-common', 'qtbase']
ERROR: Nothing PROVIDES 'python' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/openembedded-core/meta/recipes-devtools/python-numpy/python-numpy_1.14.5.bb DEPENDS on or otherwise requires it)
python was skipped: Recipe is blacklisted: ROS 2 is Python 3 only
NOTE: Runtime target 'python-numpy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-numpy', 'python']
NOTE: Runtime target 'python-qt-binding' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-qt-binding']
NOTE: Runtime target 'rqt-shell' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-shell', 'python-qt-binding']
NOTE: Runtime target 'rqt-graph' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-graph', 'python-qt-binding']
NOTE: Runtime target 'rqt-py-console' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-py-console', 'python-qt-binding']
NOTE: Runtime target 'rqt-top' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-top', 'python-qt-binding']
ERROR: Nothing RPROVIDES 'rqt-gui' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-msg/rqt-msg_1.0.2-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-shell/rqt-shell_1.0.0-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-image-view/rqt-image-view_1.0.3-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-topic/rqt-topic_1.1.0-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-graph/rqt-graph_1.0.3-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-py-console/rqt-py-console_1.0.0-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-top/rqt-top_1.0.0-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-reconfigure/rqt-reconfigure_1.0.4-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-console/rqt-console_1.1.0-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-service-caller/rqt-service-caller_1.0.3-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-srv/rqt-srv_1.0.1-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-action/rqt-action_1.0.1-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-publisher/rqt-publisher_1.1.0-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-plot/rqt-plot_1.0.7-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-gui_1.0.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-gui'
NOTE: Runtime target 'rqt-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui']
NOTE: Runtime target 'rqt-gui-py' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-py']
ERROR: Nothing RPROVIDES 'rqt-msg-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-msg/rqt-msg_1.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-msg-dev'
NOTE: Runtime target 'rqt-msg-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-msg-dev']
ERROR: Nothing RPROVIDES 'rqt-shell-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-shell/rqt-shell_1.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-shell-dev'
NOTE: Runtime target 'rqt-shell-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-shell-dev']
NOTE: Runtime target 'qt-gui-py-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-py-common']
NOTE: Runtime target 'qt-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui']
ERROR: Nothing RPROVIDES 'qt-gui-cpp' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-image-view/rqt-image-view_1.0.3-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/qt-gui-core/qt-gui-cpp_1.0.7-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-gui-cpp_1.0.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qt-gui-cpp'
NOTE: Runtime target 'qt-gui-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-cpp']
ERROR: Nothing RPROVIDES 'rqt-gui-cpp' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-image-view/rqt-image-view_1.0.3-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-gui-cpp_1.0.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-gui-cpp'
NOTE: Runtime target 'rqt-gui-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-cpp']
ERROR: Nothing RPROVIDES 'rqt-image-view-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-image-view/rqt-image-view_1.0.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-image-view-dev'
NOTE: Runtime target 'rqt-image-view-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-image-view-dev']
ERROR: Nothing RPROVIDES 'rqt-topic-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-topic/rqt-topic_1.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-topic-dev'
NOTE: Runtime target 'rqt-topic-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-topic-dev']
NOTE: Runtime target 'qt-dotgraph' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-dotgraph']
ERROR: Nothing RPROVIDES 'rqt-graph-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-graph/rqt-graph_1.0.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-graph-dev'
NOTE: Runtime target 'rqt-graph-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-graph-dev']
ERROR: Nothing RPROVIDES 'rqt-py-console-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-py-console/rqt-py-console_1.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-py-console-dev'
NOTE: Runtime target 'rqt-py-console-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-py-console-dev']
ERROR: Nothing RPROVIDES 'rqt-top-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-top/rqt-top_1.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-top-dev'
NOTE: Runtime target 'rqt-top-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-top-dev']
ERROR: Nothing RPROVIDES 'rqt-reconfigure-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-reconfigure/rqt-reconfigure_1.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-reconfigure-dev'
NOTE: Runtime target 'rqt-reconfigure-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-reconfigure-dev']
ERROR: Nothing RPROVIDES 'rqt-console-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-console/rqt-console_1.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-console-dev'
NOTE: Runtime target 'rqt-console-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-console-dev']
ERROR: Nothing RPROVIDES 'rqt-service-caller-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-service-caller/rqt-service-caller_1.0.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-service-caller-dev'
NOTE: Runtime target 'rqt-service-caller-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-service-caller-dev']
ERROR: Nothing RPROVIDES 'rqt-py-common-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-py-common_1.0.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-py-common-dev'
NOTE: Runtime target 'rqt-py-common-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-py-common-dev']
ERROR: Nothing RPROVIDES 'qtbase' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-py-common_1.0.5-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtbase' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtbase']
ERROR: Nothing RPROVIDES 'rqt-srv-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-srv/rqt-srv_1.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-srv-dev'
NOTE: Runtime target 'rqt-srv-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-srv-dev']
ERROR: Nothing RPROVIDES 'rqt-action-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-action/rqt-action_1.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-action-dev'
NOTE: Runtime target 'rqt-action-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-action-dev']
ERROR: Nothing RPROVIDES 'rqt-publisher-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-publisher/rqt-publisher_1.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-publisher-dev'
NOTE: Runtime target 'rqt-publisher-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-publisher-dev']
ERROR: Nothing RPROVIDES 'python3-matplotlib' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-plot/rqt-plot_1.0.7-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-matplotlib' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-matplotlib']
ERROR: Nothing RPROVIDES 'rqt-plot-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt-plot/rqt-plot_1.0.7-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-plot-dev'
NOTE: Runtime target 'rqt-plot-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-plot-dev']
ERROR: Nothing RPROVIDES 'python-numpy-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/openembedded-core/meta/recipes-devtools/python-numpy/python-numpy_1.14.5.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python-numpy-dev'
NOTE: Runtime target 'python-numpy-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-numpy-dev']
ERROR: Nothing RPROVIDES 'python-subprocess' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/openembedded-core/meta/recipes-devtools/python-numpy/python-numpy_1.14.5.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python-subprocess' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-subprocess']
ERROR: Nothing RPROVIDES 'qt-gui-cpp-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/qt-gui-core/qt-gui-cpp_1.0.7-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qt-gui-cpp-dev'
NOTE: Runtime target 'qt-gui-cpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-cpp-dev']
ERROR: Nothing RPROVIDES 'rqt-gui-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-gui_1.0.5-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-gui-dev'
NOTE: Runtime target 'rqt-gui-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-dev']
ERROR: Nothing PROVIDES 'python-qt-binding' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/qt-gui-core/qt-gui-cpp_1.0.7-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'python-qt-binding'
ERROR: Nothing PROVIDES 'qt-gui' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-gui_1.0.5-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-gui-cpp_1.0.5-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/rqt/rqt-gui-py_1.0.5-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'qt-gui'
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-qt5-bindings' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/python-qt-binding/python-qt-binding_1.0.3-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/qt-gui-core/qt-gui_1.0.7-1.bb DEPENDS on or otherwise requires it). Close matches:
  python-qt-binding

Signed-off-by: Martin Jansa <martin.jansa@lge.com>