{foxy} ecl-linear-algebra: drop runtime dependency on sophus
* sophus PN is empty and not created
* fixes:
ERROR: ros-image-world-1.0-r0 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install connman packagegroup-core-boot packagegroup-ros-world run-postinsts' returned 1:
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-ros-world-1.0-r0.qemux86_64 requires packagegroup-ros-world-foxy, but none of the providers can be installed
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

 * opkg_finalize_intercepts: Failed to open dir /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-yPD7WI/opkg-intercept-DeTF3I: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-yPD7WI/opkg-intercept-DeTF3I: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-yPD7WI: No such file or directory.

ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/log.do_rootfs.68176
NOTE: recipe ros-image-world-1.0-r0: task do_rootfs: Failed
ERROR: Task (/jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros-common/recipes-core/images/ros-image-world.bb:do_rootfs) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>