collada-dom: inherit pkgconfig
Newer oe-core doesn't pull many default dependencies anymore:
https://lists.openembedded.org/g/openembedded-core/message/156185
add explicit dependency on pkgconfig through pkgconfig.bbclass as
we're using it here.

Fixes:
  ERROR: collada-dom-2.4.0-r0 do_package_qa: QA Issue: collada-dom: ELF binary /usr/lib/libcollada-dom2.4-dp.so.2.4.0 has relocations in .text [textrel]

* in this case it doesn't cause clear error about missing pkg-config
  instead it builds own minizip and pcre and resulting library then
  has textrel inside which is caught by the QA check

  - with-pkgconfig
  + without pkg-config
  @@ -1,7 +1,7 @@
   DEBUG: Executing python function extend_recipe_sysroot
  -NOTE: Direct dependencies are ['/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/cmake/cmake-native_3.21.1.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/gcc/gcc-cross_11.2.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/gcc/gcc-runtime_11.2.bb:do_populate_sysroot', 'virtual:native:/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/icecc-create-env/icecc-create-env_0.1.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-core/glibc/glibc_2.34.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-core/libxml/libxml2_2.9.12.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-support/libpcre/libpcre_8.45.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-support/boost/boost_1.77.0.bb:do_populate_sysroot', 'virtual:native:/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'virtual:native:/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/ninja/ninja_1.10.2.bb:do_populate_sysroot']
  +NOTE: Direct dependencies are ['virtual:native:/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/icecc-create-env/icecc-create-env_0.1.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-support/libpcre/libpcre_8.45.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', 'virtual:native:/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/ninja/ninja_1.10.2.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-core/libxml/libxml2_2.9.12.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/gcc/gcc-runtime_11.2.bb:do_populate_sysroot', 'virtual:native:/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/cmake/cmake-native_3.21.1.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-devtools/gcc/gcc-cross_11.2.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-support/boost/boost_1.77.0.bb:do_populate_sysroot', '/jenkins/mjansa/build/ose/honister/oe-core/meta/recipes-core/glibc/glibc_2.34.bb:do_populate_sysroot']
   NOTE: Installed into sysroot: []
  -NOTE: Skipping as already exists in sysroot: ['cmake-native', 'gcc-cross-i686', 'gcc-runtime', 'icecc-create-env-native', 'glibc', 'quilt-native', 'libxml2', 'libpcre', 'boost', 'pkgconfig-native', 'pseudo-native', 'patch-native', 'ninja-native', 'zstd-native', 'ncurses-native', 'bzip2-native', 'zlib-native', 'curl-native', 'xz-native', 'libgcc', 'linux-libc-headers', 'bzip2', 'zlib', 'libtool-native', 'attr-native', 'gmp-native', 'texinfo-dummy-native', 'gnu-config-native', 'mpfr-native', 'binutils-cross-i686', 'libmpc-native', 'flex-native', 'python3', 'icu', 're2c-native', 'openssl-native', 'gettext-minimal-native', 'opkg-utils', 'm4-native', 'libxcrypt', 'util-linux', 'libffi', 'gdbm', 'readline', 'xz', 'libtirpc', 'sqlite3', 'libnsl2', 'openssl', 'util-linux-libuuid', 'libcap-ng', 'ncurses', 'bash-completion']
  +NOTE: Skipping as already exists in sysroot: ['pseudo-native', 'icecc-create-env-native', 'libpcre', 'quilt-native', 'ninja-native', 'libxml2', 'gcc-runtime', 'patch-native', 'cmake-native', 'gcc-cross-i686', 'boost', 'glibc', 'bzip2', 'zlib', 'linux-libc-headers', 'libgcc', 'bzip2-native', 'ncurses-native', 'zlib-native', 'xz-native', 'curl-native', 'zstd-native', 'icu', 'python3', 're2c-native', 'libtool-native', 'attr-native', 'gnu-config-native', 'gmp-native', 'flex-native', 'libmpc-native', 'binutils-cross-i686', 'texinfo-dummy-native', 'mpfr-native', 'opkg-utils', 'gettext-minimal-native', 'openssl-native', 'gdbm', 'util-linux', 'libnsl2', 'libtirpc', 'sqlite3', 'libffi', 'xz', 'libxcrypt', 'readline', 'openssl', 'm4-native', 'libcap-ng', 'ncurses', 'util-linux-libuuid', 'bash-completion']
   DEBUG: Python function extend_recipe_sysroot finished
   DEBUG: Executing shell function do_configure
   -- The C compiler identification is GNU 11.2.0
  @@ -20,19 +20,54 @@
   -- Using cmake version 3.21
   -- installing to /usr
   -- compiling with double float precision
  --- Found PkgConfig: /jenkins/mjansa/build/ose/honister/BUILD/work/qemux86-webos-linux/collada-dom/2.4.0-r0/recipe-sysroot-native/usr/bin/pkg-config (found version "0.29.2")
  +-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
   -- Found Boost: /jenkins/mjansa/build/ose/honister/BUILD/work/qemux86-webos-linux/collada-dom/2.4.0-r0/recipe-sysroot/usr/lib/cmake/Boost-1.77.0/BoostConfig.cmake (found version "1.77.0") found components: filesystem system
   -- found boost version: 1.77.0
   -- Found ZLIB: /jenkins/mjansa/build/ose/honister/BUILD/work/qemux86-webos-linux/collada-dom/2.4.0-r0/recipe-sysroot/usr/lib/libz.so (found version "1.2.11")
   -- Found LibXml2: /jenkins/mjansa/build/ose/honister/BUILD/work/qemux86-webos-linux/collada-dom/2.4.0-r0/recipe-sysroot/usr/lib/libxml2.so (found version "2.9.12")
   -- libxml2 found
  --- Checking for module 'minizip'
  ---   No package 'minizip' found
   -- compiling minizip from sources and linking statically
  --- Checking for module 'libpcrecpp'
  ---   Found libpcrecpp, version 8.45
  --- Looking for C++ include pcrecpp.h
  --- Looking for C++ include pcrecpp.h - found
  +-- System pcre not found, using local from sources
  +-- Found BZip2: /jenkins/mjansa/build/ose/honister/BUILD/work/qemux86-webos-linux/collada-dom/2.4.0-r0/recipe-sysroot/usr/lib/libbz2.so (found version "1.0.8")
  +-- Looking for BZ2_bzCompressInit
  +-- Looking for BZ2_bzCompressInit - found
  +-- Found Readline: /jenkins/mjansa/build/ose/honister/BUILD/work/qemux86-webos-linux/collada-dom/2.4.0-r0/recipe-sysroot/usr/include
  +-- Looking for dirent.h
  +-- Looking for dirent.h - found
  +-- Looking for stdint.h
  +-- Looking for stdint.h - found
  +-- Looking for inttypes.h
  +-- Looking for inttypes.h - found
  +-- Looking for sys/stat.h
  +-- Looking for sys/stat.h - found
  +-- Looking for sys/types.h
  +-- Looking for sys/types.h - found
  +-- Looking for unistd.h
  +-- Looking for unistd.h - found
  +-- Looking for windows.h
  +-- Looking for windows.h - not found
  +-- Looking for C++ include type_traits.h
  +-- Looking for C++ include type_traits.h - not found
  +-- Looking for C++ include bits/type_traits.h
  +-- Looking for C++ include bits/type_traits.h - not found
  +-- Looking for bcopy
  +-- Looking for bcopy - found
  +-- Looking for memmove
  +-- Looking for memmove - found
  +-- Looking for strerror
  +-- Looking for strerror - found
  +-- Looking for strtoll
  +-- Looking for strtoll - found
  +-- Looking for strtoq
  +-- Looking for strtoq - found
  +-- Looking for _strtoi64
  +-- Looking for _strtoi64 - not found
  +-- Looking for stddef.h
  +-- Looking for stddef.h - found
  +-- Check size of long long
  +-- Check size of long long - done
  +-- Check size of unsigned long long
  +-- Check size of unsigned long long - done
   -- Configuring done
   -- Generating done
   CMake Warning:

Signed-off-by: Martin Jansa <martin.jansa@lge.com>