{melodic} vesc-driver: work around return-type issue
* fixes:
FAILED: CMakeFiles/vesc_driver_node.dir/src/vesc_interface.cpp.o
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"vesc_driver\" -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/git/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/recipe-sysroot/usr/opt/ros/melodic/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/recipe-sysroot/usr/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0=/usr/src/debug/vesc-driver/1.1.0-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0=/usr/src/debug/vesc-driver/1.1.0-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/recipe-sysroot -MD -MT CMakeFiles/vesc_driver_node.dir/src/vesc_interface.cpp.o -MF CMakeFiles/vesc_driver_node.dir/src/vesc_interface.cpp.o.d -o CMakeFiles/vesc_driver_node.dir/src/vesc_interface.cpp.o -c TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/git/src/vesc_interface.cpp
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/git/src/vesc_interface.cpp: In member function 'void* vesc_driver::VescInterface::Impl::rxThread()':
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/vesc-driver/1.1.0-1-r0/git/src/vesc_interface.cpp:147:1: error: no return statement in function returning non-void [-Werror=return-type]
  147 | }
      | ^
cc1plus: some warnings being treated as errors

Signed-off-by: Martin Jansa <martin.jansa@lge.com>