enable-fortran: respect fortran in ROS_WORLD_SKIP_GROUPS
* fixes:
  https://github.com/ros/meta-ros/issues/766
* remove all recipes depending on libgfortran as reported in:
ERROR: Nothing PROVIDES 'libgfortran' (but /jenkins/mjansa/build/ros/webos-melodic-dunfell/meta-openembedded/meta-oe/recipes-devtools/lapack/lapack_3.9.0.bb DEPENDS on or otherwise requires it)
libgfortran was skipped: libgfortran needs fortran support to be enabled in the compiler
NOTE: Runtime target 'fetch-ikfast-plugin' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-ikfast-plugin', 'lapack', 'libgfortran']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'fetch-ikfast-plugin', 'lapack', 'libgfortran']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'fetch-ikfast-plugin', 'lapack', 'libgfortran']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'fetch-ikfast-plugin', 'lapack', 'libgfortran']
NOTE: Runtime target 'fetch-ikfast-plugin-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-ikfast-plugin-dev', 'lapack', 'libgfortran']
NOTE: Runtime target 'slam-karto' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slam-karto', 'sparse-bundle-adjustment', 'lapack', 'libgfortran']
NOTE: Runtime target 'fetch-navigation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-navigation', 'slam-karto', 'sparse-bundle-adjustment', 'lapack', 'libgfortran']
NOTE: Runtime target 'fetch-navigation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-navigation-dev', 'slam-karto', 'sparse-bundle-adjustment', 'lapack', 'libgfortran']
NOTE: Runtime target 'slam-karto-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slam-karto-dev', 'sparse-bundle-adjustment', 'lapack', 'libgfortran']
NOTE: Runtime target 'sparse-bundle-adjustment' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sparse-bundle-adjustment', 'lapack', 'libgfortran']
NOTE: Runtime target 'sparse-bundle-adjustment-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sparse-bundle-adjustment-dev', 'lapack', 'libgfortran']
NOTE: Runtime target 'nextage-ik-plugin' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nextage-ik-plugin', 'lapack', 'libgfortran']
NOTE: Runtime target 'nextage-ik-plugin-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nextage-ik-plugin-dev', 'lapack', 'libgfortran']
NOTE: Runtime target 'abb-irb2400-moveit-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['abb-irb2400-moveit-plugins', 'lapack', 'libgfortran']
NOTE: Runtime target 'abb-irb2400-moveit-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['abb-irb2400-moveit-plugins-dev', 'lapack', 'libgfortran']
NOTE: Runtime target 'jackal-cartographer-navigation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jackal-cartographer-navigation', 'cartographer-ros', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'jackal-cartographer-navigation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jackal-cartographer-navigation-dev', 'cartographer-ros', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'ridgeback-cartographer-navigation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ridgeback-cartographer-navigation', 'cartographer-ros', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'ridgeback-cartographer-navigation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ridgeback-cartographer-navigation-dev', 'cartographer-ros', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'cartographer-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-ros', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'husky-cartographer-navigation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['husky-cartographer-navigation', 'cartographer-ros', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'husky-cartographer-navigation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['husky-cartographer-navigation-dev', 'cartographer-ros', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'cartographer-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-ros-dev', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'mrp2-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrp2-common', 'mrp2-navigation', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'mrp2-common-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrp2-common-dev', 'mrp2-navigation', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'mrp2-navigation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrp2-navigation', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'mrp2-navigation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrp2-navigation-dev', 'cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'cartographer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'cartographer-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-dev', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'robot-calibration' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-calibration', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'fetch-calibration' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-calibration', 'robot-calibration', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'fetch-calibration-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-calibration-dev', 'robot-calibration', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'robot-calibration-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-calibration-dev', 'ceres-solver', 'lapack', 'libgfortran']
NOTE: Runtime target 'ceres-solver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ceres-solver-dev', 'lapack', 'libgfortran']
NOTE: Runtime target 'ceres-solver-staticdev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ceres-solver-staticdev', 'lapack', 'libgfortran']
NOTE: Runtime target 'nav2d' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2d', 'nav2d-tutorials', 'nav2d-karto', 'suitesparse-cholmod', 'lapack', 'libgfortran']
NOTE: Runtime target 'nav2d-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2d-dev', 'nav2d-tutorials', 'nav2d-karto', 'suitesparse-cholmod', 'lapack', 'libgfortran']
NOTE: Runtime target 'nav2d-tutorials' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2d-tutorials', 'nav2d-karto', 'suitesparse-cholmod', 'lapack', 'libgfortran']
NOTE: Runtime target 'nav2d-tutorials-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2d-tutorials-dev', 'nav2d-karto', 'suitesparse-cholmod', 'lapack', 'libgfortran']
NOTE: Runtime target 'nav2d-karto' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2d-karto', 'suitesparse-cholmod', 'lapack', 'libgfortran']
NOTE: Runtime target 'nav2d-karto-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2d-karto-dev', 'suitesparse-cholmod', 'lapack', 'libgfortran']
NOTE: Runtime target 'suitesparse-cholmod' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['suitesparse-cholmod', 'lapack', 'libgfortran']
NOTE: Runtime target 'suitesparse-cholmod-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['suitesparse-cholmod-dev', 'lapack', 'libgfortran']
NOTE: Runtime target 'lapack' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lapack', 'libgfortran']
NOTE: Runtime target 'lapack-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lapack-dev', 'libgfortran']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>