{melodic} stage: add missing dependency on libglu
* current rosdistro unfortunately maps opengl only to mesa:
opengl:
  arch: [mesa]
  debian: [libgl1-mesa-dev, libglu1-mesa-dev]
  fedora: [mesa-libGL-devel, mesa-libGLU-devel]
  freebsd: [mesa-libs]
  gentoo: [virtual/opengl]
  macports: [mesa]
  openembedded: [mesa@openembedded-core]
  opensuse: [Mesa-devel]
  rhel: [mesa-libGL-devel, mesa-libGLU-devel]
  slackware:
    slackpkg:
      packages: [mesa]
  ubuntu: [libgl1-mesa-dev, libglu1-mesa-dev]
but for stage we really need libglu to be enabled as well (and it's
provided by separate libglu recipe in openembedded-core)

* fixes:
| -- Found X11: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/stage/4.3.0-r0/recipe-sysroot/usr/lib/libX11.so
| -- Found FLTK: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/stage/4.3.0-r0/recipe-sysroot/usr/lib/libfltk_images.so;/jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/stage/4.3.0-r0/recipe-sysroot/usr/lib/libfltk_forms.so;/jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/stage/4.3.0-r0/recipe-sysroot/usr/lib/libfltk_gl.so;/jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/stage/4.3.0-r0/recipe-sysroot/usr/lib/libGL.so;/jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/stage/4.3.0-r0/recipe-sysroot/usr/lib/libfltk.so
| CMake Error at CMakeLists.txt:104 (MESSAGE):
|   OpenGL GLU not found, aborting
|
|
| -- Configuring incomplete, errors occurred!

* then there are few packaging issues:

WARNING: stage-4.3.0-r0 do_package: QA Issue: stage: Files/directories were installed but not shipped in any package:
  /usr/lib/Stage-4.3/expand_swarm.so
  /usr/lib/Stage-4.3/pioneer_flocking.so
  /usr/lib/Stage-4.3/fasr2.so
  /usr/lib/Stage-4.3/expand_pioneer.so
  /usr/lib/Stage-4.3/dynamic.so
  /usr/lib/Stage-4.3/wander.so
  /usr/lib/Stage-4.3/source.so
  /usr/lib/Stage-4.3/lasernoise.so
  /usr/lib/Stage-4.3/rasterize.so
  /usr/lib/Stage-4.3/fasr.so
  /usr/lib/Stage-4.3/sink.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
stage: 11 installed and not shipped files. [installed-vs-shipped]
ERROR: stage-4.3.0-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so: stage path '/work/core2-64-oe-linux/stage/4.3.0-r0/packages-split/stage/usr/lib/libstage.so' [dev-so]

Signed-off-by: Martin Jansa <martin.jansa@lge.com>