{foxy} resolve dependency issues in new recipes
ERROR: Nothing PROVIDES 'UNRESOLVED-benchmark' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/google-benchmark-vendor/google-benchmark-vendor_0.0.3-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'google-benchmark-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['google-benchmark-vendor', 'UNRESOLVED-benchmark']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'google-benchmark-vendor', 'UNRESOLVED-benchmark']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'google-benchmark-vendor', 'UNRESOLVED-benchmark']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'google-benchmark-vendor', 'UNRESOLVED-benchmark']
NOTE: Runtime target 'ament-cmake-google-benchmark' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-google-benchmark', 'google-benchmark-vendor', 'UNRESOLVED-benchmark']
NOTE: Runtime target 'performance-test-fixture' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['performance-test-fixture', 'google-benchmark-vendor', 'UNRESOLVED-benchmark']
ERROR: Nothing PROVIDES 'google-benchmark-vendor' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/performance-test-fixture/performance-test-fixture_0.0.4-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'google-benchmark-vendor'
ERROR: Nothing PROVIDES 'UNRESOLVED-pugixml-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-io_1.1.1-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'lanelet2-validation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-validation', 'lanelet2-io', 'UNRESOLVED-pugixml-dev']
NOTE: Runtime target 'lanelet2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2', 'lanelet2-validation', 'lanelet2-io', 'UNRESOLVED-pugixml-dev']
NOTE: Runtime target 'lanelet2-examples' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-examples', 'lanelet2-io', 'UNRESOLVED-pugixml-dev']
NOTE: Runtime target 'lanelet2-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-python', 'lanelet2-projection', 'lanelet2-io', 'UNRESOLVED-pugixml-dev']
NOTE: Runtime target 'lanelet2-projection' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-projection', 'lanelet2-io', 'UNRESOLVED-pugixml-dev']
NOTE: Runtime target 'lanelet2-io' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-io', 'UNRESOLVED-pugixml-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-rospkg-native' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/mrt-cmake-modules/mrt-cmake-modules_1.0.8-1.bb, virtual:native:/jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/mrt-cmake-modules/mrt-cmake-modules_1.0.8-1.bb DEPENDS on or otherwise requires it). Close matches:
  python3-rosdep-native
  python3-rospkg-native
NOTE: Runtime target 'mrt-cmake-modules' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrt-cmake-modules', 'UNRESOLVED-python3-rospkg-native']
NOTE: Runtime target 'lanelet2-routing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-routing', 'mrt-cmake-modules-native', 'UNRESOLVED-python3-rospkg-native']
NOTE: Runtime target 'lanelet2-traffic-rules' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-traffic-rules', 'lanelet2-core', 'mrt-cmake-modules-native', 'UNRESOLVED-python3-rospkg-native']
NOTE: Runtime target 'lanelet2-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-core', 'mrt-cmake-modules-native', 'UNRESOLVED-python3-rospkg-native']
NOTE: Runtime target 'lanelet2-maps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-maps', 'lanelet2-core', 'mrt-cmake-modules-native', 'UNRESOLVED-python3-rospkg-native']
ERROR: Nothing PROVIDES 'UNRESOLVED-lcov-native' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/mrt-cmake-modules/mrt-cmake-modules_1.0.8-1.bb, virtual:native:/jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/mrt-cmake-modules/mrt-cmake-modules_1.0.8-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'ament-cmake-google-benchmark-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/ament-cmake/ament-cmake-google-benchmark_0.9.7-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ament-cmake-google-benchmark-dev'
NOTE: Runtime target 'ament-cmake-google-benchmark-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-google-benchmark-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-benchmark' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/google-benchmark-vendor/google-benchmark-vendor_0.0.3-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-benchmark' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-benchmark']
ERROR: Nothing RPROVIDES 'google-benchmark-vendor-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/google-benchmark-vendor/google-benchmark-vendor_0.0.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'google-benchmark-vendor-dev'
NOTE: Runtime target 'google-benchmark-vendor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['google-benchmark-vendor-dev']
ERROR: Nothing RPROVIDES 'lanelet2-routing-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-routing_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-routing-dev'
NOTE: Runtime target 'lanelet2-routing-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-routing-dev']
ERROR: Nothing RPROVIDES 'lanelet2-validation-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-validation_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-validation-dev'
NOTE: Runtime target 'lanelet2-validation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-validation-dev']
ERROR: Nothing RPROVIDES 'lanelet2-examples-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-examples_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-examples-dev'
NOTE: Runtime target 'lanelet2-examples-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-examples-dev']
ERROR: Nothing RPROVIDES 'nav2-rviz-plugins' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/roverrobotics-ros2/rover-navigation_0.1.1-2.bb RDEPENDS on or otherwise requires it)
nav2-rviz-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'nav2-rviz-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-rviz-plugins']
NOTE: Runtime target 'rover-navigation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rover-navigation', 'nav2-rviz-plugins']
NOTE: Runtime target 'roverrobotics-ros2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roverrobotics-ros2', 'rover-navigation', 'nav2-rviz-plugins']
NOTE: Runtime target 'roverrobotics-ros2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roverrobotics-ros2-dev', 'rover-navigation', 'nav2-rviz-plugins']
NOTE: Runtime target 'rover-simulation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rover-simulation', 'rover-navigation', 'nav2-rviz-plugins']
NOTE: Runtime target 'rover-navigation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rover-navigation-dev', 'nav2-rviz-plugins']
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/roverrobotics-ros2/rover-navigation_0.1.1-2.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
ERROR: Nothing RPROVIDES 'lanelet2-projection-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-projection_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-projection-dev'
NOTE: Runtime target 'lanelet2-projection-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-projection-dev']
ERROR: Nothing RPROVIDES 'performance-test-fixture-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/performance-test-fixture/performance-test-fixture_0.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'performance-test-fixture-dev'
NOTE: Runtime target 'performance-test-fixture-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['performance-test-fixture-dev']
ERROR: Nothing RPROVIDES 'rover-simulation-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/roverrobotics-ros2/rover-simulation_0.1.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rover-simulation-dev'
NOTE: Runtime target 'rover-simulation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rover-simulation-dev']
ERROR: Nothing RPROVIDES 'lanelet2-core-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-core_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-core-dev'
NOTE: Runtime target 'lanelet2-core-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-core-dev']
ERROR: Nothing RPROVIDES 'lanelet2-io-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-io_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-io-dev'
NOTE: Runtime target 'lanelet2-io-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-io-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-pugixml-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-io_1.1.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-pugixml-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-pugixml-dev']
ERROR: Nothing RPROVIDES 'mrt-cmake-modules-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/mrt-cmake-modules/mrt-cmake-modules_1.0.8-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mrt-cmake-modules-dev'
NOTE: Runtime target 'mrt-cmake-modules-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mrt-cmake-modules-dev']
ERROR: Nothing RPROVIDES 'lanelet2-traffic-rules-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-traffic-rules_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-traffic-rules-dev'
NOTE: Runtime target 'lanelet2-traffic-rules-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-traffic-rules-dev']
ERROR: Nothing RPROVIDES 'lanelet2-maps-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-maps_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-maps-dev'
NOTE: Runtime target 'lanelet2-maps-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-maps-dev']
ERROR: Nothing RPROVIDES 'lanelet2-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-dev'
NOTE: Runtime target 'lanelet2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-dev']
ERROR: Nothing RPROVIDES 'lanelet2-python-dev' (but /jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/lanelet2/lanelet2-python_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lanelet2-python-dev'
NOTE: Runtime target 'lanelet2-python-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lanelet2-python-dev']
ERROR: Nothing RPROVIDES 'google-benchmark-vendor-native' (but virtual:native:/jenkins/mjansa/build/ros/webos-foxy-gatesgarth/meta-ros/meta-ros2-foxy/generated-recipes/ament-cmake/ament-cmake-google-benchmark_0.9.7-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'google-benchmark-vendor-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['google-benchmark-vendor-native']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>