{melodic} pilz-trajectory-generation: use -I instead of -isystem
* fixes:
DEBUG: Executing shell function do_compile
NOTE: VERBOSE=1 cmake --build ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/build --target all -- -j 80
[1/55] ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"pilz_trajectory_generation\" -Dplanning_context_loader_circ_EXPORTS -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/eigen3 -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0=/usr/src/debug/pilz-trajectory-generation/0.4.10-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot -fPIC   -std=c++11 -Wall -Wextra -Wno-unused-parameter -Werror -MD -MT CMakeFiles/planning_context_loader_circ.dir/src/path_circle_generator.cpp.o -MF CMakeFiles/planning_context_loader_circ.dir/src/path_circle_generator.cpp.o.d -o CMakeFiles/planning_context_loader_circ.dir/src/path_circle_generator.cpp.o -c ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/src/path_circle_generator.cpp
FAILED: CMakeFiles/planning_context_loader_circ.dir/src/path_circle_generator.cpp.o
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"pilz_trajectory_generation\" -Dplanning_context_loader_circ_EXPORTS -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/eigen3 -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0=/usr/src/debug/pilz-trajectory-generation/0.4.10-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot -fPIC   -std=c++11 -Wall -Wextra -Wno-unused-parameter -Werror -MD -MT CMakeFiles/planning_context_loader_circ.dir/src/path_circle_generator.cpp.o -MF CMakeFiles/planning_context_loader_circ.dir/src/path_circle_generator.cpp.o.d -o CMakeFiles/planning_context_loader_circ.dir/src/path_circle_generator.cpp.o -c ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/src/path_circle_generator.cpp
In file included from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/kdl/utilities/utility.h:27,
                 from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/kdl/frames.hpp:129,
                 from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/kdl/path.hpp:47,
                 from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/include/pilz_trajectory_generation/path_circle_generator.h:21,
                 from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/src/path_circle_generator.cpp:18:
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/c++/8.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
[2/55] ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"pilz_trajectory_generation\" -Dsequence_capability_EXPORTS -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/eigen3 -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0=/usr/src/debug/pilz-trajectory-generation/0.4.10-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot -fPIC   -std=c++11 -Wall -Wextra -Wno-unused-parameter -Werror -MD -MT CMakeFiles/sequence_capability.dir/src/trajectory_blender_transition_window.cpp.o -MF CMakeFiles/sequence_capability.dir/src/trajectory_blender_transition_window.cpp.o.d -o CMakeFiles/sequence_capability.dir/src/trajectory_blender_transition_window.cpp.o -c ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/src/trajectory_blender_transition_window.cpp
FAILED: CMakeFiles/sequence_capability.dir/src/trajectory_blender_transition_window.cpp.o
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"pilz_trajectory_generation\" -Dsequence_capability_EXPORTS -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic/include -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -isystem ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/eigen3 -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0=/usr/src/debug/pilz-trajectory-generation/0.4.10-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot -fPIC   -std=c++11 -Wall -Wextra -Wno-unused-parameter -Werror -MD -MT CMakeFiles/sequence_capability.dir/src/trajectory_blender_transition_window.cpp.o -MF CMakeFiles/sequence_capability.dir/src/trajectory_blender_transition_window.cpp.o.d -o CMakeFiles/sequence_capability.dir/src/trajectory_blender_transition_window.cpp.o -c ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/src/trajectory_blender_transition_window.cpp
In file included from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/c++/8.2.0/complex:44,
                 from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/eigen3/Eigen/Core:96,
                 from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/eigen3/Eigen/Geometry:11,
                 from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/include/pilz_trajectory_generation/trajectory_functions.h:21,
                 from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/include/pilz_trajectory_generation/trajectory_blender_transition_window.h:21,
                 from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/git/src/trajectory_blender_transition_window.cpp:18:
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr/include/c++/8.2.0/cmath:45:15: fatal error: math.h: No such file or directory
 #include_next <math.h>
               ^~~~~~~~
compilation terminated.
...
compilation terminated.
ninja: build stopped: subcommand failed.
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/temp/log.do_compile.34653)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>