packagegroup-ros1-comm: inherit ros_distro_${ROS_DISTRO}
* to automatically skip the recipe when there isn't any
  ROS 1 distro layer being included (e.g. meta-ros1-melodic)

* fixes:
ERROR: Nothing RPROVIDES 'roslib' (but /OE/meta-ros/meta-ros1/recipes-core/packagegroups/packagegroup-ros1-comm.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'roslib' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roslib']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-ros1-comm', 'roslib']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>