ros-python2-recipe-blacklist.inc: remove openbox, pyxdg
* it was fixed in newer meta-oe with:
  https://git.openembedded.org/meta-openembedded/commit/?id=6aab1a829e55fbd2444c93941371920091855785

* and in hardknott this was causing:
ERROR: Nothing PROVIDES 'openbox' (but /jenkins/home/workspace/jansa/ros2-foxy-hardknott/ros2-foxy-hardknott/meta-openembedded/meta-oe/recipes-graphics/openbox/obconf_git.bb DEPENDS on or otherwise requires it)
openbox was skipped: Recipe is blacklisted: Depends on blacklisted python2
ERROR: Nothing RPROVIDES 'obconf' (but /jenkins/home/workspace/jansa/ros2-foxy-hardknott/ros2-foxy-hardknott/meta-openembedded/meta-oe/recipes-graphics/openbox/obconf_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'obconf'
NOTE: Runtime target 'obconf' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['obconf']
ERROR: Nothing RPROVIDES 'obconf-dev' (but /jenkins/home/workspace/jansa/ros2-foxy-hardknott/ros2-foxy-hardknott/meta-openembedded/meta-oe/recipes-graphics/openbox/obconf_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'obconf-dev'
NOTE: Runtime target 'obconf-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['obconf-dev']

* pyxdg was also fixed by using distutils3 instead of distutils
ERROR: Nothing RPROVIDES 'pyxdg' (but /jenkins/home/workspace/jansa/ros2-foxy-hardknott/ros2-foxy-hardknott/meta-openembedded/meta-oe/recipes-graphics/openbox/openbox_3.6.1.bb RDEPENDS on or otherwise requires it)
pyxdg was skipped: Recipe is blacklisted: Depends on blacklisted python2
NOTE: Runtime target 'pyxdg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pyxdg']
NOTE: Runtime target 'openbox' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['openbox', 'pyxdg']
NOTE: Runtime target 'openbox-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['openbox-dev', 'pyxdg']
ERROR: Nothing RPROVIDES 'openbox-config' (but /jenkins/home/workspace/jansa/ros2-foxy-hardknott/ros2-foxy-hardknott/meta-openembedded/meta-oe/recipes-graphics/openbox/openbox_3.6.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'openbox-config'
NOTE: Runtime target 'openbox-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['openbox-config']
ERROR: Nothing RPROVIDES 'openbox-theme-clearlooks' (but /jenkins/home/workspace/jansa/ros2-foxy-hardknott/ros2-foxy-hardknott/meta-openembedded/meta-oe/recipes-graphics/openbox/openbox_3.6.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'openbox-theme-clearlooks'
NOTE: Runtime target 'openbox-theme-clearlooks' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['openbox-theme-clearlooks']
ERROR: Nothing RPROVIDES 'openbox-core' (but /jenkins/home/workspace/jansa/ros2-foxy-hardknott/ros2-foxy-hardknott/meta-openembedded/meta-oe/recipes-graphics/openbox/openbox_3.6.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'openbox-core'
NOTE: Runtime target 'openbox-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['openbox-core']
ERROR: Nothing RPROVIDES 'obconf' (but /jenkins/home/workspace/jansa/ros2-foxy-hardknott/ros2-foxy-hardknott/meta-openembedded/meta-oe/recipes-graphics/openbox/obconf_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'obconf'
NOTE: Runtime target 'obconf' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['obconf']
ERROR: Nothing RPROVIDES 'obconf-dev' (but /jenkins/home/workspace/jansa/ros2-foxy-hardknott/ros2-foxy-hardknott/meta-openembedded/meta-oe/recipes-graphics/openbox/obconf_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'obconf-dev'
NOTE: Runtime target 'obconf-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['obconf-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>