{noetic} criutils, handeye: unblacklist by mapping python-termcolor to python3-termcolor
* python3-termcolor added in:
  https://github.com/ros/rosdistro/pull/29534

* fixes:
ERROR: Nothing RPROVIDES 'criutils' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-plugins_0.1.0-1.bb RDEPENDS on or otherwise requires it)
criutils was skipped: Recipe is blacklisted: Depends on unavailable ROS_UNRESOLVED_DEP-python-termcolor
NOTE: Runtime target 'criutils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['criutils']
NOTE: Runtime target 'moveit-calibration-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-calibration-plugins', 'criutils']
ERROR: Nothing RPROVIDES 'handeye' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-plugins_0.1.0-1.bb RDEPENDS on or otherwise requires it)
handeye was skipped: Recipe is blacklisted: Depends on criutils->unavailable ROS_UNRESOLVED_DEP-python-termcolor
NOTE: Runtime target 'handeye' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['handeye']
ERROR: Nothing RPROVIDES 'moveit-calibration-plugins-dev' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/moveit-calibration/moveit-calibration-plugins_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-calibration-plugins-dev'
NOTE: Runtime target 'moveit-calibration-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-calibration-plugins-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>