{eloquent} remove cartographer-ros and cartographer-ros-msgs from world
* fixes:
  ERROR: Nothing RPROVIDES 'python-core' (but /jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros-common/recipes-devtools/python/python-sphinx_1.6.7.bb RDEPENDS on or otherwise requires it)
  NOTE: Runtime target 'python-core' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python-core']
  NOTE: Runtime target 'cartographer-ros' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['cartographer-ros', 'cartographer', 'python-sphinx', 'python-core']
  NOTE: Runtime target 'cartographer-ros-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['cartographer-ros-dev', 'cartographer', 'python-sphinx', 'python-core']
  NOTE: Runtime target 'cartographer' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['cartographer', 'python-sphinx', 'python-core']
  NOTE: Runtime target 'cartographer-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['cartographer-dev', 'python-sphinx', 'python-core']
  ERROR: Nothing RPROVIDES 'python-sphinx-dev' (but /jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros-common/recipes-devtools/python/python-sphinx_1.6.7.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'python-sphinx-dev'
  NOTE: Runtime target 'python-sphinx-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python-sphinx-dev']
  ERROR: Nothing RPROVIDES 'python-sphinx' (but /jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros-common/recipes-devtools/python/python-sphinx_1.6.7.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'python-sphinx'
  NOTE: Runtime target 'python-sphinx' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python-sphinx']
  ERROR: Nothing PROVIDES 'python' (but /jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros-common/recipes-devtools/python/python-sphinx_1.6.7.bb DEPENDS on or otherwise requires it)
  python was skipped: Recipe is blacklisted: ROS 2 is Python 3 only