{common}{ros2} openscenegraph: Add OSGL-1.0 license
Add the OSGPL-1.0 license which is based on the LGPL-2.1-only license
with WxWindows-exception-3.1 in the meta-ros-common licenses directory.

Update the recipe to use the newly added OSGL-1.0 license replacing
the existing "LGPL-2.1-only & WxWindows-exception-3.1" license
designation which is not recognized by the build system and triggers a
QA warning as well as a SPDX creation error if SBOM is enabled in the
build:

ERROR: openscenegraph-3.6.5+git-r0 do_create_spdx: Cannot find any text for license WxWindows-exception-3.1

Signed-off-by: Christian Kohn <chris.kohn@amd.com>