urdfdom: updating to 0.2.10
The installation of urdfdom 0.2.8 needed a patch because of some
problems with the installation:
ERROR: QA Issue: non debug package contains .debug directory: urdfdom path [...]/packages-split/urdfdom/usr/share/urdfdom/.debug/urdf_to_graphiz
ERROR: QA Issue: non debug package contains .debug directory: urdfdom path [...]/packages-split/urdfdom/usr/share/urdfdom/.debug/urdf_mem_test
ERROR: QA Issue: non debug package contains .debug directory: urdfdom path [...]/packages-split/urdfdom/usr/share/urdfdom/.debug/check_urdf
ERROR: QA run found fatal errors. Please consider fixing them.
ERROR: Function failed: do_package_qa

In version 0.2.10, these problems were resolved and hence, we can
remove the patch.