Revert "Drop python*-pyproj_1.9.5.1.bb (no longer used by ROS 1 components)"
This reverts commit 93d9860f5c47102cfffed22af75824e3869f6527.

Now it's used again by geodesy in latest Eloquent release

* fixes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'UNRESOLVED-python-pyproj' (but /jenkins/mjansa/build-ros/ros2-eloquent-thud/meta-ros/meta-ros2-eloquent/generated-recipes/geographic-info/geodesy_1.0.1-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'geographic-info' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['geographic-info', 'geodesy', 'UNRESOLVED-python-pyproj']
NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'geographic-info', 'geodesy', 'UNRESOLVED-python-pyproj']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'geographic-info', 'geodesy', 'UNRESOLVED-python-pyproj']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'geographic-info', 'geodesy', 'UNRESOLVED-python-pyproj']
NOTE: Runtime target 'geodesy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['geodesy', 'UNRESOLVED-python-pyproj']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>