{melodic} libcmt: fetch libcmt with bitbake fetcher instead of ExternalProject_add
* fixes:
libcmt/2.1.13-1-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/ExternalProject.cmake:2324 (message):
  error: could not find git for clone of libcmt
Call Stack (most recent call first):
  webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/libcmt/2.1.13-1-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/ExternalProject.cmake:3100 (_ep_add_download_command)
  CMakeLists.txt:12 (ExternalProject_Add)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>