{foxy} smac-planner: remove runtime dependency on ceres-solver
* ceres-solver has empty PN causing:
NOTE: recipe webos-image-ros-world-1.0-r3: task do_rootfs: Started
ERROR: webos-image-ros-world-1.0-r3 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/opkg.conf -t /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/temp/ipktemp/ -o /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends kernel-vmlinux --add-ignore-recommends update-rc.d install opkg packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-ros-world packagegroup-webos-extended run-postinsts' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-ros-world-1.0-r0.qemux86 requires packagegroup-ros-world-foxy, but none of the providers can be installed
 *   - package packagegroup-ros-world-foxy-1.0-r0.qemux86 requires smac-planner, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides ceres-solver needed by smac-planner-0.4.5-1-r0.qemux86
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

 * opkg_finalize_intercepts: Failed to open dir /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/temp/ipktemp//opkg-R76aiJ/opkg-intercept-uPDdcP: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/temp/ipktemp//opkg-R76aiJ/opkg-intercept-uPDdcP: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/temp/ipktemp//opkg-R76aiJ: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/rootfs//var/cache/opkg/volatile: No such file or directory.
Disfavor package: kernel-vmlinux

Signed-off-by: Martin Jansa <martin.jansa@lge.com>