{noetic} cmvision: restrict with x11 skip group
* due to wxwidgets and fltk

* fixes:
ERROR: Nothing PROVIDES 'wxwidgets' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/cmvision/cmvision_0.5.0-2.bb DEPENDS on or otherwise requires it)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'cmvision' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cmvision', 'wxwidgets']
NOTE: Runtime target 'packagegroup-ros-world-noetic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-noetic', 'cmvision', 'wxwidgets']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'cmvision', 'wxwidgets']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'cmvision', 'wxwidgets']
ERROR: Nothing PROVIDES 'fltk' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/cmvision/cmvision_0.5.0-2.bb DEPENDS on or otherwise requires it)
fltk was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Nothing RPROVIDES 'cmvision-dev' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/cmvision/cmvision_0.5.0-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cmvision-dev'
NOTE: Runtime target 'cmvision-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cmvision-dev']
ERROR: Nothing RPROVIDES 'wxwidgets' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/cmvision/cmvision_0.5.0-2.bb RDEPENDS on or otherwise requires it)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'wxwidgets' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['wxwidgets']
ERROR: Nothing RPROVIDES 'fltk' (but /jenkins/mjansa/build/ros/webos-noetic-honister/meta-ros/meta-ros1-noetic/generated-recipes/cmvision/cmvision_0.5.0-2.bb RDEPENDS on or otherwise requires it)
fltk was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'fltk' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fltk']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>