{dashing} packagegroup-ros-world-dashing: drop dependency on launch-ros-sandbox and cross-compile
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-docker' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/cross-compile/cross-compile_0.1.1-1.bb, /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/launch-ros-sandbox/launch-ros-sandbox_0.0.2-4.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'cross-compile' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cross-compile', 'UNRESOLVED-python3-docker']
NOTE: Runtime target 'packagegroup-ros-world-dashing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-dashing', 'cross-compile', 'UNRESOLVED-python3-docker']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'cross-compile', 'UNRESOLVED-python3-docker']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'cross-compile', 'UNRESOLVED-python3-docker']
NOTE: Runtime target 'launch-ros-sandbox' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['launch-ros-sandbox', 'UNRESOLVED-python3-docker']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>