{melodic} uwsim-bullet: fix LICENSE
* fixes:
WARNING: /jenkins/mjansa/build-ros/webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/uwsim-bullet/uwsim-bullet_2.82.2-1.bb: uwsim-bullet: LIC
 is not in the valid list of separators (&|() )
ERROR: /jenkins/mjansa/build-ros/webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/uwsim-bullet/uwsim-bullet_2.82.2-1.bb: Error executing a python function in

The stack trace of python calls that resulted in this exception/failure was:
File: '<code>', lineno: 2, function: <module>
     0001:__anon_25__jenkins_mjansa_build_ros_webos_melodic_thud_openembedded_core_meta_classes_patch_bbclass(d)
 *** 0002:__anon_688__jenkins_mjansa_build_ros_webos_melodic_thud_openembedded_core_meta_classes_base_bbclass(d)
     0003:__anon_1186__jenkins_mjansa_build_ros_webos_melodic_thud_openembedded_core_meta_classes_insane_bbclass(d)
     0004:__anon_251__jenkins_mjansa_build_ros_webos_melodic_thud_openembedded_core_meta_classes_package_bbclass(d)
     0005:__anon_264__jenkins_mjansa_build_ros_webos_melodic_thud_openembedded_core_meta_classes_package_ipk_bbclass(d)
     0006:__anon_25__jenkins_mjansa_build_ros_webos_melodic_thud_openembedded_core_meta_classes_debian_bbclass(d)
File: '/jenkins/mjansa/build-ros/webos-melodic-thud/openembedded-core/meta/classes/base.bbclass', lineno: 573, function: __anon_688__jenkins_mjansa_build_ros_webos_melodic_t
     0569:        # superset of all per-package licenses. We do not do advanced (pattern)
     0570:        # matching of license expressions - just check that all license strings
     0571:        # in LICENSE_<pkg> are found in LICENSE.
     0572:        license_set = oe.license.list_licenses(license)
 *** 0573:        for pkg in d.getVar('PACKAGES').split():
     0574:            pkg_license = d.getVar('LICENSE_' + pkg)
     0575:            if pkg_license:
     0576:                unlisted = oe.license.list_licenses(pkg_license) - license_set
     0577:                if unlisted:
File: '/jenkins/mjansa/build-ros/webos-melodic-thud/openembedded-core/meta/lib/oe/license.py', lineno: 240, function: list_licenses
     0236:    """Simply get a list of all licenses mentioned in a license string.
     0237:       Binary operators are not applied or taken into account in any way"""
     0238:    visitor = ListVisitor()
     0239:    try:
 *** 0240:        visitor.visit_string(licensestr)
     0241:    except SyntaxError as exc:
     0242:        raise LicenseSyntaxError(licensestr, exc)
     0243:    return visitor.licenses
File: '/jenkins/mjansa/build-ros/webos-melodic-thud/openembedded-core/meta/lib/oe/license.py', lineno: 69, function: visit_string
     0065:        self.visit(ast.parse(' '.join(elements)))
     0066:
     0067:    """Syntax tree visitor which can accept OpenEmbedded license strings"""
     0068:    def visit_string(self, licensestr):
 *** 0069:        self.visit_elements(self.get_elements(licensestr))
     0070:
     0071:class FlattenVisitor(LicenseVisitor):
     0072:    """Flatten a license tree (parsed from a string) by selecting one of each
     0073:    set of OR options, in the way the user specifies"""
File: '/jenkins/mjansa/build-ros/webos-melodic-thud/openembedded-core/meta/lib/oe/license.py', lineno: 57, function: get_elements
     0053:                if pos > 0 and license_pattern.match(elements[pos-1]):
     0054:                    new_elements.append('&')
     0055:                element = '"' + element + '"'
     0056:            elif not license_operator.match(element):
 *** 0057:                raise InvalidLicense(element)
     0058:            new_elements.append(element)
     0059:
     0060:        return new_elements
     0061:
Exception: oe.license.InvalidLicense: invalid characters in license 'Check-author's-website'

ERROR: Exception during parse: Traceback (most recent call last):
  File "/jenkins/mjansa/build-ros/webos-melodic-thud/bitbake/lib/bb/cooker.py", line 2146, in parse_next
    parsed, result = next(self.results)
  File "/jenkins/mjansa/build-ros/webos-melodic-thud/bitbake/lib/bb/cooker.py", line 2132, in parse_generator
    result = self.result_queue.get(timeout=0.25)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
TypeError: __init__() missing 1 required positional argument: 'license'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>