{eloquent} libg2o: skip without opengl
* fixes:
ERROR: Nothing PROVIDES 'mesa' (but meta-ros2-eloquent/generated-recipes/libg2o/libg2o_2019.11.23-4.bb DEPENDS on or otherwise requires it)
mesa was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'libg2o' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libg2o', 'mesa']
NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'libg2o', 'mesa']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'libg2o', 'mesa']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'libg2o', 'mesa']
ERROR: Nothing RPROVIDES 'libg2o-dev' (but meta-ros2-eloquent/generated-recipes/libg2o/libg2o_2019.11.23-4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'libg2o-dev'
NOTE: Runtime target 'libg2o-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libg2o-dev']
ERROR: Nothing RPROVIDES 'mesa' (but meta-ros2-eloquent/generated-recipes/libg2o/libg2o_2019.11.23-4.bb RDEPENDS on or otherwise requires it)
mesa was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'mesa' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mesa']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>