{galactic} rmf-visualization-schedule: remove runtime dependency on empty nlohmann-json and websocketpp
* fixes:
  ros-image-world/1.0-r0$ /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install rmf-visualization-schedule

  Collected errors:
   * Solver encountered 1 problem(s):
   * Problem 1/1:
   *   - nothing provides websocketpp needed by rmf-visualization-schedule-1.2.1-1-r0.core2-64
   *
   * Solution 1:
   *   - do not ask to install a package providing rmf-visualization-schedule

* unfortunately opkg doesn't show the whole chain of dependencies which are broken, so image.do_rootfs
  was failing with:

  ERROR: ros-image-world-1.0-r0 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install connman packagegroup-core-boot packagegroup-ros-world run-postinsts' returned 1:
  Collected errors:
   * Solver encountered 1 problem(s):
   * Problem 1/1:
   *   - package packagegroup-ros-world-1.0-r0.qemux86_64 requires packagegroup-ros-world-galactic, but none of the providers can be installed
   *
   * Solution 1:
   *   - do not ask to install a package providing packagegroup-ros-world

   * opkg_finalize_intercepts: Failed to open dir /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-mA1ME1/opkg-intercept-IlNSRs: No such file or directory.
   * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-mA1ME1/opkg-intercept-IlNSRs: No such file or directory.
   * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-mA1ME1: No such file or directory.

  ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/log.do_rootfs.7349

* and trying to manually install packagegroup-ros-world-galactic shows that it's
  an issue with rmf-visualization-schedule:

  ros-image-world/1.0-r0$ /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install packagegroup-ros-world-galactic

  Collected errors:
   * Solver encountered 1 problem(s):
   * Problem 1/1:
   *   - package packagegroup-ros-world-galactic-1.0-r0.qemux86_64 requires rmf-visualization-schedule, but none of the providers can be installed
   *
   * Solution 1:
   *   - do not ask to install a package providing packagegroup-ros-world-galactic

  and then manually installing rmf-visualization-schedule shows the error at the top

Signed-off-by: Martin Jansa <martin.jansa@lge.com>