{melodic} ros-distro-recipe-blacklist.inc: add web-video-server
* fixes:
ERROR: Nothing PROVIDES 'ffmpeg' (but /jenkins/home/workspace/jansa/ros1-melodic-warrior/ros1-melodic-warrior/meta-ros/meta-ros1-melodic/generated-recipes/web-video-server/web-video-server_0.2.1-1.bb DEPENDS on or otherwise requires it)
ffmpeg was skipped: because it has a restricted license 'commercial'. Which is not whitelisted in LICENSE_FLAGS_WHITELIST
ERROR: Nothing PROVIDES 'cv-bridge' (but /jenkins/home/workspace/jansa/ros1-melodic-warrior/ros1-melodic-warrior/meta-ros/meta-ros1-melodic/generated-recipes/web-video-server/web-video-server_0.2.1-1.bb DEPENDS on or otherwise requires it)
cv-bridge was skipped: Recipe is blacklisted: Depends on gstreamer1.0-plugins-base which is not available for raspberrypi MACHINEs with vc4graphics in MACHINE_FEATURES, but without opengl in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'ffmpeg' (but /jenkins/home/workspace/jansa/ros1-melodic-warrior/ros1-melodic-warrior/meta-ros/meta-ros1-melodic/generated-recipes/web-video-server/web-video-server_0.2.1-1.bb RDEPENDS on or otherwise requires it)
ffmpeg was skipped: because it has a restricted license 'commercial'. Which is not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'ffmpeg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ffmpeg']
ERROR: Nothing RPROVIDES 'web-video-server-dev' (but /jenkins/home/workspace/jansa/ros1-melodic-warrior/ros1-melodic-warrior/meta-ros/meta-ros1-melodic/generated-recipes/web-video-server/web-video-server_0.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'web-video-server-dev'
NOTE: Runtime target 'web-video-server-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['web-video-server-dev']
ERROR: Nothing RPROVIDES 'web-video-server' (but /jenkins/home/workspace/jansa/ros1-melodic-warrior/ros1-melodic-warrior/meta-ros/meta-ros1-melodic/generated-recipes/web-video-server/web-video-server_0.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'web-video-server'
NOTE: Runtime target 'web-video-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['web-video-server']
ERROR: Nothing RPROVIDES 'cv-bridge' (but /jenkins/home/workspace/jansa/ros1-melodic-warrior/ros1-melodic-warrior/meta-ros/meta-ros1-melodic/generated-recipes/web-video-server/web-video-server_0.2.1-1.bb RDEPENDS on or otherwise requires it)
cv-bridge was skipped: Recipe is blacklisted: Depends on gstreamer1.0-plugins-base which is not available for raspberrypi MACHINEs with vc4graphics in MACHINE_FEATURES, but without opengl in DISTRO_FEATURES
NOTE: Runtime target 'cv-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cv-bridge']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>