{dashing} packagegroup-ros-world-dashing: remove cloudwatch-metrics-common
* cloudwatch-metrics-common installs only header files in PN-dev, static library in PN-staticdev
  and debug files in PN-dbg, so the PN is empty and not created, causing:

NOTE: recipe ros-image-world-1.0-r0: task do_rootfs: Started
ERROR: ros-image-world-1.0-r0 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install connman packagegroup-core-boot packagegroup-ros-world run-postinsts' returned 1:
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - nothing provides cloudwatch-metrics-common needed by packagegroup-ros-world-dashing-1.0-r0.all
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

 * opkg_finalize_intercepts: Failed to open dir /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-qoCmzQ/opkg-intercept-1imciq: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-qoCmzQ/opkg-intercept-1imciq: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-qoCmzQ: No such file or directory.

ERROR: ros-image-world-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/qemux86-oe-linux/ros-image-world/1.0-r0/temp/log.do_rootfs.44254
NOTE: recipe ros-image-world-1.0-r0: task do_rootfs: Failed
ERROR: Task (/jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros-common/recipes-core/images/ros-image-world.bb:do_rootfs) failed with exit code '1'

packages-split/
packages-split/cloudwatch-metrics-common-dev
packages-split/cloudwatch-metrics-common-dev/usr
packages-split/cloudwatch-metrics-common-dev/usr/share
packages-split/cloudwatch-metrics-common-dev/usr/share/cloudwatch_metrics_common
packages-split/cloudwatch-metrics-common-dev/usr/share/cloudwatch_metrics_common/cmake
packages-split/cloudwatch-metrics-common-dev/usr/share/cloudwatch_metrics_common/cmake/cloudwatch_metrics_commonConfig.cmake
packages-split/cloudwatch-metrics-common-dev/usr/share/cloudwatch_metrics_common/cmake/cloudwatch_metrics_commonConfigVersion.cmake
packages-split/cloudwatch-metrics-common-dev/usr/share/cloudwatch_metrics_common/cmake/cloudwatch_metrics_common-targets-noconfig.cmake
packages-split/cloudwatch-metrics-common-dev/usr/share/cloudwatch_metrics_common/cmake/cloudwatch_metrics_common-targets.cmake
packages-split/cloudwatch-metrics-common-dev/usr/include
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/metric_service_factory.hpp
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/utils
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/utils/metric_serialization.hpp
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/utils/cloudwatch_metrics_facade.hpp
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/utils/metric_file_manager.hpp
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/utils/metric_object.h
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/cloudwatch_options.h
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/definitions
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/definitions/definitions.h
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/metric_batcher.h
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/metric_service.hpp
packages-split/cloudwatch-metrics-common-dev/usr/include/cloudwatch_metrics_common/metric_publisher.hpp
packages-split/cloudwatch-metrics-common-locale
packages-split/cloudwatch-metrics-common-staticdev
packages-split/cloudwatch-metrics-common-staticdev/usr
packages-split/cloudwatch-metrics-common-staticdev/usr/lib
packages-split/cloudwatch-metrics-common-staticdev/usr/lib/libcloudwatch_metrics_common.a
packages-split/cloudwatch-metrics-common-doc
packages-split/cloudwatch-metrics-common-dbg
packages-split/cloudwatch-metrics-common-dbg/usr
packages-split/cloudwatch-metrics-common-dbg/usr/src
packages-split/cloudwatch-metrics-common-dbg/usr/src/debug
packages-split/cloudwatch-metrics-common-dbg/usr/src/debug/cloudwatch-metrics-common
packages-split/cloudwatch-metrics-common-dbg/usr/src/debug/cloudwatch-metrics-common/1.1.2-1-r0
packages-split/cloudwatch-metrics-common-dbg/usr/src/debug/cloudwatch-metrics-common/1.1.2-1-r0/git
packages-split/cloudwatch-metrics-common-dbg/usr/src/debug/cloudwatch-metrics-common/1.1.2-1-r0/git/include
packages-split/cloudwatch-metrics-common-dbg/usr/src/debug/cloudwatch-metrics-common/1.1.2-1-r0/git/include/cloudwatch_metrics_common
packages-split/cloudwatch-metrics-common-dbg/usr/src/debug/cloudwatch-metrics-common/1.1.2-1-r0/git/include/cloudwatch_metrics_common/metric_service_factory.hpp
...

Signed-off-by: Martin Jansa <martin.jansa@lge.com>