{foxy} ros-distro.inc: plotjuggler: use ament_cmake instead of ros_catkin
* fixes:
  ERROR: ParseError at meta-ros/meta-ros2-foxy/generated-recipes/plotjuggler/plotjuggler_2.8.4-1.bb:106: Could not inherit file classes/ros_catkin.bbclass

Signed-off-by: Martin Jansa <martin.jansa@lge.com>