{foxy} embree-vendor: require opengl
* fixes:
ERROR: Nothing PROVIDES 'glfw' (but ros2-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/embree-vendor/embree-vendor_0.0.6-1.bb DEPENDS on or otherwise requires it)
glfw was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'embree-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['embree-vendor', 'glfw']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'embree-vendor', 'glfw']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'embree-vendor', 'glfw']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'embree-vendor', 'glfw']
ERROR: Nothing RPROVIDES 'glfw' (but ros2-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/embree-vendor/embree-vendor_0.0.6-1.bb RDEPENDS on or otherwise requires it)
glfw was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'glfw' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['glfw']
ERROR: Nothing RPROVIDES 'embree-vendor-dev' (but ros2-foxy-hardknott/meta-ros/meta-ros2-foxy/generated-recipes/embree-vendor/embree-vendor_0.0.6-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'embree-vendor-dev'
NOTE: Runtime target 'embree-vendor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['embree-vendor-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>