{melodic} flir-ptu-description: depend on xacro-native
* fixes:
ERROR: flir-ptu-description-0.2.1-1-r0 do_compile: Execution of '/jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/temp/run.do_compile.68738' failed with exit code 1:
[1/1] cd /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/git && /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/build/catkin_generated/env_cached.sh xacro -o /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/devel/share/flir_ptu_description/urdf/example.urdf /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/git/urdf/example.urdf.xacro
FAILED: /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/devel/share/flir_ptu_description/urdf/example.urdf
cd /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/git && /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/build/catkin_generated/env_cached.sh xacro -o /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/devel/share/flir_ptu_description/urdf/example.urdf /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/git/urdf/example.urdf.xacro
/jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/flir-ptu-description/0.2.1-1-r0/build/catkin_generated/env_cached.sh: line 16: exec: xacro: not found
ninja: build stopped: subcommand failed.

* add many native dependencies needed to build xacro-native

Signed-off-by: Martin Jansa <martin.jansa@lge.com>