{melodic} ros-distro.inc: add mapping for libxext, libxmu, libxi
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libxext' (but generated-recipes/uwsim-bullet/uwsim-bullet_2.82.2-1.bb DEPENDS on or otherwise requires it)
Missing or unbuildable dependency chain was: ['uwsim-bullet', 'UNRESOLVED-libxext']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'uwsim-bullet', 'UNRESOLVED-libxext']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'uwsim-bullet', 'UNRESOLVED-libxext']
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'uwsim-bullet', 'UNRESOLVED-libxext']
Missing or unbuildable dependency chain was: ['uwsim-osgbullet', 'uwsim-bullet', 'UNRESOLVED-libxext']
ERROR: Nothing PROVIDES 'UNRESOLVED-libxmu-dev' (but generated-recipes/lvr2/lvr2_19.12.1-1.bb, generated-recipes/mapviz/mapviz_1.2.0-1.bb DEPENDS on or otherwise requires it)
Missing or unbuildable dependency chain was: ['mapviz', 'UNRESOLVED-libxmu-dev']
Missing or unbuildable dependency chain was: ['tile-map', 'mapviz', 'UNRESOLVED-libxmu-dev']
Missing or unbuildable dependency chain was: ['multires-image', 'mapviz', 'UNRESOLVED-libxmu-dev']
Missing or unbuildable dependency chain was: ['mapviz-plugins', 'mapviz', 'UNRESOLVED-libxmu-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-libxi-dev' (but generated-recipes/lvr2/lvr2_19.12.1-1.bb, generated-recipes/mapviz/mapviz_1.2.0-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'UNRESOLVED-libxext' (but generated-recipes/uwsim-bullet/uwsim-bullet_2.82.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libxext' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libxext']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libxmu-dev' (but generated-recipes/lvr2/lvr2_19.12.1-1.bb, generated-recipes/mapviz/mapviz_1.2.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libxmu-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libxmu-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libxi-dev' (but generated-recipes/lvr2/lvr2_19.12.1-1.bb, generated-recipes/mapviz/mapviz_1.2.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libxi-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libxi-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>