{dashing} ros-distro.inc: Set ROS_UNRESOLVED_PLATFORM_PKG_graphicsmagick to "graphicsmagick"
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-graphicsmagick' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/navigation2/nav2-map-server_0.2.6-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'nav2-map-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-map-server', 'UNRESOLVED-graphicsmagick']
NOTE: Runtime target 'navigation2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation2', 'nav2-map-server', 'UNRESOLVED-graphicsmagick']
NOTE: Runtime target 'nav2-system-tests' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-system-tests', 'navigation2', 'nav2-map-server', 'UNRESOLVED-graphicsmagick']
NOTE: Runtime target 'nav2-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup', 'navigation2', 'nav2-map-server', 'UNRESOLVED-graphicsmagick']
NOTE: Runtime target 'turtlebot3-navigation2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-navigation2', 'nav2-bringup', 'navigation2', 'nav2-map-server', 'UNRESOLVED-graphicsmagick']
NOTE: Runtime target 'turtlebot3' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3', 'turtlebot3-navigation2', 'nav2-bringup', 'navigation2', 'nav2-map-server', 'UNRESOLVED-graphicsmagick']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>