{eloquent} ros-distro-recipe-blacklist.inc: add few more entries detected with bitbake world
* these were shown only in "bitbake world" and not in "bitbake ros-image-world"
  because even when they are generated with superflore they weren't included
  in ros-image-world

* e.g. tracetools-read is generated "manually" with superflore because it's
  on gitlab, not github and superflore doesn't support other git repositories than
  github

ERROR: Nothing RPROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_python3-babeltrace}' (but meta-ros/meta-ros2-eloquent/recipes-ros2/ros2-tracing/tracetools-read_0.2.12-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${ROS_UNRESOLVED_PLATFORM_PKG_python3-babeltrace}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${ROS_UNRESOLVED_PLATFORM_PKG_python3-babeltrace}']
ERROR: Required build target 'tracetools-read' has no buildable providers.
Missing or unbuildable dependency chain was: ['tracetools-read', '${ROS_UNRESOLVED_PLATFORM_PKG_python3-babeltrace}']

* packagegroup-ros-turtlebot3-core, packagegroup-ros-turtlebot3-extended
  are included only in turtlebot3 specific images, not in world image

ERROR: Nothing RPROVIDES 'turtlebot3-bringup' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'turtlebot3-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-bringup']
ERROR: Nothing RPROVIDES 'packagegroup-ros-turtlebot3-core' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-ros-turtlebot3-core'
NOTE: Runtime target 'packagegroup-ros-turtlebot3-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-turtlebot3-core']
ERROR: Nothing RPROVIDES 'hls-lfcd-lds-driver' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'hls-lfcd-lds-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['hls-lfcd-lds-driver']
ERROR: Nothing RPROVIDES 'turtlebot3-msgs' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'turtlebot3-msgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-msgs']

* all dependencies on rviz2, rviz-rendering-tests, rviz-visual-testing-framework,
  ros-testing, ros2test-native were removed from ros-image-world before
  they were blacklisted themselves, so I wasn't seeing these errors in
  ros-image-world

ERROR: Nothing PROVIDES 'launch-testing-ament-cmake' (but meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros-testing_0.2.0-1.bb DEPENDS on or otherwise requires it)
launch-testing-ament-cmake was skipped: Recipe is blacklisted: launch: depends on launch-testing-native->launch-native
ERROR: Nothing PROVIDES 'rviz-common' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-visual-testing-framework_7.0.4-1.bb, meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb DEPENDS on or otherwise requires it)
rviz-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'qtbase' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-visual-testing-framework_7.0.4-1.bb, meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-rendering-tests_7.0.4-1.bb, meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
ERROR: Nothing PROVIDES 'rviz-rendering' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-rendering-tests_7.0.4-1.bb DEPENDS on or otherwise requires it)
rviz-rendering was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'rviz-ogre-vendor' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb DEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'ros-testing-dev' (but meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros-testing_0.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ros-testing-dev'
NOTE: Runtime target 'ros-testing-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-testing-dev']
ERROR: Nothing RPROVIDES 'ros-testing' (but meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros-testing_0.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ros-testing'
NOTE: Runtime target 'ros-testing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-testing']
ERROR: Nothing RPROVIDES 'rviz-visual-testing-framework' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-visual-testing-framework_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-visual-testing-framework'
NOTE: Runtime target 'rviz-visual-testing-framework' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-testing-framework']
ERROR: Nothing RPROVIDES 'rviz-visual-testing-framework-dev' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-visual-testing-framework_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-visual-testing-framework-dev'
NOTE: Runtime target 'rviz-visual-testing-framework-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-testing-framework-dev']
ERROR: Nothing RPROVIDES 'rviz-common' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-visual-testing-framework_7.0.4-1.bb, meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
rviz-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-common']
ERROR: Nothing RPROVIDES 'turtlebot3' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'turtlebot3' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3']
ERROR: Nothing RPROVIDES 'packagegroup-ros-turtlebot3-extended' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-ros-turtlebot3-extended'
NOTE: Runtime target 'packagegroup-ros-turtlebot3-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-turtlebot3-extended']
ERROR: Nothing RPROVIDES 'cartographer-ros' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
cartographer-ros was skipped: Recipe is blacklisted: cartographer: depends on cartographer which does not build in ROS2 yet
NOTE: Runtime target 'cartographer-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-ros']
ERROR: Nothing RPROVIDES 'turtlebot3-applications-msgs' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'turtlebot3-applications-msgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-applications-msgs']
ERROR: Nothing RPROVIDES 'slam-karto' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-extended.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'slam-karto' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slam-karto']
ERROR: Nothing RPROVIDES 'turtlebot3-msgs' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'turtlebot3-msgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-msgs']
ERROR: Nothing RPROVIDES 'packagegroup-ros-turtlebot3-core' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-ros-turtlebot3-core'
NOTE: Runtime target 'packagegroup-ros-turtlebot3-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-turtlebot3-core']
ERROR: Nothing RPROVIDES 'hls-lfcd-lds-driver' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'hls-lfcd-lds-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['hls-lfcd-lds-driver']
ERROR: Nothing RPROVIDES 'turtlebot3-bringup' (but meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'turtlebot3-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-bringup']
ERROR: Nothing RPROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_python3-babeltrace}' (but meta-ros/meta-ros2-eloquent/recipes-ros2/ros2-tracing/tracetools-read_0.2.12-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${ROS_UNRESOLVED_PLATFORM_PKG_python3-babeltrace}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${ROS_UNRESOLVED_PLATFORM_PKG_python3-babeltrace}']
NOTE: Runtime target 'tracetools-read' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tracetools-read', '${ROS_UNRESOLVED_PLATFORM_PKG_python3-babeltrace}']
NOTE: Runtime target 'tracetools-read-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tracetools-read-dev', '${ROS_UNRESOLVED_PLATFORM_PKG_python3-babeltrace}']
ERROR: Nothing RPROVIDES 'rviz-rendering' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-rendering-tests_7.0.4-1.bb RDEPENDS on or otherwise requires it)
rviz-rendering was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-rendering' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-rendering']
ERROR: Nothing RPROVIDES 'rviz-rendering-tests' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-rendering-tests_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-rendering-tests'
NOTE: Runtime target 'rviz-rendering-tests' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-rendering-tests']
ERROR: Nothing RPROVIDES 'rviz-rendering-tests-dev' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-rendering-tests_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-rendering-tests-dev'
NOTE: Runtime target 'rviz-rendering-tests-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-rendering-tests-dev']
ERROR: Nothing RPROVIDES 'rviz-ogre-vendor' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-ogre-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-ogre-vendor']
ERROR: Nothing RPROVIDES 'rviz2' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz2'
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
ERROR: Nothing RPROVIDES 'rviz-default-plugins' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
rviz-default-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-default-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-default-plugins']
ERROR: Nothing RPROVIDES 'rviz2-dev' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz2-dev'
NOTE: Runtime target 'rviz2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2-dev']
ERROR: Nothing RPROVIDES 'launch-testing-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb RDEPENDS on or otherwise requires it)
launch-testing-native was skipped: Recipe is blacklisted: launch: depends on launch-native
NOTE: Runtime target 'launch-testing-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['launch-testing-native']
ERROR: Nothing RPROVIDES 'ros2cli-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ros2cli-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2cli-native']
ERROR: Nothing RPROVIDES 'launch-ros-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'launch-ros-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['launch-ros-native']
ERROR: Nothing RPROVIDES 'launch-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'launch-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['launch-native']
ERROR: Nothing RPROVIDES 'launch-testing-ros-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'launch-testing-ros-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['launch-testing-ros-native']
ERROR: Nothing PROVIDES 'launch-testing-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/launch/launch-testing-ament-cmake_0.9.6-1.bb, virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb DEPENDS on or otherwise requires it)
launch-testing-native was skipped: Recipe is blacklisted: launch: depends on launch-native
ERROR: Nothing PROVIDES 'ros2cli-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  re2c-native
  rsync-native
  ros2test-native
ERROR: Nothing PROVIDES 'launch-ros-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  launch-testing-native
  launch-ros
  cwautomacros-native
ERROR: Nothing PROVIDES 'launch-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  slang-native
  anthy-native
  xau-native
ERROR: Nothing PROVIDES 'launch-testing-ros-native' (but virtual:native:meta-ros/meta-ros2-eloquent/generated-recipes/ros-testing/ros2test_0.2.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  launch-testing-native
  launch-testing-ros
  launch-testing-ament-cmake-native

Signed-off-by: Martin Jansa <martin.jansa@lge.com>