packagegroup-ros2-demos: inherit ros_distro_${ROS_DISTRO}
* to automatically skip the recipe when there isn't any
  ROS 1 distro layer being included (e.g. meta-ros2-foxy)

* fixe:
ERROR: Nothing RPROVIDES 'demo-nodes-cpp' (but /OE/meta-ros/meta-ros2/recipes-core/packagegroups/packagegroup-ros2-demos.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'demo-nodes-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['demo-nodes-cpp']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-ros2-demos', 'demo-nodes-cpp']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>