{noetic} ros-distro.inc: add mapping for python3-pyassimp
* fixes:
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-python3-pyassimp' (but meta-ros/meta-ros1-noetic/generated-recipes/moveit-python/moveit-python_0.4.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-python3-pyassimp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-python3-pyassimp']
NOTE: Runtime target 'moveit-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-python', 'ROS_UNRESOLVED_DEP-python3-pyassimp']
NOTE: Runtime target 'moveit-python-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-python-dev', 'ROS_UNRESOLVED_DEP-python3-pyassimp']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>