{common} tvm: Fix branch and git destsuffix
- github.com/dmlc/dmlc-core: project moved from master to main branch

  ERROR: tvm-0.7.0-r0 do_fetch: Fetcher failure: Unable to find revision 6c401e242c59a1f4c913918246591bb13fd714e7 in branch master even from upstream

- Changed destsuffix=git to  destsuffix=${BB_GIT_DEFAULT_DESTSUFFIX} to fix:

  | .../tvm/0.7.0/sources/tvm-0.7.0/include/tvm/runtime/container.h:27:10: fatal error: dmlc/logging.h: No such file or directory
  |    27 | #include <dmlc/logging.h>
  |       |          ^~~~~~~~~~~~~~~~

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>