{eloquent} resolve dependency issues from new recipes
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-doxygen' (but meta-ros2-eloquent/generated-recipes/dynamic-graph/dynamic-graph_4.2.2-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'dynamic-graph' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dynamic-graph', 'UNRESOLVED-doxygen']
NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'dynamic-graph', 'UNRESOLVED-doxygen']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'dynamic-graph', 'UNRESOLVED-doxygen']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'dynamic-graph', 'UNRESOLVED-doxygen']
ERROR: Nothing PROVIDES 'UNRESOLVED-libboost-system-dev' (but meta-ros2-eloquent/generated-recipes/hls-lfcd-lds-driver/hls-lfcd-lds-driver_2.0.1-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'hls-lfcd-lds-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['hls-lfcd-lds-driver', 'UNRESOLVED-libboost-system-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-sphinx' (but meta-ros2-eloquent/generated-recipes/cartographer/cartographer_1.0.9001-1.bb DEPENDS on or otherwise requires it). Close matches:
  python3-sphinx
NOTE: Runtime target 'cartographer-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-ros', 'cartographer', 'UNRESOLVED-python3-sphinx']
NOTE: Runtime target 'cartographer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer', 'UNRESOLVED-python3-sphinx']
ERROR: Nothing PROVIDES 'UNRESOLVED-libboost-iostreams-dev' (but meta-ros2-eloquent/generated-recipes/cartographer/cartographer_1.0.9001-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'cartographer-ros-dev' (but meta-ros2-eloquent/generated-recipes/cartographer-ros/cartographer-ros_1.0.9001-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cartographer-ros-dev'
NOTE: Runtime target 'cartographer-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-ros-dev']
ERROR: Nothing RPROVIDES 'rqt-gui-py' (but meta-ros2-eloquent/generated-recipes/rqt-robot-monitor/rqt-robot-monitor_1.0.1-1.bb, meta-ros2-eloquent/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-2.bb RDEPENDS on or otherwise requires it)
rqt-gui-py was skipped: Recipe is blacklisted: qt5: depends on qt-gui->qtbase; pyqt5: depends on rqt-gui->python-qt-binding->python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-gui-py' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-py']
NOTE: Runtime target 'rqt-robot-monitor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-robot-monitor', 'rqt-gui-py']
NOTE: Runtime target 'rqt-moveit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-moveit', 'rqt-gui-py']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python3-rospkg-modules' (but meta-ros2-eloquent/generated-recipes/rqt-robot-monitor/rqt-robot-monitor_1.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python3-rospkg-modules' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python3-rospkg-modules']
ERROR: Nothing RPROVIDES 'qt-gui' (but meta-ros2-eloquent/generated-recipes/rqt-robot-monitor/rqt-robot-monitor_1.0.1-1.bb RDEPENDS on or otherwise requires it)
qt-gui was skipped: Recipe is blacklisted: qt5: depends on qtbase; pyqt5: depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'qt-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui']
ERROR: Nothing RPROVIDES 'rqt-py-common' (but meta-ros2-eloquent/generated-recipes/rqt-robot-monitor/rqt-robot-monitor_1.0.1-1.bb, meta-ros2-eloquent/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-2.bb RDEPENDS on or otherwise requires it)
rqt-py-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; pyqt5: depends on python-qt-binding->python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-py-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-py-common']
ERROR: Nothing RPROVIDES 'qt-gui-py-common' (but meta-ros2-eloquent/generated-recipes/rqt-robot-monitor/rqt-robot-monitor_1.0.1-1.bb RDEPENDS on or otherwise requires it)
qt-gui-py-common was skipped: Recipe is blacklisted: qt5: depends on python-qt-bindings->qtbase; pyqt5: depends on python-qt-binding->python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'qt-gui-py-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-py-common']
ERROR: Nothing RPROVIDES 'python-qt-binding' (but meta-ros2-eloquent/generated-recipes/rqt-robot-monitor/rqt-robot-monitor_1.0.1-1.bb, meta-ros2-eloquent/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-2.bb RDEPENDS on or otherwise requires it)
python-qt-binding was skipped: Recipe is blacklisted: qt5: depends on qtbase; pyqt5: depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'python-qt-binding' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-qt-binding']
ERROR: Nothing RPROVIDES 'rqt-gui' (but meta-ros2-eloquent/generated-recipes/rqt-robot-monitor/rqt-robot-monitor_1.0.1-1.bb, meta-ros2-eloquent/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-2.bb RDEPENDS on or otherwise requires it)
rqt-gui was skipped: Recipe is blacklisted: qt5: depends on python-qt-binding->qtbase; pyqt5: depends on python-qt-binding->python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui']
ERROR: Nothing RPROVIDES 'rqt-robot-monitor-dev' (but meta-ros2-eloquent/generated-recipes/rqt-robot-monitor/rqt-robot-monitor_1.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-robot-monitor-dev'
NOTE: Runtime target 'rqt-robot-monitor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-robot-monitor-dev']
ERROR: Nothing RPROVIDES 'dynamic-graph-dev' (but meta-ros2-eloquent/generated-recipes/dynamic-graph/dynamic-graph_4.2.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dynamic-graph-dev'
NOTE: Runtime target 'dynamic-graph-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dynamic-graph-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libboost-system-dev' (but meta-ros2-eloquent/generated-recipes/hls-lfcd-lds-driver/hls-lfcd-lds-driver_2.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libboost-system-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libboost-system-dev']
ERROR: Nothing RPROVIDES 'hls-lfcd-lds-driver-dev' (but meta-ros2-eloquent/generated-recipes/hls-lfcd-lds-driver/hls-lfcd-lds-driver_2.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'hls-lfcd-lds-driver-dev'
NOTE: Runtime target 'hls-lfcd-lds-driver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['hls-lfcd-lds-driver-dev']
ERROR: Nothing RPROVIDES 'rqt-moveit-dev' (but meta-ros2-eloquent/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-moveit-dev'
NOTE: Runtime target 'rqt-moveit-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-moveit-dev']
ERROR: Nothing RPROVIDES 'rqt-topic' (but meta-ros2-eloquent/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-2.bb RDEPENDS on or otherwise requires it)
rqt-topic was skipped: Recipe is blacklisted: qt5: depends on python-qt-bindings->qtbase; pyqt5: depends on python-qt-binding->python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-topic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-topic']
ERROR: Nothing RPROVIDES 'cartographer-dev' (but meta-ros2-eloquent/generated-recipes/cartographer/cartographer_1.0.9001-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cartographer-dev'
NOTE: Runtime target 'cartographer-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libboost-iostreams-dev' (but meta-ros2-eloquent/generated-recipes/cartographer/cartographer_1.0.9001-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libboost-iostreams-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libboost-iostreams-dev']
Signed-off-by: Martin Jansa <martin.jansa@lge.com>