{melodic} ros-distro.inc: add mapping for libgeos++-dev, libfltk-dev, libjsoncpp-dev, libqt5*, qt*, binutils, libfftw3
* libqt5multimedia5-plugins, qtmultimedia5-dev, qtdeclarative5-dev
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libgeos++-dev' (but generated-recipes/marti-common/swri-transform-util_2.11.0-1.bb, generated-recipes/marti-common/swri-geometry-util_2.11.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'swri-transform-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'tile-map' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tile-map', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'multires-image' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multires-image', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'mapviz-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-plugins', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'swri-route-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-route-util', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'mapviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz', 'swri-transform-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'swri-geometry-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-geometry-util', 'UNRESOLVED-libgeos++-dev']
NOTE: Runtime target 'swri-image-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-image-util', 'swri-geometry-util', 'UNRESOLVED-libgeos++-dev']

ERROR: Nothing PROVIDES 'UNRESOLVED-libfltk-dev' (but generated-recipes/stage/stage_4.3.0.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'stage' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['stage', 'UNRESOLVED-libfltk-dev']
NOTE: Runtime target 'safe-teleop-stage' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['safe-teleop-stage', 'stage', 'UNRESOLVED-libfltk-dev']
NOTE: Runtime target 'roomba-stage' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roomba-stage', 'stage-ros', 'stage', 'UNRESOLVED-libfltk-dev']
NOTE: Runtime target 'navigation-tutorials' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation-tutorials', 'roomba-stage', 'stage-ros', 'stage', 'UNRESOLVED-libfltk-dev']
NOTE: Runtime target 'teb-local-planner-tutorials' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['teb-local-planner-tutorials', 'stage-ros', 'stage', 'UNRESOLVED-libfltk-dev']
NOTE: Runtime target 'navigation-stage' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation-stage', 'stage-ros', 'stage', 'UNRESOLVED-libfltk-dev']
NOTE: Runtime target 'stage-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['stage-ros', 'stage', 'UNRESOLVED-libfltk-dev']

ERROR: Nothing PROVIDES 'UNRESOLVED-libjsoncpp-dev' (but generated-recipes/fkie-potree-rviz-plugin/fkie-potree-rviz-plugin_1.0.0.bb, generated-recipes/mapviz/tile-map_1.2.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'fkie-potree-rviz-plugin' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fkie-potree-rviz-plugin', 'UNRESOLVED-libjsoncpp-dev']

ERROR: Nothing PROVIDES 'UNRESOLVED-libqt5multimedia5-plugins' (but generated-recipes/plotjuggler/plotjuggler_2.5.0-1.bb, generated-recipes/kvh-geo-fog-3d/kvh-geo-fog-3d-rviz_1.3.3-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'plotjuggler' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plotjuggler', 'UNRESOLVED-libqt5multimedia5-plugins']
NOTE: Runtime target 'kvh-geo-fog-3d-rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['kvh-geo-fog-3d-rviz', 'UNRESOLVED-libqt5multimedia5-plugins']
NOTE: Runtime target 'kvh-geo-fog-3d' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['kvh-geo-fog-3d', 'kvh-geo-fog-3d-rviz', 'UNRESOLVED-libqt5multimedia5-plugins']

ERROR: Nothing PROVIDES 'UNRESOLVED-qtmultimedia5-dev' (but generated-recipes/plotjuggler/plotjuggler_2.5.0-1.bb, generated-recipes/kvh-geo-fog-3d/kvh-geo-fog-3d-rviz_1.3.3-1.bb DEPENDS on or otherwise requires it)

ERROR: Nothing PROVIDES 'UNRESOLVED-qtdeclarative5-dev' (but generated-recipes/plotjuggler/plotjuggler_2.5.0-1.bb, generated-recipes/kvh-geo-fog-3d/kvh-geo-fog-3d-rviz_1.3.3-1.bb DEPENDS on or otherwise requires it)

ERROR: Nothing PROVIDES 'UNRESOLVED-binutils' (but generated-recipes/plotjuggler/plotjuggler_2.5.0-1.bb DEPENDS on or otherwise requires it)

ERROR: Nothing PROVIDES 'UNRESOLVED-libfftw3' (but generated-recipes/uwsim-osgocean/uwsim-osgocean_1.0.4-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'uwsim-osgocean' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uwsim-osgocean', 'UNRESOLVED-libfftw3']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'uwsim-osgocean', 'UNRESOLVED-libfftw3']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'uwsim-osgocean', 'UNRESOLVED-libfftw3']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'uwsim-osgocean', 'UNRESOLVED-libfftw3']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>