{melodic} resolve dependency issues in new recipes
* fixes:
ERROR: Nothing PROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb DEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'rviz-animated-view-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-animated-view-controller', 'rviz']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'rviz-animated-view-controller', 'rviz']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'rviz-animated-view-controller', 'rviz']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'rviz-animated-view-controller', 'rviz']
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
ERROR: Nothing PROVIDES 'mesa' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb DEPENDS on or otherwise requires it)
mesa was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'gazebo-rosdev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/franka-ros/franka-gazebo_0.8.1-2.bb DEPENDS on or otherwise requires it)
gazebo-rosdev was skipped: Recipe is blacklisted: Depends on gazebo which is not available
NOTE: Runtime target 'franka-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['franka-gazebo', 'gazebo-rosdev']
ERROR: Nothing PROVIDES 'franka-example-controllers' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/franka-ros/franka-gazebo_0.8.1-2.bb DEPENDS on or otherwise requires it)
franka-example-controllers was skipped: Recipe is blacklisted: qt5: Requires panda-moveit-config->moveit-ros-visualization->qtbase which requires meta-qt5 to be included; ogre: depends on panda-moveit-config->moveit-ros-visualization->ogre which is not available
ERROR: Nothing PROVIDES 'gazebo-ros-control' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/franka-ros/franka-gazebo_0.8.1-2.bb DEPENDS on or otherwise requires it)
gazebo-ros-control was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
ERROR: Nothing RPROVIDES 'rviz-animated-view-controller-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-animated-view-controller-dev'
NOTE: Runtime target 'rviz-animated-view-controller-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-animated-view-controller-dev']
ERROR: Nothing RPROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb RDEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz']
ERROR: Nothing RPROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtbase' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtbase']
ERROR: Nothing RPROVIDES 'mesa' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb RDEPENDS on or otherwise requires it)
mesa was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'mesa' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mesa']
ERROR: Nothing RPROVIDES 'franka-gazebo-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/franka-ros/franka-gazebo_0.8.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'franka-gazebo-dev'
NOTE: Runtime target 'franka-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['franka-gazebo-dev']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/franka-ros/franka-gazebo_0.8.1-2.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
ERROR: Nothing RPROVIDES 'franka-example-controllers' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/franka-ros/franka-gazebo_0.8.1-2.bb RDEPENDS on or otherwise requires it)
franka-example-controllers was skipped: Recipe is blacklisted: qt5: Requires panda-moveit-config->moveit-ros-visualization->qtbase which requires meta-qt5 to be included; ogre: depends on panda-moveit-config->moveit-ros-visualization->ogre which is not available
NOTE: Runtime target 'franka-example-controllers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['franka-example-controllers']
ERROR: Nothing RPROVIDES 'gazebo-ros-control' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/franka-ros/franka-gazebo_0.8.1-2.bb RDEPENDS on or otherwise requires it)
gazebo-ros-control was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-control']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>