{dashing} swri-prefix-tools: replace python-psutil with python3-psutil
* python(2) is blacklisted in ROS2 distributions
* fixes:
ERROR: Nothing PROVIDES 'python' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/openembedded-core/meta/recipes-devtools/python-numpy/python-numpy_1.14.5.bb, /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-openembedded/meta-python/recipes-devtools/python/python-psutil_5.4.6.bb, /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros-common/recipes-devtools/python/python-sphinx_1.6.7.bb DEPENDS on or otherwise requires it)
python was skipped: Recipe is blacklisted: ROS 2 is Python 3 only
NOTE: Runtime target 'python-psutil' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-psutil', 'python']
NOTE: Runtime target 'swri-prefix-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-prefix-tools', 'python-psutil', 'python']
NOTE: Runtime target 'swri-prefix-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-prefix-tools-dev', 'python-psutil', 'python']