{rolling} ublox-ubx-interfaces: Add missing DEPENDS
Add rosidl build tools for do_configure.  Add rcl-interfaces to resolve a missing build
dependency:

TOPDIR/tmp-glibc/work/core2-64-oe-linux/ublox-ubx-interfaces/0.3.5-4-r0/recipe-sysroot-native/usr/include/python3.9/Python.h:44:10: fatal error: crypt.h: No such file or directory

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>