{melodic} points-preprocessor: restrict with qt5 in ROS_WORLD_SKIP_GROUPS
* fixes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/core-perception/points-preprocessor_1.14.9-1.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
NOTE: Runtime target 'points-preprocessor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['points-preprocessor', 'qtbase']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'points-preprocessor', 'qtbase']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'points-preprocessor', 'qtbase']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'points-preprocessor', 'qtbase']
ERROR: Nothing RPROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/core-perception/points-preprocessor_1.14.9-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtbase' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtbase']
ERROR: Nothing RPROVIDES 'points-preprocessor-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/core-perception/points-preprocessor_1.14.9-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'points-preprocessor-dev'
NOTE: Runtime target 'points-preprocessor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['points-preprocessor-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>