ros-python2-recipe-blacklist.inc: unblacklist mongodb
* it uses python3 since zeus with 4.2 version introduced in:
  https://git.openembedded.org/meta-openembedded/commit/?id=1849429a791457250236778793c36a12f0df3194

* fixes:
  ERROR: Nothing PROVIDES 'mongodb' (but /meta-ros2-foxy/generated-recipes/warehouse-ros-mongo/warehouse-ros-mongo_2.0.0-1.bb DEPENDS on or otherwise requires it)
  mongodb was skipped: Recipe is blacklisted: Depends on blacklisted python2
  NOTE: Runtime target 'warehouse-ros-mongo' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['warehouse-ros-mongo', 'mongodb']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>