{rolling} webots-ros2-control: backport some changes to make it compatible with hardware-interfaces version now in rolling
* fixes:
FAILED: CMakeFiles/webots_ros2_control_system.dir/src/Ros2ControlSystem.cpp.o
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DDEFAULT_RMW_IMPLEMENTATION=rmw_cyclonedds_cpp -DPLUGINLIB__DISABLE_BOOST_FUNCTIONS -Dwebots_ros2_control_system_EXPORTS -I/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot/usr/include/webots/cpp -I/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/include -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0=/usr/src/debug/webots-ros2-control/1.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0=/usr/src/debug/webots-ros2-control/1.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot -fPIC   -Wall -Wextra -Wpedantic -std=gnu++17 -MD -MT CMakeFiles/webots_ros2_control_system.dir/src/Ros2ControlSystem.cpp.o -MF CMakeFiles/webots_ros2_control_system.dir/src/Ros2ControlSystem.cpp.o.d -o CMakeFiles/webots_ros2_control_system.dir/src/Ros2ControlSystem.cpp.o -c /jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/src/Ros2ControlSystem.cpp
In file included from /jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/src/Ros2ControlSystem.cpp:15:
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/include/webots_ros2_control/Ros2ControlSystem.hpp:22:10: fatal error: hardware_interface/base_interface.hpp: No such file or directory
   22 | #include "hardware_interface/base_interface.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

and

FAILED: CMakeFiles/webots_ros2_control_system.dir/src/Ros2ControlSystem.cpp.o
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DDEFAULT_RMW_IMPLEMENTATION=rmw_cyclonedds_cpp -DPLUGINLIB__DISABLE_BOOST_FUNCTIONS -Dwebots_ros2_control_system_EXPORTS -I/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot/usr/include/webots/cpp -I/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/include -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0=/usr/src/debug/webots-ros2-control/1.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0=/usr/src/debug/webots-ros2-control/1.1.1-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot -fPIC   -Wall -Wextra -Wpedantic -std=gnu++17 -MD -MT CMakeFiles/webots_ros2_control_system.dir/src/Ros2ControlSystem.cpp.o -MF CMakeFiles/webots_ros2_control_system.dir/src/Ros2ControlSystem.cpp.o.d -o CMakeFiles/webots_ros2_control_system.dir/src/Ros2ControlSystem.cpp.o -c /jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/src/Ros2ControlSystem.cpp
In file included from /jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/include/webots_ros2_control/Ros2ControlSystem.hpp:30,
                 from /jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/src/Ros2ControlSystem.cpp:15:
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/include/webots_ros2_control/Ros2ControlSystemInterface.hpp:32:78: error: expected template-name before '<' token
   32 |   class Ros2ControlSystemInterface : public hardware_interface::BaseInterface<hardware_interface::SystemInterface>
      |                                                                              ^
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/include/webots_ros2_control/Ros2ControlSystemInterface.hpp:32:78: error: expected '{' before '<' token
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/include/webots_ros2_control/Ros2ControlSystemInterface.hpp:32:78: error: expected unqualified-id before '<' token
In file included from /jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/src/Ros2ControlSystem.cpp:15:
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/include/webots_ros2_control/Ros2ControlSystem.hpp:51:36: error: invalid use of incomplete type 'class webots_ros2_control::Ros2ControlSystemInterface'
   51 |   class Ros2ControlSystem : public Ros2ControlSystemInterface
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~

and don't import all the changes, because that would cause folling error, so undo the change from:
https://github.com/cyberbotics/webots_ros2/pull/315/commits/107325369c0a59371203a8faae5b2b0fa4cab398#diff-120507ddaf4b6e842b1cbff1b3fa073dceebe266221e033d26dc9d3157d2ac0f

FAILED: CMakeFiles/webots_ros2_control.dir/src/Ros2Control.cpp.o
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DDEFAULT_RMW_IMPLEMENTATION=rmw_cyclonedds_cpp -DPLUGINLIB__DISABLE_BOOST_FUNCTIONS -Dwebots_ros2_control_Ep
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/src/Ros2Control.cpp: In member function 'virtual void webots_ros2_control::Ros2Control::init(webots_ros2_driver::WebotsNode*, std::unordered_map<std::__cxx11::basic_string:
/jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/work/core2-64-oe-linux/webots-ros2-control/1.1.1-1-r0/git/src/Ros2Control.cpp:83:86: error: no matching function for call to 'hardware_interface::ResourceManager::import_component(std::remove_reference<std::unique_ptr<webots_ros2'
   83 |         resourceManager->import_component(std::move(webotsSystem), controlHardware[i]);
      |

Signed-off-by: Martin Jansa <martin.jansa@lge.com>