{melodic} mpc-local-planner: blacklist unconditionally
* fixes:
ERROR: Nothing PROVIDES 'control-box-rst' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mpc-local-planner/mpc-local-planner_0.0.2-1.bb DEPENDS on or otherwise requires it)
control-box-rst was skipped: Recipe is blacklisted: Depends on unavailable UNRESOLVED-coinor-libipopt-dev
:
Signed-off-by: Martin Jansa <martin.jansa@lge.com>