{humble}: Add compressed-depth-image-transport bbappend file
Fix format-security build failure since __VA_ARGS__ is used.

compressed-depth-image-transport/2.5.1-1-r0/recipe-sysroot/usr/
include/rcutils/rcutils/logging_macros.h:79:18: error: format not
a string literal and no format arguments [-Werror=format-security]
    rcutils_log(&__rcutils_logging_location, severity, name, __VA_ARGS__);

Signed-off-by: zhengjia zhu <quic_zhezhu@quicinc.com>
Signed-off-by: Jiaxing Shi <quic_jiaxshi@quicinc.com>