{dashing} cartographer: remove python-sphinx dependency
* it's python-sphinx not ${PYTHON_PN}-sphinx (python3-sphinx) in the
  generated recipe

* fixes:
ERROR: Nothing PROVIDES 'python' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/openembedded-core/meta/recipes-devtools/python-numpy/python-numpy_1.14.5.bb, /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-openembedded/meta-python/recipes-devtools/python/python-psutil_5.4.6.bb, /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros-common/recipes-devtools/python/python-sphinx_1.6.7.bb DEPENDS on or otherwise requires it)
python was skipped: Recipe is blacklisted: ROS 2 is Python 3 only

NOTE: Runtime target 'cartographer-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-ros', 'cartographer', 'python-sphinx', 'python']
NOTE: Runtime target 'turtlebot3-cartographer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-cartographer', 'cartographer-ros', 'cartographer', 'python-sphinx', 'python']
NOTE: Runtime target 'turtlebot3-cartographer-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-cartographer-dev', 'cartographer-ros', 'cartographer', 'python-sphinx', 'python']
NOTE: Runtime target 'cartographer-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-ros-dev', 'cartographer', 'python-sphinx', 'python']
NOTE: Runtime target 'cartographer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer', 'python-sphinx', 'python']
NOTE: Runtime target 'cartographer-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cartographer-dev', 'python-sphinx', 'python']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>