meta-ros-python2: remove python-native bbappend
* setting native RPROVIDES is no longer needed and even causes new QA error
  which leads to parsing error:
  ERROR: ros1-melodic-hardknott/meta-python2/recipes-devtools/python/python-native_2.7.18.bb: QA Issue: ros1-melodic-hardknott/meta-python2/recipes-devtools/python/python-native_2.7.18.bb: Variable RPROVIDES is set as not being package specific, please fix this. [pkgvarcheck]
  ERROR: ros1-melodic-hardknott/meta-python2/recipes-devtools/python/python-native_2.7.18.bb: Fatal QA errors found, failing task.
  ERROR: Failed to parse recipe: ros1-melodic-hardknott/meta-python2/recipes-devtools/python/python-native_2.7.18.bb

Signed-off-by: Martin Jansa <martin.jansa@lge.com>