{galactic} domain-bridge: remove runtime dependency on zstd-vendor and inherit pokgconfig
* fixes:
ERROR: webos-image-ros-world-1.0-r3 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build/ros/webos-galactic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/webos-image-ros-world/1.0-r3/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/webos-galactic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/webos-image-ros-world/1.0-r3/opkg.conf -t /jenkins/mjansa/build/ros/webos-galactic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/webos-image-ros-world/1.0-r3/temp/ipktemp/ -o /jenkins/mjansa/build/ros/webos-galactic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/webos-image-ros-world/1.0-r3/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends update-rc.d install bluez-firmware-rpidistro-bcm4345c0-hcd kernel-module-i2c-dev kernel-module-spi-bcm2835 kernel-module-pidev kernel-modules linux-firmware-rpidistro-bcm43455 opkg os-release ostree ostree-initramfs ostree-kernel packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-ros-world packagegroup-webos-extended run-postinsts udev-rules-rpi' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-ros-world-1.0-r0.raspberrypi4 requires packagegroup-ros-world-galactic, but none of the providers can be installed
 *   - package packagegroup-ros-world-galactic-1.0-r0.raspberrypi4 requires domain-bridge, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides zstd-vendor needed by domain-bridge-0.4.0-1-r0.raspberrypi4
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

Signed-off-by: Martin Jansa <martin.jansa@lge.com>