{melodic} packagegroup-ros-world-melodic: remove runtime dependency on audio-common, audio-capture, audio-play, sound-play without commerical in LICENSE_FLAGS_WHITELIST
* fixes:
ERROR: Nothing PROVIDES 'gstreamer1.0-plugins-ugly' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb DEPENDS on or otherwise requires it)
gstreamer1.0-plugins-ugly was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'audio-capture' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-capture', 'gstreamer1.0-plugins-ugly']
NOTE: Runtime target 'audio-play' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-play', 'gstreamer1.0-plugins-ugly']

ERROR: Nothing RPROVIDES 'gstreamer1.0-plugins-ugly' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb RDEPENDS on or otherwise requires it)
gstreamer1.0-plugins-ugly was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'gstreamer1.0-plugins-ugly' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-ugly']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>