{dashing} ros-distro.inc: Set ROS_UNRESOLVED_PLATFORM_PKG_proj to "proj"
* Fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-proj' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/marti-common/swri-transform-util_3.0.3-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'swri-transform-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-transform-util', 'UNRESOLVED-proj']
NOTE: Runtime target 'swri-route-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-route-util', 'swri-transform-util', 'UNRESOLVED-proj']

ERROR: Nothing RPROVIDES 'UNRESOLVED-proj' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/marti-common/swri-transform-util_3.0.3-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-proj' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-proj']
ERROR: Nothing RPROVIDES 'swri-transform-util-dev' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/marti-common/swri-transform-util_3.0.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'swri-transform-util-dev'
NOTE: Runtime target 'swri-transform-util-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['swri-transform-util-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>