{melodic} resolve dependency issues in new recipes
* fixes:
NOTE: Multiple providers are available for runtime fuse-doc (fuse-doc, fuse)
Consider defining a PREFERRED_RPROVIDER entry to match fuse-doc
ERROR: Nothing PROVIDES 'gazebo-ros-control' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/copernicus/copernicus-control_1.1.0-1.bb DEPENDS on or otherwise requires it)
gazebo-ros-control was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'copernicus-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['copernicus-control', 'gazebo-ros-control']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'copernicus-control', 'gazebo-ros-control']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'copernicus-control', 'gazebo-ros-control']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'copernicus-control', 'gazebo-ros-control']
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-kakasi' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/aques-talk_2.1.24-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'aques-talk' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['aques-talk', 'ROS_UNRESOLVED_DEP-kakasi']
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-nkf' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/aques-talk_2.1.24-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'sound-play' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/aques-talk_2.1.24-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/google-cloud-texttospeech_2.1.24-1.bb DEPENDS on or otherwise requires it)
sound-play was skipped: Recipe is blacklisted: gst-ugly: Depends on gstreamer1.0-plugins-ugly which requires commercial license; python-gi: Depends on unavailable python-gi
NOTE: Runtime target 'google-cloud-texttospeech' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['google-cloud-texttospeech', 'sound-play']
ERROR: Nothing PROVIDES 'moveit-ros-planning-interface' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb DEPENDS on or otherwise requires it)
moveit-ros-planning-interface was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'webots-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros', 'moveit-ros-planning-interface']
ERROR: Nothing PROVIDES 'ros-controllers' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb DEPENDS on or otherwise requires it)
ros-controllers was skipped: Recipe is blacklisted: Requires rqt-joint-trajectory-controller->rqt-gui-py->qt-gui->qtbase which requires meta-qt5 to be included and rqt-joint-trajectory-controller->rqt-gui-py->qt-gui->python-pyqt5 which requires pyqt5
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/fuse/fuse-viz_0.4.2-1.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
NOTE: Runtime target 'fuse-viz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse-viz', 'qtbase']
NOTE: Runtime target 'fuse' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse', 'fuse-viz', 'qtbase']
ERROR: Nothing PROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/fuse/fuse-viz_0.4.2-1.bb DEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-python-google-cloud-texttospeech-pip' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/google-cloud-texttospeech_2.1.24-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'fuse-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/fuse/fuse_0.4.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'fuse-dev'
NOTE: Runtime target 'fuse-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse-dev']
ERROR: Nothing RPROVIDES 'copernicus-control-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/copernicus/copernicus-control_1.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'copernicus-control-dev'
NOTE: Runtime target 'copernicus-control-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['copernicus-control-dev']
ERROR: Nothing RPROVIDES 'gazebo-ros-control' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/copernicus/copernicus-control_1.1.0-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros-control was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-control']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-kakasi' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/aques-talk_2.1.24-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-kakasi' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-kakasi']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-nkf' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/aques-talk_2.1.24-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-nkf' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-nkf']
ERROR: Nothing RPROVIDES 'sound-play' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/aques-talk_2.1.24-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/google-cloud-texttospeech_2.1.24-1.bb RDEPENDS on or otherwise requires it)
sound-play was skipped: Recipe is blacklisted: gst-ugly: Depends on gstreamer1.0-plugins-ugly which requires commercial license; python-gi: Depends on unavailable python-gi
NOTE: Runtime target 'sound-play' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sound-play']
ERROR: Nothing RPROVIDES 'aques-talk-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/aques-talk_2.1.24-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'aques-talk-dev'
NOTE: Runtime target 'aques-talk-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['aques-talk-dev']
ERROR: Nothing RPROVIDES 'ros-controllers' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb RDEPENDS on or otherwise requires it)
ros-controllers was skipped: Recipe is blacklisted: Requires rqt-joint-trajectory-controller->rqt-gui-py->qt-gui->qtbase which requires meta-qt5 to be included and rqt-joint-trajectory-controller->rqt-gui-py->qt-gui->python-pyqt5 which requires pyqt5
NOTE: Runtime target 'ros-controllers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-controllers']
ERROR: Nothing RPROVIDES 'webots-ros-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'webots-ros-dev'
NOTE: Runtime target 'webots-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webots-ros-dev']
ERROR: Nothing RPROVIDES 'moveit-ros-planning-interface' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/webots-ros/webots-ros_4.1.0-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-planning-interface was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-ros-planning-interface' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-planning-interface']
ERROR: Nothing RPROVIDES 'fuse-viz-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/fuse/fuse-viz_0.4.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'fuse-viz-dev'
NOTE: Runtime target 'fuse-viz-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse-viz-dev']
ERROR: Nothing RPROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/fuse/fuse-viz_0.4.2-1.bb RDEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-python-google-cloud-texttospeech-pip' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/google-cloud-texttospeech_2.1.24-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-python-google-cloud-texttospeech-pip' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-python-google-cloud-texttospeech-pip']
ERROR: Nothing RPROVIDES 'google-cloud-texttospeech-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/jsk-3rdparty/google-cloud-texttospeech_2.1.24-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'google-cloud-texttospeech-dev'
NOTE: Runtime target 'google-cloud-texttospeech-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['google-cloud-texttospeech-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>