amazon-kinesis-video-streams-producer-sdk-cpp: shorten the name to amazon-kvs-sdk-cpp
* kvs-sdk name is used in kinesis ROS component, use that

* current name is too long for some filesystems when it's
  also using some long PACKAGE_ARCH like bellow:

ERROR: amazon-kinesis-video-streams-producer-sdk-cpp-kinesis-video-native-build-1.7.8-r0 do_generate_toolchain_file: Build of do_generate_toolchain_file failed
ERROR: amazon-kinesis-video-streams-producer-sdk-cpp-kinesis-video-native-build-1.7.8-r0 do_generate_toolchain_file: Traceback (most recent call last):
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/bitbake/lib/bb/build.py", line 631, in exec_task
    return _exec_task(fn, task, d, quieterr)
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/bitbake/lib/bb/build.py", line 605, in _exec_task
    event.fire(TaskSucceeded(task, logfn, localdata), localdata)
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/bitbake/lib/bb/event.py", line 215, in fire
    fire_class_handlers(event, d)
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/bitbake/lib/bb/event.py", line 124, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/bitbake/lib/bb/event.py", line 96, in execute_handler
    ret = handler(event)
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/openembedded-core/meta/classes/sstate.bbclass", line 1083, in sstate_eventhandler
    bb.siggen.dump_this_task(sstatepkg + '_' + taskname + ".tgz" ".siginfo", d)
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/bitbake/lib/bb/siggen.py", line 354, in dump_this_task
    bb.parse.siggen.dump_sigtask(fn, task, outfile, "customfile:" + referencestamp)
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/openembedded-core/meta/lib/oe/sstatesig.py", line 198, in dump_sigtask
    super(bb.siggen.SignatureGeneratorBasicHash, self).dump_sigtask(fn, task, stampbase, runtime)
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/bitbake/lib/bb/siggen.py", line 305, in dump_sigtask
    raise err
  File "/jenkins/mjansa/build-ros/ros2-dashing-warrior/bitbake/lib/bb/siggen.py", line 299, in dump_sigtask
    os.rename(tmpfile, sigfile)
OSError: [Errno 36] File name too long: '/jenkins/mjansa/build-ros/ros2-dashing-warrior/sstate-cache/51/sigtask.i58j3rp0' -> '/jenkins/mjansa/build-ros/ros2-dashing-warrior/sstate-cache/51/sstate:amazon-kinesis-video-streams-producer-sdk-cpp-kinesis-video-native-build:cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi:1.7.8:r0:cortexa7t2hf-neon-vfpv4:3:51b3f44894127997b80be8495c7a206894983d1d8ecaf411624ab49e99e77fe8_generate_toolchain_file.tgz.siginfo'

ERROR: Task (/jenkins/mjansa/build-ros/ros2-dashing-warrior/meta-ros/meta-ros-common/recipes-devtools/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp-kinesis-video-native-build_1.7.8.bb:do_generate_toolchain_file) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>