{melodic} rc-genicam-api: skip ldflags QA for aarch64
* fixes:
ERROR: rc-genicam-api-2.3.4-1-r0 do_package_qa: QA Issue: File /usr/lib/libNodeMapData_gcc48_v3_1.so in package rc-genicam-api doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/lib/libGenApi_gcc48_v3_1.so in package rc-genicam-api doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/lib/libLog_gcc48_v3_1.so in package rc-genicam-api doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/lib/liblog4cpp_gcc48_v3_1.so in package rc-genicam-api doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/lib/libGCBase_gcc48_v3_1.so in package rc-genicam-api doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/lib/libMathParser_gcc48_v3_1.so in package rc-genicam-api doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/lib/libXmlParser_gcc48_v3_1.so in package rc-genicam-api doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]

* for some reason it's only aarch64 prebuilt libraries which are missing it:
mjansa@kangaroo-build:/jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/cortexa72-oe-linux/rc-genicam-api/2.3.5-1-r0/git$ for i in genicam/bin/Linux64_ARM/lib*; do echo $i; ../recipe-sysroot-native/usr/bin/aarch64-oe-linux/aarch64-oe-linux-objdump
 -p $i | grep GNU_HASH; done
genicam/bin/Linux64_ARM/libGCBase_gcc48_v3_1.so
genicam/bin/Linux64_ARM/libGenApi_gcc48_v3_1.so
genicam/bin/Linux64_ARM/libLog_gcc48_v3_1.so
genicam/bin/Linux64_ARM/libMathParser_gcc48_v3_1.so
genicam/bin/Linux64_ARM/libNodeMapData_gcc48_v3_1.so
genicam/bin/Linux64_ARM/libXmlParser_gcc48_v3_1.so
genicam/bin/Linux64_ARM/liblog4cpp_gcc48_v3_1.so

mjansa@kangaroo-build:/jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/cortexa72-oe-linux/rc-genicam-api/2.3.5-1-r0/git$ for i in genicam/bin/Linux32_ARMhf/lib*; do echo $i; ../recipe-sysroot-native/usr/bin/aarch64-oe-linux/aarch64-oe-linux-objdu
mp -p $i | grep GNU_HASH; done
genicam/bin/Linux32_ARMhf/libGCBase_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libGenApi_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libLog_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libMathParser_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libNodeMapData_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libXmlParser_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/liblog4cpp_gcc46_v3_1.so
  GNU_HASH             0x00000138

mjansa@kangaroo-build:/jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/cortexa72-oe-linux/rc-genicam-api/2.3.5-1-r0/git$ for i in genicam/bin/Linux32_ARMhf/lib*; do echo $i; ../recipe-sysroot-native/usr/bin/aarch64-oe-linux/aarch64-oe-linux-objdu
mp -p $i | grep GNU_HASH; done
genicam/bin/Linux32_ARMhf/libGCBase_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libGenApi_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libLog_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libMathParser_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libNodeMapData_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/libXmlParser_gcc46_v3_1.so
  GNU_HASH             0x00000138
genicam/bin/Linux32_ARMhf/liblog4cpp_gcc46_v3_1.so
  GNU_HASH             0x00000138
mjansa@kangaroo-build:/jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/cortexa72-oe-linux/rc-genicam-api/2.3.5-1-r0/git$ for i in genicam/bin/Linux32_i86/lib*; do echo $i; ../recipe-sysroot-native/usr/bin/aarch64-oe-linux/aarch64-oe-linux-objdump -p $i | grep GNU_HASH; done
genicam/bin/Linux32_i86/libGCBase_gcc42_v3_1.so
  GNU_HASH             0x00000b88
genicam/bin/Linux32_i86/libGenApi_gcc42_v3_1.so
  GNU_HASH             0x0000aa24
genicam/bin/Linux32_i86/libLog_gcc42_v3_1.so
  GNU_HASH             0x0000054c
genicam/bin/Linux32_i86/libMathParser_gcc42_v3_1.so
  GNU_HASH             0x0000048c
genicam/bin/Linux32_i86/libNodeMapData_gcc42_v3_1.so
  GNU_HASH             0x00000778
genicam/bin/Linux32_i86/libXmlParser_gcc42_v3_1.so
  GNU_HASH             0x00002f34
genicam/bin/Linux32_i86/liblog4cpp_gcc42_v3_1.so
  GNU_HASH             0x0000154c

Signed-off-by: Martin Jansa <martin.jansa@lge.com>