{rolling} resolve dependency issues in new recipes
* fixes:
ERROR: Nothing PROVIDES 'plotjuggler' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.5.0-1.bb DEPENDS on or otherwise requires it)
plotjuggler was skipped: Recipe is blacklisted: qt5: Requires qtbase which requires meta-qt5 to be included; qt5-widgets: needs widgets enabled in qtbase PACKAGECONFIG; opengl: requires opengl to be enabled in qtbase
NOTE: Runtime target 'plotjuggler-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plotjuggler-ros', 'plotjuggler']
NOTE: Runtime target 'packagegroup-ros-world-rolling' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-rolling', 'plotjuggler-ros', 'plotjuggler']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'plotjuggler-ros', 'plotjuggler']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'plotjuggler-ros', 'plotjuggler']
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-libwebsocketpp-dev' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-schedule_1.2.0-2.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'rmf-visualization-schedule' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-visualization-schedule', 'ROS_UNRESOLVED_DEP-libwebsocketpp-dev']
NOTE: Runtime target 'rmf-visualization' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-visualization', 'rmf-visualization-schedule', 'ROS_UNRESOLVED_DEP-libwebsocketpp-dev']
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-nlohmann-json-dev' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-schedule_1.2.0-2.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'rviz-common' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-rviz2-plugins_1.2.0-2.bb DEPENDS on or otherwise requires it)
rviz-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rmf-visualization-rviz2-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-visualization-rviz2-plugins', 'rviz-common']
ERROR: Nothing PROVIDES 'rviz-default-plugins' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-rviz2-plugins_1.2.0-2.bb DEPENDS on or otherwise requires it)
rviz-default-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'rviz-rendering' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-rviz2-plugins_1.2.0-2.bb DEPENDS on or otherwise requires it)
rviz-rendering was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'turtlesim' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/geometry-tutorials/turtle-tf2-py_0.3.1-1.bb RDEPENDS on or otherwise requires it)
turtlesim was skipped: Recipe is blacklisted: qt5: depends on qtbase; qt5-widgets: needs widgets enabled in qtbase PACKAGECONFIG
NOTE: Runtime target 'turtlesim' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlesim']
NOTE: Runtime target 'turtle-tf2-py' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtle-tf2-py', 'turtlesim']
NOTE: Runtime target 'turtle-tf2-py-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtle-tf2-py-dev', 'turtlesim']
ERROR: Nothing RPROVIDES 'plotjuggler' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.5.0-1.bb RDEPENDS on or otherwise requires it)
plotjuggler was skipped: Recipe is blacklisted: qt5: Requires qtbase which requires meta-qt5 to be included; qt5-widgets: needs widgets enabled in qtbase PACKAGECONFIG; opengl: requires opengl to be enabled in qtbase
NOTE: Runtime target 'plotjuggler' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plotjuggler']
ERROR: Nothing RPROVIDES 'plotjuggler-ros-dev' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/plotjuggler-ros/plotjuggler-ros_1.5.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'plotjuggler-ros-dev'
NOTE: Runtime target 'plotjuggler-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plotjuggler-ros-dev']
ERROR: Nothing RPROVIDES 'rmf-visualization-schedule-dev' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-schedule_1.2.0-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rmf-visualization-schedule-dev'
NOTE: Runtime target 'rmf-visualization-schedule-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-visualization-schedule-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-libwebsocketpp-dev' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-schedule_1.2.0-2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-libwebsocketpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-libwebsocketpp-dev']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-nlohmann-json-dev' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-schedule_1.2.0-2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-nlohmann-json-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-nlohmann-json-dev']
ERROR: Nothing RPROVIDES 'rviz-common' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-rviz2-plugins_1.2.0-2.bb RDEPENDS on or otherwise requires it)
rviz-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-common']
ERROR: Nothing RPROVIDES 'rviz-default-plugins' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-rviz2-plugins_1.2.0-2.bb RDEPENDS on or otherwise requires it)
rviz-default-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-default-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-default-plugins']
ERROR: Nothing RPROVIDES 'rmf-visualization-rviz2-plugins-dev' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-rviz2-plugins_1.2.0-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rmf-visualization-rviz2-plugins-dev'
NOTE: Runtime target 'rmf-visualization-rviz2-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-visualization-rviz2-plugins-dev']
ERROR: Nothing RPROVIDES 'rviz-rendering' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization-rviz2-plugins_1.2.0-2.bb RDEPENDS on or otherwise requires it)
rviz-rendering was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-rendering' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-rendering']
ERROR: Nothing RPROVIDES 'rmf-visualization-dev' (but /jenkins/mjansa/build/ros/webos-rolling-dunfell/meta-ros/meta-ros2-rolling/generated-recipes/rmf-visualization/rmf-visualization_1.2.0-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rmf-visualization-dev'
NOTE: Runtime target 'rmf-visualization-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-visualization-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>