python-pyproj: upgrade to 1.9.6 and use pypi.bbclass
* newer version is needed to fix build with newer python-3.7:
_proj.c:7421:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
     *type = tstate->exc_type;
                     ^~~~~~~~
                     curexc_type
* see https://github.com/pyproj4/pyproj/issues/138
  https://github.com/pyproj4/pyproj/issues/136
* and pypi.bbclass is needed to fetch the source from
  files.pythonhosted.org, the old pypi.python.org/packages/source
  doesn't have the new releases
* the newest version is 2.1.3, but that needs a bit more changes
  like:
  DEPENDS += "${PYTHON_PN}-cython-native"
  and then it still fails with:
  | Proj executable not found. Please set PROJ_DIR variable.
  | ERROR: 'python3 setup.py build ' execution failed.
  will probably need native pyproj as well, I'll leave that to someone
  actually using pyproj (I was just fixing the build error detected in
  bitbake world with Yocto 2.7 Warrior).

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>