{noetic} Set LICENSE to BSD-3-Clause
Set the LICENSE variable to BSD-3-Clause so that it gets correctly
recognized as an SPDX identifier.

  ERROR: ros-comm-1.16.0-1-r0 do_create_spdx: Cannot find any text for license BSD

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>