{noetic} rx-service-tools: restrict with wxpython ROS_WORLD_SKIP_GROUPS
* fixes:
ERROR: Nothing RPROVIDES 'wxpython' (but meta-ros1-noetic/generated-recipes/rx-service-tools/rx-service-tools_1.0.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'wxpython' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['wxpython']
NOTE: Runtime target 'rx-service-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rx-service-tools', 'wxpython']
NOTE: Runtime target 'rx-service-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rx-service-tools-dev', 'wxpython']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>