{melodic} pass-through-controllers: add dependency on control-msgs
* it's in ROS_TEST_DEPENDS but the dependency is needed even without testing
  enabled to fix:

FAILED: CMakeFiles/pass_through_controllers.dir/src/pass_through_controllers.cpp.o
/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"pass_through_controllers\" -Dpass_through_controllers_EXPORTS -I/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/git/include -I/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/git/test/hw_interface -I/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/include -I/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -isystem /jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/git/BEFORE -isystem /jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/devel/include -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0=/usr/src/debug/pass-through-controllers/0.1.0-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0=/usr/src/debug/pass-through-controllers/0.1.0-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/recipe-sysroot -fPIC -std=c++14 -MD -MT CMakeFiles/pass_through_controllers.dir/src/pass_through_controllers.cpp.o -MF CMakeFiles/pass_through_controllers.dir/src/pass_through_controllers.cpp.o.d -o CMakeFiles/pass_through_controllers.dir/src/pass_through_controllers.cpp.o -c /jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/git/src/pass_through_controllers.cpp
In file included from /jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/git/include/pass_through_controllers/pass_through_controllers.h:33,
                 from /jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/git/src/pass_through_controllers.cpp:31:
/jenkins/mjansa/build/ros/ros1-melodic-hardknott/tmp-glibc/work/core2-64-oe-linux/pass-through-controllers/0.1.0-1-r0/git/include/pass_through_controllers/trajectory_interface.h:33:10: fatal error: control_msgs/FollowJointTrajectoryGoal.h: No such file or directory
   33 | #include <control_msgs/FollowJointTrajectoryGoal.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Martin Jansa <martin.jansa@lge.com>