{noetic} ompl: remove optional dependency on unresolved opende
* fixes:
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-opende' (but meta-ros1-noetic/generated-recipes/ompl/ompl_1.5.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-opende' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-opende']
NOTE: Runtime target 'ompl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ompl', 'ROS_UNRESOLVED_DEP-opende']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-libflann-dev' (but meta-ros1-noetic/generated-recipes/ompl/ompl_1.5.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-libflann-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-libflann-dev']
ERROR: Nothing RPROVIDES 'ompl-dev' (but meta-ros1-noetic/generated-recipes/ompl/ompl_1.5.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ompl-dev'
NOTE: Runtime target 'ompl-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ompl-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>