{ros2} lely-core: Fix failures to pkg_resources
The pkg_resources modules has been removed in setuptools 82.

This causes a build failure in canopen-tests when cogen is run:

 Traceback (most recent call last):
 File ".../recipe-sysroot-native/opt/ros/jazzy/bin/cogen", line 33, in <module>
 ...
 File ".../canopen-tests/0.3.2-1/recipe-sysroot-native/opt/ros/jazzy/lib/python3.14/site-packages/cogen/cogen.py", line 18, in <module>
     from dcfgen.cli import Master, Slave
 File .../canopen-tests/0.3.2-1/recipe-sysroot-native/usr/lib/python3.14/site-packages/dcfgen/cli.py", line 4, in <module>
     import pkg_resources
 ModuleNotFoundError: No module named 'pkg_resources'

This merge request from the upstream repository replaces it with
importlib.

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>