{foxy} resolve dependency issues in new recipes
* fixes:
ERROR: Nothing PROVIDES 'gazebo-ros' (but meta-ros/meta-ros2-foxy/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.1-1.bb DEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-ros2-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros2-control', 'gazebo-ros']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'gazebo-ros2-control', 'gazebo-ros']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'gazebo-ros2-control', 'gazebo-ros']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'gazebo-ros2-control', 'gazebo-ros']
NOTE: Runtime target 'gazebo-ros2-control-demos' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros2-control-demos', 'gazebo-ros2-control', 'gazebo-ros']
ERROR: Nothing PROVIDES 'gazebo-rosdev' (but meta-ros/meta-ros2-foxy/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.1-1.bb DEPENDS on or otherwise requires it)
gazebo-rosdev was skipped: Recipe is blacklisted: gazebo: depends on gazebo which is not available
ERROR: Nothing PROVIDES 'mongodb' (but meta-ros/meta-ros2-foxy/generated-recipes/warehouse-ros-mongo/warehouse-ros-mongo_2.0.0-1.bb DEPENDS on or otherwise requires it)
mongodb was skipped: Recipe is blacklisted: src/mongo/util/net/ssl_manager.cpp:557:70: error: invalid conversion from 'size_t*' {aka 'unsigned int*'} to 'long unsigned int*' [-fpermissive] http://caprica.lgsvl.com:8080/Errors/Details/1509767
NOTE: Runtime target 'warehouse-ros-mongo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warehouse-ros-mongo', 'mongodb']
ERROR: Nothing PROVIDES 'glfw' (but meta-ros/meta-ros2-foxy/generated-recipes/embree-vendor/embree-vendor_0.0.6-1.bb DEPENDS on or otherwise requires it)
glfw was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'embree-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['embree-vendor', 'glfw']
ERROR: Nothing PROVIDES 'rviz2' (but meta-ros/meta-ros2-foxy/generated-recipes/color-names/color-names_0.0.1-1.bb DEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'color-names' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['color-names', 'rviz2']
ERROR: Nothing PROVIDES 'gazebo-ros-pkgs' (but meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3-simulations/turtlebot3-gazebo_2.2.1-1.bb DEPENDS on or otherwise requires it)
gazebo-ros-pkgs was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'turtlebot3-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-gazebo', 'gazebo-ros-pkgs']
NOTE: Runtime target 'turtlebot3-simulations' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-simulations', 'turtlebot3-gazebo', 'gazebo-ros-pkgs']
ERROR: Nothing PROVIDES 'turtlebot3' (but meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3-simulations/turtlebot3-gazebo_2.2.1-1.bb DEPENDS on or otherwise requires it)
turtlebot3 was skipped: Recipe is blacklisted: qt5: depends on turtlebot3-bringup, turtlebot3-navigation2 which depend on rviz2 which depends on qtbase; opengl: depends turtlebot3-bringup which depends on on rviz2 which depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on turtlebot3-bringup, turtlebot3-navigation2 which depend on rviz2 which depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'turtlebot3-simulations-dev' (but meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3-simulations/turtlebot3-simulations_2.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtlebot3-simulations-dev'
NOTE: Runtime target 'turtlebot3-simulations-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-simulations-dev']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but meta-ros/meta-ros2-foxy/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.1-1.bb, meta-ros/meta-ros2-foxy/generated-recipes/gazebo-ros2-control/gazebo-ros2-control-demos_0.0.1-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
ERROR: Nothing RPROVIDES 'gazebo-ros2-control-dev' (but meta-ros/meta-ros2-foxy/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gazebo-ros2-control-dev'
NOTE: Runtime target 'gazebo-ros2-control-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros2-control-dev']
ERROR: Nothing RPROVIDES 'gazebo-rosdev' (but meta-ros/meta-ros2-foxy/generated-recipes/gazebo-ros2-control/gazebo-ros2-control_0.0.1-1.bb RDEPENDS on or otherwise requires it)
gazebo-rosdev was skipped: Recipe is blacklisted: gazebo: depends on gazebo which is not available
NOTE: Runtime target 'gazebo-rosdev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-rosdev']
ERROR: Nothing RPROVIDES 'gazebo-ros2-control-demos-dev' (but meta-ros/meta-ros2-foxy/generated-recipes/gazebo-ros2-control/gazebo-ros2-control-demos_0.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gazebo-ros2-control-demos-dev'
NOTE: Runtime target 'gazebo-ros2-control-demos-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros2-control-demos-dev']
ERROR: Nothing RPROVIDES 'warehouse-ros-mongo-dev' (but meta-ros/meta-ros2-foxy/generated-recipes/warehouse-ros-mongo/warehouse-ros-mongo_2.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'warehouse-ros-mongo-dev'
NOTE: Runtime target 'warehouse-ros-mongo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warehouse-ros-mongo-dev']
ERROR: Nothing RPROVIDES 'rqt-topic' (but meta-ros/meta-ros2-foxy/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb RDEPENDS on or otherwise requires it)
rqt-topic was skipped: Recipe is blacklisted: qt5: rdepends on rqt-gui-py which depends qt-gui which depends on qtbase; pyqt5: rdepends on python-qt-binding and rqt-gui-py which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-topic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-topic']
NOTE: Runtime target 'rqt-moveit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-moveit', 'rqt-topic']
NOTE: Runtime target 'rqt-moveit-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-moveit-dev', 'rqt-topic']
ERROR: Nothing RPROVIDES 'python-qt-binding' (but meta-ros/meta-ros2-foxy/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb RDEPENDS on or otherwise requires it)
python-qt-binding was skipped: Recipe is blacklisted: qt5: depends on qtbase; pyqt5: depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'python-qt-binding' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-qt-binding']
ERROR: Nothing RPROVIDES 'rqt-gui-py' (but meta-ros/meta-ros2-foxy/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb RDEPENDS on or otherwise requires it)
rqt-gui-py was skipped: Recipe is blacklisted: qt5: depends on qt-gui which depends on qtbase; pyqt5: depends on qt-gui which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-gui-py' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-py']
ERROR: Nothing RPROVIDES 'rqt-py-common' (but meta-ros/meta-ros2-foxy/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb RDEPENDS on or otherwise requires it)
rqt-py-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; pyqt5: rdepends on python-qt-binding which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-py-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-py-common']
ERROR: Nothing RPROVIDES 'rqt-gui' (but meta-ros/meta-ros2-foxy/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-1.bb RDEPENDS on or otherwise requires it)
rqt-gui was skipped: Recipe is blacklisted: qt5: depends on qt-gui which depends on qtbase; pyqt5: depends on qt-gui which depends on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-gui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui']
ERROR: Nothing RPROVIDES 'glfw' (but meta-ros/meta-ros2-foxy/generated-recipes/embree-vendor/embree-vendor_0.0.6-1.bb RDEPENDS on or otherwise requires it)
glfw was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'glfw' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['glfw']
ERROR: Nothing RPROVIDES 'embree-vendor-dev' (but meta-ros/meta-ros2-foxy/generated-recipes/embree-vendor/embree-vendor_0.0.6-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'embree-vendor-dev'
NOTE: Runtime target 'embree-vendor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['embree-vendor-dev']
ERROR: Nothing RPROVIDES 'rviz2' (but meta-ros/meta-ros2-foxy/generated-recipes/color-names/color-names_0.0.1-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
ERROR: Nothing RPROVIDES 'color-names-dev' (but meta-ros/meta-ros2-foxy/generated-recipes/color-names/color-names_0.0.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'color-names-dev'
NOTE: Runtime target 'color-names-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['color-names-dev']
ERROR: Nothing RPROVIDES 'popf' (but meta-ros/meta-ros2-foxy/generated-recipes/ros2-planning-system/plansys2-executor_1.0.7-2.bb, meta-ros/meta-ros2-foxy/generated-recipes/ros2-planning-system/plansys2-popf-plan-solver_1.0.7-2.bb RDEPENDS on or otherwise requires it)
popf was skipped: Recipe is blacklisted: Depends on unavailable ROS_UNRESOLVED_DEP-coinor-libcbc-dev, ROS_UNRESOLVED_DEP-coinor-libclp-dev, ROS_UNRESOLVED_DEP-coinor-libcoinutils-dev, ROS_UNRESOLVED_DEP-coinor-libcgl-dev
NOTE: Runtime target 'popf' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['popf']
NOTE: Runtime target 'plansys2-terminal' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-terminal', 'plansys2-executor', 'popf']
NOTE: Runtime target 'plansys2-terminal-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-terminal-dev', 'plansys2-executor', 'popf']
NOTE: Runtime target 'plansys2-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-bringup', 'plansys2-executor', 'popf']
NOTE: Runtime target 'plansys2-bringup-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-bringup-dev', 'plansys2-executor', 'popf']
NOTE: Runtime target 'plansys2-bt-actions' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-bt-actions', 'plansys2-executor', 'popf']
NOTE: Runtime target 'plansys2-bt-actions-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-bt-actions-dev', 'plansys2-executor', 'popf']
NOTE: Runtime target 'plansys2-executor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-executor', 'popf']
NOTE: Runtime target 'plansys2-executor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-executor-dev', 'popf']
NOTE: Runtime target 'plansys2-planner' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-planner', 'plansys2-popf-plan-solver', 'popf']
NOTE: Runtime target 'plansys2-planner-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-planner-dev', 'plansys2-popf-plan-solver', 'popf']
NOTE: Runtime target 'plansys2-popf-plan-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-popf-plan-solver', 'popf']
ERROR: Nothing RPROVIDES 'gazebo-ros-pkgs' (but meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3-simulations/turtlebot3-gazebo_2.2.1-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros-pkgs was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-ros-pkgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-pkgs']
ERROR: Nothing RPROVIDES 'turtlebot3' (but meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3-simulations/turtlebot3-gazebo_2.2.1-1.bb RDEPENDS on or otherwise requires it)
turtlebot3 was skipped: Recipe is blacklisted: qt5: depends on turtlebot3-bringup, turtlebot3-navigation2 which depend on rviz2 which depends on qtbase; opengl: depends turtlebot3-bringup which depends on on rviz2 which depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on turtlebot3-bringup, turtlebot3-navigation2 which depend on rviz2 which depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'turtlebot3' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3']
ERROR: Nothing RPROVIDES 'turtlebot3-gazebo-dev' (but meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3-simulations/turtlebot3-gazebo_2.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtlebot3-gazebo-dev'
NOTE: Runtime target 'turtlebot3-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-gazebo-dev']
ERROR: Nothing RPROVIDES 'plansys2-popf-plan-solver-dev' (but meta-ros/meta-ros2-foxy/generated-recipes/ros2-planning-system/plansys2-popf-plan-solver_1.0.7-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'plansys2-popf-plan-solver-dev'
NOTE: Runtime target 'plansys2-popf-plan-solver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-popf-plan-solver-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>