{noetic} apriltag: inherit python3targetconfig
* inherit python3native as do_configure calls python3 to figure out CFLAGS,
  which will unfortunately contain e.g. -I/usr/include/python3.6m from host,
  which is obviously wrong for cross-compilation:

   Called from: [1]     /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt
/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt(110):  execute_process(COMMAND which python3 OUTPUT_QUIET RESULT_VARIABLE Python3_NOT_FOUND )
   Called from: [1]     /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt
/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt(111):  execute_process(COMMAND python3 -c import numpy RESULT_VARIABLE Numpy_NOT_FOUND )
   Called from: [1]     /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt
/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt(114):  if(NOT Python3_NOT_FOUND AND NOT Numpy_NOT_FOUND AND PYTHONLIBS_FOUND AND BUILD_PYTHON_WRAPPER )
   Called from: [1]     /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt
/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt(116):  execute_process(COMMAND python3 /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/python_build_flags.py OUTPUT_VARIABLE PY_OUT )
   Called from: [1]     /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt
/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt(117):  set(PY_VARS CFLAGS LDFLAGS LINKER EXT_SUFFIX )
   Called from: [1]     /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt
/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/CMakeLists.txt(118):  cmake_parse_arguments(PY  CFLAGS;LDFLAGS;LINKER;EXT_SUFFIX  CFLAGS;-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -I/usr/include/python3.6m -I/usr/lib/python3/dist-packages/numpy/core/include -Wno-strict-prototypes;LINKER;x86_64-linux-gnu-gcc;LDFLAGS;-pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -lpython3.6m -Wl,-Bsymbolic-functions  -Wl,-z,relro;EXT_SUFFIX;.cpython-36m-x86_64-linux-gnu.so; )

* leading to:
FAILED: apriltag_pywrap.o
cd /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/build && /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/bin/aarch64-oe-linux/aarch64-oe-linux-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -I/usr/include/python3.6m -I/usr/lib/python3/dist-packages/numpy/core/include -Wno-strict-prototypes -I/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/build -c -o apriltag_pywrap.o /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/apriltag_pywrap.c
cc1: warning: include location "/usr/include/python3.6m" is unsafe for cross-compilation [-Wpoison-system-directories]
In file included from /usr/include/python3.6m/Python.h:8,
                 from /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/apriltag_pywrap.c:4:
/usr/include/python3.6m/pyconfig.h:9:12: fatal error: aarch64-linux-gnu/python3.6m/pyconfig.h: No such file or directory
    9 | #  include <aarch64-linux-gnu/python3.6m/pyconfig.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

* with python3native the values are better:
CFLAGS;-Wno-unused-result -Wsign-compare -DNDEBUG -g -Wall -isystem/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/include -pipe -isystem/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/include -pipe -fPIC -I/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/include/python3.9 -I/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/numpy/core/include -Wno-strict-prototypes;LINKER;gcc;LDFLAGS;-pthread -shared -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib -Wl,--enable-new-dtags -Wl,-rpath-link,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib -Wl,-rpath,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib -Wl,-rpath,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/jenkins/home/anaconda/ros1-eloquent-hardknott/tmp-glibc/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib -Wl,--enable-new-dtags -Wl,-rpath-link,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib -Wl,-rpath,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib -Wl,-rpath,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/jenkins/home/anaconda/ros1-eloquent-hardknott/tmp-glibc/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 -L. -lpython3.9 -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib                         -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib                         -Wl,-rpath,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib                         -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/jenkins/home/anaconda/ros1-eloquent-hardknott/tmp-glibc/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib                         -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib                         -Wl,-rpath,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/lib                         -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/jenkins/home/anaconda/ros1-eloquent-hardknott/tmp-glibc/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2;EXT_SUFFIX;.cpython-39-x86_64-linux-gnu.so;

* but still using configuration for native not target python3, inherit python3targetconfig with following values:
CFLAGS;-march=armv8-a+crc+crypto --sysroot=/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot -Wno-unused-result -Wsign-compare -DNDEBUG -g -Wall -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/home/anaconda/ros1-eloquent-hardknott/tmp-glibc/work/cortexa72-oe-linux/python3/3.9.5-r0=/usr/src/debug/python3/3.9.5-r0 -fdebug-prefix-map=/jenkins/home/anaconda/ros1-eloquent-hardknott/tmp-glibc/work/cortexa72-oe-linux/python3/3.9.5-r0=/usr/src/debug/python3/3.9.5-r0 -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot= -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native= -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/home/anaconda/ros1-eloquent-hardknott/tmp-glibc/work/cortexa72-oe-linux/python3/3.9.5-r0=/usr/src/debug/python3/3.9.5-r0 -fdebug-prefix-map=/jenkins/home/anaconda/ros1-eloquent-hardknott/tmp-glibc/work/cortexa72-oe-linux/python3/3.9.5-r0=/usr/src/debug/python3/3.9.5-r0 -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot= -fdebug-prefix-map=/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native= -fPIC -I/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot/usr/include/python3.9 -I/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/numpy/core/include -Wno-strict-prototypes;LINKER;aarch64-oe-linux-gcc;LDFLAGS;-mcpu=cortex-a72 -march=armv8-a+crc+crypto --sysroot=/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot -shared -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -L. -lpython3.9 -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -L/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed;EXT_SUFFIX;.cpython-39-aarch64-linux-gnu.so;

* then add python3-numpy-native to fix:

-- Found PythonLibs: /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot/usr/lib/libpython3.so (found version "3.9.5")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'

shown only after adding python3native

* then change python3native to python3target config to fix:
| FAILED: apriltag_pywrap.o
| cd /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/build && /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/bin/aarch64-oe-linux/aarch64-oe-linux-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -Wall -isystem/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/include -pipe -isystem/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/include -pipe -fPIC -I/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/include/python3.9 -I/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/numpy/core/include -Wno-strict-prototypes -I/jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/build -c -o apriltag_pywrap.o /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/apriltag_pywrap.c
| In file included from /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib/aarch64-oe-linux/gcc/aarch64-oe-linux/10.2.0/include-fixed/syslimits.h:7,
|                  from /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib/aarch64-oe-linux/gcc/aarch64-oe-linux/10.2.0/include-fixed/limits.h:34,
|                  from /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/include/python3.9/Python.h:11,
|                  from /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/apriltag_pywrap.c:4:
| /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/lib/aarch64-oe-linux/gcc/aarch64-oe-linux/10.2.0/include-fixed/limits.h:195:61: error: no include path in which to search for limits.h
|   195 | #include_next <limits.h>  /* recurse down to the real one */
|       |                                                             ^
| In file included from /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/git/apriltag_pywrap.c:4:
| /jenkins/mjansa/build/ros/ros1-noetic-hardknott/tmp-glibc/work/cortexa72-oe-linux/apriltag/3.1.5-1-r0/recipe-sysroot-native/usr/include/python3.9/Python.h:25:10: fatal error: stdio.h: No such file or directory
|    25 | #include <stdio.h>
|       |          ^~~~~~~~~
| compilation terminated.

* and now it installs in wrong destination:
ERROR: apriltag-3.1.5-1-r0 do_package: QA Issue: apriltag: Files/directories were installed but not shipped in any package:
  /home
  /home/mjansa
  /home/mjansa/.local
  /home/mjansa/.local/lib
  /home/mjansa/.local/lib/python3.9
  /home/mjansa/.local/lib/python3.9/site-packages
  /home/mjansa/.local/lib/python3.9/site-packages/apriltag.cpython-39-aarch64-linux-gnu.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
apriltag: 7 installed and not shipped files. [installed-vs-shipped]

because CMakeLists.txt uses:
  apriltag/3.1.5-1-r0/git$ python3 -m site --user-site OUTPUT_VARIABLE PY_DEST
  /home/mjansa/.local/lib/python3.6/site-packages

  add a patch to allow setting PY_DEST from OE recipe

Signed-off-by: Martin Jansa <martin.jansa@lge.com>