{melodic} exotica-*, moveit-commander, pilz-*: add x11 to ROS_WORLD_SKIP_GROUPS
* exotica-core-task-maps, exotica-ompl-solver, exotica-python
* pilz-industrial-motion-testutils, pilz-industrial-motion, pilz-robot-programming
* fixes:
ERROR: Nothing PROVIDES 'exotica-core' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-core-task-maps_5.1.3-3.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ompl-solver_5.1.3-3.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-python_5.1.3-3.bb DEPENDS on or otherwise requires it)
exotica-core was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'exotica-core-task-maps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-core-task-maps', 'exotica-core']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'exotica-core-task-maps', 'exotica-core']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'exotica-core-task-maps', 'exotica-core']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'exotica-core-task-maps', 'exotica-core']
NOTE: Runtime target 'exotica-ompl-solver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ompl-solver', 'exotica-core']
NOTE: Runtime target 'exotica-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-python', 'exotica-core']
ERROR: Nothing PROVIDES 'pilz-trajectory-generation' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-industrial-motion/pilz-robot-programming_0.4.10-1.bb DEPENDS on or otherwise requires it)
pilz-trajectory-generation was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-planning(-interface)->moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'pilz-robot-programming' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-robot-programming', 'pilz-trajectory-generation']
NOTE: Runtime target 'pilz-industrial-motion' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-industrial-motion', 'pilz-robot-programming', 'pilz-trajectory-generation']
ERROR: Nothing RPROVIDES 'moveit-ros-planning-interface' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/moveit/moveit-commander_1.0.2-1.bb RDEPENDS on or otherwise requires it)
moveit-ros-planning-interface was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-ros-planning-interface' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-ros-planning-interface']
NOTE: Runtime target 'moveit-commander' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-commander', 'moveit-ros-planning-interface']
ERROR: Nothing RPROVIDES 'moveit-commander-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/moveit/moveit-commander_1.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'moveit-commander-dev'
NOTE: Runtime target 'moveit-commander-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-commander-dev']
ERROR: Nothing RPROVIDES 'pilz-industrial-motion-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-industrial-motion/pilz-industrial-motion_0.4.10-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-industrial-motion-dev'
NOTE: Runtime target 'pilz-industrial-motion-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-industrial-motion-dev']
ERROR: Nothing RPROVIDES 'pilz-trajectory-generation' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-industrial-motion/pilz-industrial-motion_0.4.10-1.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-industrial-motion/pilz-robot-programming_0.4.10-1.bb RDEPENDS on or otherwise requires it)
pilz-trajectory-generation was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-planning(-interface)->moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'pilz-trajectory-generation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-trajectory-generation']
ERROR: Nothing RPROVIDES 'exotica-core-task-maps-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-core-task-maps_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-core-task-maps-dev'
NOTE: Runtime target 'exotica-core-task-maps-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-core-task-maps-dev']
ERROR: Nothing RPROVIDES 'exotica-core' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-core-task-maps_5.1.3-3.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ompl-solver_5.1.3-3.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-python_5.1.3-3.bb RDEPENDS on or otherwise requires it)
exotica-core was skipped: Recipe is blacklisted: Depends on moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES and moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'exotica-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-core']
ERROR: Nothing RPROVIDES 'pilz-robot-programming-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-industrial-motion/pilz-robot-programming_0.4.10-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-robot-programming-dev'
NOTE: Runtime target 'pilz-robot-programming-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-robot-programming-dev']
ERROR: Nothing RPROVIDES 'exotica-ompl-solver-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-ompl-solver_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-ompl-solver-dev'
NOTE: Runtime target 'exotica-ompl-solver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-ompl-solver-dev']
ERROR: Nothing RPROVIDES 'exotica-python-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/exotica/exotica-python_5.1.3-3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'exotica-python-dev'
NOTE: Runtime target 'exotica-python-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exotica-python-dev']

ERROR: Nothing PROVIDES 'moveit-commander' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-industrial-motion/pilz-industrial-motion-testutils_0.4.10-1.bb DEPENDS on or otherwise requires it)
moveit-commander was skipped: Recipe is blacklisted: opengl: Depends on moveit-ros-planning-interface->moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on moveit-ros-planning-interface which depends on  moveit-ros-perception->freeglut which requires x11
ERROR: Nothing RPROVIDES 'pilz-industrial-motion-testutils-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-industrial-motion/pilz-industrial-motion-testutils_0.4.10-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-industrial-motion-testutils-dev'
NOTE: Runtime target 'pilz-industrial-motion-testutils-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-industrial-motion-testutils-dev']
ERROR: Nothing RPROVIDES 'pilz-industrial-motion-testutils' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-industrial-motion/pilz-industrial-motion-testutils_0.4.10-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-industrial-motion-testutils'
NOTE: Runtime target 'pilz-industrial-motion-testutils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-industrial-motion-testutils']
ERROR: Nothing RPROVIDES 'moveit-commander' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-industrial-motion/pilz-industrial-motion-testutils_0.4.10-1.bb RDEPENDS on or otherwise requires it)
moveit-commander was skipped: Recipe is blacklisted: opengl: Depends on moveit-ros-planning-interface->moveit-ros-planning->moveit-ros-perception->mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on moveit-ros-planning-interface which depends on  moveit-ros-perception->freeglut which requires x11
NOTE: Runtime target 'moveit-commander' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-commander']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>