{melodic} packagegroup-ros-world-melodic: remove lex-common
* lex-common installs only header files in PN-dev, static library in PN-staticdev
  and debug files in PN-dbg, so the PN is empty and not created, causing:

ERROR: ros-image-world-1.0-r0 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install connman packagegroup-core-boot packagegroup-ros-world run-postinsts' returned 1:
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - nothing provides lex-common needed by packagegroup-ros-world-melodic-1.0-r0.all
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

 * opkg_finalize_intercepts: Failed to open dir /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-wh3Yxl/opkg-intercept-qcgB2o: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-wh3Yxl/opkg-intercept-qcgB2o: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-wh3Yxl: No such file or directory.

ros1-melodic-thud$ find tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-doc
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/include
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/include/lex_common
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/include/lex_common/lex_common.h
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/include/lex_common/lex_param_helper.h
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/include/lex_common/error_codes.h
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/include/lex_common/lex_configuration.h
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/share
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/share/lex_common
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/share/lex_common/cmake
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/share/lex_common/cmake/lex_common-targets-noconfig.cmake
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/share/lex_common/cmake/lex_commonConfigVersion.cmake
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/share/lex_common/cmake/lex_commonConfig.cmake
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dev/usr/share/lex_common/cmake/lex_common-targets.cmake
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include/lex_common
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include/lex_common/lex_common.h
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include/lex_common/error_codes.h
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/include/lex_common/lex_configuration.h
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/src
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/src/lex_param_helper.cpp
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-dbg/usr/src/debug/lex-common/1.0.0-1-r0/git/src/lex_common.cpp
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-staticdev
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-staticdev/usr
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-staticdev/usr/lib
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-staticdev/usr/lib/liblex_common.a
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common-locale
tmp-glibc/work/core2-64-oe-linux/lex-common/1.0.0-1-r0/packages-split/lex-common

Signed-off-by: Martin Jansa <martin.jansa@lge.com>