{melodic} mapviz, mapviz-plugins, multires-image, qt-gui-core, rosmon, rqt*, tile-map: blacklist based on qt-gui-cpp
* rqt-gui-core, rqt-image-view, rqt-multiplot, rqt-rosmon, rqt-rviz, rqt
* instead of unknown-victim
* fixes:
ERROR: Nothing PROVIDES 'qt-gui-cpp' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt/rqt-gui-cpp_0.5.1-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/qt-gui-core/qt-gui-core_0.4.0-1.bb DEPENDS on or otherwise requires it)
qt-gui-cpp was skipped: Recipe is blacklisted: Requires qtbase which requires meta-qt5 to be included and python-qt-binding which requires pyqt5; qt-gui-cpp: requires pyqt5-native for sip
ERROR: Nothing RPROVIDES 'rqt-gui-cpp' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-rviz/rqt-rviz_0.6.0.bb
/jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb
/jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/mapviz_1.2.0-1.bb
/jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-multiplot-plugin/rqt-multiplot_0.0.10.bb
/jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt/rqt-gui-cpp_0.5.1-1.bb
/jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt/rqt_0.5.1-1.bb
/jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rosmon/rqt-rosmon_2.2.1-1.bb
/jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-image-view/rqt-image-view_0.4.14-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-gui-cpp'
NOTE: Runtime target 'rqt-gui-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-cpp']
ERROR: Nothing RPROVIDES 'rqt-multiplot' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-multiplot-plugin/rqt-multiplot_0.0.10.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-multiplot'
NOTE: Runtime target 'rqt-multiplot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-multiplot']
ERROR: Nothing RPROVIDES 'mapviz-plugins' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/mapviz-plugins_1.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mapviz-plugins'
NOTE: Runtime target 'mapviz-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-plugins']
ERROR: Nothing RPROVIDES 'rosmon' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rosmon/rosmon_2.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rosmon'
NOTE: Runtime target 'rosmon' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosmon']
ERROR: Nothing RPROVIDES 'rqt-image-view' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-image-view/rqt-image-view_0.4.14-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-image-view'
NOTE: Runtime target 'rqt-image-view' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-image-view']
ERROR: Nothing RPROVIDES 'multires-image' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/multires-image_1.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'multires-image'
NOTE: Runtime target 'multires-image' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multires-image']
ERROR: Nothing RPROVIDES 'tile-map' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/tile-map_1.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'tile-map'
NOTE: Runtime target 'tile-map' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tile-map']
ERROR: Nothing RPROVIDES 'packagegroup-ros-world-melodic' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-world.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-ros-world-melodic'
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic']
ERROR: Nothing RPROVIDES 'qt-gui-core' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/qt-gui-core/qt-gui-core_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qt-gui-core'
NOTE: Runtime target 'qt-gui-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-core']
ERROR: Nothing RPROVIDES 'rqt' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt/rqt_0.5.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt'
NOTE: Runtime target 'rqt' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt']
ERROR: Nothing RPROVIDES 'rqt-rosmon' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rosmon/rqt-rosmon_2.2.1-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rosmon/rosmon_2.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-rosmon'
NOTE: Runtime target 'rqt-rosmon' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-rosmon']
ERROR: Nothing RPROVIDES 'mapviz' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/mapviz_1.2.0-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/tile-map_1.2.0-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/multires-image_1.2.0-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/mapviz-plugins_1.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mapviz'
NOTE: Runtime target 'mapviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz']
ERROR: Nothing RPROVIDES 'mapviz-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/mapviz_1.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mapviz-dev'
NOTE: Runtime target 'mapviz-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-dev']
ERROR: Nothing RPROVIDES 'rqt-multiplot-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-multiplot-plugin/rqt-multiplot_0.0.10.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-multiplot-dev'
NOTE: Runtime target 'rqt-multiplot-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-multiplot-dev']
ERROR: Nothing RPROVIDES 'tile-map-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/tile-map_1.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'tile-map-dev'
NOTE: Runtime target 'tile-map-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tile-map-dev']
ERROR: Nothing RPROVIDES 'rqt-gui-cpp-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt/rqt-gui-cpp_0.5.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-gui-cpp-dev'
NOTE: Runtime target 'rqt-gui-cpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-cpp-dev']
ERROR: Nothing RPROVIDES 'qt-gui-cpp' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt/rqt-gui-cpp_0.5.1-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/qt-gui-core/qt-gui-core_0.4.0-1.bb RDEPENDS on or otherwise requires it)
qt-gui-cpp was skipped: Recipe is blacklisted: Requires qtbase which requires meta-qt5 to be included and python-qt-binding which requires pyqt5; qt-gui-cpp: requires pyqt5-native for sip
NOTE: Runtime target 'qt-gui-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-cpp']
ERROR: Nothing RPROVIDES 'packagegroup-ros-world' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-world.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-ros-world'
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world']
ERROR: Nothing RPROVIDES 'rqt-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt/rqt_0.5.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-dev'
NOTE: Runtime target 'rqt-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-dev']
ERROR: Nothing RPROVIDES 'rqt-rosmon-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rosmon/rqt-rosmon_2.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-rosmon-dev'
NOTE: Runtime target 'rqt-rosmon-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-rosmon-dev']
ERROR: Nothing RPROVIDES 'prbt-hardware-support' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-robots/pilz-status-indicator-rqt_0.5.14-1.bb RDEPENDS on or otherwise requires it)
prbt-hardware-support was skipped: Recipe is blacklisted: Depends on pilz-utils->unavailable clang-tidy
NOTE: Runtime target 'prbt-hardware-support' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['prbt-hardware-support']
NOTE: Runtime target 'pilz-status-indicator-rqt' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-status-indicator-rqt', 'prbt-hardware-support']
ERROR: Nothing RPROVIDES 'pilz-status-indicator-rqt-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/pilz-robots/pilz-status-indicator-rqt_0.5.14-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pilz-status-indicator-rqt-dev'
NOTE: Runtime target 'pilz-status-indicator-rqt-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pilz-status-indicator-rqt-dev']
ERROR: Nothing RPROVIDES 'rosmon-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rosmon/rosmon_2.2.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rosmon-dev'
NOTE: Runtime target 'rosmon-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosmon-dev']
ERROR: Nothing RPROVIDES 'rqt-image-view-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-image-view/rqt-image-view_0.4.14-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-image-view-dev'
NOTE: Runtime target 'rqt-image-view-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-image-view-dev']
ERROR: Nothing RPROVIDES 'multires-image-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/multires-image_1.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'multires-image-dev'
NOTE: Runtime target 'multires-image-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multires-image-dev']
ERROR: Nothing RPROVIDES 'mapviz-plugins-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/mapviz-plugins_1.2.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mapviz-plugins-dev'
NOTE: Runtime target 'mapviz-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-plugins-dev']
ERROR: Nothing RPROVIDES 'qt-gui-core-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/qt-gui-core/qt-gui-core_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qt-gui-core-dev'
NOTE: Runtime target 'qt-gui-core-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-core-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>