{eloquent} packagegroup-ros-world-eloquent: Remove turtlesim
* fixes:
  ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/turtlesim/turtlesim_1.1.0-1.bb DEPENDS on or otherwise requires it). Close matches:
    netbase
  NOTE: Runtime target 'turtlesim' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['turtlesim', 'qtbase']
  NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'turtlesim', 'qtbase']
  NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'turtlesim', 'qtbase']
  NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'turtlesim', 'qtbase']
  ERROR: Nothing RPROVIDES 'qtbase' (but /jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/turtlesim/turtlesim_1.1.0-1.bb RDEPENDS on or otherwise requires it)
  NOTE: Runtime target 'qtbase' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['qtbase']
  ERROR: Nothing RPROVIDES 'turtlesim-dev' (but /jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/turtlesim/turtlesim_1.1.0-1.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'turtlesim-dev'
  NOTE: Runtime target 'turtlesim-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['turtlesim-dev']