{rolling} rosidl-generator-py: revert one upstream change to fix duplicate libraries in the image
* this prevents e.g. libstd_msgs__python.so in std-msgs package to be installed in 2 locations:
  raspberrypi4-webos-linux-gnueabi/std-msgs$ find 2.2.3-1-r0-rolling/image -name libstd_msgs__python.so
  2.2.3-1-r0-rolling/image/usr/lib/python3.9/site-packages/std_msgs/libstd_msgs__python.so
  2.2.3-1-r0-rolling/image/usr/lib/libstd_msgs__python.so

* which causes shlib mapping to show a lot of errors like:
  ERROR: std-msgs-2.2.3-1-r0 do_package: std-msgs: Multiple shlib providers for libstd_msgs__python.so: std-msgs, std-msgs (used by files: /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/std-msgs/2.2.3-1-r0/packages-split/std-msgs/usr/lib/python3.9/site-packages/std_msgs/std_msgs_s__rosidl_typesupport_fastrtps_c.cpython-39-arm-linux-gnueabi.so)
  ERROR: std-msgs-2.2.3-1-r0 do_package: std-msgs: Multiple shlib providers for libbuiltin_interfaces__python.so: builtin-interfaces, builtin-interfaces (used by files: /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/std-msgs/2.2.3-1-r0/packages-split/std-msgs/usr/lib/python3.9/site-packages/std_msgs/libstd_msgs__python.so)
  ERROR: std-msgs-2.2.3-1-r0 do_package: std-msgs: Multiple shlib providers for libstd_msgs__python.so: std-msgs, std-msgs (used by files: /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/std-msgs/2.2.3-1-r0/packages-split/std-msgs/usr/lib/python3.9/site-packages/std_msgs/std_msgs_s__rosidl_typesupport_introspection_c.cpython-39-arm-linux-gnueabi.so)
  ERROR: std-msgs-2.2.3-1-r0 do_package: std-msgs: Multiple shlib providers for libbuiltin_interfaces__python.so: builtin-interfaces, builtin-interfaces (used by files: /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/std-msgs/2.2.3-1-r0/packages-split/std-msgs/usr/lib/libstd_msgs__python.so)
  ERROR: std-msgs-2.2.3-1-r0 do_package: std-msgs: Multiple shlib providers for libstd_msgs__python.so: std-msgs, std-msgs (used by files: /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/std-msgs/2.2.3-1-r0/packages-split/std-msgs/usr/lib/python3.9/site-packages/std_msgs/std_msgs_s__rosidl_typesupport_c.cpython-39-arm-linux-gnueabi.so)

* with this change applied, following 5 files aren't installed by std-msgs:
raspberrypi4-webos-linux-gnueabi/std-msgs$ diff -rq 2.2.3-1-r0-rolling/image 2.2.3-1-r0-rolling-fixed/image
Only in 2.2.3-1-r0-rolling/image/usr/lib/python3.9/site-packages/std_msgs: libstd_msgs__python.so
Only in 2.2.3-1-r0-rolling/image/usr/lib/python3.9/site-packages/std_msgs: _std_msgs_s.ep.rosidl_typesupport_c.c
Only in 2.2.3-1-r0-rolling/image/usr/lib/python3.9/site-packages/std_msgs: _std_msgs_s.ep.rosidl_typesupport_fastrtps_c.c
Only in 2.2.3-1-r0-rolling/image/usr/lib/python3.9/site-packages/std_msgs: _std_msgs_s.ep.rosidl_typesupport_introspection_c.c
Only in 2.2.3-1-r0-rolling/image/usr/lib/python3.9/site-packages: std_msgs.egg-info

* the same issue exists in a lot of recipes, e.g. builtin-interfaces has the same issue:
  ERROR: builtin-interfaces-1.0.3-1-r0 do_package: builtin-interfaces: Multiple shlib providers for libbuiltin_interfaces__python.so: builtin-interfaces, builtin-interfaces (used by files: /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/builtin-interfaces/1.0.3-1-r0/packages-split/builtin-interfaces/usr/lib/python3.9/site-packages/builtin_interfaces/builtin_interfaces_s__rosidl_typesupport_fastrtps_c.cpython-39-arm-linux-gnueabi.so)
  ERROR: builtin-interfaces-1.0.3-1-r0 do_package: builtin-interfaces: Multiple shlib providers for libbuiltin_interfaces__python.so: builtin-interfaces, builtin-interfaces (used by files: /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/builtin-interfaces/1.0.3-1-r0/packages-split/builtin-interfaces/usr/lib/python3.9/site-packages/builtin_interfaces/builtin_interfaces_s__rosidl_typesupport_introspection_c.cpython-39-arm-linux-gnueabi.so)
  ERROR: builtin-interfaces-1.0.3-1-r0 do_package: builtin-interfaces: Multiple shlib providers for libbuiltin_interfaces__python.so: builtin-interfaces, builtin-interfaces (used by files: /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/builtin-interfaces/1.0.3-1-r0/packages-split/builtin-interfaces/usr/lib/python3.9/site-packages/builtin_interfaces/builtin_interfaces_s__rosidl_typesupport_c.cpython-39-arm-linux-gnueabi.so)

* for ros-image-world this causes 500+ ERROR messages like this,
  but be aware that these are shown only once, if you build it, ignore the errors
  then next time when the build is reused from sstate it won't show the error.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>