{foxy} fix dependency issues with x11 and qt5, pyqt5 enabled in the same build
* we regularly test builds with ROS as a DISTRO which includes x11 in DISTRO_FEATURES
  but doesn't include opengl and doesn't use meta-qt5 layer

  Then we build with webOS OSE which doesn't have x11, but has opengl in DISTRO_FEATURES
  builds with meta-qt5 layer, but old branch where pyqt5 isn't compatible with meta-oe sip

  This covers some combinations of DISTRO_FEATURES/BBLAYERS and resulting ROS_WORLD_SKIP_GROUPS
  but cannot cover all possible combinations other projects use.

  This fix is for dependency issues detected in ros-image-world after adding meta-qt5 into ROS DISTRO
  build.

* fixes:
ERROR: Nothing PROVIDES 'glew' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/tile-map_2.1.0-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb DEPENDS on or otherwise requires it)
glew was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'tile-map' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tile-map', 'glew']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'tile-map', 'glew']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'tile-map', 'glew']
NOTE: Runtime target 'multires-image' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multires-image', 'mapviz', 'glew']
NOTE: Runtime target 'mapviz-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-plugins', 'mapviz', 'glew']
NOTE: Runtime target 'mapviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz', 'glew']
ERROR: Nothing PROVIDES 'rqt-gui-cpp' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/rqt-image-view/rqt-image-view_1.1.1-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb DEPENDS on or otherwise requires it)
rqt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qt-gui-cpp and qtbase itself which requires meta-qt5 to be included; pyqt5: depends on qt-gui-cpp which depends python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: depends on qt-gui-cpp which fails to compile
NOTE: Runtime target 'rqt-image-view' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-image-view', 'rqt-gui-cpp']
NOTE: Runtime target 'rqt-common-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-common-plugins', 'rqt-image-view', 'rqt-gui-cpp']
ERROR: Nothing PROVIDES 'qt-gui-cpp' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/rqt-image-view/rqt-image-view_1.1.1-1.bb DEPENDS on or otherwise requires it)
qt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qtbase which requires meta-qt5 to be included; pyqt5: depends on python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: do_compile task fails: requires pyqt5-native for sip
ERROR: Nothing PROVIDES 'freeglut' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb DEPENDS on or otherwise requires it)
freeglut was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'rviz-common' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-rviz-plugins_0.4.7-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/slam-toolbox/slam-toolbox_2.4.0-1.bb DEPENDS on or otherwise requires it)
rviz-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'nav2-rviz-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-rviz-plugins', 'rviz-common']
NOTE: Runtime target 'nav2-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'rviz-common']
NOTE: Runtime target 'turtlebot3-navigation2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-navigation2', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'rviz-common']
NOTE: Runtime target 'navigation2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation2', 'nav2-rviz-plugins', 'rviz-common']
NOTE: Runtime target 'slam-toolbox' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slam-toolbox', 'rviz-common']
ERROR: Nothing PROVIDES 'rviz-default-plugins' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-rviz-plugins_0.4.7-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/slam-toolbox/slam-toolbox_2.4.0-1.bb DEPENDS on or otherwise requires it)
rviz-default-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'rviz-rendering' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-rviz-plugins_0.4.7-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/slam-toolbox/slam-toolbox_2.4.0-1.bb DEPENDS on or otherwise requires it)
rviz-rendering was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'rviz-ogre-vendor' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-rviz-plugins_0.4.7-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/slam-toolbox/slam-toolbox_2.4.0-1.bb DEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'tile-map-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/tile-map_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'tile-map-dev'
NOTE: Runtime target 'tile-map-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tile-map-dev']
ERROR: Nothing RPROVIDES 'glew' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/tile-map_2.1.0-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
glew was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'glew' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['glew']
ERROR: Nothing RPROVIDES 'rqt-gui-cpp' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/rqt-image-view/rqt-image-view_1.1.1-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
rqt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qt-gui-cpp and qtbase itself which requires meta-qt5 to be included; pyqt5: depends on qt-gui-cpp which depends python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: depends on qt-gui-cpp which fails to compile
NOTE: Runtime target 'rqt-gui-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-gui-cpp']
ERROR: Nothing RPROVIDES 'qt-gui-cpp' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/rqt-image-view/rqt-image-view_1.1.1-1.bb RDEPENDS on or otherwise requires it)
qt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qtbase which requires meta-qt5 to be included; pyqt5: depends on python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: do_compile task fails: requires pyqt5-native for sip
NOTE: Runtime target 'qt-gui-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-cpp']
ERROR: Nothing RPROVIDES 'rqt-image-view-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/rqt-image-view/rqt-image-view_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-image-view-dev'
NOTE: Runtime target 'rqt-image-view-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-image-view-dev']
ERROR: Nothing RPROVIDES 'nav2-bringup-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-bringup_0.4.7-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'nav2-bringup-dev'
NOTE: Runtime target 'nav2-bringup-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup-dev']
ERROR: Nothing RPROVIDES 'multires-image-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/multires-image_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'multires-image-dev'
NOTE: Runtime target 'multires-image-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multires-image-dev']
ERROR: Nothing RPROVIDES 'mapviz-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mapviz-dev'
NOTE: Runtime target 'mapviz-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-dev']
ERROR: Nothing RPROVIDES 'freeglut' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz_2.1.0-1.bb RDEPENDS on or otherwise requires it)
freeglut was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'freeglut' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['freeglut']
ERROR: Nothing RPROVIDES 'rqt-common-plugins-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/rqt-common-plugins/rqt-common-plugins_1.0.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-common-plugins-dev'
NOTE: Runtime target 'rqt-common-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-common-plugins-dev']
ERROR: Nothing RPROVIDES 'navigation2-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/navigation2_0.4.7-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'navigation2-dev'
NOTE: Runtime target 'navigation2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation2-dev']
ERROR: Nothing RPROVIDES 'mapviz-plugins-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/mapviz/mapviz-plugins_2.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mapviz-plugins-dev'
NOTE: Runtime target 'mapviz-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mapviz-plugins-dev']
ERROR: Nothing RPROVIDES 'rviz-default-plugins' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-rviz-plugins_0.4.7-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/slam-toolbox/slam-toolbox_2.4.0-1.bb RDEPENDS on or otherwise requires it)
rviz-default-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-default-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-default-plugins']
ERROR: Nothing RPROVIDES 'rviz-common' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-rviz-plugins_0.4.7-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/slam-toolbox/slam-toolbox_2.4.0-1.bb RDEPENDS on or otherwise requires it)
rviz-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-common']
ERROR: Nothing RPROVIDES 'rviz-rendering' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-rviz-plugins_0.4.7-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/slam-toolbox/slam-toolbox_2.4.0-1.bb RDEPENDS on or otherwise requires it)
rviz-rendering was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-rendering' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-rendering']
ERROR: Nothing RPROVIDES 'rviz-ogre-vendor' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-rviz-plugins_0.4.7-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/slam-toolbox/slam-toolbox_2.4.0-1.bb RDEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-ogre-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-ogre-vendor']
ERROR: Nothing RPROVIDES 'nav2-rviz-plugins-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/navigation2/nav2-rviz-plugins_0.4.7-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'nav2-rviz-plugins-dev'
NOTE: Runtime target 'nav2-rviz-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-rviz-plugins-dev']
ERROR: Nothing RPROVIDES 'turtlebot3-navigation2-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/turtlebot3/turtlebot3-navigation2_2.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtlebot3-navigation2-dev'
NOTE: Runtime target 'turtlebot3-navigation2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-navigation2-dev']
ERROR: Nothing RPROVIDES 'slam-toolbox-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-honister/meta-ros/meta-ros2-foxy/generated-recipes/slam-toolbox/slam-toolbox_2.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'slam-toolbox-dev'
NOTE: Runtime target 'slam-toolbox-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slam-toolbox-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>