{noetic} points-preprocessor: fix runtime dependency on gtest
* fixes:
ERROR: Nothing RPROVIDES 'gtest' (but /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/core-perception/points-preprocessor_1.14.9
NOTE: Runtime target 'gtest' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gtest']
NOTE: Runtime target 'points-preprocessor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['points-preprocessor', 'gtest']
NOTE: Runtime target 'packagegroup-ros-world-noetic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-noetic', 'points-preprocessor', 'gtest']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'points-preprocessor', 'gtest']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'points-preprocessor', 'gtest']
ERROR: Nothing RPROVIDES 'points-preprocessor-dev' (but /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/core-perception/points-p
No eligible RPROVIDERs exist for 'points-preprocessor-dev'
NOTE: Runtime target 'points-preprocessor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['points-preprocessor-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>