{melodic} ypspur: stage bindir as well
* fixes ypspur-ros build issue:
DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-gcc
-- Check for working C compiler: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++
-- Check for working CXX compiler: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/devel
-- Using CMAKE_PREFIX_PATH: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot/usr/opt/ros/melodic;webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot/usr
-- This workspace overlays: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot/usr/opt/ros/melodic
-- Found PythonInterp: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot-native/usr/bin/python-native/python2 (found suitable version "2.7.16", minimum required is "2")
-- Using PYTHON_EXECUTABLE: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot-native/usr/bin/python-native/python2
-- Using default Python package layout
-- Found PY_em: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using empy: webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using CATKIN_ENABLE_TESTING: 0
-- catkin 0.7.23
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;gennodejs;genpy
-- ypspur_ros: 4 messages, 0 services
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   chrono
--   thread
--   atomic
--   system
--   date_time
CMake Error at webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot/usr/share/ypspur/cmake/YPSpurTargets.cmake:97 (message):
  The imported target "ypspur-coordinator" references the file

     "webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot/usr/bin/ypspur-coordinator"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot/usr/share/ypspur/cmake/YPSpurTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/recipe-sysroot/usr/share/ypspur/ypspur-config.cmake:52 (include)
  CMakeLists.txt:43 (find_package)

-- Configuring incomplete, errors occurred!
See also "webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/build/CMakeFiles/CMakeOutput.log".
See also "webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/build/CMakeFiles/CMakeError.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/ypspur-ros/0.3.1-1-r0/temp/log.do_configure.60267)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>