graphicsmagick: move to meta-ros2 to share between dashing and eloquent
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-graphicsmagick' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/navigation2/nav2-map-server_0.3.2-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'nav2-map-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-map-server', 'UNRESOLVED-graphicsmagick']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>