image-view: add missing dependency on gtk+
* fixes:
  image-view/1.12.23-r0/image_pipeline-1.12.23/image_view/src/nodes/stereo_view.cpp:53:10: fatal error: gtk/gtk.h: No such file or directory
   #include <gtk/gtk.h>
             ^~~~~~~~~~~
   compilation terminated.
* also add x11 to required DISTRO_FEATURES as gtk+ is available only with x11 or directfb,
  otherwise ti causes another error in world builds:

  ERROR: Nothing PROVIDES 'gtk+' (but meta-ros/recipes-ros/image-pipeline/image-view_1.12.23.bb DEPENDS on or otherwise requires it)
  gtk+ was skipped: one of '['directfb', 'x11']' needs to be in DISTRO_FEATURES

* GTK2DISTROFEATURES variable and ANY_OF_DISTRO_FEATURES check is
  available since 2.0 Jethro (that should be old enough that all
  meta-ros/legacy users already have support for this).

  commit 60157da8a6df0c7ec5bb572bea5124af273bab08
  Author: Joe Slater <jslater@windriver.com>
  Date:   Thu May 7 12:55:26 2015 -0700

    distro_features_check: add any of test

  commit ef967c70182eeccb59c7511d838a7ecb0b2315c1
  Author: Richard Purdie <richard.purdie@linuxfoundation.org>
  Date:   Mon Sep 28 11:53:35 2015 +0100

    classes/meta: Add DISTRO_FEATURES check for gtk+/gtk3+

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>