{galactic} libg2o: fix build with libeigen-3.4.0
* generic Vector type was added to libeigen-3.4.0 with:
  https://gitlab.com/libeigen/eigen/-/commit/2a39659d793fcde656593bbf01948bc0bd568181

* fixes:
FAILED: g2o/examples/bal/CMakeFiles/bal_example.dir/bal_example.cpp.o
libg2o/2020.5.29-3-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -DUNIX -Ilibg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3 -Ilibg2o/2020.5.29-3-r0/git -Ilibg2o/2020.5.29-3-r0/build -Ilibg2o/2020.5.29-3-r0/git/g2o/solvers/cholmod -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=libg2o/2020.5.29-3-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=libg2o/2020.5.29-3-r0=/usr/src/debug/libg2o/2020.5.29-3-r0                      -fdebug-prefix-map=libg2o/2020.5.29-3-r0=/usr/src/debug/libg2o/2020.5.29-3-r0                      -fdebug-prefix-map=libg2o/2020.5.29-3-r0/recipe-sysroot=                      -fdebug-prefix-map=libg2o/2020.5.29-3-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=libg2o/2020.5.29-3-r0/recipe-sysroot  -Wall -W -DNDEBUG -O3 -msse3 -std=gnu++14 -MD -MT g2o/examples/bal/CMakeFiles/bal_example.dir/bal_example.cpp.o -MF g2o/examples/bal/CMakeFiles/bal_example.dir/bal_example.cpp.o.d -o g2o/examples/bal/CMakeFiles/bal_example.dir/bal_example.cpp.o -c libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:96:52: error: template argument 2 is invalid
   96 | class VertexPointBAL : public BaseVertex<3, Vector3> {
      |                                                    ^
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp: In member function 'virtual void VertexPointBAL::oplusImpl(const double*)':
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:114:5: error: reference to 'Vector3' is ambiguous
  114 |     Vector3::ConstMapType v(update);
      |     ^~~~~~~
In file included from libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/Core:295,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:27:
libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/src/Core/Matrix.h:524:7: note: candidates are: 'template<class Type> using Vector3 = Eigen::Matrix<Type, 3, 1>'
  524 | using Vector##SizeSuffix = Matrix<Type, Size, 1>;                 \
      |       ^~~~~~
libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/src/Core/Matrix.h:541:1: note: in expansion of macro 'EIGEN_MAKE_TYPEDEFS'
  541 | EIGEN_MAKE_TYPEDEFS(3, 3)
      | ^~~~~~~~~~~~~~~~~~~
In file included from libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h:34,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:32:
libg2o/2020.5.29-3-r0/git/g2o/core/eigen_types.h:50:9: note:                 'using Vector3 = g2o::VectorN<3>'
   50 |   using Vector3 = VectorN<3>;
      |         ^~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:115:5: error: '_estimate' was not declared in this scope
  115 |     _estimate += v;
      |     ^~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:115:18: error: 'v' was not declared in this scope
  115 |     _estimate += v;
      |                  ^
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:113:40: warning: unused parameter 'update' [-Wunused-parameter]
  113 |   virtual void oplusImpl(const double* update) {
      |                          ~~~~~~~~~~~~~~^~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp: At global scope:
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:141:93: error: template argument 2 is invalid
  141 | class EdgeObservationBAL : public BaseBinaryEdge<2, Vector2, VertexCameraBAL, VertexPointBAL> {
      |                                                                                             ^
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp: In member function 'bool EdgeObservationBAL::operator()(const T*, const T*, T*) const':
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:197:26: error: there are no arguments to 'measurement' that depend on a template parameter, so a declaration of 'measurement' must be available [-fpermissive]
  197 |     error = prediction - measurement().cast<T>();
      |                          ^~~~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:197:26: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:197:46: error: expected primary-expression before '>' token
  197 |     error = prediction - measurement().cast<T>();
      |                                              ^
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:197:48: error: expected primary-expression before ')' token
  197 |     error = prediction - measurement().cast<T>();
      |                                                ^
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp: In function 'int main(int, char**)':
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:276:10: error: 'class VertexPointBAL' has no member named 'setId'
  276 |       p->setId(id);
      |          ^~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:277:10: error: 'class VertexPointBAL' has no member named 'setMarginalized'
  277 |       p->setMarginalized(true);
      |          ^~~~~~~~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:278:45: error: no matching function for call to 'g2o::SparseOptimizer::addVertex(VertexPointBAL*&)'
  278 |       bool addedVertex = optimizer.addVertex(p);
      |                          ~~~~~~~~~~~~~~~~~~~^~~
In file included from libg2o/2020.5.29-3-r0/git/g2o/core/base_edge.h:35,
                 from libg2o/2020.5.29-3-r0/git/g2o/core/base_fixed_sized_edge.h:35,
                 from libg2o/2020.5.29-3-r0/git/g2o/core/base_binary_edge.h:30,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:33:
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:572:18: note: candidate: 'virtual bool g2o::OptimizableGraph::addVertex(g2o::HyperGraph::Vertex*, g2o::HyperGraph::Data*)'
  572 |     virtual bool addVertex(HyperGraph::Vertex* v, Data* userData);
      |                  ^~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:572:18: note:   candidate expects 2 arguments, 1 provided
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:573:18: note: candidate: 'virtual bool g2o::OptimizableGraph::addVertex(g2o::HyperGraph::Vertex*)'
  573 |     virtual bool addVertex(HyperGraph::Vertex* v) { return addVertex(v, 0);}
      |                  ^~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:573:48: note:   no known conversion for argument 1 from 'VertexPointBAL*' to 'g2o::HyperGraph::Vertex*'
  573 |     virtual bool addVertex(HyperGraph::Vertex* v) { return addVertex(v, 0);}
      |                            ~~~~~~~~~~~~~~~~~~~~^
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:574:10: note: candidate: 'bool g2o::OptimizableGraph::addVertex(g2o::OptimizableGraph::Vertex*, g2o::HyperGraph::Data*)'
  574 |     bool addVertex(OptimizableGraph::Vertex* v, Data* userData);
      |          ^~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:574:10: note:   candidate expects 2 arguments, 1 provided
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:575:10: note: candidate: 'bool g2o::OptimizableGraph::addVertex(g2o::OptimizableGraph::Vertex*)'
  575 |     bool addVertex(OptimizableGraph::Vertex* v) { return addVertex(v, 0); }
      |          ^~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:575:46: note:   no known conversion for argument 1 from 'VertexPointBAL*' to 'g2o::OptimizableGraph::Vertex*'
  575 |     bool addVertex(OptimizableGraph::Vertex* v) { return addVertex(v, 0); }
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:297:10: error: 'class EdgeObservationBAL' has no member named 'setVertex'
  297 |       e->setVertex(0, cam);
      |          ^~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:298:10: error: 'class EdgeObservationBAL' has no member named 'setVertex'
  298 |       e->setVertex(1, point);
      |          ^~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:299:10: error: 'class EdgeObservationBAL' has no member named 'setInformation'
  299 |       e->setInformation(Matrix2::Identity());
      |          ^~~~~~~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:299:25: error: reference to 'Matrix2' is ambiguous
  299 |       e->setInformation(Matrix2::Identity());
      |                         ^~~~~~~
In file included from libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/Core:295,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:27:
libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/src/Core/Matrix.h:520:7: note: candidates are: 'template<class Type> using Matrix2 = Eigen::Matrix<Type, 2, 2>'
  520 | using Matrix##SizeSuffix = Matrix<Type, Size, Size>;              \
      |       ^~~~~~
libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/src/Core/Matrix.h:540:1: note: in expansion of macro 'EIGEN_MAKE_TYPEDEFS'
  540 | EIGEN_MAKE_TYPEDEFS(2, 2)
      | ^~~~~~~~~~~~~~~~~~~
In file included from libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h:34,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:32:
libg2o/2020.5.29-3-r0/git/g2o/core/eigen_types.h:68:9: note:                 'using Matrix2 = g2o::MatrixN<2>'
   68 |   using Matrix2 = MatrixN<2>;
      |         ^~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:300:10: error: 'class EdgeObservationBAL' has no member named 'setMeasurement'
  300 |       e->setMeasurement(Vector2(obsX, obsY));
      |          ^~~~~~~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:300:25: error: reference to 'Vector2' is ambiguous
  300 |       e->setMeasurement(Vector2(obsX, obsY));
      |                         ^~~~~~~
In file included from libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/Core:295,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:27:
libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/src/Core/Matrix.h:524:7: note: candidates are: 'template<class Type> using Vector2 = Eigen::Matrix<Type, 2, 1>'
  524 | using Vector##SizeSuffix = Matrix<Type, Size, 1>;                 \
      |       ^~~~~~
libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/src/Core/Matrix.h:540:1: note: in expansion of macro 'EIGEN_MAKE_TYPEDEFS'
  540 | EIGEN_MAKE_TYPEDEFS(2, 2)
      | ^~~~~~~~~~~~~~~~~~~
In file included from libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h:34,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:32:
libg2o/2020.5.29-3-r0/git/g2o/core/eigen_types.h:49:9: note:                 'using Vector2 = g2o::VectorN<2>'
   49 |   using Vector2 = VectorN<2>;
      |         ^~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:301:41: error: no matching function for call to 'g2o::SparseOptimizer::addEdge(EdgeObservationBAL*&)'
  301 |       bool addedEdge = optimizer.addEdge(e);
      |                        ~~~~~~~~~~~~~~~~~^~~
In file included from libg2o/2020.5.29-3-r0/git/g2o/core/base_edge.h:35,
                 from libg2o/2020.5.29-3-r0/git/g2o/core/base_fixed_sized_edge.h:35,
                 from libg2o/2020.5.29-3-r0/git/g2o/core/base_binary_edge.h:30,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:33:
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:582:18: note: candidate: 'virtual bool g2o::OptimizableGraph::addEdge(g2o::HyperGraph::Edge*)'
  582 |     virtual bool addEdge(HyperGraph::Edge* e);
      |                  ^~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:582:44: note:   no known conversion for argument 1 from 'EdgeObservationBAL*' to 'g2o::HyperGraph::Edge*'
  582 |     virtual bool addEdge(HyperGraph::Edge* e);
      |                          ~~~~~~~~~~~~~~~~~~^
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:583:10: note: candidate: 'bool g2o::OptimizableGraph::addEdge(g2o::OptimizableGraph::Edge*)'
  583 |     bool addEdge(OptimizableGraph::Edge* e);
      |          ^~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/core/optimizable_graph.h:583:42: note:   no known conversion for argument 1 from 'EdgeObservationBAL*' to 'g2o::OptimizableGraph::Edge*'
  583 |     bool addEdge(OptimizableGraph::Edge* e);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~^
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:317:7: error: reference to 'Vector3' is ambiguous
  317 |       Vector3 p;
      |       ^~~~~~~
In file included from libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/Core:295,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:27:
libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/src/Core/Matrix.h:524:7: note: candidates are: 'template<class Type> using Vector3 = Eigen::Matrix<Type, 3, 1>'
  524 | using Vector##SizeSuffix = Matrix<Type, Size, 1>;                 \
      |       ^~~~~~
libg2o/2020.5.29-3-r0/recipe-sysroot/usr/include/eigen3/Eigen/src/Core/Matrix.h:541:1: note: in expansion of macro 'EIGEN_MAKE_TYPEDEFS'
  541 | EIGEN_MAKE_TYPEDEFS(3, 3)
      | ^~~~~~~~~~~~~~~~~~~
In file included from libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h:34,
                 from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:32:
libg2o/2020.5.29-3-r0/git/g2o/core/eigen_types.h:50:9: note:                 'using Vector3 = g2o::VectorN<3>'
   50 |   using Vector3 = VectorN<3>;
      |         ^~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:318:14: error: 'p' was not declared in this scope
  318 |       ifs >> p(0) >> p(1) >> p(2);
      |              ^
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:320:14: error: 'class VertexPointBAL' has no member named 'setEstimate'
  320 |       point->setEstimate(p);
      |              ^~~~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:359:22: error: 'class VertexPointBAL' has no member named 'estimate'
  359 |       fout << (*it)->estimate().transpose() << endl;
      |                      ^~~~~~~~
In file included from libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:32:
libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h: In instantiation of 'static void g2o::AutoDifferentiation<Edge, EstimateAccess>::computeError(Edge*) [with Edge = EdgeObservationBAL; EstimateAccess = g2o::EstimateAccessor<EdgeObservationBAL>]':
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:202:3:   required from here
libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h:156:25: error: 'Dimension' is not a member of 'EdgeObservationBAL'
  156 |     static_assert(Edge::Dimension > 0, "Dynamically sized edges are not supported");
      |                         ^~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h:157:31: error: '_nr_of_vertices' is not a member of 'EdgeObservationBAL'
  157 |     computeErrorNs(that, std::make_index_sequence<Edge::_nr_of_vertices>());
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h: In instantiation of 'static void g2o::AutoDifferentiation<Edge, EstimateAccess>::linearize(Edge*) [with Edge = EdgeObservationBAL; EstimateAccess = g2o::EstimateAccessor<EdgeObservationBAL>]':
libg2o/2020.5.29-3-r0/git/g2o/examples/bal/bal_example.cpp:202:3:   required from here
libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h:168:25: error: 'Dimension' is not a member of 'EdgeObservationBAL'
  168 |     static_assert(Edge::Dimension > 0, "Dynamically sized edges are not supported");
      |                         ^~~~~~~~~
libg2o/2020.5.29-3-r0/git/g2o/core/auto_differentiation.h:169:33: error: '_nr_of_vertices' is not a member of 'EdgeObservationBAL'
  169 |     linearizeOplusNs(that, std::make_index_sequence<Edge::_nr_of_vertices>());
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Martin Jansa <martin.jansa@lge.com>