{melodic} ros-distro.inc: add mapping for daemontools
* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-daemontools' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/robot-upstart/robot-upstart_0.3.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-daemontools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-daemontools']
NOTE: Runtime target 'robot-upstart' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-upstart', 'UNRESOLVED-daemontools']
NOTE: Runtime target 'robot-upstart-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['robot-upstart-dev', 'UNRESOLVED-daemontools']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>