{melodic} fix dependency issues from new recipes
* fixes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'UNRESOLVED-gstreamer1.0-alsa' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.7-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'audio-play' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-play', 'UNRESOLVED-gstreamer1.0-alsa']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'audio-play', 'UNRESOLVED-gstreamer1.0-alsa']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'audio-play', 'UNRESOLVED-gstreamer1.0-alsa']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'audio-play', 'UNRESOLVED-gstreamer1.0-alsa']
ERROR: Nothing PROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-safety_0.7.1-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-mavros_0.7.1-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-simple-waypoint_0.7.1-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-diagnostic_0.7.1-2.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'heifu-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-bringup', 'heifu-safety', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
NOTE: Runtime target 'heifu-safety' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-safety', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
NOTE: Runtime target 'heifu-mavros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-mavros', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
NOTE: Runtime target 'heifu-simple-waypoint' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-simple-waypoint', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
NOTE: Runtime target 'heifu-diagnostic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-diagnostic', '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
ERROR: Nothing PROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/roboticsgroup-upatras-gazebo-plugins/roboticsgroup-upatras-gazebo-plugins_0.2.0-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/gazebo-video-monitor-plugins/gazebo-video-monitor-plugins_0.4.2-1.bb DEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'roboticsgroup-upatras-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roboticsgroup-upatras-gazebo-plugins', 'gazebo-ros']
NOTE: Runtime target 'gazebo-video-monitor-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-video-monitor-plugins', 'gazebo-ros']
ERROR: Nothing PROVIDES 'UNRESOLVED-libboost-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ixblue-stdbin-decoder/ixblue-stdbin-decoder_0.1.2-1.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ixblue-ins-stdbin-driver/ixblue-ins-driver_0.1.3-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'ixblue-stdbin-decoder' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ixblue-stdbin-decoder', 'UNRESOLVED-libboost-dev']
NOTE: Runtime target 'ixblue-ins-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ixblue-ins-driver', 'ixblue-stdbin-decoder', 'UNRESOLVED-libboost-dev']
NOTE: Runtime target 'ixblue-ins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ixblue-ins', 'ixblue-ins-driver', 'ixblue-stdbin-decoder', 'UNRESOLVED-libboost-dev']
ERROR: Nothing PROVIDES 'image-view' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-tools_0.7.1-2.bb DEPENDS on or otherwise requires it)
image-view was skipped: Recipe is blacklisted: Depends on gtk+->x11
NOTE: Runtime target 'heifu-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-tools', 'image-view']
ERROR: Nothing PROVIDES 'dynamic-graph-python' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dynamic-graph-tutorial/dynamic-graph-tutorial_1.2.2-1.bb DEPENDS on or otherwise requires it)
dynamic-graph-python was skipped: Recipe is blacklisted: dynamic-graph-python: do_configure task fails:
NOTE: Runtime target 'dynamic-graph-tutorial' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dynamic-graph-tutorial', 'dynamic-graph-python']
ERROR: Nothing PROVIDES 'ixblue-stdbin-decoder' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ixblue-ins-stdbin-driver/ixblue-ins-driver_0.1.3-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'ixblue-stdbin-decoder'
ERROR: Nothing RPROVIDES 'heifu-bringup-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-bringup_0.7.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'heifu-bringup-dev'
NOTE: Runtime target 'heifu-bringup-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-bringup-dev']
ERROR: Nothing RPROVIDES 'ridgeback-gazebo-plugins' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dingo-simulator/dingo-gazebo_0.1.0-1.bb RDEPENDS on or otherwise requires it)
ridgeback-gazebo-plugins was skipped: Recipe is blacklisted: Depends on gazebo which is not available
NOTE: Runtime target 'ridgeback-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ridgeback-gazebo-plugins']
NOTE: Runtime target 'dingo-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dingo-gazebo', 'ridgeback-gazebo-plugins']
NOTE: Runtime target 'dingo-simulator' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dingo-simulator', 'dingo-gazebo', 'ridgeback-gazebo-plugins']
ERROR: Nothing RPROVIDES 'gazebo-plugins' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dingo-simulator/dingo-gazebo_0.1.0-1.bb RDEPENDS on or otherwise requires it)
gazebo-plugins was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-rosdev which is not available
NOTE: Runtime target 'gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-plugins']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dingo-simulator/dingo-gazebo_0.1.0-1.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/roboticsgroup-upatras-gazebo-plugins/roboticsgroup-upatras-gazebo-plugins_0.2.0-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/gazebo-video-monitor-plugins/gazebo-video-monitor-plugins_0.4.2-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
ERROR: Nothing RPROVIDES 'gazebo-ros-control' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dingo-simulator/dingo-gazebo_0.1.0-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros-control was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-control']
ERROR: Nothing RPROVIDES 'dingo-gazebo-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dingo-simulator/dingo-gazebo_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dingo-gazebo-dev'
NOTE: Runtime target 'dingo-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dingo-gazebo-dev']
ERROR: Nothing RPROVIDES 'hector-gazebo-plugins' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dingo-simulator/dingo-gazebo_0.1.0-1.bb RDEPENDS on or otherwise requires it)
hector-gazebo-plugins was skipped: Recipe is blacklisted: Depends on gazebo which is not available
NOTE: Runtime target 'hector-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['hector-gazebo-plugins']
ERROR: Nothing RPROVIDES 'audio-play-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.7-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'audio-play-dev'
NOTE: Runtime target 'audio-play-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-play-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-gstreamer1.0-alsa' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.7-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-gstreamer1.0-alsa' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-gstreamer1.0-alsa']
ERROR: Nothing RPROVIDES '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-safety_0.7.1-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-mavros_0.7.1-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-simple-waypoint_0.7.1-2.bb, /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-diagnostic_0.7.1-2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${ROS_UNRESOLVED_PLATFORM_PKG_ros_utils}']
ERROR: Nothing RPROVIDES 'heifu-safety-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-safety_0.7.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'heifu-safety-dev'
NOTE: Runtime target 'heifu-safety-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-safety-dev']
ERROR: Nothing RPROVIDES 'roboticsgroup-upatras-gazebo-plugins-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/roboticsgroup-upatras-gazebo-plugins/roboticsgroup-upatras-gazebo-plugins_0.2.0-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'roboticsgroup-upatras-gazebo-plugins-dev'
NOTE: Runtime target 'roboticsgroup-upatras-gazebo-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roboticsgroup-upatras-gazebo-plugins-dev']
ERROR: Nothing RPROVIDES 'dingo-simulator-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dingo-simulator/dingo-simulator_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dingo-simulator-dev'
NOTE: Runtime target 'dingo-simulator-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dingo-simulator-dev']
ERROR: Nothing RPROVIDES 'gazebo-video-monitor-plugins-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/gazebo-video-monitor-plugins/gazebo-video-monitor-plugins_0.4.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gazebo-video-monitor-plugins-dev'
NOTE: Runtime target 'gazebo-video-monitor-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-video-monitor-plugins-dev']
ERROR: Nothing RPROVIDES 'ixblue-stdbin-decoder-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ixblue-stdbin-decoder/ixblue-stdbin-decoder_0.1.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ixblue-stdbin-decoder-dev'
NOTE: Runtime target 'ixblue-stdbin-decoder-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ixblue-stdbin-decoder-dev']
ERROR: Nothing RPROVIDES 'image-view' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-tools_0.7.1-2.bb RDEPENDS on or otherwise requires it)
image-view was skipped: Recipe is blacklisted: Depends on gtk+->x11
NOTE: Runtime target 'image-view' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-view']
ERROR: Nothing RPROVIDES 'heifu-tools-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-tools_0.7.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'heifu-tools-dev'
NOTE: Runtime target 'heifu-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-tools-dev']
ERROR: Nothing RPROVIDES 'gtest' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/core-perception/points-preprocessor_1.14.9-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'gtest' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gtest']
NOTE: Runtime target 'points-preprocessor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['points-preprocessor', 'gtest']
ERROR: Nothing RPROVIDES 'points-preprocessor-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/core-perception/points-preprocessor_1.14.9-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'points-preprocessor-dev'
NOTE: Runtime target 'points-preprocessor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['points-preprocessor-dev']
ERROR: Nothing RPROVIDES 'ixblue-ins-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ixblue-ins-stdbin-driver/ixblue-ins_0.1.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ixblue-ins-dev'
NOTE: Runtime target 'ixblue-ins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ixblue-ins-dev']
ERROR: Nothing RPROVIDES 'dynamic-graph-tutorial-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dynamic-graph-tutorial/dynamic-graph-tutorial_1.2.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dynamic-graph-tutorial-dev'
NOTE: Runtime target 'dynamic-graph-tutorial-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dynamic-graph-tutorial-dev']
ERROR: Nothing RPROVIDES 'rviz' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dingo-desktop/dingo-viz_0.1.0-1.bb RDEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz']
NOTE: Runtime target 'dingo-viz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dingo-viz', 'rviz']
NOTE: Runtime target 'dingo-desktop' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dingo-desktop', 'dingo-viz', 'rviz']
NOTE: Runtime target 'dingo-viz-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dingo-viz-dev', 'rviz']
ERROR: Nothing RPROVIDES 'ixblue-ins-driver-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ixblue-ins-stdbin-driver/ixblue-ins-driver_0.1.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ixblue-ins-driver-dev'
NOTE: Runtime target 'ixblue-ins-driver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ixblue-ins-driver-dev']
ERROR: Nothing RPROVIDES 'heifu-mavros-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-mavros_0.7.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'heifu-mavros-dev'
NOTE: Runtime target 'heifu-mavros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-mavros-dev']
ERROR: Nothing RPROVIDES 'heifu-simple-waypoint-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-simple-waypoint_0.7.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'heifu-simple-waypoint-dev'
NOTE: Runtime target 'heifu-simple-waypoint-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-simple-waypoint-dev']
ERROR: Nothing RPROVIDES 'heifu-diagnostic-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/heifu/heifu-diagnostic_0.7.1-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'heifu-diagnostic-dev'
NOTE: Runtime target 'heifu-diagnostic-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['heifu-diagnostic-dev']
ERROR: Nothing RPROVIDES 'dingo-desktop-dev' (but /jenkins/mjansa/build/ros/webos-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/dingo-desktop/dingo-desktop_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dingo-desktop-dev'
NOTE: Runtime target 'dingo-desktop-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dingo-desktop-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>