{rolling} resolve dependency issues in new recipes
ERROR: Nothing PROVIDES 'qtx11extras' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'rviz-visual-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-tools', 'qtx11extras']
NOTE: Runtime target 'packagegroup-ros-world-rolling' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-rolling', 'rviz-visual-tools', 'qtx11extras']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'rviz-visual-tools', 'qtx11extras']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'rviz-visual-tools', 'qtx11extras']
ERROR: Nothing PROVIDES 'rviz-ogre-vendor' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.0-1.bb DEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-clang' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/zenoh-bridge-dds/zenoh-bridge-dds_0.5.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'zenoh-bridge-dds' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['zenoh-bridge-dds', 'ROS_UNRESOLVED_DEP-clang']
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-cargo' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/zenoh-bridge-dds/zenoh-bridge-dds_0.5.0-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'qtx11extras' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtx11extras' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtx11extras']
ERROR: Nothing RPROVIDES 'rviz-visual-tools-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-visual-tools-dev'
NOTE: Runtime target 'rviz-visual-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-tools-dev']
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.0-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
ERROR: Nothing RPROVIDES 'rviz-ogre-vendor' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/rviz-visual-tools/rviz-visual-tools_4.1.0-1.bb RDEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-ogre-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-ogre-vendor']
ERROR: Nothing RPROVIDES 'gazebo-plugins' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/aws-robomaker-small-warehouse-world/aws-robomaker-small-warehouse-world_1.0.1-1.bb RDEPENDS on or otherwise requires it)
gazebo-plugins was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-plugins']
NOTE: Runtime target 'aws-robomaker-small-warehouse-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['aws-robomaker-small-warehouse-world', 'gazebo-plugins']
NOTE: Runtime target 'aws-robomaker-small-warehouse-world-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['aws-robomaker-small-warehouse-world-dev', 'gazebo-plugins']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/aws-robomaker-small-warehouse-world/aws-robomaker-small-warehouse-world_1.0.1-1.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: gazebo: depends on gazebo-rosdev->gazebo which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-gazebo' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/aws-robomaker-small-warehouse-world/aws-robomaker-small-warehouse-world_1.0.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-gazebo']
ERROR: Nothing RPROVIDES 'zenoh-bridge-dds-dev' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/zenoh-bridge-dds/zenoh-bridge-dds_0.5.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'zenoh-bridge-dds-dev'
NOTE: Runtime target 'zenoh-bridge-dds-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['zenoh-bridge-dds-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>