{foxy} rc-dynamics-api: unblacklist and fix
* add dependency on protobuf-native:, because
  it tries to run js_embed and fails with:
  /bin/sh: js_embed: command not found
  and it does depend only on target protobuf

* inherit ros_insane_dev_so to ignore dev-so QA issue
  ERROR: rc-dynamics-api-0.10.3-1-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so: rc-dynamics-api path '/work/core2-64-oe-linux/rc-dynamics-api/0.10.3-1-r0/packages-split/rc-dynamics-api/usr/lib/librc_dynamics_api.so' [dev-so]

* js_embed was removed in 3.15.0-rc1 with:
  https://github.com/protocolbuffers/protobuf/commit/143851ed257b7c24e945396cb4acc0da697dff65
  but with 3.15.2 version in meta-oe[hardknott] it still works somehow without it:
  rc-dynamics-api/0.10.3-1-r0$ find . -name js_embed

  there is no direct all in rc-dynamics-api source (except the bundled protobuf sources)
  so it probably correcly uses protobuf from OE instead of this bundled copy and then
  the 3.15.2 just doesn't call js_embed during build anymore as it removed.

rc-dynamics-api/0.10.3-1-r0/git$ git grep js_embed
rc_dynamics_api/opt/protobuf/BUILD:    name = "js_embed",
rc_dynamics_api/opt/protobuf/BUILD:    cmd = "$(location :js_embed) $(SRCS) > $@",
rc_dynamics_api/opt/protobuf/BUILD:    tools = [":js_embed"],
rc_dynamics_api/opt/protobuf/cmake/libprotoc.cmake:add_executable(js_embed ${protobuf_source_dir}/src/google/protobuf/compiler/js/embed.cc)
rc_dynamics_api/opt/protobuf/cmake/libprotoc.cmake:  DEPENDS js_embed ${js_well_known_types_sources}
rc_dynamics_api/opt/protobuf/cmake/libprotoc.cmake:  COMMAND js_embed ${js_well_known_types_sources} > ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types_embed.cc
rc_dynamics_api/opt/protobuf/src/Makefile.am:             js_embed$(EXEEXT)
rc_dynamics_api/opt/protobuf/src/Makefile.am:# to build the js_embed binary using $(CXX_FOR_BUILD) so that it is executable
rc_dynamics_api/opt/protobuf/src/Makefile.am:js_embed$(EXEEXT): $(srcdir)/google/protobuf/compiler/js/embed.cc
rc_dynamics_api/opt/protobuf/src/Makefile.am:google/protobuf/compiler/js/well_known_types_embed.cc: js_embed$(EXEEXT) $(js_well_known_types_sources)
rc_dynamics_api/opt/protobuf/src/Makefile.am:   $$oldpwd/js_embed$(EXEEXT) $(js_well_known_types_sources) > $$oldpwd/$@

Signed-off-by: Martin Jansa <martin.jansa@lge.com>