{melodic} add new ROS_WORLD_SKIP_GROUPS element pyassimp and blacklist recipes depending on python-pyassimp
* there are many more recipes depending python-pyassimp, convert it to
  ROS_WORLD_SKIP_GROUPS

ERROR: Nothing PROVIDES 'UNRESOLVED-python-pyassimp' (but generated-recipes/exotica/exotica-python_5.0.0.bb DEPENDS on or otherwise requires it)
Missing or unbuildable dependency chain was: ['exotica-ompl-solver', 'exotica-python', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'exotica-ompl-solver', 'exotica-python', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'exotica-ompl-solver', 'exotica-python', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'exotica-ompl-solver', 'exotica-python', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['exotica', 'exotica-ompl-solver', 'exotica-python', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['exotica-examples', 'exotica-ompl-solver', 'exotica-python', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['exotica-core-task-maps', 'exotica-python', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['exotica-python', 'UNRESOLVED-python-pyassimp']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python-pyassimp' (but generated-recipes/exotica/exotica-python_5.0.0.bb, generated-recipes/moveit/moveit-commander_1.0.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python-pyassimp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['pilz-robot-programming', 'moveit-commander', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['pilz-industrial-motion', 'pilz-robot-programming', 'moveit-commander', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['pilz-robot-programming-dev', 'moveit-commander', 'UNRESOLVED-python-pyassimp']
Missing or unbuildable dependency chain was: ['moveit-commander', 'UNRESOLVED-python-pyassimp']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>