{foxy} resolve dependency issues in new recipes
ERROR: Nothing RPROVIDES 'nav2-bringup' (but /jenkins/mjansa/build/ros/webos-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/mppic/mppic_0.2.1-2.bb RDEPENDS on or otherwise requires it)
nav2-bringup was skipped: Recipe is blacklisted: qt5: depends on slam-toolbox which depends on qtbase; x11: depends on slam-toolbox which depends on rviz-common->rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES; opengl: depends on navigation2 which depends on nav2-rviz-plugins which depends on rviz-common, rviz-rendering, rviz-default-plugins which depend on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES
NOTE: Runtime target 'nav2-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup']
NOTE: Runtime target 'mppic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mppic', 'nav2-bringup']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'mppic', 'nav2-bringup']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'mppic', 'nav2-bringup']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'mppic', 'nav2-bringup']
NOTE: Runtime target 'mppic-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mppic-dev', 'nav2-bringup']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>