python3-argcomplete: backport 1.12.1 from gatesgarth
* instead of older 1.9.4 imported from meta-iot-cloud
* the one backported from meta-oe also has native BBCLASSEXTEND to fix:

ERROR: Nothing RPROVIDES 'python3-argcomplete-native' (but virtual:native:meta-ros/meta-ros2-rolling/generated-recipes/rosidl/rosidl-cli_2.2.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-argcomplete-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-argcomplete-native']
NOTE: Runtime target 'rosidl-cli-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosidl-cli-native', 'python3-argcomplete-native']
NOTE: Runtime target 'ros1-rosbag-storage-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros1-rosbag-storage-vendor', 'ros1-bridge', 'trajectory-msgs', 'rosidl-typesupport-fastrtps-cpp-native', 'rosidl-cli-native', 'python3-argcomplete-native']
NOTE: Runtime target 'packagegroup-ros-world-rolling' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-rolling', 'ros1-rosbag-storage-vendor', 'ros1-bridge', 'trajectory-msgs', 'rosidl-typesupport-fastrtps-cpp-native', 'rosidl-cli-native', 'python3-argcomplete-native']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'ros1-rosbag-storage-vendor', 'ros1-bridge', 'trajectory-msgs', 'rosidl-typesupport-fastrtps-cpp-native', 'rosidl-cli-native', 'python3-argcomplete-native']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-rolling', 'ros1-rosbag-storage-vendor', 'ros1-bridge', 'trajectory-msgs', 'rosidl-typesupport-fastrtps-cpp-native', 'rosidl-cli-native', 'python3-argcomplete-native']
....

Signed-off-by: Martin Jansa <martin.jansa@lge.com>