{foxy} image-proc, image-publisher: blacklist, because depend on opencv4
* fixes:

ERROR: image-proc-2.1.1-1-r0 do_configure: Function failed: do_configure (log file is located at image-proc/2.1.1-1-r0/temp/log.do_configure.57024)
ERROR: Logfile of failure stored in: image-proc/2.1.1-1-r0/temp/log.do_configure.57024
Log data follows:
| DEBUG: Executing shell function do_configure
| -- The C compiler identification is GNU 8.3.0
| -- The CXX compiler identification is GNU 8.3.0
| -- Check for working C compiler: image-proc/2.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
| -- Check for working C compiler: image-proc/2.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Check for working CXX compiler: image-proc/2.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
| -- Check for working CXX compiler: image-proc/2.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Detecting CXX compile features
| -- Detecting CXX compile features - done
| -- Found ament_cmake: 0.9.6 (image-proc/2.1.1-1-r0/recipe-sysroot-native/usr/share/ament_cmake/cmake)
| -- Found PythonInterp: image-proc/2.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.7", minimum required is "3")
| -- Using PYTHON_EXECUTABLE: image-proc/2.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
| -- Found rclcpp: 2.0.1 (image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rclcpp/cmake)
| -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
| CMake Warning at image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmake-extras.cmake:30 (find_package):
|   By not providing "Findrosidl_adapter.cmake" in CMAKE_MODULE_PATH this
|   project has asked CMake to find a package configuration file provided by
|   "rosidl_adapter", but CMake did not find one.
|
|   Could not find a package configuration file provided by "rosidl_adapter"
|   with any of the following names:
|
|     rosidl_adapterConfig.cmake
|     rosidl_adapter-config.cmake
|
|   Add the installation prefix of "rosidl_adapter" to CMAKE_PREFIX_PATH or set
|   "rosidl_adapter_DIR" to a directory containing one of the above files.  If
|   "rosidl_adapter" provides a separate development package or SDK, be sure it
|   has been installed.
| Call Stack (most recent call first):
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmakeConfig.cmake:41 (include)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/rosidl_generator_cConfig.cmake:41 (include)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_c-extras.cmake:11 (find_package)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_cConfig.cmake:41 (include)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtime-extras.cmake:12 (find_package)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtimeConfig.cmake:41 (include)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/builtin_interfacesConfig.cmake:41 (include)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/rcl_interfacesConfig.cmake:41 (include)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rcl/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rcl/cmake/rclConfig.cmake:41 (include)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/libstatistics_collector/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/libstatistics_collector/cmake/libstatistics_collectorConfig.cmake:41 (include)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rclcpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rclcpp/cmake/rclcppConfig.cmake:41 (include)
|   CMakeLists.txt:15 (find_package)
|
|
| -- Found OpenSSL: image-proc/2.1.1-1-r0/recipe-sysroot/usr/lib/libcrypto.so (found version "1.1.1g")
| -- Found FastRTPS: image-proc/2.1.1-1-r0/recipe-sysroot/usr/include
| -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
| -- Found rmw_implementation_cmake: 1.0.1 (image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rmw_implementation_cmake/cmake)
| -- Using RMW implementation 'rmw_fastrtps_cpp' as default
| -- Looking for pthread.h
| -- Looking for pthread.h - found
| -- Looking for pthread_create
| -- Looking for pthread_create - not found
| -- Looking for pthread_create in pthreads
| -- Looking for pthread_create in pthreads - not found
| -- Looking for pthread_create in pthread
| -- Looking for pthread_create in pthread - found
| -- Found Threads: TRUE
| -- Found rclcpp_components: 2.0.1 (image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/rclcpp_components/cmake)
| -- Found cv_bridge: 2.2.0 (image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/cv_bridge/cmake)
| -- Found image_transport: 2.3.0 (image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/image_transport/cmake)
| CMake Error at CMakeLists.txt:21 (find_package):
|   Could not find a configuration file for package "OpenCV" that is compatible
|   with requested version "4".
|
|   The following configuration files were considered but not accepted:
|
|     image-proc/2.1.1-1-r0/recipe-sysroot/usr/share/OpenCV/OpenCVConfig.cmake, version: 3.4.5
|
|
|
| -- Configuring incomplete, errors occurred!
| See also "image-proc/2.1.1-1-r0/build/CMakeFiles/CMakeOutput.log".
| See also "image-proc/2.1.1-1-r0/build/CMakeFiles/CMakeError.log".
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at image-proc/2.1.1-1-r0/temp/log.do_configure.57024)
NOTE: recipe image-proc-2.1.1-1-r0: task do_configure: Failed
ERROR: Task (/jenkins/mjansa/build/ros/ros2-foxy-warrior/meta-ros/meta-ros2-foxy/generated-recipes/image-pipeline/image-proc_2.1.1-1.bb:do_configure) failed with exit code '1'

ERROR: image-publisher-2.1.1-1-r0 do_configure: Function failed: do_configure (log file is located at image-publisher/2.1.1-1-r0/temp/log.do_configure.57093)
ERROR: Logfile of failure stored in: image-publisher/2.1.1-1-r0/temp/log.do_configure.57093
Log data follows:
| DEBUG: Executing shell function do_configure
| -- The C compiler identification is GNU 8.3.0
| -- The CXX compiler identification is GNU 8.3.0
| -- Check for working C compiler: image-publisher/2.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
| -- Check for working C compiler: image-publisher/2.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Check for working CXX compiler: image-publisher/2.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
| -- Check for working CXX compiler: image-publisher/2.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Detecting CXX compile features
| -- Detecting CXX compile features - done
| -- Found ament_cmake: 0.9.6 (image-publisher/2.1.1-1-r0/recipe-sysroot-native/usr/share/ament_cmake/cmake)
| -- Found PythonInterp: image-publisher/2.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.7", minimum required is "3")
| -- Using PYTHON_EXECUTABLE: image-publisher/2.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
| -- Found cv_bridge: 2.2.0 (image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/cv_bridge/cmake)
| -- Found camera_info_manager: 2.3.0 (image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/camera_info_manager/cmake)
| -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
| CMake Warning at image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmake-extras.cmake:30 (find_package):
|   By not providing "Findrosidl_adapter.cmake" in CMAKE_MODULE_PATH this
|   project has asked CMake to find a package configuration file provided by
|   "rosidl_adapter", but CMake did not find one.
|
|   Could not find a package configuration file provided by "rosidl_adapter"
|   with any of the following names:
|
|     rosidl_adapterConfig.cmake
|     rosidl_adapter-config.cmake
|
|   Add the installation prefix of "rosidl_adapter" to CMAKE_PREFIX_PATH or set
|   "rosidl_adapter_DIR" to a directory containing one of the above files.  If
|   "rosidl_adapter" provides a separate development package or SDK, be sure it
|   has been installed.
| Call Stack (most recent call first):
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmakeConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/rosidl_generator_cConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_c-extras.cmake:11 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_cConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtime-extras.cmake:12 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtimeConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/builtin_interfacesConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/rcl_interfacesConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rcl/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rcl/cmake/rclConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/libstatistics_collector/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/libstatistics_collector/cmake/libstatistics_collectorConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rclcpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rclcpp/cmake/rclcppConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/camera_calibration_parsers/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/camera_calibration_parsers/cmake/camera_calibration_parsersConfig.cmake:41 (include)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/camera_info_manager/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
|   image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/camera_info_manager/cmake/camera_info_managerConfig.cmake:41 (include)
|   CMakeLists.txt:15 (find_package)
|
|
| -- Found OpenSSL: image-publisher/2.1.1-1-r0/recipe-sysroot/usr/lib/libcrypto.so (found version "1.1.1g")
| -- Found FastRTPS: image-publisher/2.1.1-1-r0/recipe-sysroot/usr/include
| -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
| -- Found rmw_implementation_cmake: 1.0.1 (image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rmw_implementation_cmake/cmake)
| -- Using RMW implementation 'rmw_fastrtps_cpp' as default
| -- Looking for pthread.h
| -- Looking for pthread.h - found
| -- Looking for pthread_create
| -- Looking for pthread_create - not found
| -- Looking for pthread_create in pthreads
| -- Looking for pthread_create in pthreads - not found
| -- Looking for pthread_create in pthread
| -- Looking for pthread_create in pthread - found
| -- Found Threads: TRUE
| -- Setting yaml-cpp_DIR to: 'image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/yaml_cpp_vendor/cmake/../../../opt/yaml_cpp_vendor/lib/cmake/yaml-cpp'
| -- Found image_transport: 2.3.0 (image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/image_transport/cmake)
| -- Found image_geometry: 2.2.0 (image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/image_geometry/cmake)
| -- Found rclcpp_components: 2.0.1 (image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/rclcpp_components/cmake)
| -- Found OpenCV: image-publisher/2.1.1-1-r0/recipe-sysroot/usr (found version "3.4.5") found components:  core
| -- opencv version 3.4.5
| CMake Error at CMakeLists.txt:34 (find_package):
|   Could not find a configuration file for package "OpenCV" that is compatible
|   with requested version "4".
|
|   The following configuration files were considered but not accepted:
|
|     image-publisher/2.1.1-1-r0/recipe-sysroot/usr/share/OpenCV/OpenCVConfig.cmake, version: 3.4.5
|
|
|
| -- Configuring incomplete, errors occurred!
| See also "image-publisher/2.1.1-1-r0/build/CMakeFiles/CMakeOutput.log".
| See also "image-publisher/2.1.1-1-r0/build/CMakeFiles/CMakeError.log".
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at image-publisher/2.1.1-1-r0/temp/log.do_configure.57093)
NOTE: recipe image-publisher-2.1.1-1-r0: task do_configure: Failed