{noetic} face-detector: add missing dependencies
* fixes:
FAILED: CMakeFiles/face_detector.dir/src/face_detection.cpp.o
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"face_detector\" -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/devel/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/git/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/recipe-sysroot/usr/include/opencv4 -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/recipe-sysroot/usr/opt/ros/noetic/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/recipe-sysroot/usr/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0=/usr/src/debug/face-detector/1.4.0-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0=/usr/src/debug/face-detector/1.4.0-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/recipe-sysroot -D_FILE_OFFSET_BITS=64 -MD -MT CMakeFiles/face_detector.dir/src/face_detection.cpp.o -MF CMakeFiles/face_detector.dir/src/face_detection.cpp.o.d -o CMakeFiles/face_detector.dir/src/face_detection.cpp.o -c TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/git/src/face_detection.cpp
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/face-detector/1.4.0-1-r0/git/src/face_detection.cpp:79:10: fatal error: yaml-cpp/yaml.h: No such file or directory
   79 | #include <yaml-cpp/yaml.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>