graphviz: fetch with git fetcher
* gitlab archives aren't stable and QA check was updated to catch them not only
  from github, but gitlab as well in:
  https://git.openembedded.org/openembedded-core/commit/?id=d76b33c6a8489378a1f5500554367127199ae19d
* fixes QA error:
  ERROR: graphviz-2.40.1-r0 do_package_qa: QA Issue: graphviz: SRC_URI uses unstable GitHub/GitLab archives, convert recipe to use git protocol [src-uri-bad]

Signed-off-by: Martin Jansa <martin.jansa@lge.com>