{melodic} jderobot-camviz: add dependency on gtkmm3
* fixes:
DEBUG: Executing shell function do_compile
NOTE: VERBOSE=1 cmake --build ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/build --target all -- -j 32
[1/3] ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DGLADE_DIR=\"\" -DROS1S_H -DROS1_H -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"jderobot_camviz\" -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/usr/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/usr/include/opencv -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0=/usr/src/debug/jderobot-camviz/0.1.0-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot -g   -Wall -Wextra -Wpedantic -Wunused-parameter -std=gnu++14 -MD -MT CMakeFiles/camViz.dir/viewer.cpp.o -MF CMakeFiles/camViz.dir/viewer.cpp.o.d -o CMakeFiles/camViz.dir/viewer.cpp.o -c ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/git/viewer.cpp
FAILED: CMakeFiles/camViz.dir/viewer.cpp.o
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DGLADE_DIR=\"\" -DROS1S_H -DROS1_H -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"jderobot_camviz\" -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/usr/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/usr/include/opencv -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0=/usr/src/debug/jderobot-camviz/0.1.0-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot -g   -Wall -Wextra -Wpedantic -Wunused-parameter -std=gnu++14 -MD -MT CMakeFiles/camViz.dir/viewer.cpp.o -MF CMakeFiles/camViz.dir/viewer.cpp.o.d -o CMakeFiles/camViz.dir/viewer.cpp.o -c ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/git/viewer.cpp
In file included from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/git/viewer.cpp:22:
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/git/viewer.h:25:10: fatal error: gtkmm.h: No such file or directory
 #include <gtkmm.h>
          ^~~~~~~~~
compilation terminated.
[2/3] ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DGLADE_DIR=\"\" -DROS1S_H -DROS1_H -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"jderobot_camviz\" -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/usr/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/usr/include/opencv -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0=/usr/src/debug/jderobot-camviz/0.1.0-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot -g   -Wall -Wextra -Wpedantic -Wunused-parameter -std=gnu++14 -MD -MT CMakeFiles/camViz.dir/camViz.cpp.o -MF CMakeFiles/camViz.dir/camViz.cpp.o.d -o CMakeFiles/camViz.dir/camViz.cpp.o -c ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/git/camViz.cpp
FAILED: CMakeFiles/camViz.dir/camViz.cpp.o
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DGLADE_DIR=\"\" -DROS1S_H -DROS1_H -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"jderobot_camviz\" -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/usr/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot/usr/include/opencv -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0=/usr/src/debug/jderobot-camviz/0.1.0-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/recipe-sysroot -g   -Wall -Wextra -Wpedantic -Wunused-parameter -std=gnu++14 -MD -MT CMakeFiles/camViz.dir/camViz.cpp.o -MF CMakeFiles/camViz.dir/camViz.cpp.o.d -o CMakeFiles/camViz.dir/camViz.cpp.o -c ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/git/camViz.cpp
In file included from ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/git/camViz.cpp:4:
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/git/viewer.h:25:10: fatal error: gtkmm.h: No such file or directory
 #include <gtkmm.h>
          ^~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/jderobot-camviz/0.1.0-1-r0/temp/log.do_compile.36674)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>