{rolling} joy: add missing dependency on rosidl-adapter and update the patch for finding SDL2
* fixes CMake warning:
CMake Warning at /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmake-extras.cmake:30 (find_package):
  By not providing "Findrosidl_adapter.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "rosidl_adapter", but CMake did not find one.

  Could not find a package configuration file provided by "rosidl_adapter"
  with any of the following names:

    rosidl_adapterConfig.cmake
    rosidl_adapter-config.cmake

  Add the installation prefix of "rosidl_adapter" to CMAKE_PREFIX_PATH or set
  "rosidl_adapter_DIR" to a directory containing one of the above files.  If
  "rosidl_adapter" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmakeConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/rosidl_generator_cConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_c-extras.cmake:11 (find_package)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_cConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtime-extras.cmake:12 (find_package)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtimeConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/builtin_interfacesConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/rcl_interfacesConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rcl/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rcl/cmake/rclConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/libstatistics_collector/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/libstatistics_collector/cmake/libstatistics_collectorConfig.cmake:41 (include)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rclcpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build/ros/webos-rolling-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot/usr/share/rclcpp/cmake/rclcppConfig.cmake:41 (include)
  CMakeLists.txt:14 (find_package)

and fixes do_compile issue:

FAILED: CMakeFiles/joy_enumerate_devices.dir/src/joy_enumerate_devices.cpp.o
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DROS_PACKAGE_NAME=\"joy\" -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/git/include -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0=/usr/src/debug/joy/3.0.0-2-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0=/usr/src/debug/joy/3.0.0-2-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot -Wall -Wextra -Wpedantic -std=gnu++14 -MD -MT CMakeFiles/joy_enumerate_devices.dir/src/joy_enumerate_devices.cpp.o -MF CMakeFiles/joy_enumerate_devices.dir/src/joy_enumerate_devices.cpp.o.d -o CMakeFiles/joy_enumerate_devices.dir/src/joy_enumerate_devices.cpp.o -c TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/git/src/joy_enumerate_devices.cpp
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/git/src/joy_enumerate_devices.cpp:32:10: fatal error: SDL.h: No such file or directory
   32 | #include <SDL.h>
      |          ^~~~~~~

FAILED: CMakeFiles/joy.dir/src/joy.cpp.o
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DDEFAULT_RMW_IMPLEMENTATION=rmw_cyclonedds_cpp -DROS_PACKAGE_NAME=\"joy\" -Djoy_EXPORTS -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/git/include -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0=/usr/src/debug/joy/3.0.0-2-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0=/usr/src/debug/joy/3.0.0-2-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/recipe-sysroot -fPIC -Wall -Wextra -Wpedantic -std=gnu++14 -MD -MT CMakeFiles/joy.dir/src/joy.cpp.o -MF CMakeFiles/joy.dir/src/joy.cpp.o.d -o CMakeFiles/joy.dir/src/joy.cpp.o -c TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/git/src/joy.cpp
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/joy/3.0.0-2-r0/git/src/joy.cpp:30:10: fatal error: SDL.h: No such file or directory
   30 | #include <SDL.h>
      |          ^~~~~~~

Signed-off-by: Martin Jansa <martin.jansa@lge.com>