{dashing} cartographer: work around linking failure with bfd
* when bfd is used, the linking fails with:
FAILED: cartographer.sensor.internal.voxel_filter_test
: && /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot-native/usr/bin/i586-oe-linux/i586-oe-linux-g++  -m32 -march=i586  --sysroot=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0=/usr/src/debug/cartographer/1.0.0-1-r0 -fdebug-prefix-map=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot= -fdebug-prefix-map=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m32 -march=i586  --sysroot=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot -DNDEBUG  -m32 -march=i586  --sysroot=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0=/usr/src/debug/cartographer/1.0.0-1-r0 -fdebug-prefix-map=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot= -fdebug-prefix-map=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m32 -march=i586  --sysroot=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed   -rdynamic CMakeFiles/cartographer.sensor.internal.voxel_filter_test.dir/cartographer/sensor/internal/voxel_filter_test.cc.o  -o cartographer.sensor.internal.voxel_filter_test  libcartographer.a -Wl,-Bstatic -lgmock_main -Wl,-Bdynamic -lpthread libcartographer_test_library.a -ldl libcartographer.a /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot/usr/lib/libceres.a /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot/usr/lib/libglog.so.0.3.5 -lunwind -lunwind-x86 -lspqr -lcholmod -lccolamd -lcamd -lcolamd -lamd -llapack -lblas -lsuitesparseconfig -lrt -lmetis -lcxsparse -llapack -lblas -lsuitesparseconfig -lrt -lmetis -lcxsparse -lgomp -lpthread -Wl,-Bstatic -llua -Wl,-Bdynamic -lm -lboost_iostreams-mt -lboost_regex-mt -lglog -lgflags -lcairo -lprotobuf -lpthread && :
/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot-native/usr/bin/i586-oe-linux/../../libexec/i586-oe-linux/gcc/i586-oe-linux/8.2.0/ld: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_sym':
/usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:134: undefined reference to `dlsym'
/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot-native/usr/bin/i586-oe-linux/../../libexec/i586-oe-linux/gcc/i586-oe-linux/8.2.0/ld: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_load':
/usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:127: undefined reference to `dlopen'
/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot-native/usr/bin/i586-oe-linux/../../libexec/i586-oe-linux/gcc/i586-oe-linux/8.2.0/ld: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_sym':
/usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:135: undefined reference to `dlerror'
/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot-native/usr/bin/i586-oe-linux/../../libexec/i586-oe-linux/gcc/i586-oe-linux/8.2.0/ld: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_load':
/usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:128: undefined reference to `dlerror'
/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot-native/usr/bin/i586-oe-linux/../../libexec/i586-oe-linux/gcc/i586-oe-linux/8.2.0/ld: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/i586-oe-linux/cartographer/1.0.0-1-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_unloadlib':
/usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:122: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

* use gold as a work around (used by default in webOS)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>