ros-python2-recipe-blacklist.inc: unblacklist rpi-gpio, rpio, python-pyassimp
* python-pyassimp was moved to separate meta-ros-python2 layer in:
  commit 7ec08231b530ac5f3be55171fabe234e7b8ebe2e
  Author: Martin Jansa <martin.jansa@lge.com>
  Date:   Wed Sep 30 05:34:24 2020 -0700

    meta-ros-python2: move python2 specific recipes to separate later

    * now with noetic support, not all ROS 1 distros use python2
    * lets move it to separate layer used only by ROS 1 melodic

* rpi-gpio uses python3 since:
  commit e57d33298c7ce15aee476380f8afd37a0c352a17
  Author: Pierre-Jean Texier <pjtexier@koncepto.io>
  Date:   Tue Dec 24 11:41:01 2019 +0000

    rpi-gpio: bump to version 0.7.0

    Also:
      - update the HOMEPAGE location
      - refresh patch
      - use 'distutils3' to support python3 -> python2 is now deprecated

* rpio uses python3 since:
  commit 2a1a8e396a7feba2b378cb066f023cd593335602
  Author: Khem Raj <raj.khem@gmail.com>
  Date:   Sun Jan 19 17:57:33 2020 -0800

    rpio: Use python3 during build

* fixes new meta-raspberrypi recipes which depends on rpi-gpio:
  ERROR: Nothing RPROVIDES 'rpi-gpio' (but meta-raspberrypi/recipes-devtools/python/python3-adafruit-blinka_6.2.2.bb RDEPENDS on or otherwise requires it)
  rpi-gpio was skipped: Recipe is blacklisted: Depends on blacklisted python2
  NOTE: Runtime target 'rpi-gpio' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['rpi-gpio']
  NOTE: Runtime target 'python3-adafruit-blinka' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python3-adafruit-blinka', 'rpi-gpio']
  NOTE: Runtime target 'python3-adafruit-circuitpython-motor-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-motor-dev', 'python3-adafruit-blinka', 'rpi-gpio']
  NOTE: Runtime target 'python3-adafruit-circuitpython-motor' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-motor', 'python3-adafruit-blinka', 'rpi-gpio']
  NOTE: Runtime target 'python3-adafruit-circuitpython-pca9685-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-pca9685-dev', 'python3-adafruit-blinka', 'rpi-gpio']
  NOTE: Runtime target 'python3-adafruit-circuitpython-pca9685' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-pca9685', 'python3-adafruit-blinka', 'rpi-gpio']
  NOTE: Runtime target 'python3-adafruit-circuitpython-busdevice' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-busdevice', 'python3-adafruit-blinka', 'rpi-gpio']
  NOTE: Runtime target 'python3-adafruit-circuitpython-busdevice-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-busdevice-dev', 'python3-adafruit-blinka', 'rpi-gpio']
  NOTE: Runtime target 'python3-adafruit-blinka-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python3-adafruit-blinka-dev', 'rpi-gpio']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>