opencv: enable dnn PACKAGECONFIG required by noetic's dnn-detect
* fixes:
FAILED: CMakeFiles/dnn_detect.dir/src/dnn_detect.cpp.o
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME="dnn_detect" -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/devel/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/recipe-sysroot/usr/opt/ros/noetic/include -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/recipe-sysroot/usr/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -ITOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/recipe-sysroot/usr/include/opencv4 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0=/usr/src/debug/dnn-detect/0.1.0-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0=/usr/src/debug/dnn-detect/0.1.0-1-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/recipe-sysroot   -std=c++11 -MD -MT CMakeFiles/dnn_detect.dir/src/dnn_detect.cpp.o -MF CMakeFiles/dnn_detect.dir/src/dnn_detect.cpp.o.d -o CMakeFiles/dnn_detect.dir/src/dnn_detect.cpp.o -c TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/git/src/dnn_detect.cpp
TOPDIR/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/dnn-detect/0.1.0-1-r0/git/src/dnn_detect.cpp:45:10: fatal error: opencv2/dnn.hpp: No such file or directory
   45 | #include <opencv2/dnn.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.