{foxy} tvm-vendor: remove runtime dependency on devel only spirv-headers package
* fixes:
ERROR: webos-image-ros-world-1.0-r3 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-i
mage-ros-world/1.0-r3/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ro
s-world/1.0-r3/opkg.conf -t /jenkins/mjansa/build/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/temp/ipktemp/ -o /jenkins/mjansa/b
uild/ros/webos-foxy-hardknott/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-world/1.0-r3/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends
kernel-vmlinux --add-ignore-recommends update-rc.d install opkg packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-ros-world packagegroup-webos-extended run-
postinsts' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-ros-world-1.0-r0.qemux86 requires packagegroup-ros-world-foxy, but none of the providers can be installed
 *   - package packagegroup-ros-world-foxy-1.0-r0.qemux86 requires tvm-vendor, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides spirv-headers needed by tvm-vendor-0.7.3-1-r0.qemux86
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

Signed-off-by: Martin Jansa <martin.jansa@lge.com>