[master]{rolling}: add osrf-pycommon to ros-distro.inc
fixing the error when building ros-image-desktop:

  ERROR: Required build target 'ros-image-desktop' has no buildable providers.
  Missing or unbuildable dependency chain was: ['ros-image-desktop', 'desktop', 'dummy-robot-bringup', 'launch', 'ROS_UNRESOLVED_DEP-python3-osrf-pycommon']

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>