{rolling} plotjuggler-msgs: add missing dependencies
| FAILED: CMakeFiles/plotjuggler_msgs__rosidl_typesupport_cpp.dir/rosidl_typesupport_cpp/plotjuggler_msgs/msg/statistics_values__type_support.cpp.o
| /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DROS_PACKAGE_NAME=\"plotjuggler_msgs\" -Dplotjuggler_msgs__rosidl_typesupport_c
pp_EXPORTS -I/jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0/build/rosidl_generator_cpp -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wforma
t-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/bui
ld/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0=/usr/src/debug/plotjuggler-msgs/0.2.0-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plo
tjuggler-msgs/0.2.0-1-r0=/usr/src/debug/plotjuggler-msgs/0.2.0-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=
/jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -W
format -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0/recipe-sysroot -fPIC -Wall -std=gnu++14 -MD -MT CMakeFiles/plotjuggler_msgs__rosidl_
typesupport_cpp.dir/rosidl_typesupport_cpp/plotjuggler_msgs/msg/statistics_values__type_support.cpp.o -MF CMakeFiles/plotjuggler_msgs__rosidl_typesupport_cpp.dir/rosidl_typesupport_cpp/plotjuggler_msgs/msg/statistics_values__type_support.cpp.o.d -o CMakeFiles/plotjuggler_msgs__rosidl_type
support_cpp.dir/rosidl_typesupport_cpp/plotjuggler_msgs/msg/statistics_values__type_support.cpp.o -c /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0/build/rosidl_typesupport_cpp/plotjuggler_msgs/msg/statistics_va
lues__type_support.cpp
| In file included from /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0/build/rosidl_typesupport_cpp/plotjuggler_msgs/msg/statistics_values__type_support.cpp:7:
| /jenkins/mjansa/build/ros/webos-rolling-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/plotjuggler-msgs/0.2.0-1-r0/build/rosidl_generator_cpp/plotjuggler_msgs/msg/detail/statistics_values__struct.hpp:19:10: fatal error: std_msgs/msg/detail/header__struct.hpp: No such file or d
irectory
|    19 | #include "std_msgs/msg/detail/header__struct.hpp"
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Martin Jansa <martin.jansa@lge.com>