{galactic} resolve dependency issues in new recipes
* fixes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'ffmpeg' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/usb-cam/usb-cam_0.4.0-1.bb DEPENDS on or otherwise requires it)
ffmpeg was skipped: because it has a restricted license 'commercial'. Which is not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'usb-cam' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['usb-cam', 'ffmpeg']
NOTE: Runtime target 'packagegroup-ros-world-galactic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-galactic', 'usb-cam', 'ffmpeg']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-galactic', 'usb-cam', 'ffmpeg']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-galactic', 'usb-cam', 'ffmpeg']
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rmf-traffic-editor/rmf-traffic-editor_1.3.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
NOTE: Runtime target 'rmf-traffic-editor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-traffic-editor', 'qtbase']
ERROR: Nothing PROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/color-names/color-names_0.0.2-1.bb DEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'color-names' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['color-names', 'rviz2']
ERROR: Nothing PROVIDES 'qt-gui-cpp' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb DEPENDS on or otherwise requires it)
qt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qtbase which requires meta-qt5 to be included; pyqt5: depends on python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: do_compile task fails: requires pyqt5-native for sip
NOTE: Runtime target 'rtabmap' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rtabmap', 'qt-gui-cpp']
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-libopenni-dev' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'libfreenect' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb DEPENDS on or otherwise requires it)
libfreenect was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
ERROR: Nothing PROVIDES 'libg2o' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb DEPENDS on or otherwise requires it)
libg2o was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libglu which requires x11 in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-python3-shapely' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rmf-traffic-editor/rmf-building-map-tools_1.3.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-python3-shapely' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-python3-shapely']
NOTE: Runtime target 'rmf-building-map-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-building-map-tools', 'ROS_UNRESOLVED_DEP-python3-shapely']
ERROR: Nothing RPROVIDES 'rmf-building-map-tools-dev' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rmf-traffic-editor/rmf-building-map-tools_1.3.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rmf-building-map-tools-dev'
NOTE: Runtime target 'rmf-building-map-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-building-map-tools-dev']
ERROR: Nothing RPROVIDES 'usb-cam-dev' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/usb-cam/usb-cam_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'usb-cam-dev'
NOTE: Runtime target 'usb-cam-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['usb-cam-dev']
ERROR: Nothing RPROVIDES 'ffmpeg' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/usb-cam/usb-cam_0.4.0-1.bb RDEPENDS on or otherwise requires it)
ffmpeg was skipped: because it has a restricted license 'commercial'. Which is not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'ffmpeg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ffmpeg']
ERROR: Nothing RPROVIDES 'rmf-traffic-editor-dev' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rmf-traffic-editor/rmf-traffic-editor_1.3.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rmf-traffic-editor-dev'
NOTE: Runtime target 'rmf-traffic-editor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-traffic-editor-dev']
ERROR: Nothing RPROVIDES 'turtlesim' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/geometry-tutorials/turtle-tf2-py_0.3.2-1.bb, /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/geometry-tutorials/turtle-tf2-cpp_0.3.2-1.bb RDEPENDS on or otherwise requires it)
turtlesim was skipped: Recipe is blacklisted: qt5: depends on qtbase; qt5-widgets: needs widgets enabled in qtbase PACKAGECONFIG
NOTE: Runtime target 'turtlesim' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlesim']
NOTE: Runtime target 'turtle-tf2-py' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtle-tf2-py', 'turtlesim']
NOTE: Runtime target 'turtle-tf2-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtle-tf2-cpp', 'turtlesim']
ERROR: Nothing RPROVIDES 'turtle-tf2-py-dev' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/geometry-tutorials/turtle-tf2-py_0.3.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtle-tf2-py-dev'
NOTE: Runtime target 'turtle-tf2-py-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtle-tf2-py-dev']
ERROR: Nothing RPROVIDES 'turtle-tf2-cpp-dev' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/geometry-tutorials/turtle-tf2-cpp_0.3.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'turtle-tf2-cpp-dev'
NOTE: Runtime target 'turtle-tf2-cpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtle-tf2-cpp-dev']
ERROR: Nothing RPROVIDES 'color-names-dev' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/color-names/color-names_0.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'color-names-dev'
NOTE: Runtime target 'color-names-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['color-names-dev']
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/color-names/color-names_0.0.2-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
ERROR: Nothing RPROVIDES 'qt-gui-cpp' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
qt-gui-cpp was skipped: Recipe is blacklisted: qt5: depends on qtbase which requires meta-qt5 to be included; pyqt5: depends on python-qt-binding which requires pyqt5; qt-gui-cpp: pyqt5; qt-gui-cpp: do_compile task fails: requires pyqt5-native for sip
NOTE: Runtime target 'qt-gui-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-cpp']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-libopenni-dev' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-libopenni-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-libopenni-dev']
ERROR: Nothing RPROVIDES 'rtabmap-dev' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rtabmap-dev'
NOTE: Runtime target 'rtabmap-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rtabmap-dev']
ERROR: Nothing RPROVIDES 'libfreenect' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
libfreenect was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'libfreenect' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libfreenect']
ERROR: Nothing RPROVIDES 'libg2o' (but /jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rtabmap/rtabmap_0.20.13-1.bb RDEPENDS on or otherwise requires it)
libg2o was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libglu which requires x11 in DISTRO_FEATURES
NOTE: Runtime target 'libg2o' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libg2o']
ERROR: Nothing RPROVIDES 'ros2pkg-native' (but virtual:native:/jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/ros2cli/ros2run_0.13.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ros2pkg-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2pkg-native']
NOTE: Runtime target 'rmf-traffic-editor-test-maps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-traffic-editor-test-maps', 'ros2run-native', 'ros2pkg-native']
NOTE: Runtime target 'rmf-traffic-editor-test-maps-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-traffic-editor-test-maps-dev', 'ros2run-native', 'ros2pkg-native']
ERROR: Nothing RPROVIDES 'ros2cli-native' (but virtual:native:/jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/ros2cli/ros2run_0.13.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ros2cli-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2cli-native']
ERROR: Nothing RPROVIDES 'std-msgs-native' (but virtual:native:/jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rmf-traffic-editor/rmf-building-map-tools_1.3.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'std-msgs-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['std-msgs-native']
ERROR: Nothing RPROVIDES 'rmf-building-map-msgs-native' (but virtual:native:/jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rmf-traffic-editor/rmf-building-map-tools_1.3.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'rmf-building-map-msgs-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmf-building-map-msgs-native']
ERROR: Nothing RPROVIDES 'rclpy-native' (but virtual:native:/jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rmf-traffic-editor/rmf-building-map-tools_1.3.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'rclpy-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rclpy-native']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-python3-shapely-native' (but virtual:native:/jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rmf-traffic-editor/rmf-building-map-tools_1.3.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-python3-shapely-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-python3-shapely-native']
ERROR: Nothing PROVIDES 'ros2cli-native' (but virtual:native:/jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/ros2cli/ros2run_0.13.2-1.bb DEPENDS on or otherwise requires it). Close matches:
  brotli-native
  re2c-native
  rosidl-cli-native
ERROR: Nothing PROVIDES 'rmf-building-map-msgs-native' (but virtual:native:/jenkins/mjansa/build/ros/ros2-galactic-honister/meta-ros/meta-ros2-galactic/generated-recipes/rmf-traffic-editor/rmf-building-map-tools_1.3.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  rmf-building-map-msgs
  rmf-building-map-tools
  rmf-building-map-tools-native

Signed-off-by: Martin Jansa <martin.jansa@lge.com>