{dashing} nav2-costmap-2d: add missing dependency on eigen3-cmake-module
* fixes:
| -- Detecting C compile features - done
| -- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-g++
| -- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-g++ -- works
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Detecting CXX compile features
| -- Detecting CXX compile features - done
| -- Found ament_cmake: 0.7.4 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/ament_cmake/cmake)
| -- Found PythonInterp: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.2", minimum required is "3")
| -- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
| -- Found geometry_msgs: 0.7.0 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/geometry_msgs/cmake)
| -- Found rosidl_adapter: 0.7.8 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/rosidl_adapter/cmake)
| -- Found laser_geometry: 2.0.0 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/laser_geometry/cmake)
| -- append /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/include/eigen3 to ()
| -- laser_geometry_INCLUDE_DIRS=/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/include/eigen3
| -- Found map_msgs: 2.0.2 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/map_msgs/cmake)
| -- Found message_filters: 3.1.3 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/message_filters/cmake)
| -- Found nav2_common: 0.2.6 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/nav2_common/cmake)
| -- Found nav2_msgs: 0.2.6 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/nav2_msgs/cmake)
| -- Found nav2_util: 0.2.6 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/nav2_util/cmake)
| -- Found rmw_implementation_cmake: 0.7.2 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/rmw_implementation_cmake/cmake)
| -- Using RMW implementation 'rmw_fastrtps_cpp'
| -- Found rmw_fastrtps_cpp: 0.7.6 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/rmw_fastrtps_cpp/cmake)
| -- Found OpenSSL: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/lib/libcrypto.so (found version "1.1.1b")
| -- Found FastRTPS: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/include
| -- Looking for pthread.h
| -- Looking for pthread.h - found
| -- Looking for pthread_create
| -- Looking for pthread_create - not found
| -- Looking for pthread_create in pthreads
| -- Looking for pthread_create in pthreads - not found
| -- Looking for pthread_create in pthread
| -- Looking for pthread_create in pthread - found
| -- Found Threads: TRUE
| -- Found nav2_voxel_grid: 0.2.6 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/nav2_voxel_grid/cmake)
| -- Found pluginlib: 2.3.3 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/pluginlib/cmake)
| -- Found tinyxml2_vendor:  (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/tinyxml2_vendor/cmake)
| -- Found TinyXML2: /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/lib/libtinyxml2.so
| -- Found poco_vendor:  (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/poco_vendor/cmake)
| -- Found tf2_sensor_msgs: 0.11.6 (/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/tf2_sensor_msgs/cmake)
| CMake Error at /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/tf2_sensor_msgs/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package):
|   By not providing "Findeigen3_cmake_module.cmake" in CMAKE_MODULE_PATH this
|   project has asked CMake to find a package configuration file provided by
|   "eigen3_cmake_module", but CMake did not find one.
|
|   Could not find a package configuration file provided by
|   "eigen3_cmake_module" with any of the following names:
|
|     eigen3_cmake_moduleConfig.cmake
|     eigen3_cmake_module-config.cmake
                                                                                                                                                                                                                                                     198,1         35%
|     eigen3_cmake_moduleConfig.cmake
|     eigen3_cmake_module-config.cmake
|
|   Add the installation prefix of "eigen3_cmake_module" to CMAKE_PREFIX_PATH
|   or set "eigen3_cmake_module_DIR" to a directory containing one of the above
|   files.  If "eigen3_cmake_module" provides a separate development package or
|   SDK, be sure it has been installed.
| Call Stack (most recent call first):
|   /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/recipe-sysroot/usr/share/tf2_sensor_msgs/cmake/tf2_sensor_msgsConfig.cmake:38 (include)
|   CMakeLists.txt:23 (find_package)
|
|
| -- Configuring incomplete, errors occurred!
| See also "/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/build/CMakeFiles/CMakeOutput.log".
| See also "/jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/build/CMakeFiles/CMakeError.log".
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros/ros2-dashing-thud/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/nav2-costmap-2d/0.2.6-1-r0/temp/log.do_configure.23681)
NOTE: recipe nav2-costmap-2d-0.2.6-1-r0: task do_configure: Failed
ERROR: Task (/jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/navigation2/nav2-costmap-2d_0.2.6-1.bb:do_configure) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>