{melodic} fsrobo-r-driver: add dependency on std-srvs
* fixes:
DEBUG: Executing shell function do_compile
NOTE: VERBOSE=1 cmake --build webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/build --target all -- -j 80
[1/7] webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-g++  -DLINUXSOCKETS=1 -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"fsrobo_r_driver\" -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/include -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/opt/ros/melodic/include -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/include -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0=/usr/src/debug/fsrobo-r-driver/0.7.1-1-r0 -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot= -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot   -std=c++14 -MD -MT CMakeFiles/fsrobo_r_driver_joint_trajectory_action.dir/src/fsrobo_r_joint_trajectory_action_node.cpp.o -MF CMakeFiles/fsrobo_r_driver_joint_trajectory_action.dir/src/fsrobo_r_joint_trajectory_action_node.cpp.o.d -o CMakeFiles/fsrobo_r_driver_joint_trajectory_action.dir/src/fsrobo_r_joint_trajectory_action_node.cpp.o -c webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/src/fsrobo_r_joint_trajectory_action_node.cpp
FAILED: CMakeFiles/fsrobo_r_driver_joint_trajectory_action.dir/src/fsrobo_r_joint_trajectory_action_node.cpp.o
webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-g++  -DLINUXSOCKETS=1 -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"fsrobo_r_driver\" -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/include -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/opt/ros/melodic/include -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/include -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0=/usr/src/debug/fsrobo-r-driver/0.7.1-1-r0 -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot= -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot   -std=c++14 -MD -MT CMakeFiles/fsrobo_r_driver_joint_trajectory_action.dir/src/fsrobo_r_joint_trajectory_action_node.cpp.o -MF CMakeFiles/fsrobo_r_driver_joint_trajectory_action.dir/src/fsrobo_r_joint_trajectory_action_node.cpp.o.d -o CMakeFiles/fsrobo_r_driver_joint_trajectory_action.dir/src/fsrobo_r_joint_trajectory_action_node.cpp.o -c webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/src/fsrobo_r_joint_trajectory_action_node.cpp
In file included from webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/src/fsrobo_r_joint_trajectory_action_node.cpp:29:
webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/include/fsrobo_r_driver/fsrobo_r_joint_trajectory_action.h:39:10: fatal error: std_srvs/Empty.h: No such file or directory
 #include <std_srvs/Empty.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
[2/7] webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-g++  -DLINUXSOCKETS=1 -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"fsrobo_r_driver\" -Dfsrobo_r_driver_EXPORTS -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/include -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/opt/ros/melodic/include -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/include -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0=/usr/src/debug/fsrobo-r-driver/0.7.1-1-r0 -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot= -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot -fPIC   -std=c++14 -MD -MT CMakeFiles/fsrobo_r_driver.dir/src/fsrobo_r_joint_trajectory_action.cpp.o -MF CMakeFiles/fsrobo_r_driver.dir/src/fsrobo_r_joint_trajectory_action.cpp.o.d -o CMakeFiles/fsrobo_r_driver.dir/src/fsrobo_r_joint_trajectory_action.cpp.o -c webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/src/fsrobo_r_joint_trajectory_action.cpp
FAILED: CMakeFiles/fsrobo_r_driver.dir/src/fsrobo_r_joint_trajectory_action.cpp.o
webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-g++  -DLINUXSOCKETS=1 -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"fsrobo_r_driver\" -Dfsrobo_r_driver_EXPORTS -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/include -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/opt/ros/melodic/include -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iwebos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot/usr/include -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0=/usr/src/debug/fsrobo-r-driver/0.7.1-1-r0 -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot= -fdebug-prefix-map=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/recipe-sysroot -fPIC   -std=c++14 -MD -MT CMakeFiles/fsrobo_r_driver.dir/src/fsrobo_r_joint_trajectory_action.cpp.o -MF CMakeFiles/fsrobo_r_driver.dir/src/fsrobo_r_joint_trajectory_action.cpp.o.d -o CMakeFiles/fsrobo_r_driver.dir/src/fsrobo_r_joint_trajectory_action.cpp.o -c webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/src/fsrobo_r_joint_trajectory_action.cpp
In file included from webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/src/fsrobo_r_joint_trajectory_action.cpp:29:
webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/git/include/fsrobo_r_driver/fsrobo_r_joint_trajectory_action.h:39:10: fatal error: std_srvs/Empty.h: No such file or directory
 #include <std_srvs/Empty.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/fsrobo-r-driver/0.7.1-1-r0/temp/log.do_compile.44310)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>