{melodic} libmodbus: set preferred version and unblacklist
* there are 2 versions in meta-oe/thud and another version in melodic:
  meta-ros1-melodic    0.8.8-1 (skipped)
  meta-oe              3.0.6 (skipped)
  meta-oe              3.1.4 (skipped)
* use 0.8 for melodic and 3.1.4 for other ROS distros
* fixes:
ERROR: Nothing RPROVIDES 'libmodbus' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/ipr-extern/ipr-extern_0.8.8-1.bb RDEPENDS on or otherwise requires it)
libmodbus was skipped: Recipe is blacklisted: Must specify PREFERRED_VERSION
libmodbus was skipped: Recipe is blacklisted: Must specify PREFERRED_VERSION
libmodbus was skipped: Recipe is blacklisted: Must specify PREFERRED_VERSION
NOTE: Runtime target 'libmodbus' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libmodbus']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'libmodbus']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'libmodbus']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'libmodbus']
NOTE: Runtime target 'ipr-extern' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ipr-extern', 'libmodbus']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>