{melodic} cartographer: Correct dependencies
* add dependency on protobuf-native and fix CMakeLists.txt to stop
  adding isystem flags to INCLUDES
* drop the dependency on python-sphinx to disable building documentation
* the dependency is incorrect anyway, because it's using during the
  build to create documentaion
* python-sphinx-native-1.6.7 builds build-sphinx with wrong too long
  shebang and has many more python dependencies, I have a patch adding
  all these dependencies to meta-ros, but it will be easier to just
  disable documentation
* python-sphinx-native-2.2.0 is only for python3
* drop -Werror-uninitialized from building the tests, because it causes:
  recipe-sysroot/usr/include/eigen3/Eigen/src/Core/DenseStorage.h:194:66:
  error: '*((void*)(&<anonymous>)+8).Eigen::DenseStorage<double, 3, 3, 1,
  0>::m_data' may be used uninitialized in this function
  [-Werror=maybe-uninitialized]
* add -ldl where needed
* remove runtime dependency on ceres-solver: it links with static ceres,
  so even shlibs code in do_package won't add the runtime dependency on
  ceres-solver
* ceres-solver PN is empty so the package isn't created

Signed-off-by: Martin Jansa <martin.jansa@lge.com>