{melodic} ueye-cam: restrict with ueye in ROS_WORLD_SKIP_GROUPS
* when building ueye-cam it will download some unofficial drivers during the build
  (should be done by bitbake fetcher instead) and then the installed binary is
  linked with the libueye_api library which isn't installed from these unofficial
  drivers, so it's useless in runtime anyway
* as shown in log.do_configure:
  -- Setting UEYE_DRIVER_DIR to: /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/ueye-cam/1.0.17-1-r0/devel/share/ueye_cam
  CMake Warning at cmake_modules/DownloadUEyeDriversUnofficial.cmake:7 (message):
    The official IDS uEye drivers were not detected on your machine.  A
    temporary version of the header/library will be downloaded locally to your
    ROS buildspace, to ensure that this package compiles.  Nevertheless, you
    (or a system administrator) MUST still download and install the official
    IDS uEye drivers (http://en.ids-imaging.com/download-ueye.html).  Also make
    sure that the IDS daemon (/etc/init.d/ueyeusbdrc) is running.
  Call Stack (most recent call first):
    CMakeLists.txt:46 (download_ueye_drivers)
* this results in:
  NOTE: recipe ueye-cam-1.0.17-1-r0: task do_package_qa: Started
  ERROR: ueye-cam-1.0.17-1-r0 do_package_qa: QA Issue: /opt/ros/melodic/lib/libueye_wrapper.so contained in package ueye-cam requires libueye_api.so()(64bit), but no providers found in RDEPENDS_ueye-cam? [file-rdeps]
  ERROR: ueye-cam-1.0.17-1-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
  ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ros/ros1-melodic-dunfell/tmp-glibc/work/core2-64-oe-linux/ueye-cam/1.0.17-1-r0/temp/log.do_package_qa.25987
  NOTE: recipe ueye-cam-1.0.17-1-r0: task do_package_qa: Failed

  lets blacklist it without ueye in ROS_WORLD_SKIP_GROUPS and whoever really
  wants to use it, can unblacklist it after providing the recipe for official
  ueye drivers for his device and adding it to ueye-cam DEPENDS (that should
  hopefully provide compatible libueye_api.so and resolve QA issue as well
  as make it usable in runtime)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>