{melodic} webrtc: Fix dependency on glib-2.0 and blacklist
* fixes:
ERROR: Nothing PROVIDES 'libglib-2.0' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/webrtc-ros/webrtc_59.0.3.bb
DEPENDS on or otherwise requires it). Close matches:
  glib-2.0
NOTE: Runtime target 'webrtc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webrtc', 'libglib-2.0']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>