bullet: move python3 compatible version from meta-ros2 to meta-ros-common
* now when older python2 version was moved to separate layer meta-ros-python2
  we can use this newer bullet for noetic from meta-ros-common

* fixes:
  ERROR: Nothing PROVIDES 'bullet' (but /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/navigation/map-server_1.17.1-1.bb, /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/geometry2/tf2-bullet_0.7.5-1.bb, /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/robot-self-filter/robot-self-filter_0.1.32-1.bb, /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/moveit/moveit-core_1.1.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  tf2-bullet