{rolling} fixing bbappends for rosidl-python
rosidl-python has undergone some changes upstream. The previous
patches are obsolete, but we needed another fix to avoid

```
ERROR: Multiple shlib providers for libunique_identifier_msgs__rosidl_generator_py.so: unique-identifier-msgs, unique-identifier-msgs
```
which was the case since .so files where installed into lib *and*
python3.12/site-packages dir.

Signed-off-by: Matthias Schoepfer <m.schoepfer@rethinkrobotics.com>