{dashing} navigation2: remove dependency on nav2-rviz-plugins when ros-qt5 isn't in DISTRO_FEATURES
* fixes:
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/navigation2/nav2-rviz-plugins_0.2.6-1.bb, /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/rviz/rviz-rendering_6.1.5-1.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
NOTE: Runtime target 'nav2-rviz-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'nav2-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'packagegroup-ros-world-dashing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-dashing', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-dashing', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'nav2-system-tests' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-system-tests', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'nav2-system-tests-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-system-tests-dev', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'turtlebot3-navigation2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-navigation2', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'turtlebot3' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3', 'turtlebot3-navigation2', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'turtlebot3-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-dev', 'turtlebot3-navigation2', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'turtlebot3-navigation2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-navigation2-dev', 'nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'nav2-bringup-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup-dev', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'navigation2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'navigation2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation2-dev', 'nav2-rviz-plugins', 'qtbase']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>