{noetic} rc-genicam-camera restrict like rc-genicam-api is
* fixes:
ERROR: Nothing PROVIDES 'rc-genicam-api' (but meta-ros1-noetic/generated-recipes/rc-genicam-camera/rc-genicam-camera_1.2.4-1.bb DEPENDS on or otherwise requires it)
rc-genicam-api was skipped: incompatible with machine raspberrypi4 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'rc-genicam-camera' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-genicam-camera', 'rc-genicam-api']
NOTE: Runtime target 'packagegroup-ros-world-noetic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-noetic', 'rc-genicam-camera', 'rc-genicam-api']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'rc-genicam-camera', 'rc-genicam-api']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'rc-genicam-camera', 'rc-genicam-api']

ERROR: Nothing RPROVIDES 'rc-genicam-api' (but meta-ros1-noetic/generated-recipes/rc-genicam-camera/rc-genicam-camera_1.2.4-1.bb RDEPENDS on or otherwise requires it)
rc-genicam-api was skipped: incompatible with machine raspberrypi4 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'rc-genicam-api' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-genicam-api']
ERROR: Nothing RPROVIDES 'rc-genicam-camera-dev' (but meta-ros1-noetic/generated-recipes/rc-genicam-camera/rc-genicam-camera_1.2.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rc-genicam-camera-dev'
NOTE: Runtime target 'rc-genicam-camera-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-genicam-camera-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>