{eloquent} packagegroup-ros-world-eloquent: remove spatio-temporal-voxel-layer
* Depends on openvdb and openexr for which we don't have recipes yet
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libopenvdb-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/spatio-temporal-voxel-layer/spatio-temporal-voxel-layer_2.1.2-2.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'spatio-temporal-voxel-layer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['spatio-temporal-voxel-layer', 'UNRESOLVED-libopenvdb-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-tbb' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/spatio-temporal-voxel-layer/spatio-temporal-voxel-layer_2.1.2-2.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-libopenvdb' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/spatio-temporal-voxel-layer/spatio-temporal-voxel-layer_2.1.2-2.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-libopenexr-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/spatio-temporal-voxel-layer/spatio-temporal-voxel-layer_2.1.2-2.bb DEPENDS on or otherwise requires it)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>