{foxy} resolve dependency issues in new recipes
* fixes:
ERROR: Nothing PROVIDES 'rc-genicam-api' (but meta-ros/meta-ros2-foxy/generated-recipes/rc-genicam-driver/rc-genicam-driver_0.1.2-1.bb DEPENDS on or otherwise requires it)
rc-genicam-api was skipped: incompatible with machine raspberrypi4 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'rc-genicam-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-genicam-driver', 'rc-genicam-api']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'rc-genicam-driver', 'rc-genicam-api']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'rc-genicam-driver', 'rc-genicam-api']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'rc-genicam-driver', 'rc-genicam-api']
ERROR: Nothing RPROVIDES 'rc-genicam-api' (but meta-ros/meta-ros2-foxy/generated-recipes/rc-genicam-driver/rc-genicam-driver_0.1.2-1.bb RDEPENDS on or otherwise requires it)
rc-genicam-api was skipped: incompatible with machine raspberrypi4 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'rc-genicam-api' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-genicam-api']
ERROR: Nothing RPROVIDES 'rc-genicam-driver-dev' (but meta-ros/meta-ros2-foxy/generated-recipes/rc-genicam-driver/rc-genicam-driver_0.1.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rc-genicam-driver-dev'
NOTE: Runtime target 'rc-genicam-driver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-genicam-driver-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>