meta-ros-common: Update python3-distlib to 0.3.8
Update python3-distlib to use the recipe from meta-python that was added
in newer Yocto releases.

This is done to solve a build error:
    ERROR: 'python3 setup.py bdist_wheel ' execution failed.

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>