{rolling} ompl: fix python interpreter used in shebang of installed demo scripts
* the interpreter is replaced since:
  https://github.com/ompl/ompl/commit/38ff9c1401ea83e4020cb09b0dcc65b47be6a94d
  but to hosttools python3

* this started to happen only after upgrade of the host OS from 18.04 to 20.04 Ubuntu

* fixes:
  ERROR: QA Issue: /usr/share/ompl/demos/StateSampling.py contained in package ompl requires /jenkins/mjansa/build/ros/ros2-rolling-dunfell/tmp-glibc/hosttools/python3, but no providers found in RDEPENDS_ompl? [file-rdeps]

Signed-off-by: Martin Jansa <martin.jansa@lge.com>