{melodic} hpp-fcl: fetch hpp-fcl with bitbake fetcher instead of ExternalProject_add
* fixes:
CMake Error at webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/hpp-fcl/1.0.1-2-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/ExternalProject.cmake:2324 (message):
  error: could not find git for clone of hpp-fcl_src
Call Stack (most recent call first):
  webos-melodic-thud/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/hpp-fcl/1.0.1-2-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/ExternalProject.cmake:3100 (_ep_add_download_command)
  CMakeLists.txt:11 (ExternalProject_Add)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>