{melodic} fuse, fuse-doc: BBMASK and rename to fuse-ros, fuse-ros-doc with a symlink
* fixes conflict with fuse recipe from meta-filesystem

ERROR: Nothing RPROVIDES 'fuse-utils' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-webosose/meta-webos/recipes-webos/com.webos.service.pdm/com.webos.service.pdm.bb RDEPENDS on or otherwise requires it)
fuse RPROVIDES fuse-utils but was skipped: Recipe is blacklisted: qt5: pyqt5: Depends on fuse-viz which depends on rviz which requires python-qt-binding which requires meta-qt5 to be included; ogre: Depends on fuse-viz which depends on rviz which depends on ogre which is not available
NOTE: Runtime target 'fuse-utils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse-utils']
NOTE: Runtime target 'com.webos.service.pdm' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.pdm', 'fuse-utils']
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended', 'com.webos.service.pdm', 'fuse-utils']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-webos-extended', 'com.webos.service.pdm', 'fuse-utils']
NOTE: Runtime target 'com.webos.service.mediaindexer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.mediaindexer', 'com.webos.service.pdm', 'fuse-utils']
NOTE: Runtime target 'com.webos.service.pdm-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.pdm-dev', 'fuse-utils']
ERROR: Nothing RPROVIDES 'com.webos.service.pdm-localization' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-webosose/meta-webos/recipes-webos/com.webos.service.pdm/com.webos.service.pdm.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'com.webos.service.pdm-localization'
NOTE: Runtime target 'com.webos.service.pdm-localization' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.pdm-localization']
ERROR: Nothing RPROVIDES 'com.webos.service.mediaindexer-dev' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-webosose/meta-webos/recipes-multimedia/com.webos.service.mediaindexer/com.webos.service.mediaindexer.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'com.webos.service.mediaindexer-dev'
NOTE: Runtime target 'com.webos.service.mediaindexer-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.mediaindexer-dev']
ERROR: Nothing PROVIDES 'fuse' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-webosose/meta-webos/recipes-upstreamable/gphotofs/gphotofs_0.5.bb, /jenkins/mjansa/build/ros/webos-melodic-honister/meta-openembedded/meta-filesystems/recipes-filesystems/ntfs-3g-ntfsprogs/ntfs-3g-ntfsprogs_2017.3.23.bb, /jenkins/mjansa/build/ros/webos-melodic-honister/meta-openembedded/meta-filesystems/recipes-filesystems/simple-mtpfs/simple-mtpfs_git.bb DEPENDS on or otherwise requires it)
fuse was skipped: Recipe is blacklisted: qt5: pyqt5: Depends on fuse-viz which depends on rviz which requires python-qt-binding which requires meta-qt5 to be included; ogre: Depends on fuse-viz which depends on rviz which depends on ogre which is not available
fuse was skipped: Recipe is blacklisted: qt5: pyqt5: Depends on fuse-viz which depends on rviz which requires python-qt-binding which requires meta-qt5 to be included; ogre: Depends on fuse-viz which depends on rviz which depends on ogre which is not available
NOTE: Runtime target 'gphotofs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gphotofs', 'fuse']
NOTE: Runtime target 'ntfs-3g' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ntfs-3g', 'fuse']
NOTE: Runtime target 'ntfs-3g-ntfsprogs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ntfs-3g-ntfsprogs', 'fuse']
NOTE: Runtime target 'simple-mtpfs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['simple-mtpfs', 'fuse']
ERROR: Nothing PROVIDES 'com.webos.service.pdm' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-webosose/meta-webos/recipes-webos/pdm-plugin/pdm-plugin.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'com.webos.service.pdm'
NOTE: Runtime target 'pdm-plugin' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pdm-plugin', 'com.webos.service.pdm']
ERROR: Nothing RPROVIDES 'gphotofs-dev' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-webosose/meta-webos/recipes-upstreamable/gphotofs/gphotofs_0.5.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gphotofs-dev'
NOTE: Runtime target 'gphotofs-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gphotofs-dev']
ERROR: Nothing RPROVIDES 'pdm-plugin-dev' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-webosose/meta-webos/recipes-webos/pdm-plugin/pdm-plugin.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'pdm-plugin-dev'
NOTE: Runtime target 'pdm-plugin-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pdm-plugin-dev']
ERROR: Nothing RPROVIDES 'ntfs-3g-ntfsprogs-dev' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-openembedded/meta-filesystems/recipes-filesystems/ntfs-3g-ntfsprogs/ntfs-3g-ntfsprogs_2017.3.23.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ntfs-3g-ntfsprogs-dev'
NOTE: Runtime target 'ntfs-3g-ntfsprogs-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ntfs-3g-ntfsprogs-dev']
ERROR: Nothing RPROVIDES 'fuse' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-openembedded/meta-filesystems/recipes-filesystems/ntfs-3g-ntfsprogs/ntfs-3g-ntfsprogs_2017.3.23.bb RDEPENDS on or otherwise requires it)
fuse was skipped: Recipe is blacklisted: qt5: pyqt5: Depends on fuse-viz which depends on rviz which requires python-qt-binding which requires meta-qt5 to be included; ogre: Depends on fuse-viz which depends on rviz which depends on ogre which is not available
fuse was skipped: Recipe is blacklisted: qt5: pyqt5: Depends on fuse-viz which depends on rviz which requires python-qt-binding which requires meta-qt5 to be included; ogre: Depends on fuse-viz which depends on rviz which depends on ogre which is not available
NOTE: Runtime target 'fuse' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fuse']
ERROR: Nothing RPROVIDES 'simple-mtpfs-dev' (but /jenkins/mjansa/build/ros/webos-melodic-honister/meta-openembedded/meta-filesystems/recipes-filesystems/simple-mtpfs/simple-mtpfs_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'simple-mtpfs-dev'
NOTE: Runtime target 'simple-mtpfs-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['simple-mtpfs-dev']

* {melodic} fuse-doc: BBMASK and rename to fuse-ros-doc with a symlink

* avoids conflict with fuse-doc package (PN-doc) created by fuse recipe and:
  NOTE: Multiple providers are available for runtime fuse-doc (fuse-doc, fuse)
  Consider defining a PREFERRED_RPROVIDER entry to match fuse-doc

* {melodic} fuse-ros, fuse-ros-doc: use normal file with 'require' instead of symlink

* makes it clearer when the original fuse recipe is upgraded and
  'require' fails to parse
* adjust fuse-doc in RDEPENDS so that it doesn't pull fuse-doc package
  from meta-filesystems recipe to the image

Signed-off-by: Martin Jansa <martin.jansa@lge.com>