{common} Fix wrong branch
github.com/dmlc/dmlc-core the branch of it has changed from master to main
ERROR: tvm-0.7.0-r0 do_fetch: Fetcher failure: Unable to find revision
6c401e242c59a1f4c913918246591bb13fd714e7 in branch master even from upstream

Signed-off-by: Albert Han <rw0501610@163.com>