{eloquent} behaviortree-cpp-v3: fix dependencies
* fixes:

DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found ZMQ: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/recipe-sysroot/usr/lib/libzmq.so
-- ZeroMQ found.
-- Found PythonInterp: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.6", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
CMake Error at CMakeLists.txt:58 (find_package):
  By not providing "Findament_cmake_gtest.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ament_cmake_gtest", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake_gtest"
  with any of the following names:

    ament_cmake_gtestConfig.cmake
    ament_cmake_gtest-config.cmake

  Add the installation prefix of "ament_cmake_gtest" to CMAKE_PREFIX_PATH or
  set "ament_cmake_gtest_DIR" to a directory containing one of the above
  files.  If "ament_cmake_gtest" provides a separate development package or
  SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/build/CMakeFiles/CMakeOutput.log".
See also "/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/build/CMakeFiles/CMakeError.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/behaviortree-cpp-v3/3.1.1-1-r0/temp/log.do_configure.6749)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>