{eloquent} nav2-msgs: fix dependencies
* fixes:

DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 0.8.2 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot-native/usr/share/ament_cmake/cmake)
-- Found PythonInterp: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.6", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
-- Found nav2_common: 0.3.2 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/nav2_common/cmake)
-- Found builtin_interfaces: 0.8.0 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake)
CMake Warning at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmake-extras.cmake:30 (find_package):
  By not providing "Findrosidl_adapter.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "rosidl_adapter", but CMake did not find one.

  Could not find a package configuration file provided by "rosidl_adapter"
  with any of the following names:

    rosidl_adapterConfig.cmake
    rosidl_adapter-config.cmake

  Add the installation prefix of "rosidl_adapter" to CMAKE_PREFIX_PATH or set
  "rosidl_adapter_DIR" to a directory containing one of the above files.  If
  "rosidl_adapter" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmakeConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_generator_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_generator_cpp/cmake/rosidl_generator_cppConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtime-extras.cmake:12 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtimeConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/builtin_interfacesConfig.cmake:38 (include)
  CMakeLists.txt:6 (find_package)

-- Found nav_msgs: 0.8.1 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/nav_msgs/cmake)
-- Found rosidl_default_generators: 0.8.0 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_default_generators/cmake)
-- Found OpenSSL: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/lib/libcrypto.so (found version "1.1.1d")
-- Found FastRTPS: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/include
-- Found action_msgs: 0.8.0 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/action_msgs/cmake)
-- Setting build type to Release as none was specified.
CMake Error at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_write_generator_arguments.cmake:61 (message):
  rosidl_write_generator_arguments() must be invoked with at least one of the
  IDL_TUPLES;NON_IDL_TUPLES;ROS_INTERFACE_FILES arguments
Call Stack (most recent call first):
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_generator_cpp/cmake/rosidl_generator_cpp_generate_interfaces.cmake:62 (rosidl_write_generator_arguments)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot-native/usr/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:48 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:286 (ament_execute_extensions)
  CMakeLists.txt:15 (rosidl_generate_interfaces)

-- Configuring incomplete, errors occurred!
See also "/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-msgs/0.3.2-1-r0/temp/log.do_configure.26724)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>