{humble} ompl: Fixed issue elf_open: Invalid argument
This issue caused by introducing ros_prefix to install directory. so, we should replace it into ros_prefix.

  | open: No such file or directory
  | elf_open: Invalid argument
  | WARNING: exit code 1 from a shell command.
  ERROR: Task (.../meta-ros/meta-ros2-humble/generated-recipes/ompl/ompl_1.6.0-1.bb:do_install) failed with exit code '1'

Signed-off-by: Mark Choi <afewgoodman.choi@gmail.com>