{rolling} ompl: remove optional dependency on unresolved opende
* fixes:
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-opende' (but /jenkins/mjansa/build/ros/webos-rolling-honister/meta-ros/meta-ros2-rolling/generated-recipes/ompl/ompl_1.5.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-opende' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-opende']
NOTE: Runtime target 'ompl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ompl', 'ROS_UNRESOLVED_DEP-opende']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>