packagegroup-ros-turtlebot3-core: include raspicam-node only with opengl in DISTRO_FEATURES and blacklist otherwise
* now when we're building for arm with ROS DISTRO and aarch64 with webOS OSE DISTRO
  it fails to build raspicam-node because default DISTRO configuration doesn't have
  'opengl' in DISTRO_FEATURES

* fixes:
  NOTE: Resolving any missing task queue dependencies
  ERROR: Nothing PROVIDES 'userland' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros1/recipes-extended/raspicam-node/raspicam-node_git.bb DEPENDS on or otherwise requires it)
  userland was skipped: Recipe is blacklisted: depends on libegl-mesa from mesa-gl which is not available without opengl in DISTRO_FEATURES
  ERROR: Nothing RPROVIDES 'raspicam-node' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb, /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros1/recipes-extended/raspicam-node/raspicam-node_git.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'raspicam-node'
  NOTE: Runtime target 'raspicam-node' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['raspicam-node']
  ERROR: Nothing RPROVIDES 'packagegroup-ros-turtlebot3-core' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'packagegroup-ros-turtlebot3-core'
  NOTE: Runtime target 'packagegroup-ros-turtlebot3-core' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['packagegroup-ros-turtlebot3-core']
  ERROR: Nothing RPROVIDES 'raspicam-node-dev' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros1/recipes-extended/raspicam-node/raspicam-node_git.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'raspicam-node-dev'
  NOTE: Runtime target 'raspicam-node-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['raspicam-node-dev']

* this mess with userland is hopefully temporary and turtlebot3 will eventually
  use the new implementation introduced in Raspberry Pi OS image based on Debian
  Bullseye https://www.raspberrypi.com/news/bullseye-camera-system/
  there are already some changes for this in meta-raspberrypi:
  https://github.com/agherzan/meta-raspberrypi/pull/963
  and meta-oe:
  https://github.com/openembedded/meta-openembedded/pull/496

Signed-off-by: Martin Jansa <martin.jansa@lge.com>