{dashing} ros-distro.inc: Set ROS_UNRESOLVED_PLATFORM_PKG_python3-pil to "python3-pillow"
* pillow is friendly PIL fork
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-pil' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/rosbridge-suite/rosbridge-library_1.0.2-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'rosbridge-library' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbridge-library', 'UNRESOLVED-python3-pil']
NOTE: Runtime target 'rosapi' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosapi', 'rosbridge-library', 'UNRESOLVED-python3-pil']
NOTE: Runtime target 'rosbridge-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbridge-server', 'rosapi', 'rosbridge-library', 'UNRESOLVED-python3-pil']
NOTE: Runtime target 'rosbridge-suite' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbridge-suite', 'rosbridge-server', 'rosapi', 'rosbridge-library', 'UNRESOLVED-python3-pil']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>