{rolling} ros-distro.inc: Add ROS_UNRESOLVED_DEP-lttng-tools
ERROR: Required build target 'ros-image-core' has no buildable providers.
Missing or unbuildable dependency chain was: ['ros-image-core', 'ros-core', 'rclcpp-lifecycle', 'rclcpp', 'tracetools', 'ROS_UNRESOLVED_DEP-lttng-tools']

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>