layer.conf: add rocko to LAYERSERIES_COMPAT_ros-layer
* meta-ros is compatible with Yocto 2.4 Rocko without any special
  handling needed to integrate it, mark it as compatible

* LAYERSERIES_COMPAT variables are used only since 2.4 Rocko, so with
  even older Yocto releases this isn't an issue, but with 2.4 it was
  failing with:

  bitbake -e zlib | tee env.zlib
  ERROR: Unable to start bitbake server

  which isn't really useful, bitbake-cookerdaemon.log shows better
  explanation:
  Traceback (most recent call last):
    File "build-rocko/bitbake/lib/bb/cookerdata.py", line 285, in parseBaseConfiguration
      self.data = self.parseConfigurationFiles(self.prefiles, self.postfiles)
    File "build-rocko/bitbake/lib/bb/cookerdata.py", line 399, in parseConfigurationFiles
      % (c, " ".join(layerseries), " ".join(compat)))
    File "build-rocko/bitbake/lib/bb/__init__.py", line 104, in fatal
      raise BBHandledException()
  bb.BBHandledException

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "build-rocko/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
      function()
    File "build-rocko/bitbake/lib/bb/server/process.py", line 433, in _startServer
      self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset)
    File "build-rocko/bitbake/lib/bb/cooker.py", line 197, in __init__
      self.initConfigurationData()
    File "build-rocko/bitbake/lib/bb/cooker.py", line 356, in initConfigurationData
      self.databuilder.parseBaseConfiguration()
    File "build-rocko/bitbake/lib/bb/cookerdata.py", line 318, in parseBaseConfiguration
      raise bb.BBHandledException
  bb.BBHandledException
  ERROR: Layer ros-layer is not compatible with the core layer which only supports these series: rocko (layer is compatible with sumo)

* and it's a bit complicated to override LAYERSERIES_COMPAT_ros-layer
  from local build without meta-ros modification, changing it in some
  other (own) layer, which is parsed after meta-ros works, but you might
  not have suitable layer for this.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>