{noetic} resolve dependency issues in new recipes
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-jq' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/microstrain-inertial/microstrain-inertial-driver_2.0.2-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'microstrain-inertial-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['microstrain-inertial-driver', 'ROS_UNRESOLVED_DEP-jq']
NOTE: Runtime target 'packagegroup-ros-world-noetic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-noetic', 'microstrain-inertial-driver', 'ROS_UNRESOLVED_DEP-jq']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'microstrain-inertial-driver', 'ROS_UNRESOLVED_DEP-jq']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-noetic', 'microstrain-inertial-driver', 'ROS_UNRESOLVED_DEP-jq']
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
NOTE: Runtime target 'rviz-animated-view-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-animated-view-controller', 'qtbase']
ERROR: Nothing PROVIDES 'mesa' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb DEPENDS on or otherwise requires it)
mesa was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb DEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-gazebo' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-gazebo_0.1.1-5.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'rm-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rm-gazebo', 'ROS_UNRESOLVED_DEP-gazebo']
ERROR: Nothing PROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-gazebo_0.1.1-5.bb DEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
ERROR: Nothing PROVIDES 'gazebo-ros-control' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-gazebo_0.1.1-5.bb DEPENDS on or otherwise requires it)
gazebo-ros-control was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
ERROR: Nothing RPROVIDES 'microstrain-inertial-driver-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/microstrain-inertial/microstrain-inertial-driver_2.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'microstrain-inertial-driver-dev'
NOTE: Runtime target 'microstrain-inertial-driver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['microstrain-inertial-driver-dev']
ERROR: Nothing RPROVIDES 'qtbase' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtbase' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtbase']
ERROR: Nothing RPROVIDES 'rviz-animated-view-controller-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-animated-view-controller-dev'
NOTE: Runtime target 'rviz-animated-view-controller-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-animated-view-controller-dev']
ERROR: Nothing RPROVIDES 'mesa' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb RDEPENDS on or otherwise requires it)
mesa-gl RPROVIDES mesa but was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
mesa was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'mesa' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mesa']
ERROR: Nothing RPROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rviz-animated-view-controller/rviz-animated-view-controller_0.2.0-2.bb RDEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: qt5: pyqt5: Requires python-qt-binding which requires meta-qt5 to be included; ogre: depends on ogre which is not available
NOTE: Runtime target 'rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz']
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-gazebo' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-gazebo_0.1.1-5.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ROS_UNRESOLVED_DEP-gazebo']
ERROR: Nothing RPROVIDES 'gazebo-ros' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-gazebo_0.1.1-5.bb RDEPENDS on or otherwise requires it)
gazebo-ros was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros']
ERROR: Nothing RPROVIDES 'rm-gazebo-dev' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-gazebo_0.1.1-5.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rm-gazebo-dev'
NOTE: Runtime target 'rm-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rm-gazebo-dev']
ERROR: Nothing RPROVIDES 'roboticsgroup-upatras-gazebo-plugins' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-gazebo_0.1.1-5.bb RDEPENDS on or otherwise requires it)
roboticsgroup-upatras-gazebo-plugins was skipped: Recipe is blacklisted: Depends on gazebo-ros, gazebo which is not available
NOTE: Runtime target 'roboticsgroup-upatras-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['roboticsgroup-upatras-gazebo-plugins']
ERROR: Nothing RPROVIDES 'gazebo-ros-control' (but /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rm-control/rm-gazebo_0.1.1-5.bb RDEPENDS on or otherwise requires it)
gazebo-ros-control was skipped: Recipe is blacklisted: Depends on gazebo, gazebo-ros which is not available
NOTE: Runtime target 'gazebo-ros-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-control']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>