{common} libflann: Relax hard dependency on openmp
Convert the openmp dependency into a package config and disable it
by default as openmp introduces a hard dependency on meta-clang and
the layer doesn't advertise such a dependency:

ERROR: Nothing PROVIDES 'openmp' (but meta-ros/meta-ros-common/recipes-extended/libflann/libflann_1.9.2.bb
       DEPENDS on or otherwise requires it).

Signed-off-by: Christian Kohn <chris.kohn@amd.com>