meta-ros-common: python3-paramiko: Remove old recipe
The python3-paramiko recipe has a missing dependency on
python3-pycrypto.  There is an updated python3-paramiko recipe in
meta-python that does not have that dependency.  Remove the recipe from
meta-ros to use that new version instead.

    NOTE: Resolving any missing task queue dependencies
    ERROR: Nothing RPROVIDES 'python3-pycrypto' (but meta-ros/meta-ros-common/recipes-devtools/python/python3-paramiko_1.16.0.bb RDEPENDS on or otherwise requires it)
    NOTE: Runtime target 'python3-pycrypto' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['python3-pycrypto']
    NOTE: Runtime target 'python3-paramiko' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['python3-paramiko', 'python3-pycrypto']
    NOTE: Runtime target 'ros-comm' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['ros-comm', 'roslaunch', 'python3-paramiko', 'python3-pycrypto']
    NOTE: Runtime target 'ros-core' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['ros-core', 'ros-comm', 'roslaunch', 'python3-paramiko', 'python3-pycrypto']
    ERROR: Required build target 'ros-image-core' has no buildable providers.
    Missing or unbuildable dependency chain was: ['ros-image-core', 'ros-core', 'ros-comm', 'roslaunch', 'python3-paramiko', 'python3-pycrypto']

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>