{dashing} packagegroup-ros-world-dashing: remove ament-clang-tidy and ament-cmake-clang-tidy from world
* fixes:
RROR: Nothing RPROVIDES 'UNRESOLVED-clang-tidy-native' (but virtual:native:/jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/ament-lint/ament-clang-tidy_0.7.11-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-clang-tidy-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-clang-tidy-native']
NOTE: Runtime target 'ament-cmake-clang-tidy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-clang-tidy', 'ament-clang-tidy-native', 'UNRESOLVED-clang-tidy-native']
NOTE: Runtime target 'ament-cmake-clang-tidy-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-clang-tidy-dev', 'ament-clang-tidy-native', 'UNRESOLVED-clang-tidy-native']

ERROR: Nothing RPROVIDES 'UNRESOLVED-clang-tidy' (but /jenkins/mjansa/build-ros/ros2-dashing-thud/meta-ros/meta-ros2-dashing/generated-recipes/ament-lint/ament-clang-tidy_0.7.11-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-clang-tidy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-clang-tidy']
NOTE: Runtime target 'ament-clang-tidy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-clang-tidy', 'UNRESOLVED-clang-tidy']
NOTE: Runtime target 'ament-clang-tidy-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-clang-tidy-dev', 'UNRESOLVED-clang-tidy']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>